// DRILL 2.  Starts RED. Do not edit this file; fix keys.ts.
import { expect, test } from "vitest";
import { createWithKey, type Row, type Store } from "./keys.ts";

/**
 * The idempotency_keys table in memory, with a round trip (one timer tick) per call, as Postgres costs one. `claim`
 * checks and writes BEFORE its round trip, in one synchronous step, which is what `insert ... on conflict do nothing`
 * is: nothing can land between the check and the write.
 */
function memoryStore(): { store: Store; rows: Map<string, Row> } {
  const rows = new Map<string, Row>();
  const roundTrip = (): Promise<void> => new Promise((resolve) => setTimeout(resolve, 1));
  const at = (user: string, key: string): string => `${user}:${key}`;
  const store: Store = {
    async find(user, key) {
      await roundTrip();
      return rows.get(at(user, key));
    },
    async put(user, key, row) {
      await roundTrip();
      rows.set(at(user, key), row);
    },
    async claim(user, key, row) {
      const held = rows.get(at(user, key));
      if (held === undefined) rows.set(at(user, key), row);
      await roundTrip();
      return { held: held ?? row, mine: held === undefined };
    },
    async forget(user, key) {
      await roundTrip();
      rows.delete(at(user, key));
    },
  };
  return { store, rows };
}
/** `make` as the run insert is: a round trip, then a fresh job id (or undefined: the document was busy). Counts its calls. */
function jobs(busy = false) {
  let made = 0;
  const make = async (): Promise<string | undefined> => {
    await new Promise((resolve) => setTimeout(resolve, 1));
    made++;
    return busy ? undefined : `job-${String(made)}`;
  };
  return { make, count: () => made };
}
const REQUEST = JSON.stringify({ queue: "ai", documentId: "d1", instruction: "add a hero" });

// The whole bug in one sentence: the answer arrives from twenty requests at once, and twenty jobs exist where one
// was pressed. Read the failing assertion: how many times was `make` called, and what happened between the moment
// each request looked for the key and the moment it wrote it?
test("twenty presses at once with one key make ONE job, and all twenty are answered with it", async () => {
  const { store } = memoryStore();
  const withKey = createWithKey(store);
  const { make, count } = jobs();
  const answers = await Promise.all(Array.from({ length: 20 }, () => withKey("ann", "press-1", REQUEST, make)));
  expect(count()).toBe(1);
  const ids = answers.map((answer) => (typeof answer === "object" ? ("made" in answer ? answer.made : answer.replay) : answer));
  expect(new Set(ids)).toEqual(new Set(["job-1"]));
  expect(answers.filter((answer) => typeof answer === "object" && "made" in answer)).toHaveLength(1); // one winner
});

test("later, the same key replays the job it made; the same key for anything else is refused", async () => {
  const { store } = memoryStore();
  const withKey = createWithKey(store);
  const { make, count } = jobs();
  expect(await withKey("ann", "press-2", REQUEST, make)).toEqual({ made: "job-1" });
  expect(await withKey("ann", "press-2", REQUEST, make)).toEqual({ replay: "job-1" });
  expect(await withKey("ann", "press-2", JSON.stringify({ queue: "ship", documentId: "d1" }), make)).toBe("key_reused");
  expect(count()).toBe(1);
});

test("a press that made nothing (the document was busy) does not use its key up", async () => {
  const { store, rows } = memoryStore();
  const withKey = createWithKey(store);
  expect(await withKey("ann", "press-3", REQUEST, jobs(true).make)).toBe("nothing");
  expect(rows.size).toBe(0); // the claim rolled back with the request
  expect(await withKey("ann", "press-3", REQUEST, jobs().make)).toEqual({ made: "job-1" });
});

test("a key is its user's own: another user's same key makes their own job", async () => {
  const { store } = memoryStore();
  const withKey = createWithKey(store);
  const { make } = jobs();
  expect(await withKey("ann", "press-4", REQUEST, make)).toEqual({ made: "job-1" });
  expect(await withKey("bob", "press-4", REQUEST, make)).toEqual({ made: "job-2" });
});
