// DRILL 2.  Starts RED. Do not edit this file; fix push-ops.ts.
import { expect, test } from "vitest";
import type { Doc, Op } from "@noon/contracts";
import { applyOp, emptyDoc } from "../../../packages/doc-model/src/index.ts";
import { pushOps } from "./push-ops.ts";

const none = new Set<string>();
const build = (...ops: Op[]): Doc => ops.reduce(applyOp, emptyDoc());
const add = (nodeId: string, parentId: string, component = "Card", props: Record<string, string | number | boolean> = {}, index = 99): Op => ({ type: "add_node", nodeId, parentId, index, component, props });
const ops = (base: Doc | undefined, target: Doc, current: Doc, earlierIds: ReadonlySet<string> = none): Op[] => {
  const result = pushOps({ base, target, current, earlierIds });
  if (!result.ok) throw new Error(result.reason);
  return result.ops;
};

/** The page as it was generated and pushed to the branch: what the engineer cloned. */
const page = build(add("a", "root", "Card", { title: "A" }), add("b", "root", "Button", { label: "B" }), add("c", "root", "Text", { value: "C" }), add("a1", "a", "Button", { label: "in A" }));

test("one changed prop is one set_prop, an unchanged page is no op at all, and a removed subtree is one remove", () => {
  const edited = applyOp(page, { type: "set_prop", nodeId: "b", key: "label", value: "Pay" });
  expect(ops(page, edited, page)).toEqual([{ type: "set_prop", nodeId: "b", key: "label", value: "Pay" }]);
  expect(ops(page, page, page)).toEqual([]);
  expect(ops(page, applyOp(page, { type: "remove_node", nodeId: "a" }), page)).toEqual([{ type: "remove_node", nodeId: "a" }]); // a1 goes with it
});

// The diff is THREE-WAY: base (the page the engineer started from), target (what they pushed), applied to
// the document as it is NOW. Read the failing assertion: which side of the canvas's own work got undone?
test("the push replays what the ENGINEER changed on the document as it is now: canvas edits since stay", () => {
  // Since the file was generated, the canvas renamed A, added d and removed c.
  const now = [{ type: "set_prop", nodeId: "a", key: "title", value: "renamed on the canvas" }, add("d", "root", "Button", { label: "D" }), { type: "remove_node", nodeId: "c" }] satisfies Op[];
  const current = now.reduce(applyOp, page);
  // The engineer, from the old file, changed b's label, edited c (gone now) and put a new node first.
  const pushed = [{ type: "set_prop", nodeId: "b", key: "label", value: "from git" }, { type: "set_prop", nodeId: "c", key: "value", value: "edited" }, add("g", "root", "Text", { value: "G" }, 0)] satisfies Op[];
  const result = ops(page, pushed.reduce(applyOp, page), current);
  expect(result).toEqual([
    { type: "add_node", nodeId: "g", parentId: "root", index: 0, component: "Text", props: { value: "G" } },
    { type: "set_prop", nodeId: "b", key: "label", value: "from git" }, // c's edit is dropped: a remove beats a concurrent edit
  ]);
  const after = result.reduce(applyOp, current);
  expect(after.nodes["a"]?.props).toEqual({ title: "renamed on the canvas" });
  expect(after.nodes["root"]?.children).toEqual(["g", "a", "b", "d"]);
});

test("without a base the document is the base: the push is the whole page", () => {
  const target = applyOp(applyOp(page, { type: "remove_node", nodeId: "c" }), { type: "set_prop", nodeId: "b", key: "label", value: "Pay" });
  expect(ops(undefined, target, page)).toEqual([{ type: "set_prop", nodeId: "b", key: "label", value: "Pay" }, { type: "remove_node", nodeId: "c" }]);
  // A base of another page (another root) is no base.
  expect(ops({ rootId: "elsewhere", nodes: {} }, target, page)).toEqual(ops(undefined, target, page));
});

test("an id that was ever part of the page is never added again, and the root must be the document's", () => {
  const readded = applyOp(page, add("old", "root", "Button", { label: "back" }));
  expect(pushOps({ base: page, target: readded, current: page, earlierIds: new Set(["old"]) })).toMatchObject({ ok: false, reason: "reused_node_id" });
  const otherRoot: Doc = { rootId: "r2", nodes: { r2: { id: "r2", component: "Page", props: {}, parentId: null, children: [] } } };
  expect(pushOps({ base: page, target: otherRoot, current: page, earlierIds: none })).toMatchObject({ ok: false, reason: "root_mismatch" });
});
