// DRILL 1 · extend a type, end to end.  Starts RED. Do not edit this file.
//
// The audit trail says when someone signed IN and nothing about when they signed OUT, so an owner reading "who was in
// the org's documents on Tuesday" sees only half of it. Carry a `signed_out` action from the contract to the row that
// writes it. You will touch, in this order:
//   1. packages/contracts/src/index.ts     `AuditAction` gains "signed_out". The enum IS the type of the column, the
//                                          api's response and the view's words, so this one edit reaches all three.
//   2. apps/web/src/audit.ts               stops compiling: SENTENCES is a Record over the WHOLE enum, and it now lacks a
//                                          key. Write its sentence: "Signed out." (the same trick as reasons.ts).
//   3. packages/db/migrations/0018_*.sql   the CHECK constraint on audit_log.action is a type too, and Postgres does not
//                                          know the contract changed. Drop and re-add it with the new value (Postgres
//                                          named the inline check `audit_log_action_check`). Never touch the trigger.
//   4. packages/db/src/index.ts            `endSession` writes the row IN THE SAME STATEMENT as the delete, exactly as
//                                          startSession does for a sign-in: `with gone as (delete from auth_sessions
//                                          where token_hash = $1 returning user_id) insert into audit_log ... select
//                                          m.org_id, 'user', u.id, u.email, 'signed_out', null, '{}' from gone join
//                                          users u ... join memberships m ...`. One row per org the user belongs to. A
//                                          token that is unknown or already expired deletes nothing, so it writes
//                                          nothing: signing out twice is still 204, and still not an event.
//   5. apps/api/src/audit.int.test.ts      the flow signs out after signing in, and the expected list gains the row
//                                          (run it when Docker is free: `make integration`).
// Then run:  make check   and   sh drills/lesson-8/check.sh
//
// Predict first: why must the row be selected FROM the deleted row (a CTE) rather than inserted after the delete
// returns, and what would a sign-out with a cookie that expired an hour ago write under each design?
import { readdirSync, readFileSync } from "node:fs";
import { expect, test } from "vitest";
import { AuditAction, AuditEntry } from "@noon/contracts";
import { auditWords } from "../../apps/web/src/audit.ts";

const root = new URL("../../", import.meta.url);
const read = (path: string): string => readFileSync(new URL(path, root), "utf8");
const base: AuditEntry = {
  id: "0f9c7a0e-1b2c-4d3e-8f00-000000000001",
  orgId: "0f9c7a0e-1b2c-4d3e-8f00-000000000002",
  actor: { kind: "user", id: "0f9c7a0e-1b2c-4d3e-8f00-000000000003", email: "owner@example.com" },
  action: "signed_in",
  documentId: null,
  detail: {},
  at: "2026-09-30T00:00:00.000Z",
};
// Not yet in the union while the drill is red: the cast keeps this file compiling until step 1 makes it a member.
const signedOut = "signed_out" as unknown as AuditAction;

test("the contract: signed_out is an audit action, and an entry with it parses", () => {
  expect(AuditAction.options).toContain("signed_out");
  expect(AuditEntry.parse({ ...base, action: "signed_out" })).toHaveProperty("action", "signed_out");
});

test("the view has words for it, and they are its own", () => {
  expect(auditWords({ ...base, action: signedOut }).what).toBe("Signed out.");
  expect(auditWords({ ...base, action: signedOut }).what).not.toBe(auditWords(base).what);
});

test("a migration after 0017 widens the CHECK constraint on audit_log.action, and leaves the append-only trigger alone", () => {
  const migrations = readdirSync(new URL("packages/db/migrations/", root)).filter((name) => /^00(1[89]|[2-9]\d)_.*\.sql$/.test(name));
  const widening = migrations.map((name) => read(`packages/db/migrations/${name}`)).find((sql) => sql.includes("signed_out"));
  expect(widening, "a migration 0018 or later that names signed_out").toBeDefined();
  expect(widening).toMatch(/audit_log_action_check/);
  expect(widening).toMatch(/check\s*\(\s*action in \(/i);
  expect(widening).not.toMatch(/drop trigger|disable trigger|drop function/i);
});

// The drills run without Postgres, so the cheapest honest check is the statement's text: the integration test in
// step 5 is the real one. What this asserts is the SHAPE the chapter insists on: one statement, the audit row
// selected from the deleted row, never a second statement after the first returned.
test("endSession deletes the session and writes the audit row in ONE statement", () => {
  const source = read("packages/db/src/index.ts");
  const start = source.indexOf("endSession: async");
  expect(start, "endSession in the db package").toBeGreaterThan(0);
  const body = source.slice(start, source.indexOf("\n    },", start));
  expect(body).toMatch(/with\s+\w+\s+as\s+\(\s*delete from auth_sessions where token_hash = \$1 returning user_id\s*\)/i);
  expect(body).toContain("audit_log");
  expect(body).toContain("'signed_out'");
  expect(body).toContain("memberships");
  expect((body.match(/pool\.query\(/g) ?? []).length).toBe(1);
});
