// DRILL 1 · extend the projection, end to end.  Starts RED. Do not edit this file.
//
// Today the generated file exists in exactly one place: inside the document's container, where the
// sandbox worker pushed it. Epic 5 will open a pull request with it, and an engineer will want to
// read it before that. Give the api `GET /documents/:id/code`: the document's generated TSX, as
// text/plain, byte-for-byte what `generate()` makes from the SAVED document. You will touch, in
// this order:
//   1. apps/api/package.json          the api does not depend on @noon/codegen or @noon/design-system
//                                     yet: add both (workspace:^) and `pnpm install`. A package that
//                                     imports what it does not declare works on your machine and
//                                     breaks in the image.
//   2. packages/contracts/src/index.ts ErrorBody names every error the api can answer with: add
//                                     `not_generated`. A document the design system can no longer
//                                     generate (a dropped component, say) is refused by name, never
//                                     served half; the reason is in `generate()`'s result.
//   3. apps/api/src/app.ts             the route, next to the preview routes. Membership only, like
//                                     them (a non-member gets the same 404 as an unknown document).
//                                     `db.documentStore().load(orgId, id)` is how the sync server reads
//                                     the tree; a document nobody opened yet has no content: that is
//                                     the EMPTY document (doc-model's `emptyDoc()`), not an error.
// Then run:  make check   and   sh drills/lesson-4/check.sh
import { expect, test } from "vitest";
import { Document, Org, Workspace, type Doc } from "@noon/contracts";
import { manifest } from "@noon/design-system";
import { generate } from "../../packages/codegen/src/index.ts";
import { applyOp, emptyDoc } from "../../packages/doc-model/src/index.ts";
import { useTestServer } from "../../apps/api/src/testing.ts";

const ctx = useTestServer();
const json = { "content-type": "application/json" };
const as = (user: string, path: string) => ctx.fetch(path, { headers: { "x-dev-user": user } });

async function aDocument(owner: string): Promise<Document> {
  const org = Org.parse(await (await ctx.fetch("/orgs", { method: "POST", headers: { "x-dev-user": owner, ...json }, body: JSON.stringify({ name: "Code" }) })).json());
  const ws = Workspace.parse(await (await ctx.fetch(`/orgs/${org.id}/workspaces`, { method: "POST", headers: { "x-dev-user": owner, ...json }, body: JSON.stringify({ name: "ws" }) })).json());
  return Document.parse(await (await ctx.fetch(`/orgs/${org.id}/workspaces/${ws.id}/documents`, { method: "POST", headers: { "x-dev-user": owner, ...json }, body: JSON.stringify({ title: "Checkout" }) })).json());
}
/** root > Card c1 > Button b1, built with the pure applier: what the room would have saved. */
function aTree(): Doc {
  let doc = emptyDoc();
  doc = applyOp(doc, { type: "add_node", nodeId: "c1", parentId: "root", index: 0, component: "Card", props: { title: "Payment" } });
  doc = applyOp(doc, { type: "add_node", nodeId: "b1", parentId: "c1", index: 0, component: "Button", props: { label: "Pay" } });
  return doc;
}

/**
 * The document as `documentStore().load` reads it: its `content` and `seq` columns. (The room's idle save that wrote
 * them was replaced by snapshots in epic 6; the columns stay load's starting point, so the drill writes them directly.)
 */
async function saved(doc: Document, tree: Doc): Promise<void> {
  await ctx.db.rawQuery("update documents set content = $3, seq = 1 where org_id = $1 and id = $2", [doc.orgId, doc.id, JSON.stringify(tree)]);
}

test("a document nobody has opened yet is the empty page: one file, one export, no import line", async () => {
  const doc = await aDocument("ann@example.com");
  const res = await as("ann@example.com", `/documents/${doc.id}/code`);
  expect(res.status).toBe(200);
  expect(res.headers.get("content-type")).toMatch(/^text\/plain/u);
  const tsx = await res.text();
  expect(tsx.match(/^export\b.*$/gmu)).toEqual(["export function Page() {"]);
  expect(tsx).toContain('data-node-id="root"');
  expect(tsx).not.toContain("import ");
});

test("the file is byte-for-byte what generate() makes from the SAVED document: what the sandbox runs and epic 5 will push", async () => {
  const doc = await aDocument("ann@example.com");
  const tree = aTree();
  await saved(doc, tree);
  const res = await as("ann@example.com", `/documents/${doc.id}/code`);
  expect(res.status).toBe(200);
  const expected = generate(tree, manifest);
  if (!expected.ok) throw new Error(expected.reason);
  expect(await res.text()).toBe(expected.tsx);
});

test("a document the design system can no longer generate is refused by name, never served half", async () => {
  const doc = await aDocument("ann@example.com");
  const drifted = applyOp(emptyDoc(), { type: "add_node", nodeId: "w1", parentId: "root", index: 0, component: "Widget", props: {} }); // no such component any more
  await saved(doc, drifted);
  const res = await as("ann@example.com", `/documents/${doc.id}/code`);
  expect(res.status).toBe(409);
  expect(await res.json()).toEqual({ error: "not_generated" }); // a NAME: the detail is for the log, never the wire
});

test("someone else's document, an unknown one and a malformed id are the same 404, and give nothing away", async () => {
  const doc = await aDocument("ann@example.com");
  for (const path of [`/documents/${doc.id}/code`, "/documents/7b6f1c2e-0000-4000-8000-000000000000/code", "/documents/not-a-uuid/code"]) {
    const res = await as("mallory@example.com", path);
    expect(res.status).toBe(404);
    expect(await res.json()).toEqual({ error: "not_found" });
  }
});
