// DRILL 2.  Starts RED. Do not edit this file; fix reaper.ts.
import { randomUUID } from "node:crypto";
import { expect, test } from "vitest";
import { fakeDocker, reap } from "./reaper.ts";

const never = (): Promise<ReadonlySet<string>> => Promise.resolve(new Set<string>());

test("an idle sandbox goes, one in use stays, another pool's is not touched, and a label that is not a uuid is left alone", async () => {
  const docker = fakeDocker();
  const [idle, busy, theirs] = [randomUUID(), randomUUID(), randomUUID()];
  await docker.start(idle, "mine");
  await docker.start(busy, "mine");
  await docker.start(theirs, "theirs");
  await docker.start("not-a-uuid", "mine");

  expect(await reap(() => Promise.resolve(new Set([busy])), docker, "mine")).toEqual([idle]);
  expect(docker.running(idle)).toBe(false);
  expect(docker.running(busy)).toBe(true);
  expect(docker.running(theirs)).toBe(true);
  expect(docker.running("not-a-uuid")).toBe(true);
  expect(await reap(() => Promise.resolve(new Set([busy])), docker, "mine")).toEqual([]); // nothing idle: nothing removed
});

// Found by the E4.2b re-verify. The reaper asks two systems, and a sandbox job can start a container
// BETWEEN its two questions. Postgres answers "nobody is using this document"; the job inserts its
// row and starts the container; then the reaper looks at Docker. Whichever question is asked second
// sees the newer world. Which order makes a container that appears in between safe?
test("a sandbox started between the reaper's two questions is never removed", async () => {
  const docker = fakeDocker();
  const late = randomUUID();
  const removed = await reap(async () => {
    await docker.start(late, "mine"); // a job starts the document's sandbox while Postgres is being asked...
    return new Set<string>(); // ...and the answer predates that job's row
  }, docker, "mine");
  expect(removed).not.toContain(late);
  expect(docker.running(late)).toBe(true);
});

test("the fix is the order of the questions, not a retry: exactly one look at Docker and one at Postgres", async () => {
  const docker = fakeDocker();
  let asked = 0;
  let listed = 0;
  const counted = { ...docker, list: (pool: string) => { listed++; return docker.list(pool); } };
  await reap(() => { asked++; return never(); }, counted, "mine");
  expect([listed, asked]).toEqual([1, 1]);
});
