import { randomBytes } from "node:crypto";
import { Client } from "pg";
import type { Org } from "@noon/contracts";
import { createDb, type Db } from "./index.ts";

// The owner password is a local secret generated by ./init.sh into .env; nothing is hard-coded here.
function ownerUrl(): string {
  if (process.env["TEST_DATABASE_URL"]) return process.env["TEST_DATABASE_URL"];
  const password = process.env["POSTGRES_PASSWORD"];
  if (!password) throw new Error("POSTGRES_PASSWORD is not set: run ./init.sh (it writes .env and starts Postgres)");
  return `postgres://noon:${password}@localhost:${process.env["PG_PORT"] ?? "5432"}/noon`;
}
export const TEST_DATABASE_URL = ownerUrl();

export type TestDb = {
  db: Db;
  /** An org owned by a throwaway user, for tests that are not about ownership. */
  createOrg(name: string): Promise<Org>;
  /** A document in a fresh org of that name, for tests about one document. */
  createDocument(orgName: string): Promise<{ id: string; orgId: string }>;
  schema: string;
  /** Raw SQL, for proving what the DATABASE refuses. Production code has no such door. */
  rawQuery(sql: string, params?: unknown[]): Promise<unknown>;
  columnsByTable(): Promise<Record<string, string[]>>;
  drop(): Promise<void>;
};

/** A migrated database inside its own throwaway Postgres schema, so test files never see each other's rows. */
export async function createTestDb({ migrate = true }: { migrate?: boolean } = {}): Promise<TestDb> {
  const schema = `test_${randomBytes(6).toString("hex")}`;
  const admin = new Client({ connectionString: TEST_DATABASE_URL, options: `-c search_path=${schema}` });
  await admin.connect();
  await admin.query(`create schema ${schema}`);

  admin.on("error", () => undefined); // a killed admin connection should fail a test, not the whole run
  const db = createDb({ connectionString: TEST_DATABASE_URL, schema });
  try {
    if (migrate) await db.migrate();
  } catch (err) {
    // Do not leak the schema or the connection when setup fails.
    await db.close();
    await admin.query(`drop schema ${schema} cascade`);
    await admin.end();
    throw err;
  }

  async function createOrg(name: string): Promise<Org> {
    const owner = await db.upsertUser({ email: "owner@example.com", name: "Owner" });
    return db.createOrg({ name, ownerId: owner.id });
  }
  return {
    db,
    schema,
    createOrg,
    async createDocument(orgName) {
      const org = await createOrg(orgName);
      const ws = await db.forOrg(org.id).createWorkspace({ name: "ws" });
      const doc = await db.forOrg(org.id).createDocument({ workspaceId: ws.id, title: "Checkout" });
      if (!doc) throw new Error("no document");
      return { id: doc.id, orgId: org.id };
    },
    rawQuery: (sql, params = []) => admin.query(sql, params),
    async columnsByTable() {
      const res = await admin.query<{ table_name: string; column_name: string }>(
        "select table_name, column_name from information_schema.columns where table_schema = $1",
        [schema],
      );
      const out: Record<string, string[]> = {};
      for (const { table_name, column_name } of res.rows) (out[table_name] ??= []).push(column_name);
      return out;
    },
    async drop() {
      await db.close();
      await admin.query(`drop schema ${schema} cascade`);
      await admin.end();
    },
  };
}
