// DRILL 1 · extend the protocol, end to end.  Starts RED. Do not edit this file.
//
// Presence should also say whether a peer is TYPING in a prop field. You will touch, in this order:
//   1. packages/contracts/src/index.ts   PresenceState: add `typing`. Think: required or optional?
//                                        The CLIENT message is a strictObject, the SERVER message is loose.
//                                        Which tabs are still open when your change is deployed?
//   2. apps/sync/src/room.ts             presence(): relay it, and keep it for newcomers (welcome.peers)
//   3. packages/peer-client/src/peer.ts  OwnPresence / setPresence (optional for this drill)
//   4. apps/web/src/Canvas.tsx           show it (optional for this drill)
// Then run:  make check   and   sh drills/lesson-2/check.sh
import { expect, test } from "vitest";
import type { ServerMessage } from "@noon/contracts";
import { ClientMessage, ServerMessage as ServerMessageSchema } from "@noon/contracts";
import { manifest } from "@noon/design-system";
import { emptyDoc } from "../../packages/doc-model/src/index.ts";
import { createRoom, type Peer } from "../../apps/sync/src/room.ts";

function peer(id: string): Peer & { inbox: ServerMessage[] } {
  const inbox: ServerMessage[] = [];
  return { actor: { kind: "user", id }, session: { userId: id, orgId: "org", expiresAt: 0 }, mayEdit: true, name: id, inbox, send: (m) => void inbox.push(m) };
}

test("a client may say it is typing; it still may not say who it is", () => {
  expect(ClientMessage.safeParse({ type: "presence", cursor: null, selection: "n1", typing: true }).success).toBe(true);
  expect(ClientMessage.safeParse({ type: "presence", cursor: null, selection: "n1", typing: "yes" }).success).toBe(false);
  expect(ClientMessage.safeParse({ type: "presence", cursor: null, selection: "n1", typing: true, name: "Mallory" }).success).toBe(false);
});

test("a tab that was opened BEFORE your change still works: presence without `typing` is accepted, in both directions", () => {
  expect(ClientMessage.safeParse({ type: "presence", cursor: null, selection: null }).success).toBe(true);
  const fromAnOldServer = { type: "presence", peerId: "p1", actor: { kind: "user", id: "u" }, name: "Ada", cursor: null, selection: null };
  expect(ServerMessageSchema.safeParse(fromAnOldServer).success).toBe(true);
});

test("the room relays `typing` to the others and tells a newcomer about it", () => {
  const room = createRoom({ doc: emptyDoc(), manifest });
  const [ada, bob] = [peer("ada"), peer("bob")];
  room.join(ada);
  room.join(bob);
  // `as never`: until you extend the contract, this argument does not type-check. Remove the cast when it does.
  room.presence(ada, { cursor: null, selection: "n1", typing: true } as never);
  expect(bob.inbox.at(-1)).toMatchObject({ type: "presence", name: "ada", typing: true });

  const late = peer("late");
  room.join(late);
  const welcome = late.inbox[0];
  expect(welcome?.type === "welcome" && welcome.peers?.find((p) => p.name === "ada")).toMatchObject({ typing: true });
});
