// DRILL 2.  Starts RED. Do not edit this file; fix moves.ts.
import { expect, test } from "vitest";
import { doc } from "../../../apps/web/src/doc.fixture.ts";
import { dropToOps } from "./moves.ts";

// The page (apps/web/src/doc.fixture.ts): root [card [button, text], stack (empty), text2].
//
// The whole bug in one sentence: a drag that means "move this here" reaches the document as something else.
// Read the failing assertion before you open moves.ts: how many ops did one drop send, what happened to the node's
// id, and what did the other person's selection (and the AI's cursor, and the audit trail) see in between?

test("one drop is ONE move_node: the same node, its new parent, its final index", () => {
  expect(dropToOps(doc, { nodeId: "text2", targetId: "card", placement: "into" })).toEqual([{ type: "move_node", nodeId: "text2", newParentId: "card", index: 2 }]);
  expect(dropToOps(doc, { nodeId: "text2", targetId: "button", placement: "after" })).toEqual([{ type: "move_node", nodeId: "text2", newParentId: "card", index: 1 }]);
  expect(dropToOps(doc, { nodeId: "button", targetId: "stack", placement: "before" })).toEqual([{ type: "move_node", nodeId: "button", newParentId: "root", index: 1 }]);
});

test("the node keeps its id: a remove and an add would be a NEW node, and everyone else's selection of it would be gone", () => {
  for (const drop of [{ nodeId: "text2", targetId: "stack", placement: "into" as const }, { nodeId: "button", targetId: "text2", placement: "after" as const }]) {
    const ops = dropToOps(doc, drop);
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({ type: "move_node", nodeId: drop.nodeId });
  }
});

test("within one parent the index is the node's FINAL place, counted after it was taken out (SPEC keystone 3)", () => {
  // [card, stack, text2]: card after stack -> [stack, card, text2] = index 1, not 2.
  expect(dropToOps(doc, { nodeId: "card", targetId: "stack", placement: "after" })).toEqual([{ type: "move_node", nodeId: "card", newParentId: "root", index: 1 }]);
  // text2 before stack -> [card, text2, stack] = index 1.
  expect(dropToOps(doc, { nodeId: "text2", targetId: "stack", placement: "before" })).toEqual([{ type: "move_node", nodeId: "text2", newParentId: "root", index: 1 }]);
  // Already inside the card: the end is counted without it.
  expect(dropToOps(doc, { nodeId: "button", targetId: "card", placement: "into" })).toEqual([{ type: "move_node", nodeId: "button", newParentId: "card", index: 1 }]);
});

test("nowhere to go sends nothing: the page, onto itself, into its own subtree, beside the page", () => {
  expect(dropToOps(doc, { nodeId: "root", targetId: "card", placement: "into" })).toEqual([]);
  expect(dropToOps(doc, { nodeId: "card", targetId: "card", placement: "after" })).toEqual([]);
  expect(dropToOps(doc, { nodeId: "card", targetId: "button", placement: "before" })).toEqual([]);
  expect(dropToOps(doc, { nodeId: "text2", targetId: "root", placement: "before" })).toEqual([]);
});

test("it does not predict the room: into a leaf is still built, and refused THERE, once, as one op", () => {
  expect(dropToOps(doc, { nodeId: "text2", targetId: "button", placement: "into" })).toEqual([{ type: "move_node", nodeId: "text2", newParentId: "button", index: 0 }]);
});
