// DRILL 1 · extend the agent's abilities, end to end.  Starts RED. Do not edit this file.
//
// read_tree hands the model the WHOLE document on every call (tools.ts says so: "ponytail: the whole
// tree, every time; a subtree argument when documents outgrow the context window"). Give the agent a
// seventh ability, `read_node`: one node and everything under it. You will touch, in this order:
//   1. apps/worker/src/tools.ts          the tool. Its `shape` is the contract with the model (what it is
//                                        TOLD it may send); `run` is what happens. An unknown id is a refusal
//                                        with a reason, not a throw: a tool answers whatever it is handed.
//   2. apps/worker/src/sdk.ts            SYSTEM_PROMPT names every ability the model has. A tool it is not
//                                        told about is a tool it will not reach for.
//   3. apps/worker/src/sdk.int.test.ts   the init check pins "exactly our six tools". Predict what happens
//                                        to it the moment you add a seventh, then update it.
// Then run:  make check   and   sh drills/lesson-3/check.sh
import { expect, test } from "vitest";
import type { Doc } from "@noon/contracts";
import { manifest } from "@noon/design-system";
import { applyOp, emptyDoc } from "../../packages/doc-model/src/index.ts";
import { probeTools } from "../../apps/worker/src/sdk.ts";
import { buildTools, type AgentPeer } from "../../apps/worker/src/tools.ts";

const EXPECTED = ["add_node", "move_node", "read_manifest", "read_node", "read_tree", "remove_node", "set_prop"];

/** root > Card c1 > Button b1; root > Text t1. Built with the pure applier, read by the tools. */
function aDocument(): Doc {
  let doc = emptyDoc();
  doc = applyOp(doc, { type: "add_node", nodeId: "c1", parentId: "root", index: 0, component: "Card", props: { title: "Payment" } });
  doc = applyOp(doc, { type: "add_node", nodeId: "b1", parentId: "c1", index: 0, component: "Button", props: { label: "Pay" } });
  doc = applyOp(doc, { type: "add_node", nodeId: "t1", parentId: "root", index: 1, component: "Text", props: { text: "Thanks" } });
  return doc;
}
/** A peer that only reads: no write goes anywhere. */
const readOnly = (doc: Doc): AgentPeer => ({ submit: () => ({ ok: false, reason: "not_ready" }), doc });

test("the agent has a seventh ability, read_node, and no other new one", () => {
  expect(buildTools(readOnly(aDocument()), manifest).map((t) => t.name).sort()).toEqual(EXPECTED);
});

test("read_node returns one subtree, refuses an id that names nothing, and refuses arguments it was not told about", async () => {
  const readNode = buildTools(readOnly(aDocument()), manifest).find((t) => t.name === "read_node");
  expect(readNode, "there is no read_node tool yet").toBeDefined();
  if (!readNode) return;

  const card = await readNode.run({ nodeId: "c1" });
  expect(card.ok).toBe(true);
  expect(JSON.parse(card.text)).toMatchObject({ id: "c1", component: "Card", props: { title: "Payment" }, children: [{ id: "b1", component: "Button" }] });
  expect(card.text).not.toContain("t1"); // the sibling is not under c1

  const nowhere = await readNode.run({ nodeId: "nowhere" });
  expect(nowhere.ok).toBe(false); // a refusal with a reason (gone), never a throw
  expect(nowhere.text).toContain("gone");

  expect((await readNode.run({ nodeId: "c1", depth: 2 })).ok).toBe(false); // the shape is strict: an argument the model invented is refused
  expect((await readNode.run({ nodeId: "constructor" })).ok).toBe(false); // a name on Object.prototype finds nothing
});

// The REAL SDK, stopped at its init message (no credentials, no tokens): the schema you wrote must be
// one the SDK can convert, or the WHOLE tool list vanishes without a word (section 4 of the chapter).
test("the real SDK registers all seven, and nothing else", async () => {
  const tools = buildTools(readOnly(aDocument()), manifest);
  expect(tools.map((t) => t.name)).toContain("read_node");
  await expect(probeTools(tools)).resolves.toBeUndefined();
}, 60_000);
