// DRILL 2.  Starts RED. Do not edit this file; fix replica.ts.
import { expect, test } from "vitest";
import { createReplica } from "./replica.ts";

test("an ordinary edit: shown at once, confirmed by its acknowledgement", () => {
  const replica = createReplica();
  replica.receive({ type: "welcome", doc: {}, seq: 0 });
  const mine = replica.local({ key: "gap", value: 1 });
  expect(replica.doc).toEqual({ gap: 1 });
  replica.receive({ type: "op", seq: 1, ...mine });
  expect(replica.pendingCount).toBe(0);
  expect(replica.doc).toEqual({ gap: 1 });
});

test("my edit landed, someone overwrote it, I reconnected: I must end with THEIR value, like everyone else", () => {
  const replica = createReplica();
  replica.receive({ type: "welcome", doc: {}, seq: 0 });
  const mine = replica.local({ key: "gap", value: 1 });

  // The server applied mine at seq 1, but the connection died before I heard. Someone else then set
  // gap to 2 (seq 2). I reconnect: the welcome already contains BOTH edits.
  replica.receive({ type: "welcome", doc: { gap: 2 }, seq: 2 });
  expect(replica.resend()).toEqual([mine]); // same id: the server will recognise it...

  // ...and answers with the ORIGINAL acknowledgement: seq 1, which is older than what I now hold.
  replica.receive({ type: "op", seq: 1, ...mine });

  expect(replica.pendingCount).toBe(0);
  expect(replica.doc).toEqual({ gap: 2 }); // last writer wins BY SEQ. Seq 2 is the last writer.
});
