// DRILL 2.  Starts RED. Do not edit this file; fix cursor.ts.
import { expect, test } from "vitest";
import { page, type Row } from "./cursor.ts";

// Five rows created within the SAME millisecond: a burst of inserts does this all the time.
const rows: Row[] = [1, 2, 3, 4, 5].map((n) => ({
  id: `0000000${String(n)}-0000-4000-8000-000000000000`,
  createdAt: `2026-01-01 10:00:00.1230${String(n)}0+00`, // .123010, .123020, ... microseconds differ
}));

function walk(limit: number): Row[] {
  const seen: Row[] = [];
  let cursor: string | undefined;
  for (let guard = 0; guard < 20; guard++) {
    const result = page(rows, limit, cursor);
    seen.push(...result.items);
    if (result.nextCursor === null) return seen;
    cursor = result.nextCursor;
  }
  throw new Error("paging never ended");
}

test.each([1, 2, 3])("walking the pages %i at a time returns every row exactly once, in order", (limit) => {
  expect(walk(limit).map((r) => r.id)).toEqual(rows.map((r) => r.id));
});
