// DRILL 1 · extend a type, end to end.  Starts RED. Do not edit this file.
//
// The conflict banner says "Commit abc… changed src/pages/noon-….tsx: It uses a React hook." The engineer
// reading it wants to know WHO to talk to. Gitea's push payload carries `pusher: { login }` (learning-tests/
// gitea FINDINGS 2), and today the loop drops it at the door. Carry the pusher's login from the webhook to
// the banner. You will touch, in this order:
//   1. apps/api/src/webhook.ts             PushReading's event gains `pusher: string | undefined`, read from
//                                          `pusher.login`. Validate it (1 to 40 of [A-Za-z0-9._-]); anything
//                                          else is `undefined`, never `invalid`: a strange name is not a reason
//                                          to lose the push. The body is a stranger's until the HMAC says
//                                          otherwise, and a login becomes a row and a line on a screen.
//   2. packages/db/migrations/NNNN_pusher.sql   (NNNN: the next free number) `pusher text` on git_events AND
//                                          document_conflicts, nullable, with the same check the api applies: the
//                                          database holds the rule too.
//   3. packages/db/src/index.ts            GitEvent and GitStore.record carry it (GitEventInput, GitEventRow, the
//                                          insert); recordConflict writes it and ConflictRow reads it.
//   4. packages/contracts/src/index.ts     Conflict gains `pusher: z.string().nullable()`. It is a strictObject:
//                                          until then the api cannot even parse a row that carries one.
//   5. apps/api/src/app.ts                 the webhook route hands `push.pusher` to record().
//   6. apps/worker/src/push.ts             keepConflict records the event's pusher (null when the reconcile found
//                                          the push: nobody delivered it, so nobody is named).
//   7. apps/web/src/conflict.ts            conflictWords gains `who`: the login, or "" when unknown. The banner
//                                          renders it as TEXT, like the commit and the file.
// Then run:  make check   and   sh drills/lesson-5/check.sh
// (`make check` will have opinions: the existing webhook and conflict tests build bodies without a pusher,
// and the type checker will name every place a Conflict is made without one. That list IS the drill.)
import { createHmac } from "node:crypto";
import { expect, test } from "vitest";
import { Document, Org, Workspace, type Conflict } from "@noon/contracts";
import { TEST_WEBHOOK_SECRET, useTestServer } from "../../apps/api/src/testing.ts";
import { readPush } from "../../apps/api/src/webhook.ts";
import { conflictWords } from "../../apps/web/src/conflict.ts";

const ctx = useTestServer();
const A = "a".repeat(40);
const B = "b".repeat(40);
const json = { "content-type": "application/json" };
const push = (fields: Record<string, unknown> = {}): Buffer =>
  Buffer.from(JSON.stringify({ ref: "refs/heads/main", before: A, after: B, commits: [], repository: { full_name: "noon/sample-app" }, ...fields }));
/** What Gitea sends: the JSON body, X-Gitea-Signature = hex HMAC-SHA256 of the raw bytes, a delivery id, the event name. */
const deliver = (body: Buffer, delivery: string): Promise<Response> =>
  ctx.fetch("/webhooks/gitea", {
    method: "POST",
    headers: { ...json, "x-gitea-event": "push", "x-gitea-delivery": delivery, "x-gitea-signature": createHmac("sha256", TEST_WEBHOOK_SECRET).update(body).digest("hex") },
    body,
  });

async function aDocument(owner: string): Promise<Document> {
  const as = { "x-dev-user": owner, ...json };
  const org = Org.parse(await (await ctx.fetch("/orgs", { method: "POST", headers: as, body: JSON.stringify({ name: "Pushers" }) })).json());
  const ws = Workspace.parse(await (await ctx.fetch(`/orgs/${org.id}/workspaces`, { method: "POST", headers: as, body: JSON.stringify({ name: "ws" }) })).json());
  return Document.parse(await (await ctx.fetch(`/orgs/${org.id}/workspaces/${ws.id}/documents`, { method: "POST", headers: as, body: JSON.stringify({ title: "Checkout" }) })).json());
}

test("a verified push says who pushed; a login the rule refuses is dropped, and the push is still an event", () => {
  expect(readPush(push({ pusher: { login: "eng" } }))).toEqual({ kind: "event", ref: "refs/heads/main", before: A, after: B, pusher: "eng" });
  // Not `invalid`: the commit is real whatever the name looks like. Not stored either: it becomes a row and a screen.
  for (const login of ["<img src=x onerror=alert(1)>", "", "x".repeat(41), 7, null, undefined]) {
    expect(readPush(push({ pusher: { login } })), JSON.stringify(login)).toEqual({ kind: "event", ref: "refs/heads/main", before: A, after: B, pusher: undefined });
  }
  expect(readPush(push())).toEqual({ kind: "event", ref: "refs/heads/main", before: A, after: B, pusher: undefined });
});

test("the pusher rides the event into git_events, under the database's own rule", async () => {
  expect((await deliver(push({ pusher: { login: "eng" } }), "who-1")).status).toBe(202);
  const columns = await ctx.db.columnsByTable();
  expect(columns["git_events"]).toContain("pusher");
  expect(columns["document_conflicts"]).toContain("pusher");
  const rows = ((await ctx.db.rawQuery("select pusher from git_events where delivery_id = $1", ["who-1"])) as { rows: { pusher: string | null }[] }).rows;
  expect(rows).toEqual([{ pusher: "eng" }]);
  // The check constraint is the database's copy of the api's rule: a row that skips the api is refused too.
  await expect(ctx.db.rawQuery("insert into git_events (ref, before_sha, after_sha, pusher) values ('refs/heads/x', $1, $2, $3)", [A, B, "<img>"])).rejects.toThrow(/check/u);
});

test("a refused push names its pusher on the canvas, as text; a push nobody delivered names nobody", async () => {
  const doc = await aDocument("ann@example.com");
  const store = ctx.db.db.gitStore();
  const refused = { commit: B, file: `src/pages/noon-${doc.id}.tsx`, reason: "hook", detail: "line 2: a hook", pusher: "eng" } as const;
  await expect(store.recordConflict(doc.id, refused as unknown as Omit<Conflict, "at">)).resolves.toBeUndefined();
  const res = await ctx.fetch(`/documents/${doc.id}/conflict`, { headers: { "x-dev-user": "ann@example.com" } });
  expect(res.status).toBe(200);
  const { conflict } = (await res.json()) as { conflict: Conflict & { pusher?: string | null } };
  expect(conflict).toMatchObject({ commit: B, reason: "hook", pusher: "eng" });
  expect(conflictWords(conflict)).toMatchObject({ who: "eng", commit: B }); // `who` is a string the banner renders as a text node

  // Found by the reconcile (no delivery, no pusher): the banner still shows, and names nobody.
  await store.recordConflict(doc.id, { ...refused, pusher: null } as unknown as Omit<Conflict, "at">);
  const again = (await (await ctx.fetch(`/documents/${doc.id}/conflict`, { headers: { "x-dev-user": "ann@example.com" } })).json()) as { conflict: Conflict };
  expect(again.conflict).toMatchObject({ pusher: null });
  expect(conflictWords(again.conflict)).toMatchObject({ who: "" });
});
