// DRILL 2.  Starts RED. Do not edit this file; fix run.ts.
import { expect, test } from "vitest";
import { runOnce, type FakePeer } from "./run.ts";

const fakePeer = (): FakePeer => ({ status: "connecting", closedBecause: undefined, close() { this.status = "closed"; this.closedBecause ??= "closed_by_caller"; } });
const never = new AbortController().signal;
/** A model that never finishes by itself: it ends only when the run's signal says so, as the real SDK does. */
const forever = (signal: AbortSignal): Promise<string> => new Promise((_, reject) => { signal.addEventListener("abort", () => { reject(new Error("aborted")); }, { once: true }); });

test("an ordinary run: the peer goes live, the model runs, the peer is closed at the end", async () => {
  const peer = fakePeer();
  setTimeout(() => { peer.status = "live"; }, 30);
  await expect(runOnce({ peer, runAgent: () => Promise.resolve("done"), cancelled: never })).resolves.toBe("done");
  expect(peer.status).toBe("closed");
});

test("a cancel ends the run as `cancelled` and stops the model", async () => {
  const peer = fakePeer();
  peer.status = "live";
  const cancelled = new AbortController();
  let modelStopped = false;
  const running = runOnce({ peer, runAgent: (signal) => { signal.addEventListener("abort", () => { modelStopped = true; }); return forever(signal); }, cancelled: cancelled.signal });
  setTimeout(() => { cancelled.abort(); }, 30);
  await expect(running).rejects.toMatchObject({ reason: "cancelled" });
  expect(modelStopped).toBe(true);
});

// Found by the E3.2 re-verify. A run that ends BEFORE its peer ever connects (the sync server is down at
// the start) must leave nothing behind: no timer, no loop, nothing that keeps ticking for the life of the
// worker. The test counts what is scheduled AFTER the run has ended.
test("a run that ends before its peer ever connects leaves no timer behind", async () => {
  const peer = fakePeer(); // never becomes live
  await expect(runOnce({ peer, runAgent: forever, cancelled: never, connectTimeoutMs: 100 })).rejects.toMatchObject({ reason: "sync_unreachable" });

  const real = globalThis.setTimeout;
  let scheduled = 0;
  globalThis.setTimeout = ((...args: Parameters<typeof setTimeout>) => { scheduled++; return real(...args); }) as typeof setTimeout;
  try {
    await new Promise((r) => real(r, 200));
  } finally {
    globalThis.setTimeout = real;
    peer.status = "live"; // whatever is still waiting for that may stop now: the process must not be kept alive by a drill
  }
  expect(scheduled).toBe(0);
});
