// DRILL 1 · extend the registry, end to end.  Starts RED. Do not edit this file.
//
// The layers tree removes a node with Delete or Backspace (E10.3); the canvas does not: a person who selected a
// Button by clicking it on the sheet has to reach for the tree or the inspector's Remove. Give the canvas the key,
// the way every key in the editor is given (chapter, section 8): ONE row in the registry drives the handler AND
// the `?` sheet, and the handler sends ONE remove_node through Canvas's `submit`, never a second write path.
// You will touch, in this order:
//   1. apps/web/src/shortcuts.ts     a new entry { scope: "canvas", action: "remove", keys: ["Delete", "Backspace"], does: ... }.
//                                    ActionOf<"canvas"> now includes "remove" (the type is derived from the table), and
//                                    the sheet lists the row under Canvas with no change to ShortcutSheet.tsx.
//   2. apps/web/src/Surface.tsx      `Props` gains `onRemove: (id: string) => void`; the keydown switch gains
//                                    `case "remove":` which calls it for the selected node, and NEVER for the page
//                                    (ROOT_ID has no parent; the replica would refuse it, but the surface can see that).
//   3. apps/web/src/Canvas.tsx       passes `onRemove={(id) => { submit({ type: "remove_node", nodeId: id }); }}`:
//                                    the same `submit` every other gesture uses, so the replica's verdict is at once
//                                    and the room's comes back as a notice like any other edit's.
// Then run:  make check   and   sh drills/lesson-10/check.sh
//
// Predict first: the selected node was removed by someone else a moment before you press Delete. What does the
// replica answer, what does the room answer, and what does the person see? (Section 1 has "DERIVED, not stored";
// usePeer.ts has `quiet`.)
import { readFileSync } from "node:fs";
import { expect, test } from "vitest";
import { actionFor, SHORTCUTS, shortcutsIn, type Shortcut } from "../../apps/web/src/shortcuts.ts";

const root = new URL("../../", import.meta.url);
const read = (path: string): string => readFileSync(new URL(path, root), "utf8");
const press = (key: string, mods: Partial<Pick<KeyboardEvent, "altKey" | "shiftKey" | "ctrlKey" | "metaKey">> = {}) => ({ key, altKey: false, shiftKey: false, ctrlKey: false, metaKey: false, ...mods });
/** The registry's own rule (shortcuts.test.ts): one keydown must never mean two things. Your row must keep it. */
const collide = (a: Shortcut, b: Shortcut): boolean =>
  (a.scope === b.scope || a.scope === "global" || b.scope === "global") &&
  a.keys.some((key) => b.keys.includes(key)) &&
  (a.alt ?? false) === (b.alt ?? false) &&
  (a.shift === undefined || b.shift === undefined || a.shift === b.shift);

test("the registry: Delete and Backspace on the canvas are the action `remove`, with a sentence for the sheet", () => {
  // Compared as strings: while the drill is red the type ActionOf<"canvas"> does not know "remove", and the test must fail HERE.
  expect(String(actionFor("canvas", press("Delete")))).toBe("remove");
  expect(String(actionFor("canvas", press("Backspace")))).toBe("remove");
  expect(actionFor("canvas", press("Delete", { ctrlKey: true }))).toBeNull(); // a browser chord stays the browser's
  const row = shortcutsIn("canvas").find((s) => s.action === "remove");
  expect(row, "a canvas/remove row in SHORTCUTS").toBeDefined();
  expect(row?.does ?? "").toMatch(/remove/iu);
});

test("the registry still has no two rows that one keydown could mean", () => {
  const collisions: string[] = [];
  for (const [i, a] of SHORTCUTS.entries()) for (const b of SHORTCUTS.slice(i + 1)) if (collide(a, b)) collisions.push(`${a.scope}/${a.action} vs ${b.scope}/${b.action}`);
  expect(collisions).toEqual([]);
});

// The drills run without a browser, so the cheapest honest check is the components' text: the surface asks the
// registry and switches on the action, and the op is built in Canvas.tsx, beside every other op.
test("the surface answers the action through a prop, and the canvas turns it into ONE remove_node through submit", () => {
  // Tested as booleans with a message, not toMatch: a failed toMatch would print the whole component.
  const surface = read("apps/web/src/Surface.tsx");
  expect(/onRemove\s*:\s*\(id: string\)\s*=>\s*void/u.test(surface), "Surface.tsx: Props gains onRemove: (id: string) => void").toBe(true);
  expect(/case "remove":/u.test(surface), 'Surface.tsx: the keydown switch gains case "remove":').toBe(true);
  const canvas = read("apps/web/src/Canvas.tsx");
  expect(/onRemove=\{[^}]*submit\(\{\s*type:\s*"remove_node"/u.test(canvas), "Canvas.tsx: onRemove submits ONE remove_node through submit").toBe(true);
});
