"""Builds docs/handbook/lesson-6.html. Every code block is cut from the real repo by anchor text,
so the page cannot show code that does not exist; a missing anchor fails the build."""
import html, os, pathlib, re, subprocess
here = pathlib.Path(__file__).resolve()
root = pathlib.Path(os.environ.get("NOON_ROOT") or (here.parents[2] if (here.parents[2] / "SPEC.md").exists() else pathlib.Path.cwd()))
out = pathlib.Path(os.environ.get("NOON_OUT") or root / "docs/handbook")
commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True).stdout.strip()

def cut(path, start, end=None, include_end=False):
    src = (root / path).read_text()
    i = src.index(start)
    j = len(src) if end is None else src.index(end, i + len(start)) + (len(end) if include_end else 0)
    body = src[i:j].rstrip()
    return (f'<p class="label">From <span class="mono">{path}</span></p>'
            f'<div class="scroll"><pre><code>{html.escape(body)}</code></pre></div>')

def shell(title, body):
    return f'<p class="label">{title}</p><div class="scroll"><pre class="out"><code>{body}</code></pre></div>'

def vs(rows, head=("TypeScript (this repo)", "Java", "Python")):
    body = "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows)
    return f'<div class="scroll"><table><tr>{"".join(f"<th>{h}</th>" for h in head)}</tr>{body}</table></div>'

def case(title, body): return f'<div class="break"><p class="label">Case study · found by review, by a learning test, or by a test that was written to refute a claim</p><p><strong>{title}</strong></p>{body}</div>'
def note(body): return f'<p class="note">{body}</p>'
m = lambda s: f"<span class='mono'>{s}</span>"

S = []
def section(sid, title, *parts): S.append((sid, title, "".join(parts)))

section("map", "The map: what durability means here",
  "<p>Epics 2 to 5 built a room that orders every edit and three kinds of peer that write through it. None of it survived a crash: F8 saved the document when a room went idle, and a sync process killed mid-edit lost everything since. Epic 6 makes one promise and keeps it under two faults. <strong>The promise (F18): no acknowledged edit is ever lost, and no edit is ever applied twice.</strong> The faults: the sync process dies (<code>kill -9</code>, no goodbye), and the database goes away (stopped, or paused so that every query hangs). A third feature (F19) makes the promise affordable: a document with ten thousand journaled edits still opens in under two seconds.</p>",
  vs([("1", m("packages/db/migrations/0012_op_journal.sql"), m("packages/db/src/index.ts"), "the op journal: an append-only table with two unique keys told apart by name; <code>append</code>, <code>find</code>, <code>everAdded</code>, <code>since</code>"),
      ("2", m("apps/sync/src/room.ts"), "", "the room's step 3 becomes <em>durable, then applied, then announced</em>; a forgotten resend is asked of the journal; keystone 4 is asked of the journal"),
      ("3", m("apps/sync/src/room.ts"), m("packages/contracts/src/index.ts"), "a failed append turns the room read-only: one <code>status</code> to everyone, no acknowledgement to anyone, and <code>recover()</code> replays the journal before saying writable"),
      ("4", m("apps/sync/src/server.ts"), m("packages/peer-client/src/peer.ts"), "a journal call bounded by a timeout; a retry loop that calls <code>recover()</code>; a client that holds its edits, refuses new ones, and sends the held ones on \"writable\""),
      ("5", m("apps/web/src/Canvas.tsx"), m("apps/worker/src/tools.ts"), m("apps/worker/src/push.ts") + ": every kind of peer hears read-only through one contract: the canvas shows an alert, the AI's tool call is refused, the git peer's event waits"),
      ("6", m("apps/sync/src/snapshots.ts"), m("packages/db/migrations/0013_snapshot_seq.sql"), "snapshots to MinIO on a cadence and on last leave, keyed so that string order is numeric order, written once (<code>IfNoneMatch</code>), named in Postgres only after they exist"),
      ("7", m("apps/sync/src/server.ts"), "", "opening a document: the newest snapshot, then only the journal rows after it; F8's idle save is deleted"),
      ("8", m("scripts/chaos/no-loss.ts"), m("scripts/chaos/kill-sync-no-loss.ts"), m("scripts/chaos/postgres-down-read-only.ts") + ": the promise as a pure check over a ledger and the journal, and two runs that break the real stack")], head=("Step", "Where", "And", "What happens")),
  "<p>Four ideas carry the epic. <strong>A write-ahead log</strong> (section 1): the op is written to a place that survives the process <em>before</em> the process tells anyone, so the acknowledgement a peer sees is a fact about the database, not about memory. <strong>At-least-once plus an idempotent resend is exactly-once</strong> (section 2): a client that never heard its answer sends the same op again with the same id, and the journal's unique key turns the second sending into the first answer. <strong>Fail visibly, recover from the log</strong> (section 3): when the log cannot be written the room stops acknowledging and says so; when it can, the room reads what landed without it before it writes again. <strong>A snapshot is a cache of the log</strong> (section 4): losing one loses nothing, so it is written best-effort and never retried, and the pointer to it is written only after the object exists.</p>",
  vs([("an append-only Postgres table as the write-ahead log, the room as the single writer", "Kafka as the log with one producer per partition; or an event store (Axon, EventStoreDB)", "the same table with psycopg; or an event store"),
      ("dedupe by <code>(document, sender, opId)</code> unique key, answered with the original row", "an idempotency key table in the same transaction as the write", "the same"),
      ("read-only as a broadcast state with a replay-before-writable recovery", "a circuit breaker that half-opens, plus a catch-up read", "the same idea; <code>pybreaker</code> for the breaker"),
      ("snapshots as gzipped objects with a conditional put and a pointer row", "an S3 checkpoint with <code>ifNoneMatch(\"*\")</code> in SDK v2; Kafka Streams' state store checkpoint", "boto3 <code>put_object(IfNoneMatch=\"*\")</code>")], head=("This repo", "Java world", "Python world")))

section("journal", "1 · The journal: durable before anyone hears of it",
  "<p>The room already had a persist step between validating an op and applying it (lesson 2 awaited it so that ordering under a slow database could be tested). Epic 6 gives that step a table and a contract, and the room's whole promise follows from <em>where</em> the step sits: an op is written to <code>op_journal</code>, and only if the write succeeds is it applied to the in-memory document, remembered, and broadcast. The sender's own copy of the broadcast is its acknowledgement. So an acknowledged op is, by construction, a row that survives the process.</p>",
  cut("packages/db/migrations/0012_op_journal.sql", "-- E6.1a (F18)"),
  "<p>Read the two constraints as two different <em>facts</em>. <code>op_journal_seq</code> on <code>(document_id, seq)</code> says one op per number: if an insert breaks it, someone else is numbering this document, which must never happen with one room per document, and the right answer is to refuse and stop writing. <code>op_journal_op</code> on <code>(document_id, actor_id, op_id)</code> says one row per sender's opId: if an insert breaks it, the room forgot a resend, and the right answer is the original row. Same SQLSTATE (23505, unique violation) for both, so the code cannot tell them apart by <em>code</em>: it reads the <em>constraint name</em> the driver exposes (<code>learning-tests/postgres</code>, finding 1).</p>",
  cut("learning-tests/postgres/test.ts", "// 1. Duplicate insert violating a unique constraint", "\n//\n// 2. After a unique-violation"),
  cut("packages/db/src/index.ts", "  /**\n   * E6.1a: journals an accepted op", "  /** What this sender's opId became, if it was ever journaled. */"),
  cut("packages/db/src/index.ts", "      async append(orgId, documentId, { seq, opId, actor, op }, claim)", "      find: async (orgId, documentId, actorId, opId) =>"),
  "<p>Three TypeScript things in that <code>append</code>. <strong><code>insert ... select ... from documents where org_id = $1 and id = $2</code></strong> is lesson 1's tenancy rule applied to the journal: the row is written <em>from</em> the document's row, so a document of another org (or one deleted meanwhile) takes no op; <code>rowCount !== 1</code> is the tell. <strong><code>\"constraint\" in err</code></strong> is the <code>in</code> operator used as a type guard: <code>err</code> is <code>unknown</code> in a <code>catch</code>, <code>instanceof Error</code> narrows it to <code>Error</code>, and <code>\"constraint\" in err</code> narrows it further to <code>Error &amp; Record&lt;\"constraint\", unknown&gt;</code>, so the comparison compiles without a cast. Java would catch <code>PSQLException</code> and read <code>getServerErrorMessage().getConstraint()</code>; psycopg gives <code>err.diag.constraint_name</code>. <strong>The row type is a Zod schema with a <code>.transform</code></strong>: <code>seq</code> is a <code>bigint</code> in Postgres and the driver hands it over as a <em>string</em> (the same finding lesson 3 hit for usage counts), so <code>JournalRow</code> converts once, at the edge, and the rest of the process sees a number.</p>",
  cut("packages/db/src/index.ts", "// seq is a bigint: a string from the driver", "const JOURNAL_COLUMNS"),
  "<p>Now the room's side. The <code>Journal</code> type is what the room needs and nothing about Postgres: four functions, injected. Without one (tests, the simulator) nothing is kept, and the room behaves as it did in lesson 2.</p>",
  cut("apps/sync/src/room.ts", "/**\n * Where accepted ops are made durable", "export type RoomLimits"),
  cut("apps/sync/src/room.ts", "  /**\n   * Makes an op durable BEFORE anyone hears of it.", "  rate?: Partial<RateLimit>;"),
  cut("apps/sync/src/room.ts", "    // 3. Durable first, then applied, then announced.", "  return {\n    get peerCount()"),
  cut("apps/sync/src/room.ts", "  /** An op the journal holds and the room does not yet", "  function storageFailed"),
  "<p>Read step 3 slowly, because the whole epic is in its order. <code>sequenced</code> is built with <code>seq + 1</code>, but <code>seq</code> itself is not moved: the number is only <em>taken</em> inside <code>accept</code>, after the append resolved. A failed write therefore leaves no gap, and the next op gets the same number. <code>journal?.append(sequenced)</code> is optional chaining on a <em>call</em>: with no journal it evaluates to <code>undefined</code> and the <code>await</code> is a no-op. <code>let original;</code> with no type and no initialiser is not <code>any</code>: TypeScript infers its type from the assignments it can see (an \"evolving\" <code>let</code>), so after the <code>try</code> it is <code>SequencedOp | undefined</code>. And <code>accept</code> is the one function that applies, numbers, remembers and announces, so that <code>recover()</code> in section 3 can do exactly what a fresh op does, to a row it found in the journal.</p>",
  "<p>The append happens <em>inside</em> the room's one-at-a-time queue. That is what makes the journal's order the broadcast order under concurrent submits: op 2 is not even validated until op 1's append has resolved. It costs one database round trip per op on the critical path (about a millisecond on the same machine, tens over a network), which is the price of the promise; batching appends is the named upgrade, and it would move the acknowledgement, not remove the rule.</p>",
  cut("apps/sync/src/room.test.ts", 'test("journal: every accepted op is journaled BEFORE', 'test("journal: a resend after the room restarted'),
  cut("packages/db/src/journal.int.test.ts", 'test("a sender\'s opId again is answered', 'test("the journal is org-scoped'),
  vs([("<code>\"constraint\" in err</code> after <code>err instanceof Error</code>: the <code>in</code> operator narrows", "<code>catch (PSQLException e) { e.getServerErrorMessage().getConstraint() }</code>", "<code>except errors.UniqueViolation as e: e.diag.constraint_name</code>"),
      ("<code>let original;</code> typed by its later assignments", "no equivalent; declare the type", "no equivalent; a plain name"),
      ("<code>journal?.append(op)</code>: optional chaining on a call", "<code>Optional.map(j -&gt; j.append(op))</code>", "<code>journal.append(op) if journal else None</code>"),
      ("a Zod row schema with <code>.transform</code> to convert <code>bigint</code> text once", "a <code>RowMapper</code> that calls <code>getLong</code>", "a <code>typecaster</code> on the cursor, or <code>int()</code> in the mapper"),
      ("<code>insert ... select from documents where org_id = $1</code>: the tenant check in the write", "the same SQL; JPA cannot express it", "the same SQL")]),
  case("E2.3's known limit: a client that resent its own forgotten op with a forged <code>baseSeq</code> got a second seq.",
       "<p>Lesson 2 named it and could not fix it: the room's memory of applied ops is bounded, and once an op fell out of it a resend looked like a new op. The room's stale guard (<code>baseSeq &lt; forgottenUpTo</code>) caught honest clients, but a client claiming to have seen everything walked past it. The journal's unique key is the fix, and it is free: the append that would have created the duplicate breaks <code>op_journal_op</code>, the original row comes back, and the room answers with it and applies nothing. The test pushes an op out of a two-entry memory and resends it with <code>baseSeq = room.seq</code>.</p>"),
  case("A key on <code>(document, opId)</code> would have refused legitimate ops.",
       "<p>The obvious dedupe key is the opId. But every broadcast shows every opId to every peer, so a peer that saw another's opId could send it as its own, and, more to the point, a bare-opId key would treat that as a resend and answer with the other peer's op. Lesson 2's memory was already keyed by sender for this reason; the journal's constraint is keyed the same way, and the database test proves that two senders may use one opId and both are written.</p>"),
  note("<strong>The principle:</strong> an acknowledgement is a promise about the future (\"this will still be true after a crash\"), so it may only be given by the thing that will still be there after the crash. The room gives it after the database has spoken, never before. Section 8's first row is what happens when the order is reversed, and drill 2 makes you find it."))

section("resend", "2 · Exactly once, again: the resend, the forgotten op, and the id that never returns",
  "<p>Lesson 2 already had exactly-once over a lying connection: a client keeps its opIds, resends what was not answered, and the room answers a resend from memory. Epic 6 removes the word \"memory\" from that sentence. With a journal, every question the room used to answer from a bounded map can be answered from a table, including after a restart.</p>",
  cut("apps/sync/src/room.ts", "  // What the room can still vouch for:", "  const rememberedNoOps"),
  cut("apps/sync/src/room.ts", "    // 1. Dedupe FIRST.", "    // 2. The document's rules first"),
  "<p>The dedupe is a two-level cache. The <code>Map</code> answers most resends in memory. An op whose <code>baseSeq</code> is behind everything the room remembers used to be refused as <code>stale</code> (\"I cannot tell whether I applied this\"); now the journal is asked with <code>find</code>: found, the original answer; not found, the op is judged now like any other. The <code>stale</code> path is kept for a room without a journal, so the simulator and lesson 2's tests still hold. Note the shape of the error handling: a journal that cannot be <em>read</em> refuses the op as <code>unavailable</code>, the same reason as a failed write, because in both cases the room does not know and must not guess.</p>",
  cut("apps/sync/src/room.ts", "    // Keystone 4: validate() only sees the document as it is", "    // An op that changes nothing"),
  "<p>Keystone 4 says a node id that was removed is never added again, or an edit meant for the dead node lands on the new one. <code>validate</code> only sees the document as it is; it cannot know what was removed. Lesson 5's git peer worked around it with <code>git log -p</code> for pushed pages. Now the room asks the journal for every actor: one indexed read per add, through a partial index on <code>(document_id, op -&gt;&gt; 'nodeId') where op -&gt;&gt; 'type' = 'add_node'</code>. The query is spelled exactly as the index is, because Postgres uses a partial index only when the query's predicate implies the index's.</p>",
  "<p>The last piece is <em>opening</em>. A room reloaded from a saved document knows only that document's <code>seq</code>. If the process died after journaling ops the save never saw, the room would number from a stale seq and every append would break <code>op_journal_seq</code>. So opening replays <code>since(seq)</code> before the room exists:</p>",
  cut("apps/sync/src/server.ts", "    // The contract checked each node's shape.", "    // A timed-out append may still land later"),
  cut("apps/sync/src/room.test.ts", 'test("journal: a client that resends its own forgotten op with a FORGED', 'test("journal: after a restart, a FORGED-baseSeq'),
  cut("apps/sync/src/room.test.ts", 'test("journal: a node id that was added and removed', 'test("journal: if the journal cannot be read'),
  cut("apps/sync/src/journal.int.test.ts", 'test("a resent op gets its original seq after a restart'),
  vs([("a <code>Map</code> in front of a table: the memory answers, the table is the truth", "Caffeine in front of JPA; the same discipline about which one is the truth", "<code>functools.lru_cache</code> in front of a query"),
      ("<code>create index ... where op -&gt;&gt; 'type' = 'add_node'</code>: a partial index on a JSON path", "the same SQL; Hibernate cannot express it", "the same; Django <code>Index(condition=...)</code>"),
      ("<code>for (const row of await store.since(...)) applyOpInto(doc, row.op)</code>", "a <code>for</code> over a <code>List</code> from a repository", "a <code>for</code> over <code>cursor.fetchall()</code>"),
      ("<code>refuse(\"unavailable\")</code> on a read failure too", "the same rule: unknown is not \"no\"", "the same")]),
  case("E5.3b's gap: an id removed on the canvas that never reached git could be re-added by a push.",
       "<p>Lesson 5 computed <code>earlierIds</code> from the repository's history, so an id that lived and died on the canvas <em>between</em> two generations of the file was unknown to the git peer, and a push could bring it back. The room now refuses it for every actor from the journal, so the git peer's push is refused op by op (<code>duplicate_node</code>). What it does <em>not</em> yet do is turn that refusal into a whole-page conflict banner; folding the journal's ids into <code>earlierIds</code> is the named follow-up.</p>"),
  case("<code>replica.ts</code>'s <code>everSent</code> rule could now go, and was left.",
       "<p>The peer-client refused to resend an op it had once sent under a seq it no longer held, because a room might apply it twice. With the journal, the room cannot. The rule is now redundant but harmless, and removing it belongs to a peer-client bead, not to a sync one: the commit says so, which is how a codebase avoids two teams reaching for the same file.</p>"),
  note("<strong>What \"exactly once\" means here, precisely:</strong> a client may send an op any number of times; the room applies it at most once; and every sending after the first is answered with the same <code>seq</code>. \"At most once\" comes from the unique key; \"at least once\" comes from the client's resend; the answer being <em>the same</em> comes from storing the original row and returning it. Remove any one of the three and the promise is gone."))

section("readonly", "3 · The database is gone: read-only, and the recovery that reads before it writes",
  "<p>SPEC §4 says: <em>Postgres or MinIO down: rooms refuse new ops with a visible read-only status; nothing is silently dropped.</em> E6.1b is that row, and it turned out to be the most delicate design in the epic, because two things must hold at once: <strong>no acknowledgement while the journal cannot be written</strong> (an acknowledgement is a promise), and <strong>no op lost</strong> (the person's edit is theirs). The resolution is that the room refuses and the <em>client</em> holds.</p>",
  cut("packages/contracts/src/index.ts", "  // To EVERY peer when the room's storage fails", "]);", True),
  cut("apps/sync/src/room.ts", "  // E6.1b (SPEC §4): the journal failed", "  // Budgets are kept per ACTOR"),
  cut("apps/sync/src/room.ts", "  function storageFailed", "    // 1. Dedupe FIRST."),
  "<p>Order matters in <code>storageFailed</code>: the <code>status</code> goes to every peer <em>before</em> the refusal that caused it goes to the sender. So when the sender's client sees <code>rejected: unavailable</code> it already knows the room is read-only and treats the refusal as \"hold this\", not \"resync\". And read the placement of the <code>readOnly</code> check in <code>handle</code>: before the dedupe. Even an answer from memory is an acknowledgement, and a read-only room gives none, not for a fresh op, not for a no-op, not for a resend it remembers. The test spells that list out.</p>",
  cut("apps/sync/src/room.ts", "    /**\n     * Leaves read-only if the journal answers again.", "    /** Resolves when every op submitted so far"),
  "<p><code>recover()</code> is the design decision of the bead. The obvious version is a health probe: ping the database, and if it answers, say \"writable\". It was rejected for two failures it would cause. First, an append can <em>land</em> and still throw (the connection dropped after the commit): the room refused the op, the client holds it, and if the room goes writable without reading, the client's resend hits <code>op_journal_op</code>, gets the original row, and the room applies it, which is fine, but every other peer never heard the op, because the original broadcast never happened. Second, a rival row at the room's next seq (section 1's other constraint) would keep the room refusing until a restart. So <code>recover()</code> first <em>replays</em> <code>since(seq)</code> through <code>accept</code>, the same function a fresh op goes through, and only then says writable. It takes its turn in the queue, so no op is judged halfway through a replay.</p>",
  "<p>Two idioms. <code>tail = done.then(() =&gt; undefined, () =&gt; undefined)</code> puts the recovery on the queue and makes sure a failure in it cannot jam the queue for every later op (<code>then</code> with two arguments handles both outcomes). <code>return done.catch(() =&gt; false)</code> gives the caller a boolean that never rejects. The room has no clock, so it cannot retry by itself; <code>onReadOnly</code> tells the server to start.</p>",
  cut("apps/sync/src/server.ts", "    // A timed-out append may still land later", "    const snapshotFrom"),
  cut("apps/sync/src/server.ts", "  function bounded<T>", "  async function serve("),
  "<p><code>bounded</code> is the timeout: <code>Promise.race</code> between the work and a timer that rejects, with <code>finally</code> clearing the timer so a fast answer does not leave one ticking. A <em>paused</em> database (the second half of the chaos check) never refuses a query; it hangs, and without this the room would wait for ever with every peer's ops queued behind it. Note what the timeout means: \"treat as failed\", not \"it failed\": the append may still land later, which is exactly why <code>recover()</code> reads before it writes. <code>heal</code> is an async IIFE (<code>void (async () =&gt; { ... })()</code>) that loops with a <code>setTimeout</code> promise whose timer is <code>unref()</code>'d so it cannot keep the process alive at shutdown.</p>",
  "<p><strong>The client's half.</strong> peer-client learns one flag from the wire and does four things with it.</p>",
  cut("packages/peer-client/src/peer.ts", "  // E6.1b: the room cannot make edits durable.", "  // Whoever asked about an op's fate"),
  cut("packages/peer-client/src/peer.ts", "  /** Writes whatever the replica says may go out now.", "  // --- presence: who else is here."),
  cut("packages/peer-client/src/peer.ts", '    if (message.type === "status") {', "    const [revisionBefore, pendingBefore]"),
  cut("packages/peer-client/src/peer.ts", "    // A refusal from a room that said it is read-only: held", "    // The room's budget is spent"),
  cut("packages/peer-client/src/peer.ts", "      // Said at once, not queued behind a room that cannot save", "      const waitingBefore"),
  "<p>Held ops are <em>not sent again and not resynced</em>: <code>flush</code> sends nothing while read-only, and a refusal with <code>unavailable</code> under a read-only room does not trigger the resync a bare <code>unavailable</code> would. New edits are refused at once with <code>read_only</code>, so a person sees why and a program stops. And \"writable\" simply calls <code>flush</code>: the held ops go out in their original order with their original opIds, so if any of them landed during the outage, the room answers from the journal. The watchdog is turned off while read-only, a named ponytail: a connection that dies half-open then is noticed by the next edit or by presence going quiet.</p>",
  "<p><strong>Every kind of peer hears it through the one contract.</strong> The canvas shows the status and an alert and disables the library. The AI's tool call gets <code>read_only</code> with a hint to stop. The git peer throws <code>WaitAgain</code>, and its event goes back to <code>pending</code> instead of <code>failed</code>: a push is never lost to an outage, because lesson 5's reconcile would never re-record it.</p>",
  cut("apps/web/src/Canvas.tsx", "          {/* E6.1b: the room's storage is down.", "          <ConflictBanner"),
  cut("apps/web/src/Canvas.tsx", "            <LibraryPanel doc={doc}", "\n"),
  cut("apps/worker/src/tools.ts", '    read_only: "The document is read-only', "  }));"),
  cut("apps/worker/src/push.ts", "        // E6.1b: the room cannot save. Not a conflict", "        // The replica refused it locally"),
  cut("apps/worker/src/git.ts", "      if (err instanceof WaitAgain) {", "      log(`${event.ref} ${event.after} failed"),
  cut("apps/sync/src/room.test.ts", 'test("recover: an append that LANDED although its reply was lost', 'test("recover: a rival\'s row'),
  cut("packages/peer-client/src/peer.test.ts", 'test("read-only: ops the room refused are HELD', 'test("read-only: a held op the room REPLAYS'),
  cut("apps/sync/src/read-only.int.test.ts", "// integration:read-only-reaches-every-peer", "// integration:read-only-on-hung-journal"),
  vs([("<code>Promise.race([work, late]).finally(() =&gt; clearTimeout(timer))</code>", "<code>CompletableFuture.orTimeout</code>; the work is not cancelled either", "<code>asyncio.wait_for</code>, which DOES cancel the task: a real difference"),
      ("<code>void (async () =&gt; { while (...) { await sleep(); await room.recover(); } })()</code>", "a <code>ScheduledExecutorService</code> task that reschedules itself", "<code>asyncio.create_task</code> of a loop"),
      ("<code>setTimeout(resolve, ms).unref()</code>", "a daemon thread", "no equivalent needed; the loop ends with the process"),
      ("<code>done.then(() =&gt; undefined, () =&gt; undefined)</code>: both outcomes handled", "<code>handle((v, e) -&gt; null)</code>", "<code>try/except</code> around the <code>await</code>"),
      ("<code>class WaitAgain extends Error {}</code> as a control-flow signal", "a checked exception type", "a custom exception class")]),
  case("A bare health probe would have gone writable with the room behind the journal.",
       "<p>The first design was \"ping Postgres every second; when it answers, broadcast writable\". Written out against the tests, it failed the lost-reply case: the append landed, the room never applied it, and the next append from anyone hit <code>op_journal_seq</code> and put the room straight back into read-only, for ever. Reading <code>since(seq)</code> first is not an optimisation of the probe; it is the only correct probe, because \"the database answers\" and \"the room agrees with the database\" are different facts.</p>"),
  case("The refusal of a held op was, to lesson 2's client, a reason to resync.",
       "<p><code>unavailable</code> in lesson 2 meant \"the persist step failed, resync and try again\", and a resync throws away the client's view and asks for a welcome. Under a read-only room that would be a reconnect storm: every held op refused, every refusal a resync, every welcome saying read-only again. The status message is what breaks the loop: a refusal under a room that <em>said</em> it is read-only is a hold. The peer test counts sockets: one.</p>"),
  case("A git peer whose event failed during an outage would have lost the push for good.",
       "<p>Lesson 5's <code>git_events</code> keys on <code>(ref, after_sha)</code>, so an event that ends <code>failed</code> is never recorded again by the reconcile. A push during a database outage must therefore not end at all: <code>WaitAgain</code> puts the event back to <code>pending</code>, and the next poll tick tries the whole event again. The ceiling is named (pages already applied are diffed again against the room as it is then, which is a no-op) and the alternative (a per-page cursor on the event) is the upgrade.</p>"),
  note("<strong>The distributed-systems shape:</strong> a single writer that stops writing the moment it cannot confirm a write; clients that keep their intent and re-offer it under the same identity; and a recovery that reconciles the writer with the log before it accepts anything new. Every piece is visible on a screen (\"read-only\", \"waiting to save 1\"), because a failure nobody can see is a failure nobody can act on."))

section("snapshots", "4 · Snapshots: a cache of the log, written once, named after it exists",
  "<p>With a journal, a document is fully defined by its rows: replay them from an empty page and you have it. That is correct and slow, and it grows without bound. F19 caps the cost: a room writes its whole document to MinIO every 500 accepted ops, every 30 seconds while anyone is connected, and when its last peer leaves or the server stops; opening a document loads the newest snapshot and replays only the rows after it. The journal stays the truth. A snapshot that fails to write loses nothing; it only leaves more rows for the next open.</p>",
  cut("packages/db/migrations/0013_snapshot_seq.sql", "-- E6.2 (F19)"),
  cut("apps/sync/src/snapshots.ts", "/** Where the snapshot of a document at `seq` lives.", "export type SnapshotStore"),
  "<p>Two facts from <code>learning-tests/minio</code> decide the key and the pointer. S3 lists keys as strings, so <code>\"10\"</code> sorts before <code>\"9\"</code>: the seq is zero-padded to 16 digits, enough for every safe integer, and <code>snapshotKey</code> refuses anything that is not one. And S3 cannot list in reverse (pages are ascending, 1000 keys each, whatever <code>MaxKeys</code> asks), so \"the newest snapshot\" is not found by listing: <code>documents.snapshot_seq</code> names it. <code>gzipSync</code> from <code>node:zlib</code> compresses by hand because the SDK does neither direction; the result is a <code>Uint8Array</code>, the web-standard byte array that Node's <code>Buffer</code> extends.</p>",
  cut("learning-tests/minio/test.ts", "// 5. Assumed IfNoneMatch", "// 7. CORRECTED"),
  cut("apps/sync/src/snapshots.ts", "export type SnapshotStore", "type S3Options"),
  cut("apps/sync/src/snapshots.ts", "    async put(orgId, documentId, seq, body)", "export type SnapshotCadence"),
  "<p><code>IfNoneMatch: \"*\"</code> is a conditional write: store this object only if no object exists at this key. A 412 (<code>PreconditionFailed</code>) means \"it is there already\", and <code>put</code> treats that as success, because the same journal prefix gives the same document, so whatever is at that key is this snapshot; overwriting it would only open a window where the object is half-written. <code>NoSuchKey</code> on <code>get</code> is \"there is no such object\" and is answered with <code>undefined</code>; every other failure propagates, because \"MinIO did not answer\" must never read as \"there is no snapshot\". The SDK's errors are told apart by <code>err.name</code>, a stable modelled string, through the small <code>named</code> helper: the same shape as section 1's constraint names.</p>",
  cut("apps/sync/src/snapshots.ts", "/**\n * When a room snapshots (SPEC §2.9)"),
  "<p>The cadence is a pure module fed by the room's <code>onAccepted</code> hook and a timer. <code>while (writing) await writing;</code> is \"wait for any write in flight\": a plain loop over a promise field, the same one-at-a-time idea lesson 5 wrote as a promise chain. The comment marked <em>Read in the same tick as <code>seq</code></em> is the correctness heart: the room edits <code>doc</code> in place, so the document is exactly the document at <code>seq</code> only until the next <code>await</code>. <code>encodeSnapshot(room.doc)</code> is called synchronously, before <code>write</code> is awaited. Move it after an <code>await</code> and a snapshot named <code>seq</code> could hold seq+3's document.</p>",
  cut("apps/sync/src/server.ts", "    const snapshotFrom", "  /**\n   * Reads what this peer may do"),
  "<p><strong>MinIO first, then Postgres.</strong> The object is stored, and only then is <code>snapshot_seq</code> moved. So the pointer never names a missing object: if the process dies between the two, the object is orphaned (harmless) and the pointer still names the previous snapshot (correct). <code>snapshotted</code>'s <code>where snapshot_seq &lt; $3</code> makes the pointer monotonic, so a slow write of an older snapshot finishing after a newer one cannot point the document backwards.</p>",
  cut("packages/db/src/index.ts", "      async snapshotted(orgId, documentId, seq) {", "      async fence(orgId, documentId)"),
  cut("apps/sync/src/server.ts", "    // The newest snapshot, or what F8's idle save wrote", "    // The contract checked each node's shape."),
  "<p>Opening picks the newer of two starting points: the snapshot, or what F8's idle save wrote before E6.2 for a document not snapshotted since. Then the same <code>since(seq)</code> replay as section 2. The close codes carry the distinction a user needs: MinIO down is 4503 (\"try again\"); a snapshot that is missing or malformed although Postgres names it is 4500 (\"damage\"), because Postgres only names an object after it was stored. <code>decodeSnapshot</code> runs the bytes through <code>Doc.safeParse</code> and <code>checkDoc</code>, so a room never opens on top of a tree that is not one.</p>",
  cut("apps/sync/src/server.ts", "  /**\n   * The last peer left: snapshot, then forget the room.", "  return new Promise((resolve) => {"),
  cut("apps/sync/src/server.ts", "        close: async () => {", "          for (const client of wss.clients)"),
  "<p>F8's save is deleted, and with it a retry loop and a setting. It had to retry for ever because the room's memory was the only copy. Now a failed snapshot is <em>logged and not retried</em>; the rejected alternative, retrying on last leave, would have kept complexity that the journal made pointless. The shutdown order is the same lesson 2 learned the hard way: snapshot every room <em>while its peers are still connected</em>, then terminate the sockets, then close the pool.</p>",
  cut("apps/sync/src/config.ts", "  // E6.2: where rooms write their snapshots.", "  // E7.1: room leases (F20)"),
  cut("docker-compose.yml", "  minio:", '    volumes: ["miniodata:/data"]', True),
  cut("apps/sync/src/main.ts", "const snapshots = s3Snapshots", "// Order matters"),
  cut("apps/sync/src/snapshots.test.ts", 'test("one write at a time'),
  cut("apps/sync/src/snapshot.int.test.ts", "// integration:snapshot-replay-only-later-rows", 'test("a snapshot that is not a well-formed document'),
  cut("apps/sync/src/snapshot.int.test.ts", "// integration:open-10k-under-2s"),
  vs([("<code>gzipSync(JSON.stringify(doc))</code> → <code>Uint8Array</code>", "<code>GZIPOutputStream</code> over a <code>ByteArrayOutputStream</code>", "<code>gzip.compress(json.dumps(doc).encode())</code>"),
      ("<code>PutObjectCommand({ IfNoneMatch: \"*\" })</code>; 412 is <code>err.name === \"PreconditionFailed\"</code>", "SDK v2 <code>PutObjectRequest.builder().ifNoneMatch(\"*\")</code>; <code>S3Exception.statusCode() == 412</code>", "<code>put_object(IfNoneMatch=\"*\")</code>; <code>ClientError</code> with code <code>PreconditionFailed</code>"),
      ("<code>String(seq).padStart(16, \"0\")</code>", "<code>String.format(\"%016d\", seq)</code>", "<code>f\"{seq:016d}\"</code>"),
      ("<code>while (writing) await writing;</code>", "a <code>ReentrantLock</code>, or wait on a <code>CompletableFuture</code> field", "<code>while self.writing: await self.writing</code>"),
      ("<code>setInterval(...).unref()</code>; <code>timer.unref()</code>", "a daemon thread on a <code>ScheduledExecutorService</code>", "an <code>asyncio</code> task cancelled at shutdown"),
      ("<code>res.Body.transformToByteArray()</code>: the SDK's body is a stream", "<code>ResponseBytes.asByteArray()</code>", "<code>obj[\"Body\"].read()</code>")]),
  case("The document was read after an <code>await</code>, and the test that reads back the snapshot caught it.",
       "<p>The first draft of <code>take</code> awaited the previous write and then called <code>write(seq, encodeSnapshot(room.doc))</code> with <code>seq</code> read before the await. Under the unit test's held write, the room moved on and the snapshot named 1 held seq 3's document. The fix is one line's position, and the comment above it exists so nobody moves it back. The integration test does the same check against MinIO: the bytes at key 7 decode to the document after exactly seven ops.</p>"),
  case("A snapshot store inside <code>packages/db</code> was rejected.",
       "<p>It would have been convenient: one store with <code>load</code>, <code>append</code>, <code>snapshot</code>. But <code>packages/db</code> is Postgres, and SPEC keystone 9 gives each store one job. S3 lives in <code>apps/sync</code>, behind a four-line <code>SnapshotStore</code> type that the tests implement in memory. The pointer, which <em>is</em> relational, stays in <code>packages/db</code>.</p>"),
  case("The listing that would have found the newest snapshot pages forward, 1000 keys at a time, for ever.",
       "<p>Measured in the learning test with 1005 objects: the newest key is on page two, and <code>MaxKeys: 5000</code> does not change that. A design that listed to find the latest snapshot would get slower with every snapshot ever taken. The pointer row costs one <code>update</code> per snapshot and one column per document, and turns \"find the newest\" into \"build the key\".</p>"),
  note("<strong>Principal-level point:</strong> a snapshot is a materialised prefix of the log. Everything about it follows from that: it may be lost (rebuild from the log), it must never be <em>wrong</em> (read the document in the same tick as its seq), two writers may race for it (conditional write, and equal content makes the loser's loss harmless), and the pointer to it is the only thing that must be consistent (write it after, move it forward only). Kafka Streams checkpoints, Raft snapshots and database checkpoints are the same four rules with other names."))

section("chaos", "5 · Proving the promise: a ledger, the journal, and two faults on the real stack",
  "<p>SPEC §4a insists that durability is verified against real processes, not simulated. Epic 6 writes two chaos checks and, more important, writes the <em>assertion</em> once as a pure module so that epic 7's failover run can use it unchanged. The idea: while the run makes edits, keep a <strong>ledger</strong> of every op each peer submitted and what it knew about that op at the moment of the fault. Afterwards, read the journal (the truth) and hold the ledger against it.</p>",
  cut("scripts/chaos/no-loss.ts", "// F18's guarantees as one pure check", "/** An op's fate"),
  cut("scripts/chaos/no-loss.ts", "export function createLedger", "/** Every broken guarantee"),
  cut("scripts/chaos/no-loss.ts", "/** Every broken guarantee, in words"),
  "<p>This is what \"no loss\" means <em>precisely</em>, and it is worth saying in words, because an interviewer will ask. An op <strong>acknowledged before the fault</strong> must be in the journal at exactly the seq it was acknowledged with. An op <strong>in flight at the fault</strong> (sent, unanswered) or <strong>made while the server was gone</strong> must settle <code>ok</code> and appear exactly once. Nothing may be refused for a reason the run did not cause, and nothing refused before the fault may be in the journal. The journal's seqs are <code>1..n</code> with no gap or repeat, no opId appears twice, and every row belongs to a tracked peer. And every peer's confirmed document is byte-identical. Then two <strong>vacuity guards</strong>: a run in which nothing was acknowledged before the fault, or nothing was in flight at it, proved nothing, and says so as a violation. SPEC §4a's rule, \"every <code>always</code> has a <code>sometimes</code>\", is that pair of lines.</p>",
  "<p>The <code>Outcome</code> and <code>Submitted</code> types are copied from peer-client's public shape rather than imported, so the module depends on nothing. <code>ledger.fault()</code> is the one moment that matters: whatever has <em>settled</em> by then counts as \"before\", everything else is \"in flight\". <code>settle(timeoutMs)</code> is <code>Promise.race</code> between \"every op settled\" and a timer, with the timer cleared afterwards, so an op that never settles is left as <code>\"unsettled\"</code> and reported as lost rather than hanging the run.</p>",
  cut("scripts/chaos/kill-sync-no-loss.ts", "/** One document, one kill.", "let verdict"),
  "<p>The kill is a <em>synchronous</em> <code>docker compose kill --signal SIGKILL sync</code> through <code>execFileSync</code>, called right after a burst of twenty edits per peer. Because the call blocks the event loop, no acknowledgement can be processed between the last <code>submit</code> and the kill: the burst is guaranteed in flight, and some of it is in the state the journal's dedupe exists for (journaled, acknowledgement never heard). The server is started again and the <em>peers are left alone</em>: F18 says they reconnect unaided, so the run waits on <code>status === \"live\" &amp;&amp; pendingCount === 0</code> and nothing else. Each round uses a fresh document and one fault (several kills on one ledger would blur \"acknowledged before <em>which</em> fault\"), and <code>ROUNDS=3</code> repeats, because a one-shot pass proves nothing. <code>finally</code> starts sync again whatever happened.</p>",
  cut("scripts/chaos/kill-sync-no-loss.ts", "const secretOrNone", "// The room's owner"),
  "<p>A TypeScript detail worth the two lines: narrowing does not cross a <em>function declaration</em>. <code>secretOrNone</code> is <code>string | undefined</code>; the <code>if (... === undefined) throw</code> narrows it to <code>string</code> in the top-level code, but <code>round()</code> is a hoisted <code>function</code> that could, as far as the compiler knows, run before the check. So a second <code>const secret: string</code> carries the narrowed value in. Java has no such issue (a final field is assigned once); Python has no such check.</p>",
  cut("scripts/chaos/postgres-down-read-only.ts", "/** One outage:", "let verdict"),
  "<p>The second run is section 3 against the real stack, twice: Postgres <em>stopped</em> (connections refused, read-only within a round trip) and <em>paused</em> (queries hang, read-only after the 5 s journal timeout). Note the §4a pitfall the code names: the fault is opened <em>before</em> the workload, because a fast pipeline outruns a late fault. Every wait polls an observable (<code>peer.readOnly</code>, <code>peer.seq</code>) with a deadline, never a fixed sleep. And the whole thing prints one JSON line and exits non-zero on FAIL, so <code>make chaos</code> can run it in a loop.</p>",
  cut("Makefile", "# Outside `make check`: the chaos checks", "# Outside `make check` (minutes"),
  cut("scripts/chaos/no-loss.test.ts", '  it("refuses a run that proved nothing', 'describe("createLedger"'),
  vs([("<code>execFileSync(\"docker\", [\"compose\", \"kill\", ...])</code>: synchronous, argument array, no shell", "<code>ProcessBuilder(...).start().waitFor()</code>", "<code>subprocess.run([...], check=True)</code>"),
      ("<code>const secret: string = secretOrNone</code> to carry a narrowing into a hoisted function", "not needed: fields have one type", "not needed: no checker"),
      ("<code>Awaited&lt;ReturnType&lt;typeof round&gt;&gt;</code>: the type of what an async function resolves to", "the <code>T</code> of a <code>CompletableFuture&lt;T&gt;</code>, spelled out", "the return annotation, spelled out"),
      ("top-level <code>await</code> in a script run by <code>node file.ts</code>", "a <code>main</code> method", "<code>asyncio.run(main())</code>"),
      ("<code>process.exit(verdict === \"PASS\" ? 0 : 1)</code> after one JSON line on stdout", "<code>System.exit</code>", "<code>sys.exit</code>")]),
  case("Several kills on one ledger were rejected.",
       "<p>The tempting run is one document, kill, kill, kill. But the ledger's central question is \"what was acknowledged <em>before the fault</em>\", and with three faults an op acknowledged after the first and lost at the second has no single answer. One fault per document per round keeps every entry's <code>atFault</code> meaningful, and <code>ROUNDS</code> gives the repetition §4a asks for.</p>"),
  case("The assertion is unit-tested on synthetic ledgers, before any chaos run trusts it.",
       "<p><code>no-loss.test.ts</code> feeds <code>noLossViolations</code> hand-written ledgers and journals: a clean run, a lost ack, an op journaled twice, a gap, an unsettled op, a refused op that is in the journal anyway, peers that diverge, and both vacuity guards. It is the cheapest way to know the checker itself is not vacuous before it is trusted against the stack. The unit layer's <code>include</code> gained <code>scripts/**/*.test.ts</code> for it, and knip treats <code>scripts/chaos/*.ts</code> as entries so their exports are not reported dead.</p>"),
  note("<strong>The Antithesis habit, in one sentence:</strong> write the property as a pure function over a ledger and the truth; make the run's only job be to break the system while the ledger fills; refuse a run that did not exercise the property. Everything in <code>scripts/chaos/</code> is that sentence, and epic Z's harness will call the same function."))

section("testing", "6 · Testing durability without a database, and then with one",
  "<p>Every rule in this chapter has a test that needs no Docker, and a second one that needs the compose stack. The first kind is what ran on every commit; the second kind runs in the clean-clone gate and in <code>make chaos</code> (the status block at the top says when). Three shapes recur.</p>",
  "<p><strong>A stand-in for the table, with the table's two unique keys.</strong> <code>memoryJournal</code> is thirty lines that behave as <code>op_journal</code> does: a resend returns the original row, a taken seq rejects, <code>since</code> filters and sorts. Because it outlives any room built on it, a test can build a second room on the same journal and stand for a restart.</p>",
  cut("apps/sync/src/room.test.ts", "/** A journal in memory with the table's two unique keys", 'test("the welcome carries'),
  "<p><strong>A stand-in behind a switch.</strong> <code>flakyJournal</code> wraps the memory journal in a <code>guard</code> that rejects while <code>down</code>, plus one deliberately nasty mode, <code>committedAnyway</code>: the next append lands <em>and</em> throws, which is the lost-reply case section 3's recovery exists for. The integration file's <code>switchableStore</code> adds <code>hang</code>, a promise that never settles, for the paused-database case. The generic <code>guard</code> is a higher-order function typed with a tuple rest parameter (<code>&lt;A extends unknown[], R&gt;(call: (...args: A) =&gt; Promise&lt;R&gt;) =&gt; (...args: A) =&gt; Promise&lt;R&gt;</code>): it wraps any async function and keeps its signature.</p>",
  cut("apps/sync/src/room.test.ts", "// --- E6.1b: with its storage unavailable the room is read-only", 'test("read-only: a failed append tells EVERY peer'),
  cut("apps/sync/src/read-only.int.test.ts", "/** op_journal in memory, with its two unique keys.", "function peerAs"),
  "<p><strong>The real store, observed.</strong> <code>countingStore</code> spreads the real <code>documentStore()</code> into a new object and replaces one method, <code>since</code>, with a version that records what it was asked and how much it returned. That is how the integration test proves \"only the rows after the snapshot were read\": <code>replays</code> equals <code>[{ after: 7, rows: 3 }]</code>, and after a snapshot at 10,000, <code>[{ after: 10_000, rows: 0 }]</code>. Object spread over a closure-based store is the TypeScript way to decorate one method; Java would subclass or proxy.</p>",
  cut("apps/sync/src/snapshot.int.test.ts", "/** The real store, with every `since` it answers written down", "const start ="),
  "<p><strong>A clock you wind by hand.</strong> The cadence tests use <code>vi.useFakeTimers()</code> and <code>advanceTimersByTimeAsync</code>, so \"every 30 seconds\" runs in milliseconds and the assertion \"never with nobody here\" is exact. The <code>rig</code> builds a room stand-in whose <code>seq</code> a test moves by hand, and a <code>write</code> that records, fails, or waits on a promise the test releases.</p>",
  cut("apps/sync/src/snapshots.test.ts", "/** A room stand-in whose seq a test moves by hand", 'test("every N accepted ops'),
  cut("apps/sync/src/snapshots.test.ts", 'test("every T while peers are connected', 'test("a failed write loses nothing'),
  vs([("<code>{ ...real, since: async (...) =&gt; { ... } }</code>: decorate one method by spread", "a subclass or a <code>Proxy</code>; Mockito's <code>spy</code>", "<code>unittest.mock.patch.object</code>"),
      ("<code>&lt;A extends unknown[], R&gt;(call: (...args: A) =&gt; Promise&lt;R&gt;)</code>", "no variadic generics; one wrapper per arity", "<code>ParamSpec</code> in <code>typing</code>"),
      ("<code>vi.useFakeTimers(); await vi.advanceTimersByTimeAsync(1000)</code>", "an injected <code>Clock</code>; Awaitility", "<code>freezegun</code>; an injected clock"),
      ("a promise the test holds and releases (<code>control.hold</code>)", "a <code>CountDownLatch</code>", "an <code>asyncio.Event</code>"),
      ("<code>new Promise&lt;T&gt;(() =&gt; undefined)</code>: a promise that never settles, for \"hangs\"", "a <code>CompletableFuture</code> never completed", "<code>asyncio.Future()</code> never set")]),
  case("The gate's unit layer did not include <code>scripts/</code>, so the chaos checker's tests would not have run.",
       "<p><code>vitest.config.ts</code>'s <code>include</code> covered <code>apps</code> and <code>packages</code>. The checker lives in <code>scripts/chaos/</code>, next to the run that uses it, so the pattern gained <code>scripts/**/*.test.ts</code>. A test that is written and not collected is the most misleading kind of green there is; check the collector when you add a test somewhere new.</p>"),
  note("<strong>Honest status, repeated here because it matters:</strong> the unit tests in this chapter (the room's journal, read-only and recover rules; peer-client's hold; the snapshotter's cadence and key rules; the chaos checker) ran green on every commit. The integration suites (<code>journal.int</code>, <code>read-only.int</code>, <code>snapshot.int</code>, <code>packages/db</code>'s <code>journal.int</code>, and the E6.1b additions to <code>push.test</code> and <code>git.int</code>) and both chaos runs are written, reviewed and committed, and passed: the suites in the clean-clone gate at <code>6700e74</code> on 2026-10-02, the chaos runs on 2026-10-01. The next section is what running them looks like."))

section("demo", "7 · Durability by hand: what to run once the stack is up",
  "<p>These are the exact commands and what each should show, in the order that builds confidence. The dev stack gains MinIO (<code>127.0.0.1:9005</code>, no console published) and the sync container refuses to start without it. Nothing here needs a token; where a document id is needed, it is the <code>?doc=</code> in the canvas's address bar.</p>",
  shell("0 · Bring the stack up",
        "./init.sh                                    # now also MinIO; sync makes the bucket \"snapshots\" at start and refuses to start without it\n"
        "docker compose ps                            # minio healthy; sync healthy\n"
        "open http://localhost:5173/?user=you@example.com     # New document; Add Stack, Add Button, drag a little; note ?doc=&lt;id&gt;"),
  shell("1 · The journal is the truth",
        "docker compose exec -T postgres psql -U noon -d noon -c \\\n"
        "  \"select seq, actor_kind, op->>'type' as op, left(op_id::text, 8) as op_id from op_journal where document_id = '&lt;id&gt;' order by seq\"\n"
        "                                             # one row per accepted op, seq 1..n with no gap; the drag is many set_prop rows"),
  shell("2 · kill -9 mid-edit (F18)",
        "# In the canvas, start dragging a node and keep dragging while you run:\n"
        "docker compose kill --signal SIGKILL sync    # the status turns \"offline\" with \"saving N…\"; keep editing: edits queue locally\n"
        "docker compose start sync                    # within seconds, without a reload: \"live\", then \"saved\"; the other tab shows the same page\n"
        "# Then the query from step 1 again: n grew by exactly the edits you made; no seq repeats; no op_id repeats:\n"
        "docker compose exec -T postgres psql -U noon -d noon -c \\\n"
        "  \"select count(*), count(distinct seq), count(distinct op_id), max(seq) from op_journal where document_id = '&lt;id&gt;'\"   # all four equal"),
  shell("3 · Postgres down: read-only, nothing lost (E6.1b)",
        "docker compose stop postgres                 # add a node NOW: the status says \"read-only · waiting to save 1…\", the alert appears, Add is disabled\n"
        "                                             # a second tab opened meanwhile is welcomed read-only\n"
        "docker compose start postgres                # within about a second: \"live · saved\"; the node you added is there, once, in both tabs\n"
        "docker compose pause postgres                # the same, but read-only arrives after the 5 s journal timeout (queries hang instead of failing)\n"
        "docker compose unpause postgres"),
  shell("4 · Snapshots (F19)",
        "docker compose exec -T postgres psql -U noon -d noon -c \"select snapshot_seq, seq from documents where id = '&lt;id&gt;'\"\n"
        "                                             # snapshot_seq moves every 500 ops, every 30 s while a tab is open, and when the last tab closes\n"
        "                                             # the object is &lt;org&gt;/&lt;id&gt;/&lt;16-digit seq&gt;.json.gz in the bucket; no console is published, the integration test reads it back\n"
        "SNAPSHOT_EVERY_OPS=5 docker compose up -d sync      # to watch the cadence by hand: every five edits moves the pointer\n"
        "docker compose logs sync | grep snapshot     # only FAILED snapshots are logged; silence is the good case"),
  shell("5 · Then the checks that prove it without hands",
        "pnpm exec vitest run --config vitest.integration.config.ts packages/db/src/journal.int.test.ts apps/sync/src/journal.int.test.ts apps/sync/src/read-only.int.test.ts apps/sync/src/snapshot.int.test.ts\n"
        "                                             # real Postgres and MinIO; the 10,000-row open is timed and must be under 2 s\n"
        "node scripts/chaos/postgres-down-read-only.ts        # one JSON line: {\"chaos\":\"postgres-down-read-only\",\"verdict\":\"PASS\",\"steps\":[...]}\n"
        "ROUNDS=3 node scripts/chaos/kill-sync-no-loss.ts     # {\"chaos\":\"kill-sync-no-loss\",\"verdict\":\"PASS\",\"rounds\":[{\"ops\":60,\"journaled\":...,\"violations\":[]},...]}\n"
        "make chaos                                   # both, in order; breaks and restores the real stack\n"
        "make check                                   # the whole gate, as the pre-commit hook runs it"),
  note("<strong>What to do when a step does not match this page:</strong> the page was cut from the code at commit <code>" + commit + "</code>, and the code is right until a test says otherwise. A step that fails is a finding: write it as <em>sequence → false belief → consequence → smallest fix</em> (SPEC §4a's form) and file it against the bead that owns the code."))

section("limits", "8 · What the type system could not see, epic 6 edition",
  "<p>Everything below compiled under <code>strict</code>, passed the linter and the first tests, or was rejected at design time by asking what the types could not ask.</p>",
  vs([("an op announced before it was durable", "the compiler cannot see the order of two awaits", "append, then <code>accept</code>; drill 2 plants the reverse"),
      ("a failed write took a sequence number", "<code>seq + 1</code> looked like <code>seq++</code>", "the number is taken inside <code>accept</code> only"),
      ("two unique violations look the same (23505)", "the code is not the constraint", "read <code>err.constraint</code> by name"),
      ("a bare-opId key would refuse a cross-peer collision", "every broadcast shows every opId", "key on <code>(document, actor, opId)</code>"),
      ("a forged <code>baseSeq</code> walked past the stale guard (E2.3)", "memory is bounded", "the journal's key answers with the original"),
      ("a reopened room numbered from a stale seq", "the saved document is behind the journal", "replay <code>since(seq)</code> at open"),
      ("a removed id came back through any actor", "<code>validate</code> sees only the present", "<code>everAdded</code> through a partial index"),
      ("a paused database hung the room for ever", "a hang is not an error", "<code>bounded</code>: a timeout that means \"treat as failed\""),
      ("a health probe went writable with the room behind the journal", "\"answers\" is not \"agrees\"", "<code>recover()</code> replays, then says writable"),
      ("a refusal under read-only was a resync, and a reconnect storm", "<code>unavailable</code> meant one thing in lesson 2", "the status message turns it into a hold"),
      ("a held op that landed would be applied twice, or heard by nobody", "a lost reply is not a failed write", "replay before writable; the resend gets the original"),
      ("a git event failed during an outage was gone for good", "<code>(ref, after_sha)</code> is never re-recorded", "<code>WaitAgain</code>: back to <code>pending</code>"),
      ("a snapshot named <code>seq</code> held a later document", "the room edits <code>doc</code> in place", "encode in the same tick as <code>seq</code>"),
      ("the pointer could name a missing object", "two writes, one crash between them", "MinIO first, then <code>snapshot_seq</code>"),
      ("a slow old snapshot could move the pointer back", "writes finish out of order", "<code>where snapshot_seq &lt; $3</code>"),
      ("\"10\" sorted before \"9\"", "S3 keys are strings", "zero-pad to 16 digits"),
      ("finding the newest snapshot by listing", "1000 keys a page, ascending only (measured)", "a pointer row; build the key"),
      ("MinIO down read as \"no snapshot\"", "one <code>undefined</code> for two facts", "<code>NoSuchKey</code> → undefined; anything else throws; 4503 vs 4500"),
      ("a chaos run that proved nothing passed", "a green run with no op in flight", "vacuity guards as violations"),
      ("a kill that landed after the burst was acknowledged", "an async kill lets acks through", "<code>execFileSync</code>: the loop is blocked until the kill lands"),
      ("a narrowing that did not reach a hoisted function", "declarations hoist; narrowings do not", "<code>const secret: string = secretOrNone</code>"),
      ("the checker's tests were not collected", "the unit pattern stopped at <code>packages</code>", "<code>scripts/**/*.test.ts</code> in the include")], head=("What went wrong, or would have", "Why", "Fix")),
  note("<strong>The pattern, extended once more:</strong> lessons 2 to 5 said types prove shapes and say nothing about order, time, repetition, memory, who is speaking, or which side of a boundary a thing is on. Epic 6 adds the two that durability turns on: types cannot see <em>whether a write happened</em> (a rejected promise may have landed; a hung one may too) and <em>what order two effects took</em> (announce, then persist, compiles as well as the reverse). Both were answered the same way as before: put the truth in one place, read it before you believe anything, and write a test that watches the order."))

toc = "".join(f'<li><a href="#{sid}">{title}</a></li>' for sid, title, _ in S)
sections = "".join(f'<section id="{sid}"><h2>{title}</h2>{body}</section>' for sid, title, body in S)
style = re.search(r"<style>.*?</style>", (root / "docs/handbook/lesson-0.template.html").read_text(), re.S).group(0)
page = (pathlib.Path(__file__).parent / "lesson-6.template.html").read_text()
page = page.replace("{{STYLE}}", style).replace("{{TOC}}", toc).replace("{{SECTIONS}}", sections).replace("{{COMMIT}}", commit)
(out / "lesson-6.html").write_text(page)
print("built", len(page), "bytes at", commit, "with", page.count('<p class="label">From'), "code blocks")
