"""Builds docs/handbook/lesson-7.html. Every code block is cut from the real repo by anchor text,
so the page cannot show code that does not exist; a missing anchor fails the build."""
import html, os, pathlib, re, subprocess
here = pathlib.Path(__file__).resolve()
root = pathlib.Path(os.environ.get("NOON_ROOT") or (here.parents[2] if (here.parents[2] / "SPEC.md").exists() else pathlib.Path.cwd()))
out = pathlib.Path(os.environ.get("NOON_OUT") or root / "docs/handbook")
commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True).stdout.strip()

def cut(path, start, end=None, include_end=False):
    src = (root / path).read_text()
    i = src.index(start)
    j = len(src) if end is None else src.index(end, i + len(start)) + (len(end) if include_end else 0)
    body = src[i:j].rstrip()
    return (f'<p class="label">From <span class="mono">{path}</span></p>'
            f'<div class="scroll"><pre><code>{html.escape(body)}</code></pre></div>')

def shell(title, body):
    return f'<p class="label">{title}</p><div class="scroll"><pre class="out"><code>{body}</code></pre></div>'

def vs(rows, head=("TypeScript (this repo)", "Java", "Python")):
    body = "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows)
    return f'<div class="scroll"><table><tr>{"".join(f"<th>{h}</th>" for h in head)}</tr>{body}</table></div>'

def case(title, body): return f'<div class="break"><p class="label">Case study · found by review, by a learning test, or by a test that was written to refute a claim</p><p><strong>{title}</strong></p>{body}</div>'
def note(body): return f'<p class="note">{body}</p>'
m = lambda s: f"<span class='mono'>{s}</span>"

S = []
def section(sid, title, *parts): S.append((sid, title, "".join(parts)))

section("map", "The map: what multi-node means here",
  "<p>Epic 6 made one sync process trustworthy: an acknowledged edit survives a crash. Epic 7 asks what happens when there are <em>two</em> of them. The whole design rests on lesson 2's first rule: one room per document orders the ops, and there can never be two rooms for one document, because two rooms would mean two orderings and two documents. So with two processes the question is not \"how do they share a room\" but \"how do they agree, at every moment, on <em>which one</em> has it\", including the moments when one of them is dead, frozen, or cut off, and cannot be asked. Three features answer it. <strong>F20, one room globally:</strong> every peer of a document lands in the same room, whichever node it asked first. <strong>F21, failover:</strong> kill the node that owns a room and the room moves to the other within one lease, with F18's guarantees intact. <strong>F22, fencing:</strong> a node paused past its lease and then resumed cannot append to the journal; it closes its sockets; the journal has no gap and no duplicate.</p>",
  vs([("1", m("packages/lease/src/index.ts"), m("packages/lease/src/lease.ts"), "a lease per document in Redis: acquire, renew and release as three Lua scripts; a fencing token from <code>INCR</code> issued with the <code>SET</code>; a <code>Holder</code> parsed back from <code>\"&lt;token&gt;:&lt;node&gt;\"</code>"),
      ("2", m("packages/lease/src/lease.ts"), "", "<code>keepLease</code>: when a holder must stop believing it holds the lease, on its own monotonic clock, counting from the moment a renewal was <em>sent</em>"),
      ("3", m("apps/sync/src/server.ts"), m("apps/api/src/app.ts"), "a room opens only under the lease; the loser closes its peers with 4409; <code>/session</code> answers the owner's address from a routing table <code>id=url,id=url</code>; the worker routes the same way"),
      ("4", m("packages/lease/src/lease.ts"), m("scripts/chaos/kill-owner-failover.ts"), "heartbeats as a routing hint; <code>takeLease</code> waits a dead owner's lease out and never steals it; the chaos run kills the owner and does not restart it"),
      ("5", m("packages/db/migrations/0014_fence.sql"), m("packages/db/src/index.ts"), "the fence: <code>claim</code> the document under the lease token before reading the journal; every append is one statement that checks the claim and locks the row; <code>Fenced</code> drops the room"),
      ("6", m("apps/sync/src/fence.ts"), m("scripts/chaos/fenced.ts"), "a fenced append ends the room, not read-only; two chaos runs: <code>docker pause</code> past the lease, and a toxiproxy cut between one node and Redis")], head=("Step", "Where", "And", "What happens")),
  "<p>Four ideas carry the epic, and they are the four an interviewer will ask about. <strong>A lease is a lock with an expiry</strong> (section 1): a holder that dies stops renewing, and the lock frees itself; the price is that \"I hold it\" is now a statement about time. <strong>Only your own clock, and only the moment you sent</strong> (section 2): a holder trusts its lease until <em>sent + 0.9 ttl</em> on a monotonic clock, never a wall clock, never Redis's clock, and gives up its peers when that passes. <strong>Liveness is a hint, never a truth</strong> (sections 3 and 4): heartbeats decide where a peer is <em>sent</em>; the lease alone decides who <em>owns</em>; a dead owner's lease is waited out, never stolen. <strong>The lock is not the safety; the storage is</strong> (section 5): a process frozen past its lease cannot know it, so the journal append itself refuses a writer whose claim is no longer the document's, in the same statement that writes. Kleppmann's fencing-token argument is the spine of the chapter, and the repo's own <code>learning-tests/redis</code> reproduced the zombie before a line of the epic was written.</p>",
  vs([("a Redis lease per document, three Lua scripts, an <code>INCR</code> token; renew every ttl/3", "Redisson <code>RLock</code> (Lua too, a watchdog renews every ttl/3); Curator's <code>InterProcessMutex</code> over ZooKeeper ephemeral nodes", "<code>redis.lock.Lock</code> with a token and a Lua release; <code>kazoo.Lock</code>; <code>python-etcd3</code> leases"),
      ("the token checked by the storage in the write statement", "Kafka's producer epoch in the broker; ZooKeeper's zxid; Chubby's sequencer handed to the file server", "the same idea; nothing in the standard library does it for you"),
      ("routing through <code>/session</code> and a table in one env variable", "a service registry (Eureka, Consul) plus sticky routing; or ZooKeeper's ephemeral nodes as the registry", "Consul, or a Redis hash of owners"),
      ("liveness as a heartbeat key with a short PX", "ZooKeeper sessions and ephemeral nodes; etcd leases with keep-alive", "etcd3 lease keep-alive; Consul checks")], head=("This repo", "Java world", "Python world")))

section("lease", "1 · The lease: one script, one token, three compare-and-sets",
  "<p>Redis was already in the stack for queues (lesson 3). SPEC §2a fixed the lease's shape from the learning test: <em>SET NX PX plus a fencing token from INCR in the same Lua script; renew and release are compare-and-set in Lua.</em> The package that implements it is small on purpose: <code>index.ts</code> talks to Redis, <code>lease.ts</code> is pure and holds every decision (parsing, deadlines, routing, waiting), so the decisions have unit tests and the I/O has an integration test against the real server.</p>",
  cut("packages/lease/src/index.ts", "/**\n * Room leases in Redis (SPEC §2a)", "// One script, so nothing can happen"),
  cut("packages/lease/src/index.ts", "// One script, so nothing can happen", "export function createLeases"),
  "<p>Read <code>ACQUIRE</code> as one atomic step, because that is what Redis makes it. Redis runs commands on one thread, and a Lua script is one command: nothing from any other client runs between its first line and its last. So <code>GET</code> (is it held?), the counter floor, <code>INCR</code> (issue a token) and <code>SET ... PX</code> (take it, with an expiry) happen with no gap, and the two properties the tests demand follow. <strong>Exactly one of N racing acquirers wins</strong>, because only the first to run sees no value. <strong>The counter moves by exactly one per acquisition</strong>, because the token is issued only on the branch that also does the <code>SET</code>; a loser returns the current holder and touches nothing. That second property is why the join-race test can assert <code>token: 1</code> after ten simultaneous joins and <code>2</code> after the room closes and is taken again. The naive version, <code>INCR</code> then <code>SET NX</code> as two round trips, would burn a token per loser and could hand a <em>smaller</em> token to a <em>later</em> owner if two acquirers interleaved, which section 5's fence could not survive.</p>",
  "<p><code>RENEW</code> and <code>RELEASE</code> compare the exact value <code>\"&lt;token&gt;:&lt;node&gt;\"</code> before touching the key. The learning test reproduced why: a holder whose lease had expired issued a plain <code>DEL</code> and deleted <em>another</em> client's freshly acquired lease. A bare <code>PEXPIRE</code> has the same flaw in the other direction: it would extend a lease that is now someone else's. Comparing the whole holder, not just the node id, also stops a node that took the same room twice from renewing its own earlier, dead acquisition (the integration test's \"same node, another acquisition\" line).</p>",
  cut("learning-tests/redis/test.ts", "// 2. CAS renew/release via Lua", "// 3. Fencing token"),
  cut("packages/lease/src/index.ts", "export function createLeases", "    async owner(documentId)"),
  "<p>Three TypeScript things in <code>createLeases</code>. <strong>The client options are the E3.1 lesson again:</strong> <code>enableOfflineQueue: false</code>, a <code>commandTimeout</code> and one retry, so every call <em>fails within a deadline</em> when Redis is away; a lease library that hangs is a room that never opens and never says why (the integration test times every failure). <strong><code>redis.eval(...) as [number, string]</code></strong> is a type assertion, not a conversion: ioredis types <code>eval</code>'s result as <code>unknown</code> because a script can return anything, and the cast records what <em>this</em> script returns. <code>parseHolder</code> then checks the string at runtime, so a key that holds something that is not ours reads as \"nobody\" rather than as a crash. <strong>The error handler never logs the error object</strong>: a failed <code>AUTH</code> carries the password in <code>err.command.args</code>, so only <code>err.message</code> goes to stderr.</p>",
  cut("packages/lease/src/lease.ts", "/**\n * Who owns a document's room", "export type LeaseKeeper"),
  "<p><code>Holder</code> is two numbers of information: <em>who</em>, and <em>which acquisition</em>. The token is the second one, and the whole of section 5 is built on it rising. <code>parseHolder</code> is strict by design: the regex refuses a leading zero, a token of more than sixteen digits (past <code>Number</code>'s safe range) and any node id that <code>NodeId</code> would refuse. A node id is a URL path segment and a compose service name, so it is lowercase letters, digits and dashes, and Zod's <code>.regex</code> carries that rule into every config file that names one.</p>",
  cut("packages/lease/src/index.int.test.ts", 'test("N simultaneous acquires', 'test("tokens rise strictly'),
  cut("packages/lease/src/index.int.test.ts", 'test("a late release by an old holder', 'test("with Redis unreachable'),
  vs([("a Lua script as a template literal, sent with <code>redis.eval(script, numKeys, ...keys, ...args)</code>", "Redisson does the same inside <code>RLock</code>; Jedis <code>eval</code>", "<code>redis.register_script</code> or <code>eval</code>"),
      ("<code>(await redis.eval(...)) as [number, string]</code>: a tuple assertion", "<code>(List&lt;Object&gt;) result</code>, then casts per element", "tuple unpacking; no check"),
      ("<code>z.string().regex(/^[a-z0-9][a-z0-9-]{0,31}$/)</code> as a reusable field", "a Bean Validation <code>@Pattern</code>", "a pydantic <code>constr(pattern=...)</code>"),
      ("eight separate <code>Redis</code> clients in one test, so the race is real", "eight <code>JedisPool</code> connections", "eight <code>redis.Redis()</code> instances"),
      ("<code>redis.on(\"error\", ...)</code> logging <code>err.message</code> only", "a <code>Logger</code> with the exception's message, not <code>toString</code>", "<code>logging.warning(str(err))</code>")]),
  case("The token issued only with the SET, or the join-race test could not count.",
       "<p>An earlier shape issued the token first (<code>INCR</code>) and then tried the <code>SET NX</code>, so ten racing joiners moved the counter by ten and the winner's token was whichever number its <code>INCR</code> happened to get. The test that asks \"exactly one acquisition happened\" cannot be written against that: token 1 for the winner is only meaningful if losers cost nothing. Moving the <code>INCR</code> after the <code>GET</code> check inside the one script made \"the counter moved by one\" a checkable fact, and the same script later took the floor (section 5) in the only place it can be applied safely: before the <code>INCR</code>, under the same atomicity.</p>"),
  case("The api acquiring leases on a node's behalf was rejected.",
       "<p>It looked simpler: <code>/session</code> knows the document and could pick a node and take the lease for it. But a lease has to be <em>renewed</em>, and only the process that holds the room knows whether it still holds the room. A node that did not acquire cannot know it must renew, and a lease renewed by a third party is a lease that outlives the room it protects. The node takes its own lease when its first peer arrives, and the api only reads.</p>"),
  note("<strong>The principle:</strong> a lease's three operations must each be atomic with their own check. Acquire checks \"free\" and takes; renew checks \"still mine\" and extends; release checks \"still mine\" and deletes. Redis gives atomicity for free inside one script, so the design puts each check and its effect in one script and never splits them across a round trip. Section 5 applies the same rule to Postgres, where the one statement is the atom."))

section("clocks", "2 · Clocks against tokens: when a holder must stop believing itself",
  "<p>A lease is a promise with a time on it, and a time raises the question every distributed-systems text spends a chapter on: <em>whose</em> time? Redis expires the key on its own clock, starting when it <em>receives</em> the command. The holder can only read its own clock. The two clocks run at slightly different rates, the message between them takes time, and the holder can be paused for a minute by the operating system, the garbage collector or <code>docker pause</code> without noticing. <code>keepLease</code> is the answer to \"until when may this process act as the owner\", and it is deliberately conservative.</p>",
  cut("packages/lease/src/lease.ts", "export type LeaseKeeper", "/**\n * The sync nodes a peer can be sent to"),
  "<p>Three decisions, each with a test. <strong>Only our monotonic clock.</strong> <code>now</code> is <code>performance.now()</code> in production, which cannot jump when NTP corrects the wall clock (<code>Date.now()</code> can, backwards). Java's <code>System.nanoTime()</code> and Python's <code>time.monotonic()</code> are the same instrument. <strong>Counting from the send, not the reply.</strong> Redis starts its <code>PX</code> countdown when the command arrives, which is after we sent it, so a deadline of <em>sent + ttl</em> on our clock can never be later than Redis's expiry; the <code>0.9</code> is the margin for the two clocks drifting. The test \"the deadline counts from when a renewal was SENT\" has a renewal that takes 800 ms to answer and asserts the lease is trusted until 300 + 900, not 1100 + 900. <strong>A hang does not extend anything.</strong> A renewal in flight is not awaited twice, but the deadline is still checked on every <code>tick</code> and every read of <code>held</code>, so a hung Redis cannot keep a room alive by never answering.</p>",
  "<p>The idiom to notice is that <code>held</code> is a getter with a side effect: reading it may fire <code>onLost</code>. That is a deliberate trade. The room's server needs \"are we still the owner\" to be true at the moment of the question, not at the last timer tick, and the cheapest way to make every reader honest is to make the read itself check the clock. <code>lose</code> is idempotent so that <code>onLost</code> runs once however many readers ask.</p>",
  cut("packages/lease/src/lease.test.ts", '  it("the deadline counts from when a renewal was SENT', '  it("a renewal that fails never shortens'),
  "<p>Now the point the doc comment makes in its last paragraph, because it is the point of the epic. <em>This is not safety.</em> A process frozen for two seconds does not run <code>expired()</code> during those two seconds; when it wakes, its first read of <code>held</code> says false and it gives up, but between the wake and that read it may already have done something, and an <code>await</code> it was inside when it froze will simply continue. The learning test measured exactly that: owner A blocked its own event loop with <code>Atomics.wait</code> for two seconds, owner B took the lease 1.7 seconds before A woke, and A's in-memory flag still said \"mine\". Kleppmann's argument in <em>How to do distributed locking</em> (and chapter 8 of DDIA) is that no amount of care with clocks closes this gap, because the pause can happen at <em>any</em> instruction, including the one after the check. The only thing that closes it is a check by the storage, at write time, of a token that the frozen process cannot have updated. That is section 5; <code>keepLease</code> only makes a <em>live</em> node let go promptly, so that failover takes one ttl rather than a ttl plus a discovery.</p>",
  cut("learning-tests/redis/test.ts", "// 4. Zombie lease when", "// 5. BullMQ jobId"),
  vs([("<code>performance.now()</code>: monotonic, milliseconds, a double", "<code>System.nanoTime()</code>", "<code>time.monotonic()</code>"),
      ("a getter with a side effect (<code>get held()</code> may fire <code>onLost</code>)", "an <code>isHeld()</code> method that also fires a listener; unusual, and documented", "a <code>@property</code> that calls a callback; unusual"),
      ("<code>now: () =&gt; number</code> injected, wound by hand in tests", "an injected <code>Clock</code> (<code>java.time.Clock</code>)", "an injected callable; <code>freezegun</code> for wall clocks only"),
      ("<code>Atomics.wait</code> on a <code>SharedArrayBuffer</code> to block the loop on purpose", "<code>Thread.sleep</code> on the one thread that matters", "<code>time.sleep</code>"),
      ("<code>renewing</code> as a plain boolean guard", "an <code>AtomicBoolean</code>", "a bool; the GIL and the loop make it safe")]),
  case("Trusting the reply time would have given a slow Redis a longer lease than it granted.",
       "<p>The obvious deadline is \"when the renewal came back plus ttl\". With an 800 ms round trip that trusts the lease for 800 ms longer than Redis will keep it: another node could acquire while this one still believes and still accepts ops. Every op accepted in that window is one the fence must refuse later, and one whose sender was told nothing for the whole window. Reading the clock before the send, into <code>sentAt</code>, and passing it to <code>trusted</code> after the answer is the whole fix; the test with the slow renewal is the mutation check.</p>"),
  case("A renewal that fails must not shorten what an earlier one earned.",
       "<p>A first version set <code>validUntil</code> from the failed attempt's send time when Redis threw, which under a flaky network would have made the room give up its peers every time one renewal failed, although the previous one had bought it another 900 ms. The rule became: a refusal (<code>false</code>) loses at once, a throw changes nothing and is tried again next tick, and only a <code>true</code> moves the deadline. The test winds the clock to 1350 after a failed renewal at 800 and asserts still held.</p>"),
  note("<strong>Principal-level point:</strong> there are two independent instruments here and they answer different questions. The <em>clock</em> answers \"may I still act as the owner\" and it is allowed to be wrong in one direction only, towards giving up early. The <em>token</em> answers \"was this write made by the current owner\" and it is never wrong, because it is compared by the storage, not by the process that might be frozen. A system that uses only the first is unsafe under pauses; a system that uses only the second is safe but has no failover time bound, because nobody ever gives anything up. This repo uses both, and keeps them in separate modules so that each has its own tests."))

section("oneroom", "3 · One room globally: the loser says 4409, and /session knows the owner",
  "<p>The lease decides who owns a room; the rest of F20 is making every peer arrive at the owner without the peer knowing anything about nodes. Lesson 2 already had the hook: a browser never dials a sync address it remembers, it asks <code>POST /documents/:id/session</code> and dials what comes back. So the routing lives in one place, and it needs one input: a table of nodes.</p>",
  cut("packages/lease/src/lease.ts", "/**\n * The sync nodes a peer can be sent to", "/** A zod field for an env"),
  "<p><code>SyncNodes</code> is a discriminated union with two shapes, and the <code>\"one\"</code> shape exists so that nothing changed for the single-node setup or for any test: one URL, no lookup, no Redis asked. <code>parseSyncNodes</code> is strict about what would route a peer nowhere: a query or fragment (it would swallow the <code>/documents/&lt;id&gt;</code> appended later), an <code>http://</code> scheme, a duplicate id, an id <code>NodeId</code> refuses. <code>URL.canParse</code> is Node 24's way to ask \"is this a URL\" without a <code>try</code>. The same field is used by the api (<code>SYNC_PUBLIC_URL</code>, what browsers dial) and by the worker (<code>SYNC_URL</code>, addresses inside the Docker network), because the two audiences reach the nodes through different networks.</p>",
  cut("apps/api/src/config.ts", "  // The address BROWSERS use to reach the sync server", "  // Set when the app is reached through one public URL"),
  cut("apps/worker/src/config.ts", "  // How THIS process reaches the sync server. Not SYNC_PUBLIC_URL", "  // Optional at startup: without it every run fails"),
  cut("packages/lease/src/lease.ts", "/**\n * Where a peer of `documentId` dials", "const randomNode"),
  "<p>The router's contract, in order. An owner that beats: its address. An owner that stopped beating: any live node, which will wait the dead lease out (section 4). No owner: any live node, whose first peer takes the lease. Nobody beating at all: route as if everyone were alive, because \"no heartbeats\" after a Redis restart must not mean \"no service\". An owner the table does not name: an error, because sending the peer anywhere else would bounce on 4409 for ever, and a loud error is how a misconfigured table is found. And Redis unreachable propagates, so the caller can say \"try again\" honestly. <code>pick</code> is injectable so the tests can force a first dial to the wrong node, which is how the race in F20 is provoked on purpose.</p>",
  cut("apps/api/src/app.ts", "  // The routing hook (SPEC §2.11)", "  // E10.8: who the document is shared with"),
  cut("apps/api/src/main.ts", "// Several sync nodes: /session reads each room's owner", "const identify"),
  cut("apps/worker/src/live.ts", "/**\n * How THIS process reaches a document's room", "/**\n * A peer in the job's document"),
  "<p>The worker's AI, preview, ship and git peers used to dial <code>ws://sync:3001</code> directly. With two nodes that would have bounced on 4409 for every room the other node owns, for ever, because those peers had no <code>/session</code> to ask. <code>syncSessions</code> gives them the same router the api has, asked before every connection. It is a seam like <code>enqueue</code>: the app takes <code>owner</code> and <code>alive</code> as functions, so the api's tests run with no Redis at all (the default rejects, and the single-node shape never calls it).</p>",
  "<p><strong>Now the node's side.</strong> A room opens only under the lease. <code>open()</code> takes it, starts renewing at once, loads the room, and hands back a room that also knows its sockets, so that losing the lease can send every peer elsewhere.</p>",
  cut("apps/sync/src/server.ts", "// 4000-4999 are ours to define.", "type Options"),
  cut("apps/sync/src/server.ts", "  /**\n   * Room ownership across sync nodes (F20)", "export function startSyncServer"),
  cut("apps/sync/src/server.ts", "  /**\n   * Takes the document's lease (when there are several nodes)", "    // The fence (F22), BEFORE the journal is read"),
  "<p>Read <code>drop</code> and <code>keepLease</code>'s <code>onLost</code> together: when the deadline passes or a renewal is refused, the room is marked <code>lost</code>, snapshots stop, the room is forgotten (so the next peer asks Redis again rather than joining a corpse), and every socket is closed with 4409. Renewal starts <em>before</em> <code>load()</code>, because replaying a long journal can take longer than a third of a ttl. And a room whose lease lapsed <em>during</em> the load is refused at the end (<code>!keeper.held</code>), released, and answered 4409, so a peer never joins a room that is already dead.</p>",
  cut("apps/sync/src/server.ts", "    if (opened.lost) {", "    const { room } = opened;"),
  cut("apps/sync/src/server.ts", "      if (opened.lost) return; // being sent elsewhere", "      let parsed;"),
  "<p>4409 is a <em>conflict</em> close code by analogy with HTTP 409, and it is the one code in the 4000s that is not fatal to a peer. peer-client's <code>FATAL_CLOSE_CODES</code> does not include it, so the peer does what it does on any non-fatal close: asks <code>session()</code> again and dials what it answers, which by now names the owner. Lesson 2's client needed no change for F20 except one test pinning this.</p>",
  cut("packages/peer-client/src/peer.ts", "const FATAL_CLOSE_CODES", "const KNOWN_TYPES"),
  cut("packages/peer-client/src/peer.test.ts", 'test("the room\'s node dies, or says the room moved (4409)', 'test("a connection that opens but never says welcome'),
  cut("docker-compose.yml", "  # One room per open document, on exactly ONE of the sync nodes", "  # Long-running work, one BullMQ queue"),
  cut("docker-compose.yml", "      # What a BROWSER on this machine dials to reach each sync node", "      # Hosting, too: PREVIEW_PUBLIC_URL"),
  cut("apps/web/vite.config.ts", "      // One path per sync node (E7.1)", "      ...(publicHost === undefined"),
  cut("apps/sync/src/one-room-globally.int.test.ts", 'test("a node whose lease is taken sends its peers away', None),
  cut("apps/sync/src/one-room-join-race.int.test.ts", "// integration:one-room-join-race", "import { randomUUID }"),
  vs([("<code>type SyncNodes = { kind: \"one\"; url } | { kind: \"many\"; nodes: ReadonlyMap }</code>", "a sealed interface with two records", "a <code>Union</code> of two dataclasses with a <code>Literal</code> tag"),
      ("<code>URL.canParse(value)</code>", "<code>new URI(value)</code> in a <code>try</code>", "<code>urllib.parse.urlparse</code>, which never throws, so check the parts"),
      ("<code>owner = () =&gt; Promise.reject(new Error(\"no lease store\"))</code> as a default that refuses", "a constructor overload that throws <code>UnsupportedOperationException</code>", "a default argument that raises"),
      ("YAML anchors: <code>sync: &amp;sync</code>, <code>sync-2: { &lt;&lt;: *sync }</code>", "the same YAML", "the same YAML"),
      ("a regex key in Vite's proxy: <code>\"^/sync(/|$)\"</code>", "a Spring Cloud Gateway route with an anchored predicate", "an nginx <code>location ~ ^/sync(/|$)</code>")]),
  case("A plain \"/sync\" proxy prefix swallowed \"/sync-2\".",
       "<p>The public demo runs through one host, and Vite forwards <code>/sync</code> to node one and <code>/sync-2</code> to node two. With prefix keys, every <code>/sync-2/documents/…</code> request matched <code>/sync</code> first and was rewritten to <code>-2/documents/…</code> on the wrong node. Anchoring the patterns (<code>^/sync(/|$)</code>) is a one-line fix, and the comment says why so nobody \"simplifies\" it back. A single-URL <code>SYNC_PUBLIC_URL</code> against two nodes is the same class of misconfiguration: browsers bounce on 4409 for every room the other node owns, and the commit names it so an operator recognises the symptom.</p>"),
  case("Hashing the document id to pick a node was rejected.",
       "<p>Consistent hashing is the textbook answer for \"which node\", and it is wrong here: a dead node would be picked every time for its share of documents, and a peer's only remedy would be to keep retrying until the lease moved. The lease is already the truth about ownership; the pick only matters for a free room, and there it should prefer a node that is alive. Section 4's heartbeats are that preference.</p>"),
  note("<strong>The shape:</strong> ownership is decided in one place (the lease), advertised through one door (<code>/session</code>), and enforced by the owner refusing what is not its (4409). A peer never needs a routing table, a node never needs to know the other nodes, and the api never needs to know which rooms are open. Each of them asks Redis one question and acts on the answer."))

section("failover", "4 · Failover: heartbeats as a hint, and a dead lease waited out",
  "<p>E7.1 left a named gap: kill the owner and its lease pins its peers to a dead address until it expires, and afterwards a random pick sends half of them back to the corpse. With peer-client's backoff (up to ten seconds) the room could come back a second ttl late. F21 budgets one ttl. Two additions close the gap, and both are careful to add <em>speed</em> without adding a second source of truth about ownership.</p>",
  cut("packages/lease/src/index.ts", "    async beat(nodeId)", "    async ready()"),
  cut("apps/sync/src/server.ts", "  // \"Alive\" into Redis every tenth of a ttl", "  const http = createServer"),
  "<p><strong>Heartbeats.</strong> Every node writes <code>node:&lt;id&gt;</code> with an expiry of a third of a ttl, every tenth of one. A killed node is known dead within ttl/3, long before any of its leases expire. Two things are not done with that knowledge, on purpose. It does not decide ownership: the router uses it only to choose where a peer is <em>sent</em>, and a node wrongly thought dead costs a peer one 4409, never a second room. And it does not steal: a lease held by a node that stopped beating is still that node's until Redis lets it go, because \"stopped beating\" and \"stopped writing\" are different facts (a paused node does neither, and wakes).</p>",
  cut("packages/lease/src/lease.ts", "/**\n * A node's first peer of a room has arrived", None),
  "<p><strong>Waiting the lease out.</strong> <code>takeLease</code> is the pure decision a node makes when its first peer of a room arrives and the acquire is refused. Held by a live node: refuse at once, the peer belongs with the owner. Held by a node that stopped beating, or by <em>our own id</em> from a previous run that was killed: poll every ttl/10 until the lease expires, then take it; if it does not expire within about a ttl it was renewed after all, so refuse. The peer's socket stays open the whole time, connecting, so the takeover lands within ttl/10 of the expiry rather than at the peer's next backoff. This is also what retires E7.1's ponytail: a restarted node no longer bounces its own peers with 4409 for up to a ttl.</p>",
  "<p>The <code>for (;;)</code> with a return in the middle is the idiom for a poll with a deadline; <code>acquiredAt</code> is read before each acquire is sent, for the reason section 2 gave. The <code>sleep</code> is injected and the tests wind a fake clock through it, so a test of \"waited out, taken within a poll of expiry\" runs in microseconds and asserts on exact numbers.</p>",
  cut("packages/lease/src/lease.test.ts", '  it("held by a node that stopped beating (killed): waited out', '  it("never waits more'),
  cut("apps/sync/src/failover.int.test.ts", "// integration:failover (E7.2, F21)", "import { randomUUID }"),
  cut("apps/sync/src/failover.int.test.ts", 'test("killing the owner moves the room', None),
  "<p>The integration test kills node-a the way a process dies: its Redis client is closed <em>first</em>, so the lease is neither renewed nor released and the heartbeat stops, then the sockets are torn down. Anything gentler (a clean <code>close()</code> releases the lease) would test a different, easier feature. The data half of F21 needs the journal and the real stack, and that is the chaos run.</p>",
  cut("scripts/chaos/kill-owner-failover.ts", "// chaos:kill-owner-failover (E7.2, SPEC F21)", "import { execFileSync }"),
  cut("scripts/chaos/kill-owner-failover.ts", "    const before = holderOf(doc);", "    const journal = psql("),
  "<p>Everything lesson 6 said about the ledger applies unchanged, which was the point of writing <code>noLossViolations</code> as a pure function: a different fault, the same assertion. Two things are new. The victim is read from the lease (<code>holderOf</code>, <code>redis-cli GET lease:&lt;id&gt;</code>), because the run does not know which node the api routed the room to, and must kill <em>that</em> one. And the victim is <em>not</em> restarted until the round is over: the peers have to find the other node through <code>/session</code> by themselves, and the takeover time is measured against <code>ttl + ttl/10 + 2 s</code>, so a takeover that waited out a second ttl fails the run.</p>",
  vs([("<code>redis.set(key, \"1\", \"PX\", ms)</code> as a heartbeat", "Redisson's lock watchdog, or an etcd lease keep-alive", "<code>r.set(key, 1, px=ms)</code>"),
      ("<code>for (;;) { ... return ...; await sleep(ms); }</code> with a deadline", "a <code>while (true)</code> with <code>Thread.sleep</code>; Awaitility in tests", "<code>while True:</code> with <code>await asyncio.sleep</code>"),
      ("<code>sleep: (ms) =&gt; Promise&lt;void&gt;</code> injected, advancing a fake clock", "an injected <code>Sleeper</code>", "an injected coroutine"),
      ("<code>await leases.close()</code> before <code>server.close()</code>: an unclean death, on purpose", "close the Jedis pool first", "close the Redis client first"),
      ("<code>Date.now() - killedAt</code> against a budget computed from the ttl", "<code>Duration.between</code>", "<code>time.time()</code> arithmetic")]),
  case("Stealing the lease as soon as the heartbeat is gone was rejected.",
       "<p>It would make failover take ttl/3 instead of a ttl. It would also make a paused owner's writes overlap with the new owner's from the moment of the steal, with nothing yet to stop them (the fence is E7.3, built after). Even with the fence, a steal turns \"the old owner is fenced when it wakes\" from a rare event into the normal one, and every op it accepted meanwhile is an op its peers were told about and the journal refused. Waiting for the expiry keeps the invariant that at most one node <em>believes</em> it owns a room at any wall-clock moment, except during a pause, and pauses are what the fence is for.</p>"),
  case("Shortening peer-client's backoff was rejected.",
       "<p>The second-ttl delay came from the client's retry curve: a peer that bounced on 4409 backed off, and by the time it asked again the lease had long expired. The tempting fix is a faster curve. The chosen one is that the <em>server</em> holds the connecting peer while it waits the lease out, so the bound on takeover comes from the node, and every client, including the worker's peers, gets it without touching their retry behaviour.</p>"),
  note("<strong>CAP, honestly:</strong> during the ttl after a kill the room is <em>unavailable</em>: the old owner is gone, the new one refuses to take the room until the lease expires, and peers hold their edits. That is a consistency-over-availability choice, made because two rooms for one document is a divergence the design cannot repair (lesson 2), while a ten-second pause is something peer-client already absorbs. The dial is <code>LEASE_TTL_MS</code>: shorter means faster failover and more false losses under load (a renewal that misses its window by a scheduler hiccup drops a healthy room); longer means the reverse. Ten seconds, renewed every three, is the default; the chaos run's budget is expressed in ttl so the test moves with the dial."))

section("fence", "5 · The fence: the check and the write are one statement",
  "<p>Section 2 ended with the argument: a process frozen past its lease cannot know it, so the storage must refuse it. F22 spells the fault out twice: <code>docker pause</code> the owner past its lease and resume it; and cut the owner off from Redis while Postgres still answers (a partition, scripted with toxiproxy). In both, the old owner wakes believing it owns the room, with ops queued and appends in flight, and the journal must end with no gap, no duplicate, and no row from it after the new owner read the journal.</p>",
  cut("packages/db/migrations/0014_fence.sql", "-- E7.3 (F22): the fence."),
  cut("packages/db/src/index.ts", "  /** E7.3: the largest lease token that ever claimed this document", "  /** What this sender's opId became"),
  cut("packages/db/src/index.ts", "/** E7.3: the append was refused because", "const QUEUES"),
  cut("packages/db/src/index.ts", "      async fence(orgId, documentId) {", "      find: async (orgId, documentId, actorId, opId) =>"),
  "<p>Three statements, and the whole feature is in how they relate. <strong><code>fence</code></strong> reads the largest token that ever claimed the document; the acquire in section 1 takes it as the <em>floor</em>, so a token issued after a Redis flush is still above every token the journal has seen. <strong><code>claim</code></strong> is how an opening becomes the document's only writer: one <code>update</code> that moves <code>fence_token</code> up to the lease token and sets <code>fence_claim</code> to a fresh random id, guarded by <code>fence_token &lt; $3</code>. Strictly less, not less-or-equal: two openings under one token (a node paused between acquire and claim, then a flush that reissues the number) cannot both claim. <strong><code>append</code></strong> is one statement: <code>insert ... select ... from documents where ... fence_claim is not distinct from $9 for update</code>. If the row still names this opening's claim, the row is written; if not, zero rows, and the store throws <code>Fenced</code>.</p>",
  "<p>Why the check must be <em>in</em> the statement rather than before it is the naive control in <code>fence.int</code>, and it is exactly the interleaving a pause produces: A reads the claim (still its own), freezes, B claims and reads the journal, A wakes and inserts. A read-then-write in app code lets that row in, one past what B read, so B's room never has it and B's next append collides on the seq. In one statement Postgres does the work. <code>FOR UPDATE</code> takes a row lock on the documents row, so an append and a claim on the same document serialise: the claim waits for an in-flight insert to commit (and B's replay then contains that row, correctly, because it was written under a claim that was still valid), or the claim commits first, and the append, which was blocked on the lock, <em>re-evaluates its WHERE against the updated row</em> (Postgres's behaviour under READ COMMITTED when a locked row changed) and inserts nothing. The test \"an append racing an uncommitted claim waits for it, then is refused\" is that second branch, with two real connections.</p>",
  "<p><code>is not distinct from</code> is SQL's null-safe equality: with no lease (one node, the tests) the append carries no claim, <code>$9</code> is <code>NULL</code>, and <code>NULL = NULL</code> would be unknown, never true; <code>IS NOT DISTINCT FROM</code> is true, so an unclaimed append lands only on a document never claimed, which is the right rule for a single node that has never had a rival.</p>",
  cut("packages/db/src/fence.int.test.ts", "// integration:append-stale-token-rejected", "let t: TestDb;"),
  cut("packages/db/src/fence.int.test.ts", 'test("an append racing an uncommitted claim', "/** The zombie:"),
  cut("packages/db/src/fence.int.test.ts", 'test("naive control:', None),
  "<p><strong>Why a claim id and not \"token at least the high-water mark\".</strong> The textbook fence compares tokens: the storage remembers the largest it has seen and refuses anything smaller. Two things about this repo made that insufficient. The counter lives in Redis, and a flushed Redis restarts it at 1, so the floor was needed to keep tokens rising at all. And even with the floor, one token can be issued twice (the pause-then-flush case), so the claim is a random id of <em>this one opening</em>, and an append compares the exact id: the loser of two openings under an equal token cannot write either. The token still matters, as the thing that orders claims and as the floor; the claim id is what an append carries.</p>",
  cut("packages/lease/src/index.int.test.ts", 'test("a floor (the journal', 'test("only the holder renews'),
  "<p><strong>The node's side.</strong> The claim happens in <code>open()</code>, after the lease and before the journal is read: from that moment only this opening's appends land, and every row a previous owner wrote before it is in what <code>load()</code> replays. A lost claim at open means a newer lease exists: 4409. A database that cannot answer the fence or the claim: 4503, try again.</p>",
  cut("apps/sync/src/server.ts", "    // The fence (F22), BEFORE the journal is read", "  /**\n   * Loads the document and its room"),
  cut("apps/sync/src/fence.ts", "import { Fenced }"),
  cut("apps/sync/src/server.ts", "    // A timed-out append may still land later: the room treats it as failed, and recover() replays it if it did.\n    // A fenced one never lands", "    const snapshotFrom"),
  "<p><code>watchFence</code> is a higher-order function typed with a tuple rest parameter, the same shape as lesson 6's <code>guard</code>: it wraps the append, keeps its signature, and tells the server <em>once</em> when a <code>Fenced</code> comes through, however many queued ops are refused behind it. The distinction it draws is the design decision of the bead: <strong>a fence is not an outage.</strong> Lesson 6's read-only mode is for a journal that will answer again; a fenced room will never be allowed to write again, so it must not sit in a heal loop pinging the database for ever. <code>onFenced</code> calls the same <code>drop</code> a lost lease calls: 4409 to every socket, snapshots stopped, room forgotten. <code>onReadOnly</code> checks <code>fenced</code> first so the heal loop is never started. The refusal itself still reaches the room, which answers \"unavailable\" to a socket that is already closing and applies nothing.</p>",
  cut("apps/sync/src/fence.test.ts", 'test("a fenced append is still refused'),
  cut("apps/sync/src/server.ts", "  /** The room's last snapshot, once the ops still in its queue are handled.", "  /**\n   * The last peer left"),
  "<p>Two more places had to learn about <code>lost</code>. A room that lost its lease or was fenced writes <em>no last snapshot</em>: the new owner is the only writer, and a snapshot from the old one could name a document the journal has moved past. And the shutdown path releases every lease after its snapshot, so that a clean stop moves rooms at once rather than a ttl later.</p>",
  "<p><strong>The runs.</strong> Both faults are scripted against the compose stack. <code>docker pause</code> freezes every thread of the container; when it is unpaused, the process continues from the instruction it was on, with its sockets still open and its in-flight promises still pending, which is the most faithful zombie there is. The partition uses toxiproxy in the path between each node and Redis, one listener per node, so <em>one</em> node can be cut off from Redis with a <code>timeout</code> toxic (bytes stop, connections stay open) while it still reaches Postgres, which is the case where the fence is the only thing standing.</p>",
  cut("docker-compose.yml", "  # E7.3: each sync node reaches Redis through this proxy", "  # E6.2: room snapshots (SPEC"),
  cut("scripts/chaos/toxiproxy.json", "["),
  cut("scripts/chaos/fenced.ts", "// chaos:zombie-fenced and chaos:partition-fenced", "import { execFileSync }"),
  cut("scripts/chaos/fenced.ts", "// The toxiproxy proxy of a node is named as the node", "const email"),
  cut("scripts/chaos/fenced.ts", "/**\n * A peer of the owner's room that never reconnects", "const org ="),
  cut("scripts/chaos/fenced.ts", "    edit(20); // on the wire...\n    await open(victim);", "    const journal = psql("),
  "<p>The <em>witness</em> is the observable for \"it closes its sockets\": a bare peer that never reconnects and never times out on its own, so the only way it stops being live is the old owner closing it. The run also reads the old owner's log for two lines: that it gave the room up (<code>lease N lost</code> or <code>fenced</code>), and how many appends the fence itself refused. A paused owner usually notices its lost lease first, from its clock, and the count is often zero; the fence is for the runs where it does not, and the report says which happened. Edits made <em>after</em> the old owner is back must also land, on the new owner, which is the last thing the ledger checks.</p>",
  vs([("<code>insert ... select ... where ... for update</code>: the check, the lock and the write in one statement", "the same SQL through JDBC; JPA's <code>@Version</code> is the row-level cousin, not this", "the same SQL with psycopg"),
      ("<code>fence_claim is not distinct from $9</code>: null-safe equality", "the same SQL; <code>&lt;=&gt;</code> in MySQL", "the same SQL"),
      ("<code>class Fenced extends Error {}</code>, told apart with <code>instanceof</code>", "a checked exception type", "a custom exception class"),
      ("<code>watchFence&lt;A extends unknown[], R&gt;(append, onFenced)</code>: a wrapper that keeps the signature", "a decorator with one wrapper per arity", "a decorator with <code>ParamSpec</code>"),
      ("<code>randomUUID()</code> as an opening's identity", "<code>UUID.randomUUID()</code>", "<code>uuid.uuid4()</code>"),
      ("<code>new Client({ options: \"-c search_path=...\" })</code>: a second real connection in a test", "a second <code>DataSource</code>", "a second <code>psycopg.connect</code>")]),
  case("The fence in app code, before the insert, was rejected by writing its failure down as a test.",
       "<p>The first sketch read <code>fence_claim</code>, compared it, and inserted. It is the shape every ORM invites, and the naive control in <code>fence.int</code> exists to keep it out: it performs the read, then the takeover, then the insert, and asserts that the zombie's row <em>is</em> in the journal. A control that shows the wrong design failing is worth more than a comment saying it would, because the next person who wants to \"simplify\" the statement has a red test to explain. Drill 2 plants this shape.</p>"),
  case("Seeding the Redis counter only at sync start was rejected.",
       "<p>Reading <code>fence_token</code> once when the node boots and <code>SET</code>ting the counter would handle a flush that happened while the node was down. A flush while it runs would still reissue tokens. Taking the floor on <em>every</em> acquire, inside the same script, costs one <code>GET</code> per acquisition and closes the window entirely; the integration test deletes the counter mid-test and asserts 43 follows 42.</p>"),
  case("Two openings under one token, and why \"less than\" is not \"less than or equal\".",
       "<p>A node acquires token 7, is paused before it claims, Redis is flushed, another node acquires and gets 7 again from a floor of 6, claims, and reads the journal. The paused node wakes and claims with 7. Under <code>&lt;=</code> it would succeed, and two rooms would each hold a valid claim; under <code>&lt;</code> it is refused and answers 4409. The exact-claim compare in the append is the second half: even if both somehow held token 7, only one holds the claim id the row names.</p>"),
  note("<strong>The distributed-systems shape, in one sentence:</strong> the lease says who <em>should</em> write, the clock says how long they may <em>believe</em> it, and the storage says whose writes actually <em>land</em>, by comparing a token the writer received when it became the owner. Chubby's sequencers, ZooKeeper's zxid, Kafka's producer epoch and etcd's revision are the same third piece with other names. A design with only the first two is the one Kleppmann's essay takes apart."))

section("tradeoffs", "6 · Trade-offs and comparisons: where this design sits",
  "<p>An interviewer will ask why Redis and not ZooKeeper or etcd, and what breaks when. Here is the honest map.</p>",
  vs([("Where the lease lives", "Redis: one node, no consensus, fast, loses everything on a flush or crash", "ZooKeeper (ZAB) or etcd (Raft): a majority must agree; survives a minority failing", "the same two choices; Consul sessions are a third"),
      ("What losing it costs", "leases are taken again; the token floor in Postgres keeps tokens rising; queues are rebuilt from the <code>jobs</code> table (SPEC §4)", "a lost quorum stops all acquisitions until it returns", ""),
      ("The fencing token", "<code>INCR</code> per document, floored by Postgres", "etcd's <code>revision</code>; ZooKeeper's <code>zxid</code> or the sequential node's number", ""),
      ("Who checks the token", "Postgres, in the append statement", "the storage the lock protects, always; ZooKeeper and etcd only <em>issue</em> it", ""),
      ("Liveness", "a heartbeat key with a short PX; a hint only", "an ephemeral node that vanishes with the session; a lease that lapses without keep-alive", ""),
      ("Java's Redisson <code>RLock</code>", "same Lua shape; a watchdog renews every ttl/3; <strong>no fencing token</strong>, so a paused holder's writes are not refused by anything", "", ""),
      ("RedLock (several Redis masters)", "not used: Kleppmann's critique applies (it still relies on timing), and one Redis with a fence in the storage is both simpler and safer for this workload", "", "")], head=("Question", "This repo", "ZooKeeper / etcd", "Notes")),
  "<p><strong>Why Redis is enough here.</strong> The lease is a <em>performance</em> mechanism in this design, not a <em>safety</em> one. Its job is to make sure that, almost always, exactly one node believes it owns a room, so that peers are not bounced and ops are not refused. Safety, the guarantee that no two writers ever both land rows for one document, is Postgres's job through the fence, and Postgres was already the truth for the journal. A consensus system would make the lease itself more reliable, at the cost of a second quorum to run, and it would still need the fence in the storage, because a leader elected by Raft can also be paused. Kleppmann's point is that the lock service is the wrong place to look for safety whatever it is built on.</p>",
  "<p><strong>What is not solved.</strong> A room moves only when its owner dies or lets go; there is no rebalancing, so a node that happened to be picked for many free rooms keeps them. The pick for a free room is random among live nodes, with no load signal. Both are named ponytails with an obvious upgrade (a room count per node in Redis, read by <code>pick</code>). Failover takes one ttl, which is visible: peers show \"offline\" for up to ten seconds. And <code>redis-proxy</code> is in the path of every run, not only chaos runs, one hop and one container that a compose override would move aside.</p>",
  "<p><strong>Redis flushed while everything runs.</strong> Every lease disappears at once. Every owner's next renewal is refused (the key is gone), so every room drops its peers within a third of a ttl; every peer asks <code>/session</code>, which sees no owner and picks a live node (or, with no heartbeats written yet, any node); the node acquires with a floor read from <code>fence_token</code>, so its token is above every claim the journal has seen, claims, replays, and opens. No op is lost: acknowledged ops are in the journal, in-flight ones are held by peer-client and re-offered after the next welcome. SPEC §4's row, <em>Redis lost: leases re-acquired; no document data lost</em>, is this paragraph.</p>",
  note("<strong>The interview answer in one breath:</strong> one lease per document in Redis with a monotonic token from the same script; holders trust it for 0.9 ttl from the send on their own monotonic clock; heartbeats route but never decide; a dead lease is waited out, never stolen; and the write path in Postgres checks a per-opening claim in the same statement that inserts, so a zombie's writes are refused whatever it believes. Consistency over availability for up to one ttl, by choice, because two rooms for one document cannot be repaired."))

section("testing", "7 · Testing two nodes without Docker, and then with it",
  "<p>The split from lesson 6 holds: every decision has a pure test that ran on every commit, and every I/O rule has an integration or chaos test that is written and unrun. Four shapes are new.</p>",
  "<p><strong>A fake clock that the sleep advances.</strong> <code>takeLease</code>'s tests inject <code>now</code>, <code>sleep</code> and <code>acquire</code>; the acquire costs one millisecond of fake time and answers \"free\" once the clock passes <code>expiresAt</code>; the sleep records what it was asked and moves the clock. So \"waited out, taken within a poll of expiry\" is an assertion on exact numbers, and the whole suite runs in milliseconds.</p>",
  "<p><strong>Two real servers in one process.</strong> <code>useTwoNodes</code> starts two <code>startSyncServer</code>s on free ports with two <code>createLeases</code> clients under a random key prefix, and hands the test a <code>route</code> that is the api's router with an injectable first pick. <code>roomAt</code> asks both servers who has peers for a document and <em>throws</em> if both do, which is the F20 invariant as a helper.</p>",
  cut("apps/sync/src/testing.ts", "/**\n * Two sync nodes sharing one Redis", "  afterAll(async () => {\n    await Promise.all(state?.servers"),
  "<p><strong>A second database connection.</strong> The race test in <code>fence.int</code> needs an <em>uncommitted</em> claim to be visible to nothing and blocking to one thing, which a pool cannot express: it opens a raw <code>pg.Client</code> on the test schema, begins a transaction, updates the row, and only then commits, while the store's append sits on the lock. <code>settled</code> being false after 300 ms is the assertion that the append waited rather than returned.</p>",
  cut("packages/db/src/fence.int.test.ts", 'test("real race, 20 rounds', 'test("naive control:'),
  "<p><strong>A witness.</strong> The chaos runs need to observe \"the old owner closed its sockets\", and a normal peer hides that by reconnecting. The witness is <code>connectPeer</code> with a <code>session</code> that answers once and then <code>null</code> (\"give up\"), so its status leaving <code>live</code> can only mean the server closed it.</p>",
  vs([("<code>sleep: (ms) =&gt; { slept.push(ms); clock += ms; return Promise.resolve(); }</code>", "a fake <code>Sleeper</code> that advances a fake <code>Clock</code>", "a fake sleep coroutine"),
      ("<code>as [RunningSyncServer, RunningSyncServer]</code>: a tuple from <code>Promise.all</code> of a mapped array", "an array of two, indexed", "a tuple from <code>asyncio.gather</code>"),
      ("<code>new Client({ options: \"-c search_path=...\" })</code>", "a JDBC URL with <code>currentSchema</code>", "<code>psycopg.connect(options=\"-c search_path=...\")</code>"),
      ("<code>if (asked) return null; asked = true;</code>: a session that answers once", "a one-shot <code>Supplier</code>", "a closure over a flag"),
      ("<code>execFileSync(\"docker\", [\"compose\", \"pause\", node])</code>", "<code>ProcessBuilder</code>", "<code>subprocess.run</code>")]),
  case("The integration test's kill had to be unclean to test anything.",
       "<p>A first draft of the failover test called <code>server.close()</code>, which snapshots and <em>releases</em> every lease; the room moved instantly and the test was green for the wrong reason. Closing the node's Redis client first, so that the release fails and the heartbeat stops, is what makes the test wait out a real lease. \"Green for the wrong reason\" is the failure mode of every test of a failure: check what the fault actually removed.</p>"),
  note("<strong>Honest status, repeated here because it matters:</strong> the unit tests (holder parsing, <code>keepLease</code>, <code>parseSyncNodes</code>, <code>syncRouter</code>, <code>takeLease</code>, <code>watchFence</code>, peer-client's reroute, the routing config fields) ran green on every commit and were mutation-checked. The integration suites (<code>lease index.int</code>, <code>api session.int</code>, <code>one-room-globally.int</code>, <code>one-room-join-race.int</code>, <code>failover.int</code>, <code>packages/db fence.int</code>) and the three chaos runs (<code>kill-owner-failover</code>, <code>fenced zombie</code>, <code>fenced partition</code>) are written, reviewed and committed, and have not been run. The next section is what running them looks like."))

section("demo", "8 · Two nodes by hand: what to run once the stack is up",
  "<p>The exact commands and what each should show. The dev stack now runs <code>sync</code> and <code>sync-2</code> (host ports 3001 and 3003), <code>redis-proxy</code> (toxiproxy, control API on 127.0.0.1:8474), and the api's <code>SYNC_PUBLIC_URL</code> is the two-node table. Where a document id is needed it is the <code>?doc=</code> in the canvas's address bar.</p>",
  shell("0 · Bring the stack up",
        "./init.sh                                    # two sync nodes; migrate runs 0014 (fence_token, fence_claim)\n"
        "docker compose ps                            # sync, sync-2, redis-proxy healthy\n"
        "open http://localhost:5173/?user=you@example.com     # New document; Add Stack; note ?doc=&lt;id&gt;"),
  shell("1 · Who owns the room (F20)",
        "docker compose exec -T redis redis-cli --no-auth-warning GET lease:&lt;id&gt;      # \"1:sync\" or \"1:sync-2\": token 1, the owner\n"
        "docker compose exec -T redis redis-cli --no-auth-warning MGET node:sync node:sync-2   # both \"1\": both beating\n"
        "curl -s -X POST -H 'x-dev-user: you@example.com' localhost:3000/documents/&lt;id&gt;/session | jq .wsUrl   # the owner's address\n"
        "# Open the same document in a second tab: it lands in the same room (edits appear in both). Open a NEW document: it may land on the other node.\n"
        "docker compose exec -T postgres psql -U noon -d noon -c \"select fence_token, fence_claim from documents where id = '&lt;id&gt;'\"   # 1, and this opening's claim"),
  shell("2 · Kill the owner (F21)",
        "docker compose kill --signal SIGKILL sync    # (or sync-2: whichever GET lease named). Keep editing: \"offline\", edits queue locally\n"
        "docker compose exec -T redis redis-cli --no-auth-warning MGET node:sync node:sync-2   # the dead one is nil within ttl/3 (about 3 s)\n"
        "# Within about 10 s (one LEASE_TTL_MS), without a reload: \"live\", then \"saved\"; the lease now names the other node with token 2:\n"
        "docker compose exec -T redis redis-cli --no-auth-warning GET lease:&lt;id&gt;      # \"2:sync-2\"\n"
        "docker compose start sync                    # back for the next run; it owns nothing until a free room's first peer lands on it"),
  shell("3 · The zombie (F22)",
        "docker compose pause &lt;owner&gt;                # the owner freezes. Edit in the tab: \"offline\"; the other node takes the room after one ttl\n"
        "docker compose unpause &lt;owner&gt;              # a moment later its log says the room was given up:\n"
        "docker compose logs --no-color &lt;owner&gt; | grep -E 'lease [0-9]+ (lost|fenced)'\n"
        "docker compose exec -T postgres psql -U noon -d noon -c \\\n"
        "  \"select count(*), count(distinct seq), max(seq) from op_journal where document_id = '&lt;id&gt;'\"   # all equal: no gap, no duplicate"),
  shell("4 · The partition (F22, the other fault)",
        "curl -s -X POST localhost:8474/proxies/sync/toxics -d '{\"name\":\"cut\",\"type\":\"timeout\",\"stream\":\"downstream\",\"toxicity\":1,\"attributes\":{\"timeout\":0}}'\n"
        "                                             # node \"sync\" can no longer hear Redis; Postgres still answers it. Its renewals fail; after 0.9 ttl it drops its rooms\n"
        "curl -s -X DELETE localhost:8474/proxies/sync/toxics/cut\n"
        "LEASE_TTL_MS=3000 docker compose up -d sync sync-2   # to watch faster: failover in about three seconds"),
  shell("5 · Then the checks that prove it without hands",
        "pnpm exec vitest run --config vitest.integration.config.ts packages/lease/src/index.int.test.ts apps/api/src/session.int.test.ts apps/sync/src/one-room-globally.int.test.ts apps/sync/src/one-room-join-race.int.test.ts apps/sync/src/failover.int.test.ts packages/db/src/fence.int.test.ts\n"
        "node scripts/chaos/kill-owner-failover.ts    # {\"chaos\":\"kill-owner-failover\",\"verdict\":\"PASS\",\"rounds\":[{\"from\":\"sync\",\"to\":\"sync-2\",\"movedAfterMs\":...,\"violations\":[]},...]}\n"
        "node scripts/chaos/fenced.ts zombie          # {\"chaos\":\"zombie-fenced\",\"verdict\":\"PASS\",\"rounds\":[{\"fencedAppends\":0,...}]}\n"
        "node scripts/chaos/fenced.ts partition       # {\"chaos\":\"partition-fenced\",...}\n"
        "make chaos                                   # all five runs, in order; breaks and restores the real stack\n"
        "make check                                   # the whole gate, as the pre-commit hook runs it"),
  cut("Makefile", "# Outside `make check`: the chaos checks", "# Outside `make check` (minutes"),
  note("<strong>What to do when a step does not match this page:</strong> the page was cut from the code at commit <code>" + commit + "</code>, and the code is right until a test says otherwise. A step that fails is a finding: write it as <em>sequence → false belief → consequence → smallest fix</em> (SPEC §4a's form) and file it against the bead that owns the code."))

section("limits", "9 · What the type system could not see, epic 7 edition",
  "<p>Everything below compiled under <code>strict</code>, passed the linter and the first tests, or was rejected at design time by asking what the types could not ask.</p>",
  vs([("a token issued to every loser of an acquire race", "two round trips look like one operation", "<code>INCR</code> only on the branch that does the <code>SET</code>, in one script"),
      ("a stale holder's <code>DEL</code> deleted the next owner's lease (measured)", "a key is a key", "compare-and-delete in Lua"),
      ("a deadline counted from the reply, not the send", "both are \"now\"", "<code>sentAt</code> read before the await"),
      ("a hung renewal kept a room alive", "a promise in flight is not an error", "the deadline is checked on every read of <code>held</code>"),
      ("a failed renewal shortened a lease an earlier one had earned", "an assignment is an assignment", "only <code>true</code> moves <code>validUntil</code>"),
      ("a wall clock that jumps backwards", "<code>Date.now()</code> and <code>performance.now()</code> are both numbers", "monotonic only"),
      ("a frozen process believes it holds the lease (measured, 1.7 s)", "no type describes a pause", "the fence in the storage"),
      ("the api took leases for nodes that could not renew them", "acquire and renew look independent", "the holder is the acquirer"),
      ("a hash pick sent peers to a dead node for ever", "a pure function looks fair", "heartbeats as a routing hint"),
      ("stealing on a missed heartbeat let a paused owner overlap the new one", "\"not beating\" reads as \"dead\"", "wait the lease out; never steal"),
      ("a second ttl lost to the client's backoff", "a retry curve has no budget", "the server holds the peer while it waits"),
      ("a restarted node bounced its own peers (E7.1's ponytail)", "its own id looked like a rival", "our own dead lease is waited out too"),
      ("\"/sync\" swallowed \"/sync-2\"", "a prefix is a prefix", "anchored regex keys"),
      ("an owner not in the routing table looped on 4409", "a <code>Map.get</code> returns undefined quietly", "throw, loudly"),
      ("the fence checked in app code let a zombie row in (the naive control)", "two statements look sequential", "one statement, <code>for update</code>"),
      ("a flushed Redis reissued token 1", "a counter is assumed monotonic", "a floor from <code>fence_token</code> on every acquire"),
      ("two openings under one token both claimed", "<code>&lt;=</code> reads as harmless", "<code>&lt;</code>, and an exact claim id"),
      ("<code>NULL = NULL</code> refused every single-node append", "SQL's three-valued logic", "<code>is not distinct from</code>"),
      ("a fenced room healed for ever", "a refused append looked like an outage", "<code>Fenced</code> drops; <code>onReadOnly</code> checks <code>fenced</code>"),
      ("a lost room wrote a last snapshot over the new owner's", "the snapshot path did not know about leases", "<code>if (opened.lost) return false</code>"),
      ("a clean close killed the failover test's reason to exist", "release and death look alike to a test", "close the Redis client first"),
      ("the worker's peers dialled one node directly", "a URL compiled fine", "<code>syncSessions</code> routes like <code>/session</code>")], head=("What went wrong, or would have", "Why", "Fix")),
  note("<strong>The pattern, extended once more:</strong> lesson 6 said types cannot see whether a write happened or which order two effects took. Epic 7 adds the two that multi-node turns on: types cannot see <em>time</em> (a deadline from the wrong instant compiles; a pause is invisible) and cannot see <em>which process is speaking</em> (a stale owner's write is the same TypeScript as a live one's). Both were answered the same way as before: put the truth in one place (Redis for who should own, Postgres for whose writes land), read it before you believe anything, compare tokens rather than clocks wherever safety is at stake, and write a test that provokes the exact interleaving."))

toc = "".join(f'<li><a href="#{sid}">{title}</a></li>' for sid, title, _ in S)
sections = "".join(f'<section id="{sid}"><h2>{title}</h2>{body}</section>' for sid, title, body in S)
style = re.search(r"<style>.*?</style>", (root / "docs/handbook/lesson-0.template.html").read_text(), re.S).group(0)
page = (pathlib.Path(__file__).parent / "lesson-7.template.html").read_text()
page = page.replace("{{STYLE}}", style).replace("{{TOC}}", toc).replace("{{SECTIONS}}", sections).replace("{{COMMIT}}", commit)
(out / "lesson-7.html").write_text(page)
print("built", len(page), "bytes at", commit, "with", page.count('<p class="label">From'), "code blocks")
