"""Builds docs/handbook/lesson-5.html. Every code block is cut from the real repo by anchor text,
so the page cannot show code that does not exist; a missing anchor fails the build."""
import html, os, pathlib, re, subprocess
here = pathlib.Path(__file__).resolve()
root = pathlib.Path(os.environ.get("NOON_ROOT") or (here.parents[2] if (here.parents[2] / "SPEC.md").exists() else pathlib.Path.cwd()))
out = pathlib.Path(os.environ.get("NOON_OUT") or root / "docs/handbook")
commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True).stdout.strip()

def cut(path, start, end=None, include_end=False):
    src = (root / path).read_text()
    i = src.index(start)
    j = len(src) if end is None else src.index(end, i + len(start)) + (len(end) if include_end else 0)
    body = src[i:j].rstrip()
    return (f'<p class="label">From <span class="mono">{path}</span></p>'
            f'<div class="scroll"><pre><code>{html.escape(body)}</code></pre></div>')

def shell(title, body):
    return f'<p class="label">{title}</p><div class="scroll"><pre class="out"><code>{body}</code></pre></div>'

def vs(rows, head=("TypeScript (this repo)", "Java", "Python")):
    body = "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows)
    return f'<div class="scroll"><table><tr>{"".join(f"<th>{h}</th>" for h in head)}</tr>{body}</table></div>'

def case(title, body): return f'<div class="break"><p class="label">Case study · found by review, by a learning test, or by a test that was written to refute a claim</p><p><strong>{title}</strong></p>{body}</div>'
def note(body): return f'<p class="note">{body}</p>'
m = lambda s: f"<span class='mono'>{s}</span>"

S = []
def section(sid, title, *parts): S.append((sid, title, "".join(parts)))

section("map", "The map: the loop closes",
  "<p>Epic 4 turned a document into one file and ran it. Epic 5 closes the loop: <strong>an engineer's push to that file becomes ops on the open canvas, a push that breaks the file's fixed shape becomes a banner and nothing else, and one press of Ship becomes one pull request that a second press updates.</strong> Along the way the sandbox lost its network and gained a token, because a preview reachable by anyone holding a document id is not a preview you can put behind a public URL. Nothing in the room changed. Git is one more peer, and like the AI and the preview it writes through the same door every browser tab uses.</p>",
  vs([("1", m("init.sh"), m("scripts/gitea.ts"), "Gitea in compose; the user <code>noon</code>, a token kept while it works, the seed as ONE commit from our own objects, a webhook to the api"),
      ("2", m("apps/worker/src/sandbox.ts"), m("apps/worker/sandbox/Dockerfile"), "a sandbox on an <code>--internal</code> network clones from a git bundle the worker fetched and handed over by <code>docker exec</code>"),
      ("3", m("apps/worker/src/sandbox-proxy.ts"), m("apps/web/preview-proxy.ts"), "the one door to every sandbox: <code>/preview/&lt;document&gt;/&lt;nonce&gt;.&lt;hmac&gt;/</code>, and the same path on the canvas's own origin through a tunnel"),
      ("4", m("packages/codegen/src/parse.ts"), "", "<code>parse(tsx, manifest)</code>: the inverse of <code>generate</code>, or a named reason and a line number"),
      ("5", m("apps/api/src/webhook.ts"), m("apps/api/src/app.ts"), "<code>POST /webhooks/gitea</code>: a public route; HMAC over the raw bytes, then one row"),
      ("6", m("packages/db/migrations/0009_git_events.sql"), m("apps/worker/src/git.ts"), "the inbox with two unique keys; the git peer's mirror, its reconcile, a worktree per event"),
      ("7", m("apps/worker/src/push-ops.ts"), m("apps/worker/src/push.ts"), "a three-way diff to minimal ops, submitted through <code>@noon/peer-client</code> as actor <code>git</code>"),
      ("8", m("packages/db/migrations/0010_document_conflicts.sql"), m("apps/web/src/ConflictBanner.tsx"), "a refused push, one row per document, a <code>role=\"alert\"</code> that names the commit and the file"),
      ("9", m("packages/db/migrations/0011_ship_jobs.sql"), m("apps/worker/src/ship.ts"), "Ship: a job whose QUEUED row is unique per document; a commit from git objects alone; a push never forced; one pull request found by <code>head.ref</code>")], head=("Step", "Where", "And", "What happens")),
  "<p>Four ideas carry the epic. <strong>At least once plus a database key is exactly once</strong> (sections 4 and 5): Gitea does not retry, so there is a second door, and both doors meet at one unique constraint. <strong>Git is a peer, not a writer</strong> (section 6): every change to a document goes through the room, so the git peer submits ops and the room may refuse them one by one. <strong>The diff is three-way</strong> (section 6): what the engineer changed, replayed on the document as it is now, never the pushed file against the document. And <strong>idempotence lives in an index, and the commit is recorded before the push</strong> (section 8). Section 2 is a security boundary that had to be rebuilt before any of this could be shown to anyone.</p>",
  vs([("a webhook receiver with a raw-body HMAC and a Postgres unique key as the dedupe", "a Kafka consumer with an idempotency key in the same transaction as the write", "the same; <code>ON CONFLICT DO NOTHING</code> in psycopg"),
      ("a reconcile on a timer and on demand, reading a bare mirror", "an outbox/inbox pattern with a poller", "a Celery beat task that lists remote refs"),
      ("a three-way tree diff to ops, replayed on the live state", "JGit's <code>ThreeWayMerger</code>; <code>diff3</code>", "<code>difflib</code> is two-way; you write the three-way"),
      ("a commit built from git objects, no checkout, over the CLI", "JGit <code>DirCache</code> + <code>CommitBuilder</code>", "dulwich; or the same CLI plumbing")], head=("This repo", "Java world", "Python world")))

section("gitea", "1 · Gitea joins the stack, and the sandbox clones through the worker",
  "<p>The stack gains a git server it owns. Gitea runs in compose on the host's loopback (3002: the api and sync have 3000 and 3001), with SQLite, no install page, no registration, sign-in to view, and one permitted webhook host: <code>api</code>. Everything <code>init.sh</code> does to it is scripted and safe to run again: make the user <code>noon</code> (<code>admin</code> is a reserved name, measured in the learning test), keep the worker's token while Gitea still accepts it and mint one otherwise, then bootstrap the repo.</p>",
  cut("docker-compose.yml", "  gitea:", '    ports: ["127.0.0.1:${GITEA_PORT:-3002}:3000"]', True),
  cut("init.sh", "# The worker's token: kept while Gitea", "GITEA_URL="),
  "<p>Read the shell carefully: the password and the token reach <code>curl</code> through a config file on stdin (<code>curl_with</code>), never as an argument, because arguments are visible to every process on the machine. The bootstrap is a TypeScript script run by Node directly (no build step), and its first job is to make the seed <em>the same commit everywhere</em>: <code>git commit-tree HEAD:seed/sample-app</code> with a fixed author and date builds a commit from objects already in this repository, so the same tree gives the same id on every machine and every run.</p>",
  cut("scripts/gitea.ts", "/**\n * The seed as ONE commit", "type Hook ="),
  cut("scripts/gitea.ts", "export async function bootstrapGitea"),
  "<p>Three habits from that file you will use everywhere in this epic. <strong><code>promisify(execFile)</code></strong> turns Node's callback-style child process into a promise; <code>execFile</code> (not <code>exec</code>) takes an argument array, so there is no shell and nothing to quote. <strong><code>new URL(\"../\", import.meta.url)</code></strong> is how an ES module finds its own directory (<code>__dirname</code> does not exist in modules). And <strong>the token goes to git as an HTTP header through <code>GIT_CONFIG_COUNT</code>/<code>GIT_CONFIG_KEY_0</code>/<code>GIT_CONFIG_VALUE_0</code></strong>, never in the URL: a URL lands in <code>.git/config</code> of every clone and in every git error message, and the worker's config refuses one that carries credentials.</p>",
  cut("apps/worker/src/config.ts", "  // No credential in it:", "  GITEA_USER"),
  "<p><strong>The sandbox cannot reach Gitea, on purpose.</strong> Since noon-9gz (section 2) each sandbox sits on its own <code>--internal</code> Docker network: no egress, no <code>host.docker.internal</code>, no other sandbox. So it cannot clone. The worker, which is on the compose network, keeps a bare mirror per seed URL, fetches it on every start, and hands <code>main</code> over as a <em>git bundle</em> by <code>docker exec</code> into the sandbox's <code>/tmp</code>, the way it already hands over the page. The clone's <code>origin</code> is that file: no host and no credential anywhere customer code can read.</p>",
  cut("apps/worker/src/sandbox.ts", "/**\n * Hands the seed to a container", "/** git's environment"),
  cut("apps/worker/src/sandbox.ts", "/** git's environment", "/**\n * Puts the generated file"),
  cut("apps/worker/sandbox/Dockerfile", "COPY --chmod=755 <<'EOF' /home/node/start.sh", "mkdir -p noon-preview"),
  "<p>Two details are the whole reliability story. The bundle is written under another name and renamed (<code>cat &gt; x.part &amp;&amp; mv x.part x</code>), so <code>start.sh</code>, which polls for the file, never reads half of one: a rename is atomic on one filesystem. And <code>mirrors</code> is a <code>Map</code> from mirror path to <em>the last fetch-and-bundle promise</em>: a new start chains onto the previous one with <code>.catch(() =&gt; undefined).then(...)</code>, so two starts never run <code>git</code> in one mirror at once (git takes ref locks and the loser would fail). That is a mutex written as a promise chain, the JavaScript way of \"one at a time per key\". Section 8 uses the same shape for pull requests.</p>",
  cut("apps/worker/src/gitea.int.test.ts", 'test("a sandbox clones from Gitea through the worker', 'test("a push to Gitea reaches'),
  vs([("<code>promisify(execFile)</code>: a child process as a promise, argument array, no shell", "<code>ProcessBuilder</code> + <code>waitFor()</code>; JGit if you would rather not shell out", "<code>asyncio.create_subprocess_exec</code>; GitPython"),
      ("<code>new URL(\"../\", import.meta.url).pathname</code>", "<code>getClass().getResource(\"..\")</code>", "<code>Path(__file__).resolve().parents[1]</code>"),
      ("a credential as <code>GIT_CONFIG_*</code> env, never in a URL", "JGit's <code>CredentialsProvider</code>; the same rule about URLs", "the same env; never <code>https://user:token@</code>"),
      ("a promise chain per key as a mutex", "<code>ConcurrentHashMap.compute</code> with a lock per key; <code>Semaphore(1)</code>", "<code>asyncio.Lock</code> per key"),
      ("a git bundle over stdin as \"the network\"", "the same file idea; or a shared volume", "the same")]),
  case("A sandbox with no route out could not clone, and routing the proxy to Gitea would have leaked every repo.",
       "<p>The obvious fix after noon-9gz's <code>--internal</code> network was a route from the pool's proxy to Gitea. Rejected: customer code runs in the sandbox, and a route to Gitea with the worker's token would let it read every repository that token reads, and would put the proxy on the compose network. A tarball from Gitea's archive endpoint was rejected too: Ship needs history to build on. The bundle keeps the trust boundary where it was: the only thing that enters a sandbox is bytes the worker wrote, and the only thing that leaves is the dev server's answers through the proxy.</p>"),
  case("The seed image no longer rebuilds on every sample-app edit.",
       "<p>Before E5.1 the sample app was <code>COPY</code>'d into the sandbox image, so any edit to <code>seed/sample-app</code> invalidated a six-minute build. Now the image holds Node, baked <code>node_modules</code> and our preview entry; the source arrives at start, from Gitea, through the worker. The test suites need no Gitea for this: <code>sandbox-testing.ts</code> pushes the same seed commit into a local bare repository, and git fetches a path exactly as it fetches a URL.</p>"))

section("door", "2 · One door with a token: the sandbox proxy, and the public URL",
  "<p>This section is two beads (noon-l96, noon-9gz) and a security review, and it had to land before the loop could be shown to anyone outside the machine. The problem: showing the app through a tunnel (ngrok's free plan: <em>one</em> hostname, no wildcards) meant the iframe's <code>http://127.0.0.1:&lt;port&gt;</code> was the <em>visitor's</em> loopback, and mixed content under https besides. So the preview had to ride the canvas's own origin, path-based: <code>/preview/&lt;document&gt;/...</code>. And once anyone with the URL can reach a preview, a document id alone must open nothing.</p>"
  "<p><strong>The token.</strong> Every sandbox's dev server serves under a base of <code>/preview/&lt;document&gt;/&lt;nonce&gt;.&lt;hmac&gt;/</code>, where the nonce is fresh for every container the worker <em>creates</em> and the HMAC signs document and nonce under a key only the worker and the pool's proxy hold. Two locks: the proxy refuses any token it did not see signed for that document (a guess, another document's, a bare id), and the sandbox refuses a token of an earlier container of the same document (its base does not match: a bare 404). A URL lives exactly as long as its container.</p>",
  cut("apps/worker/src/sandbox-proxy.ts", "const PATH =", "/**\n * The sandbox's Vite accepts"),
  "<p>Read <code>previewDocument</code>: <code>timingSafeEqual</code>, not <code>===</code>. A string compare returns at the first differing byte, and the time it takes tells an attacker how many bytes they have right. The regex fixes both strings at 32 hex digits before the compare, because <code>timingSafeEqual</code> <em>throws</em> on different lengths. The same two lines guard the webhook in section 4.</p>",
  cut("apps/worker/src/sandbox-proxy.ts", "  // The preview's HMR WebSocket", "  server.listen(port);"),
  "<p>The proxy is Node's standard library and nothing else: <code>node:http</code>'s <code>createServer</code> for requests, <code>request</code> to forward them, and the server's <code>upgrade</code> event for WebSockets, where the HTTP handshake is replayed by hand over a raw <code>node:net</code> socket and the bytes are piped both ways. It has to be stdlib-only because of <em>where it runs</em>: inside the sandbox image, handed to Node as a string (<code>node --input-type=module-typescript -e</code>: Node 24 strips the types of a script it was given on the command line too). No second image to build or keep in step; a label on the container names the program and key it runs, so a changed program or key is a container made anew.</p>",
  cut("apps/worker/src/sandbox.ts", "const PROXY_PORT = 8080;", "/** Names what a key signs"),
  cut("apps/worker/src/sandbox.ts", "async function makeProxy", '  const networks = (await run("network", "ls"'),
  "<p>The key is <em>derived</em>, not a new secret: <code>HMAC(SESSION_TOKEN_SECRET, \"noon-sandbox-preview-key\")</code>. The sync server's secret never leaves the worker (the proxy gets only the derived key), and a stack whose <code>.env</code> predates the bead starts without a new entry. Key derivation is the general tool here: one root secret, one purpose-named key per use, and no use can be turned into another.</p>",
  cut("apps/worker/src/config.ts", "  // The preview tokens' key, derived", "  return {"),
  "<p><strong>The network.</strong> Each sandbox gets a Docker network of its own with <code>--internal</code>, and the proxy is joined to every one of them. Two facts were measured before this shape was chosen, and both are in the comment: Docker publishes <em>no</em> port for an internal-only container (hence a proxy at all), and turning inter-container traffic off on one shared network cut the proxy off too (hence one network per document). Disk is capped the same way: a read-only root, the working tree a 256 MB tmpfs, <code>/tmp</code> 64 MB, both counted against the container's memory, so filling them costs the sandbox its own memory and never the host's disk.</p>",
  cut("apps/worker/src/sandbox.ts", "/**\n * The document's own network.", "/** Puts a container on a network"),
  "<p><strong>The public URL.</strong> The canvas's own Vite dev server forwards <code>^/preview/</code>, HTTP and WebSocket alike, to the stack's sandbox proxy on the loopback, path unchanged, with one fixed target. No lookup, no door to any other port, and no check of its own: the sandbox proxy is the check. The api rewrites only the <em>origin</em> of the stored URL when <code>PREVIEW_PUBLIC_URL</code> is set; the row keeps the loopback truth, and the contract lets the canvas frame exactly two things: this machine's loopback, or its own origin under <code>/preview/</code>.</p>",
  cut("apps/web/preview-proxy.ts", "/**\n * The running page through the canvas's OWN origin"),
  cut("packages/contracts/src/index.ts", "/**\n * A document's preview as the canvas reads it (F15)", "// --- Conflicts (F16b)"),
  vs([("<code>timingSafeEqual</code> after a regex fixes the length", "<code>MessageDigest.isEqual</code>", "<code>hmac.compare_digest</code>"),
      ("a key derived with HMAC from one root secret", "<code>HKDF</code> in JCA; the same idea", "<code>hashlib.pbkdf2_hmac</code> / <code>cryptography</code>'s HKDF"),
      ("<code>server.on(\"upgrade\")</code> and a hand-written 101 handshake over <code>net.connect</code>", "Spring Cloud Gateway does it for you; Undertow's proxy handler", "aiohttp's <code>web.WebSocketResponse</code> relayed by hand"),
      ("a proxy program handed to <code>node -e</code> inside another image", "a jar copied into the image; no equivalent of \"the source is the artifact\"", "<code>python -c</code> with the module's text: the same trick"),
      ("Vite's <code>proxy</code> with one target and <code>ws: true</code>", "an nginx <code>location</code> with <code>proxy_pass</code>; the same fixed target rule", "the same nginx")]),
  case("Vite's own 404 named the base, and would have handed the document id to anyone trying ports.",
       "<p>Before the token, the base was <code>/preview/&lt;document&gt;/&lt;port&gt;/</code>, and the dev server had to answer <em>nothing</em> outside it. Its own 404 page says \"did you mean to visit /preview/&lt;document&gt;/...\": read in Vite's source, measured on a local run. So a plugin with <code>enforce: \"pre\"</code> answers a bare 404 first. With the token the id alone opens nothing anyway, but the plugin stays: a defence you can point at is worth more than one you infer.</p>"
       + cut("apps/worker/sandbox/Dockerfile", "/**\n * The worker's PREVIEW_BASE", "export default async (env)")),
  case("Through the tunnel the frame stayed blank: a header of the tunnel's own turned every module request into a preflight, and Vite answered it before its proxy did.",
       "<p>ngrok adds <code>ngrok-skip-browser-warning</code>, which makes every module request from the opaque-origin frame a CORS preflight from origin <code>\"null\"</code>. Vite answers every preflight <em>itself</em>, before any proxy or plugin, by its default origin rule (localhost only): a 204 with no <code>Access-Control-Allow-Origin</code>, and a blank frame. The sandbox, which owns that decision (its CORS lock allows exactly <code>\"null\"</code>), never saw the request. The fix keeps Vite's rule for the canvas's own files and lets the preflight <em>continue</em> to the proxy. Rejected: allowing <code>\"null\"</code> on the canvas itself, which would let any sandboxed frame of any site read the canvas's source.</p>"
       + cut("apps/web/preview-proxy.int.test.ts", "// A module request with a header of its own", 'test("the canvas\'s own files stay closed')),
  case("The 401s on the preview's module requests were the tunnel's basic auth, not ours.",
       "<p>With basic auth on the tunnel, the canvas loaded (the browser had the credentials) and the preview's module requests failed with 401: requests from inside a sandboxed frame carry no credentials. Nothing in this repository was wrong, and the fix was in the tunnel's policy. The lesson is about debugging across boundaries: when a request fails, first establish <em>which hop</em> answered. The response's headers name the server; a 401 with the tunnel's realm is not your 401.</p>"),
  case("The per-org preview cap became exact, and lesson 4's third drill question got a new ending.",
       "<p>Lesson 4 declined to make \"at most four previews per org\" exact, and named the upgrade: an advisory lock per org. The noon-9gz security review asked for it, and it is eight lines: the <code>INSERT ... SELECT</code> runs in a transaction that first takes <code>pg_advisory_xact_lock(hashtext('noon:preview:' || org))</code>, so opens of one org take turns and the count inside the statement is the truth. The ponytail comment named a ceiling and an upgrade path; the review called the upgrade; the shape of the code did not have to change to take it.</p>"
       + cut("packages/db/src/index.ts", "  /** One statement, returning ids, holding the org's preview lock", "  async function one<T>")),
  note("<strong>What noon-9gz did not do, and says so:</strong> the Docker socket the sandbox worker holds stays raw. A socket proxy that filters by API section still allows <code>create</code> and <code>exec</code>, which is root; an authorization plugin is the real fix, and it is written down as such. A security review that ends with \"here is what is still open\" is worth more than one that ends with \"done\"."))

section("parse", "3 · Reading the file back: parse is the inverse of generate",
  "<p>Keystone 8 has two directions. <code>generate</code> (lesson 4) takes a tree to one file of a fixed shape. <code>parse</code> takes a file back to a tree, <em>only while it still has that shape</em>, and every way out of the shape has a name and a line number, because that is what the conflict banner shows. The file is untrusted input: anyone who can push wrote it.</p>",
  cut("packages/codegen/src/parse.ts", "/**\n * Keystone 8, the way back", "type ParseReason"),
  "<p>Three decisions follow from \"untrusted\". The file is <strong>parsed, never run</strong>: TypeScript's own parser (<code>ts.createSourceFile</code>, syntax only, no program and no type checker), already a dependency of the design-system package, so no new package. Sizes are <strong>capped before parsing</strong> (2 MB, 5000 nodes, depth 64: the room's own defaults, copied not imported, because codegen must not depend on the sync app). And <strong>a value is accepted only as a literal read from its syntax</strong>: a string literal's text, a numeric literal's normalised text, <code>true</code>, <code>false</code>. Nothing is evaluated.</p>",
  cut("packages/codegen/src/parse.ts", "type ParseReason =", "const DESIGN_SYSTEM"),
  "<p>The reason type is a <em>union of string literal types</em>, and it starts with <code>CodegenReason</code>: everything <code>generate</code> can refuse, <code>parse</code> can refuse too, because the last thing <code>parse</code> does is hand its tree to <code>generate</code>. That is the design's centre: the rules about components, props and tree shape exist <em>once</em>, in <code>generate</code>, and are the same in both directions. A second copy here would drift, and a document this accepts but <code>generate</code> refuses would be a push that lands on the canvas and then cannot be shipped.</p>",
  cut("packages/codegen/src/parse.ts", "/** A refusal that carries the line", "function read(tsx"),
  "<p><code>OutOfShape</code> is a class extending <code>Error</code> with a <code>readonly reason</code> field assigned in the constructor. Note what it is <em>not</em>: a parameter property (<code>constructor(readonly reason: ...)</code>), which this repo bans (<code>erasableSyntaxOnly</code>), because Node's type stripping cannot erase syntax that generates code. The walk throws it from wherever the shape breaks; <code>parse</code> catches once, at the top, and turns it into a value. A <code>RangeError</code> there is not a bug: TypeScript's parser recurses, and a file nested far past our depth cap overflows its stack before our cap is checked; that is a reason (<code>too_deep</code>), not a crash.</p>",
  cut("packages/codegen/src/parse.ts", "  // ponytail: `parseDiagnostics` is internal", "  const imported = new Set"),
  "<p>A ponytail with a fence around it: <code>parseDiagnostics</code> is internal to TypeScript, stable for a decade and used by most tools, and the public route is a whole <code>Program</code> just to ask for syntax errors. The cast goes through <code>unknown</code> to a type with an optional field; if the field ever disappears the guard refuses <em>every</em> file loudly, rather than accepting broken ones quietly. That is the rule for depending on something you were not promised: make its absence fail closed.</p>",
  cut("packages/codegen/src/parse.ts", "  // Iterative, like generate:", "  return { rootId, nodes };"),
  cut("packages/codegen/src/parse.ts", "/** A prop's value, read from its syntax only", "/** The children that are elements"),
  cut("packages/codegen/src/parse.test.ts", 'test("unit:parse-roundtrip: formatting is not shape', 'test("unit:parse-roundtrip: an in-shape edit'),
  cut("packages/codegen/src/parse.test.ts", 'test("unit:parse-shape-breakers: nesting deep enough', "test.each<[string, unknown]>"),
  vs([("<code>ts.createSourceFile(..., ScriptKind.TSX)</code>: a syntax tree, no checker", "JavaParser / ANTLR: a parse tree, no symbol resolution", "<code>ast.parse</code>"),
      ("a value read from a literal's syntax", "<code>LiteralExpr.getValue()</code>", "<code>ast.literal_eval</code>: the same promise, evaluate nothing"),
      ("<code>class OutOfShape extends Error { readonly reason }</code>, assigned in the body", "a checked exception with a field", "an exception class with an attribute"),
      ("<code>as unknown as { parseDiagnostics?: unknown }</code>: a cast through <code>unknown</code>, then a runtime check", "reflection on a private field, then <code>instanceof</code>", "<code>getattr(node, \"_private\", None)</code>, then a type check"),
      ("<code>ts.forEachChild(node, function find(n) { ... return ts.forEachChild(n, find); })</code>: a named function expression to recurse", "a recursive <code>Visitor</code>", "<code>ast.walk</code> or a recursive helper")]),
  case("A quoted attribute containing <code>&amp;</code> means one thing in the parser and another in the page.",
       "<p>JSX string attributes have no backslash escapes but <em>do</em> decode HTML entities when compiled: <code>label=\"a &amp;amp; b\"</code> renders as <code>a &amp; b</code>, while TypeScript's parser hands back the raw text. A round trip through such a value would silently change the document. So a quoted attribute with <code>&amp;</code> is refused with the fix in the message (write it as <code>{\"...\"}</code>), and <code>generate</code> only ever writes expression attributes. Lesson 4 had the mirror-image bug: <code>-0</code> written as <code>0</code>.</p>"),
  case("A byte-exact comparison against a fresh generation was rejected as the shape test.",
       "<p>The tempting definition of \"in shape\" is \"equals what <code>generate</code> writes\". It would call every reformat, every reordered import and every comment a conflict, and engineers reformat. Shape is structural: one import, one exported component, a tree of elements with literal props. The tests say it in one line: <em>formatting is not shape</em>. What byte-equality is right for is Ship (section 8), where the file is <em>ours</em>.</p>"),
  note("<strong>Principal-level point:</strong> when a system has an encoder and a decoder, make one of them the judge. Here the decoder ends by calling the encoder, so \"parses\" implies \"generates\", and there is exactly one place a rule about pages lives. The alternative, two implementations kept in step by tests, is the design most codebases have and most codebases regret."))

section("webhook", "4 · A public route: the webhook",
  "<p><code>POST /webhooks/gitea</code> is the first route in this api with no user behind it. Gitea has nobody to send. So the route assumes a stranger wrote the request until the signature says otherwise, and reads <em>nothing</em> from the body before that.</p>",
  cut("apps/api/src/webhook.ts", "const HEX_SIGNATURE", "const Sha ="),
  "<p>The <em>raw</em> bytes are signed. A parse-and-reserialise (<code>JSON.stringify(JSON.parse(body))</code>) would verify something Gitea never sent: one byte of whitespace is another body. The regex first, then <code>timingSafeEqual</code>: same two lines as the proxy's token, same reasons. And note the argument order: <code>header: string | undefined</code>, because a missing header is a normal case, not an exception.</p>",
  cut("apps/api/src/app.ts", "  const smallBodies = bodyLimit", "  app.use((c, next) => (c.req.path === WEBHOOK_PATH ? webhookBodies : smallBodies)(c, next));", True),
  cut("apps/api/src/app.ts", "  // E5.3a: Gitea's push webhook, public", '  app.post("/orgs"'),
  "<p>Order of the checks, and why each is where it is. <strong>Body size before anything is read</strong>: a push payload lists commits, and a big push is over the api's 64 KB limit, so this route alone gets 1 MiB; the middleware picks the limit by path. <strong>No secret configured: 404</strong>, the route does not exist, and the reconcile alone notices pushes. <strong>Signature</strong>, from the raw <code>arrayBuffer</code>. <strong>Delivery id</strong>: required, printable, at most 100 characters, because it becomes a unique key. <strong>Event name</strong>: anything but <code>push</code> is ignored. Then, and only then, the body is parsed.</p>",
  cut("apps/api/src/webhook.ts", "const Sha = z.string()", "export type PushReading"),
  cut("apps/api/src/webhook.ts", "/** What a VERIFIED push body says"),
  "<p>Only <code>ref</code>, <code>before</code> and <code>after</code> are read. Gitea truncates the commit list for big pushes, so the file lists in the payload are not trusted for anything; the git peer reads its mirror instead. Two pushes are <em>ignored</em> rather than stored: a deleted branch (<code>after</code> all zeros), and the push Gitea fires the moment a hook is registered (<code>before</code> all zeros, learning-tests/gitea FINDINGS 2). A real new branch looks exactly like the registration push, so it is ignored too, and the reconcile finds it. The <code>BRANCH</code> regex with its three negative lookaheads (<code>(?!-)</code>, <code>(?!.*\\.\\.)</code>, <code>(?!.*//)</code>) narrows a ref name to what a person pushes, because the name becomes a row, a log line and, in section 6, a git argument.</p>",
  cut("apps/api/src/webhook.test.ts", 'test("anything that is not exactly 64 lowercase hex digits', 'test("a push to a branch is a commit event'),
  cut("apps/api/src/webhook.int.test.ts", 'test("the same delivery again', 'test("without the right signature'),
  cut("apps/api/src/webhook.int.test.ts", 'test("a body over 1 MiB', 'test("every other route'),
  vs([("<code>Buffer.from(await c.req.arrayBuffer())</code>: the bytes as sent", "<code>@RequestBody byte[]</code>, or a <code>ContentCachingRequestWrapper</code>", "<code>await request.body()</code> in FastAPI"),
      ("<code>bodyLimit</code> chosen per path by a middleware", "<code>spring.servlet.multipart.max-request-size</code> is global; a filter per path", "Starlette middleware; nginx <code>client_max_body_size</code> per location"),
      ("<code>PushReading</code>: a discriminated union with <code>kind</code>", "a sealed interface with three records", "a <code>Union</code> of dataclasses, matched with <code>match</code>"),
      ("<code>string | undefined</code> for a header that may be absent", "<code>Optional&lt;String&gt;</code>", "<code>str | None</code>"),
      ("202 recorded, 200 duplicate, 401 unauthenticated, 413 too large", "the same codes", "the same codes")]),
  case("The delivery id is not signed, so a captured body replayed under a fresh id would have been a new event.",
       "<p><code>X-Gitea-Delivery</code> is a header, and the HMAC covers only the body. Anyone who captured one delivery could replay the body with a made-up id and pass every check above. Dedupe on the delivery id alone is therefore not dedupe. The second unique key, <code>(ref, after_sha)</code>, is what makes the replay a <code>duplicate</code>, and it is also where the webhook and the reconcile meet (section 5). The test sends the same body under a fresh id and ten copies at once: Postgres decides, not a look-then-insert in the api.</p>"),
  case("A body that is not even JSON is a 401, not a 400.",
       "<p>Read the order again: the signature is checked before the body is parsed, so an unsigned non-JSON body is refused as <em>unauthenticated</em>. That is not an accident of ordering, it is the point: the api tells an anonymous caller nothing about what it does with a body, not even that it expects JSON. A signed body that is not a push is a 400, because whoever holds the secret is Gitea.</p>"),
  note("<strong>The rule for a public route:</strong> authenticate the bytes, then read them; bound the size before you do either; and never let a header you did not sign be the thing that makes two requests one."))

section("inbox", "5 · At least once, exactly once, and the second door",
  "<p>A webhook is at-least-once delivery at best, and Gitea's is worse: a failed delivery is <em>never retried</em> (SPEC §2a, measured in the learning test). So the api cannot be the only way a push is noticed, and a push noticed twice must be worked once. Both problems are solved in the same table.</p>",
  cut("packages/db/migrations/0009_git_events.sql", "-- E5.3a: the git peer's inbox."),
  "<p>Read it as a state machine and two keys. The status is <code>pending → running → done | failed</code>, and a <code>CHECK</code> ties <code>finished_at</code> to the terminal states, as lesson 3's jobs did. <code>delivery_id</code> is unique and nullable: the reconcile has none. <code>(ref, after_sha)</code> is unique and is <em>where the two doors meet</em>: whichever records a commit on a branch first wins, and the other finds it taken. The database decides. A \"look, then insert\" in the api would let two doors at the same instant both pass.</p>",
  cut("packages/db/src/index.ts", "    gitStore: () => ({", "      documentOrg: async"),
  "<p><code>on conflict do nothing</code> with <em>no target</em> means either unique key makes the insert a no-op, and <code>returning id</code> tells the caller which happened (<code>rowCount === 1</code>). <code>claim()</code> is lesson 3's pattern: one <code>UPDATE</code> with <code>for update skip locked</code>, so two peers never take one event and neither waits. And the reconcile flag is a <em>one-row table</em>: <code>id boolean primary key default true check (id)</code> can hold exactly one row, ever. Requests coalesce into it, and <code>requestReconcile</code> writes nothing when it is already set, so a burst of opens takes no row locks at all.</p>",
  cut("apps/worker/src/git.ts", "/**\n * The git peer's half of E5.3a", "/** A generated page a commit touched"),
  cut("apps/worker/src/git.ts", "/** What the reconcile records:", "export type GitPeer"),
  cut("apps/worker/src/git.ts", "  async function reconcile(): Promise<number>", "  /**\n   * The pages the commit touched"),
  "<p>The reconcile is the second door: fetch the mirror, list its branches, and record every branch whose commit is not the newest one recorded, a new branch from zeros. It runs on a 30 s timer and <em>when a document is opened</em>: <code>POST /documents/:id/session</code> sets the flag, and the peer takes it <strong>before</strong> fetching, so an open that arrives during a fetch sets it again and is not lost. A new branch, which the webhook cannot tell from the registration push, is caught this way, and the e2e tests lean on it: they open the document to ask for a reconcile now.</p>",
  cut("apps/worker/src/git.ts", "  async function processNext()", "  return {\n    reconcile,"),
  "<p>Each event is worked in its own <em>worktree</em> (<code>git worktree add --detach</code>), removed in <code>finally</code> by three steps that each tolerate the others' failure, and swept at start after a crash. A commit the mirror does not have is fetched; if the fetch fails, the event goes back to <code>pending</code> rather than <code>failed</code>, because the reconcile would never re-record it and a lost push is the one thing this design exists to prevent. Fetched and still missing means force-pushed away before we looked: nothing to apply, ever.</p>",
  cut("apps/worker/src/git.ts", "    async start({ pollMs, reconcileMs, onAlive })", "/** A page as the job's worktree holds it"),
  "<p>Two idioms in the tick. <code>running ??= tick().finally(() =&gt; (running = undefined))</code> is \"one tick at a time\" in one line: <code>??=</code> assigns only when the left side is nullish, so a beat that arrives while a tick runs does nothing, and the <code>finally</code> clears the slot. And <code>for (let n = 0; n &lt; EVENTS_PER_TICK &amp;&amp; (await processNext()); n += 1);</code> is a loop with an empty body: the work is in the condition, and it stops at the first \"nothing waiting\" or after twenty.</p>",
  cut("apps/worker/src/git.ts", "/** A page as the job's worktree holds it"),
  cut("apps/worker/src/git.int.test.ts", 'test("the webhook and the reconcile meet', 'test("a new branch, which the webhook ignores'),
  cut("apps/worker/src/git.int.test.ts", 'test("while Gitea is away an event waits', "// --- integration:worktree-cleaned"),
  vs([("two unique keys and <code>on conflict do nothing</code> as the dedupe", "the same SQL; Spring Integration's <code>IdempotentReceiver</code> if you must", "the same SQL"),
      ("<code>for update skip locked</code> to claim", "the same, as a native query", "the same"),
      ("a one-row table: <code>id boolean primary key default true check (id)</code>", "the same trick; or a singleton row by convention", "the same"),
      ("<code>running ??= tick().finally(...)</code>", "an <code>AtomicBoolean</code> guard, or a single-thread executor", "an <code>asyncio.Lock</code>, or a task you check <code>done()</code> on"),
      ("<code>open(path, O_RDONLY | O_NOFOLLOW)</code> from <code>node:fs/promises</code>", "<code>Files.newByteChannel(p, NOFOLLOW_LINKS)</code>", "<code>os.open(p, os.O_RDONLY | os.O_NOFOLLOW)</code>"),
      ("a worktree per job, removed in <code>finally</code>, swept at start", "a temp dir per job with a shutdown hook and a startup sweep", "the same")]),
  case("A pushed symlink named like a page could have read <code>/proc/self/environ</code>.",
       "<p>The git peer reads each changed page from the job's worktree. A commit can contain a symlink at <code>src/pages/noon-&lt;id&gt;.tsx</code> pointing anywhere: <code>/proc/self/environ</code> holds the peer's own environment, including the Gitea token. A plain <code>readFile</code> would follow it. The page is opened with <code>O_NOFOLLOW</code>, which fails with <code>ELOOP</code> on a symlink; <code>stat().isFile()</code> refuses a directory (a submodule checks out as one); and the size is checked against parse's cap before the read. The refusal has a name the banner shows: <code>not_a_file</code>.</p>"
       + cut("apps/worker/src/git.int.test.ts", 'test("a pushed symlink named like a page')),
  case("A force-push back to an old commit reads as \"known\", and the comment says so.",
       "<p>Keying on <code>(ref, after_sha)</code> means a branch moved <code>A → B → A</code> records nothing the second time it points at A: the row for <code>(ref, A)</code> exists. This is a ponytail with a named ceiling (such reverts go unseen) and a named upgrade (key on <code>(ref, before, after)</code>). The reason it is acceptable today is what the loop does with events: a page that is already what the document holds produces no ops, so a missed revert is a missed no-op until the next real push.</p>"),
  note("<strong>The distributed-systems shape, in one paragraph:</strong> a producer that may deliver zero or one times; a receiver that writes an idempotent row keyed on the <em>content</em>, not the delivery; a second source of truth (the mirror) polled on a timer and on demand, writing through the same key; a claim that is one atomic update; and a failure mode (\"the source is unreachable\") that returns the work to the queue rather than ending it. Every piece is in Postgres, and none of it is in application memory."))

section("push", "6 · A push becomes ops: git is a peer",
  "<p>Keystone 2 says every change to a document goes through the room. The git peer honours it literally: it joins the document through <code>@noon/peer-client</code> like a browser tab, with a session token whose actor is <code>git</code>, and submits ops. The room stamps every op with the actor and the commit as its run, and the room may refuse any op, one by one. A push that wrote to Postgres directly would be a second write path, and the whole of epic 2 (ordering, budgets, presence, the journal to come in epic 6) would not apply to it.</p>",
  cut("apps/worker/src/push.ts", "/**\n * E5.3b (F16a): a pushed generated page becomes ops", "export function createPushApplier"),
  cut("apps/worker/src/push.ts", "    const peer = connectPeer({", "/**\n * E5.4 (F16b): what the canvas's banner shows"),
  "<p>Read <code>current: peer.confirmed</code>. The base of the diff is what the room holds, never the optimistic tree and never a copy in Postgres that may be behind the room. And read <code>peer.close()</code> in <code>finally</code>: an op still unanswered is settled <code>connection_closed</code>, so nothing awaits for ever. The session's <code>sub</code> must be a uuid, so it is the event's id; the commit rides as <code>runId</code>. That is why the e2e test can assert, from the frames the canvas received, that the op came from <code>{ kind: \"git\", runId: &lt;the commit&gt; }</code>.</p>",
  "<p><strong>The diff is three-way.</strong> The engineer cloned the branch at some commit, edited the page, pushed. Meanwhile the canvas kept editing. Diffing the <em>pushed file</em> against the <em>document</em> would treat every canvas edit since the file was generated as something the engineer undid. So: base = the page at the commit before the push, target = the pushed page, and the ops are what changed between them, replayed on the document as it is <em>now</em>.</p>",
  cut("apps/worker/src/push-ops.ts", "/**\n * E5.3b: what a push means", "export type PushOps"),
  cut("apps/worker/src/push-ops.ts", "export function pushOps(", "  const working = structuredClone"),
  "<p>Before any op is made, two whole-page refusals. <code>root_mismatch</code>: the file's page is another document's. <code>reused_node_id</code>: keystone 4 says an id that was removed is never added again, or an edit meant for the dead node lands on the new one; \"removed\" is decided against <em>every id the page ever held in the repo's history</em> (<code>earlierIds</code>, from <code>git log -p</code>) and against the document now. <code>component_changed</code>: no op changes what a node <em>is</em>; a remove and an add would re-use its id.</p>",
  cut("apps/worker/src/push-ops.ts", "  const working = structuredClone(current);", "/** Every id from the root down"),
  "<p>Then the ops, in three passes over a <em>working copy</em> (<code>structuredClone</code>: a deep copy of plain data, built into modern JavaScript). Each op is tried on the copy with <code>applyOpInto</code>, the mutating applier from lesson 2, and only an op that changed the copy is kept: one whose node was removed on the canvas meanwhile, or whose value is already set, is dropped, which is the result the room would reach anyway. Adds first, parents before children, each placed after the previous sibling that is in place (<code>anchor</code>). Then props, in sorted key order, so the ops are the same on every run. Then removes, parents first, so a removed subtree is one op. Moves use the longest run of siblings still in their old order, which is a longest increasing subsequence in <code>O(n log n)</code> with a binary search written as <code>(lo + hi) &gt;&gt; 1</code>.</p>",
  cut("apps/worker/src/push-ops.ts", "/**\n * The siblings that need no move"),
  cut("apps/worker/src/git.ts", "  async function pageBase(commit", "  async function removeWorktree"),
  cut("apps/worker/src/push-ops.test.ts", 'test("the push replays what the ENGINEER changed', 'test("without a base the document is the base'),
  cut("apps/worker/src/push.int.test.ts", 'test("the push replays the engineer\'s change on the document as it is NOW', 'test("only the document\'s own branch speaks'),
  vs([("<code>structuredClone(doc)</code>: a deep copy of plain data", "no built-in; copy constructors, or Kryo", "<code>copy.deepcopy</code>"),
      ("<code>satisfies Op[]</code>: check a literal against a type without widening it", "no equivalent; the declared type IS the widening", "no equivalent"),
      ("<code>tails.at(-1)</code>; <code>(lo + hi) &gt;&gt; 1</code>", "<code>list.get(list.size() - 1)</code>; <code>&gt;&gt;&gt; 1</code> for the unsigned midpoint", "<code>tails[-1]</code>; <code>(lo + hi) // 2</code>; <code>bisect</code>"),
      ("<code>for (let id = stack.pop(); id !== undefined; id = stack.pop())</code>", "<code>while (!stack.isEmpty()) { var id = stack.pop(); }</code>", "<code>while stack: id = stack.pop()</code>"),
      ("the git peer as a WebSocket client of our own sync server", "the same: a service that is a client of another", "the same"),
      ("a JWT with <code>actor: { kind: \"git\", runId: commit }</code>", "a service account with claims", "the same")]),
  case("Diffing the pushed file against the document would have undone every canvas edit since the file was generated.",
       "<p>This is the rejected design, and the second drill plants it. The unit test builds the case: since the page was generated the canvas renamed A, added D and removed C; the engineer, from the old file, relabelled B, edited C and added G first. Two-way against the document sends: add G, <em>re-add C</em>, <em>rename A back</em>, relabel B, <em>remove D</em>. Three-way sends: add G, relabel B; C's edit is dropped because a remove beats a concurrent edit, the same rule the room applies to two browser tabs. The property test then runs three hundred random pages and random edits and checks the ops rebuild the pushed page exactly and that the same inputs give the same ops.</p>"),
  case("Ship's own pushes would come back as events and undo the canvas edits that raced them.",
       "<p>Named in E5.3b's commit as a hand-off, closed in E5.5. When Ship pushes the page it generated from the document, the webhook fires and the git peer sees a push on the document's branch. Diffed, that push says \"the label went from <em>Before</em> to <em>Shipped</em>\", which the room already holds; but a canvas edit made <em>while</em> Ship ran would be reverted by it. So Ship records its commit on its job <strong>before</strong> pushing, and the git peer asks <code>shippedCommit(sha)</code> before it reads or opens anything. The order is the whole fix: recorded after the push, the webhook could win the race.</p>"
       + cut("apps/worker/src/push.int.test.ts", 'test("a commit Ship made is skipped: a canvas edit')),
  case("Only the document's own branch speaks for it.",
       "<p>The same page on <code>main</code> and on <code>noon/&lt;id&gt;</code> would land twice, once per branch, and a feature branch of the engineer's would edit a document they were only experimenting on. So a page is applied only from <code>refs/heads/noon/&lt;its document&gt;</code>: the branch the sandbox works on and Ship pushes. Everything else is <code>skipped: other_branch</code>, and a skipped page says nothing about the document, so it neither sets nor clears a conflict (section 7).</p>"),
  note("<strong>The rule, in one line:</strong> when two parties edit the same thing from different starting points, diff each against <em>its own</em> starting point and replay onto the current state. That is what git itself does in a merge, what lesson 2's room does with two tabs, and what a push-becomes-ops has to do or it is a revert engine."))

section("conflict", "7 · A refusal that is visible: the conflict banner",
  "<p>Section 6 already refused an out-of-shape page whole: nothing sent, so the room's tree and its <code>seq</code> cannot move. E5.4 makes the refusal visible without changing that. The git peer records it; the canvas reads it every two seconds and shows a <code>role=\"alert\"</code> above the editor: commit, file, and why. Editing is not blocked. The e2e proves \"nothing moved\" by hashing the room's tree as a fresh joiner is welcomed with it, before and after the push.</p>",
  cut("packages/db/migrations/0010_document_conflicts.sql", "-- E5.4 (F16b)"),
  cut("packages/db/src/index.ts", "      async recordConflict(documentId, input)", "      async clearConflict"),
  "<p>One row per document, by primary key. <code>insert ... select ... from documents where id = $1</code> inserts nothing for a document deleted meanwhile, instead of failing on the foreign key. <code>on conflict (document_id) do update set ... = excluded.*</code> is Postgres's upsert: <code>excluded</code> is the row that <em>would</em> have been inserted. A later refused push replaces the conflict; a later applied one deletes it; a skipped one changes nothing.</p>",
  cut("packages/db/src/index.ts", "// `detail` is parse's words about a file an engineer wrote", "const GitEventRow"),
  "<p><code>detail</code> is capped by a Zod <code>.transform</code>, not refused: parse's words about an engineer's file may be long, and a conflict must always be shown. That is a trust-boundary decision made in the right direction: what is validated (the reason, the sha, the file length) is what a stranger could exploit; what is only trimmed is what would merely be inconvenient.</p>",
  cut("packages/contracts/src/index.ts", "// --- Conflicts (F16b)", "// --- Ship (F17)"),
  "<p><strong>One vocabulary, checked by the compiler.</strong> <code>ConflictReason</code> is one Zod enum listing codegen's reasons, parse's, push-ops' and the git peer's own. <code>PushOutcome</code>'s reason is typed with it, so a reason added in the worker without a contract entry stops compiling. And the canvas's sentences are a <code>Record&lt;ConflictReason, string&gt;</code>, so a reason added to the contract without a sentence stops compiling in turn. Two compile errors are how a new refusal announces itself to two teams.</p>",
  cut("apps/web/src/conflict.ts", "/**\n * Why a pushed file was not applied", "  unknown_prop:"),
  cut("apps/web/src/conflict.ts", "/** What the banner says"),
  cut("apps/web/src/ConflictBanner.tsx", "export function ConflictBanner"),
  "<p>Commit and file come from an engineer's push. The banner renders them inside <code>{...}</code> in JSX, which React turns into <em>text nodes</em>, never markup; the web test's fixture has a file named <code>&lt;img src=x onerror=alert(1)&gt;.tsx</code> to make the point. The polling is a <code>setTimeout</code> chain with a <code>stopped</code> flag, not <code>setInterval</code>: a slow answer never overlaps the next ask, and the cleanup function React calls on unmount stops the chain. A 404 stops it for good: the canvas says so itself when the document goes.</p>",
  cut("apps/worker/src/push.ts", "/**\n * E5.4 (F16b): what the canvas's banner shows"),
  cut("apps/api/src/conflict.int.test.ts", 'test("a refused push is the document\'s conflict', 'test("a reason outside the contract'),
  cut("e2e/conflict.spec.ts", "/** JSON with every object's keys sorted", 'test("a push that breaks'),
  vs([("<code>Record&lt;ConflictReason, string&gt;</code>: the compiler demands every key", "an <code>EnumMap</code> does not; an exhaustive <code>switch</code> over a sealed type does", "<code>dict[Literal[...], str]</code> is not checked for completeness; <code>assert_never</code> in a match is"),
      ("<code>z.string().transform((d) =&gt; d.slice(0, 300))</code>: trim, do not refuse", "a <code>@Size</code> would refuse; a setter that truncates", "a validator that returns the trimmed value"),
      ("<code>on conflict (document_id) do update set x = excluded.x</code>", "the same SQL; <code>MERGE</code> in newer engines", "the same SQL"),
      ("<code>{words.commit}</code> in JSX: a text node", "Thymeleaf's <code>th:text</code> escapes; <code>th:utext</code> does not", "Jinja2 autoescape on"),
      ("a <code>setTimeout</code> chain with a <code>stopped</code> flag in a <code>useEffect</code> cleanup", "a <code>ScheduledExecutorService</code> you shut down", "an <code>asyncio.Task</code> you cancel")]),
  case("A message over the room, and a column on <code>git_events</code>, were both rejected as the place for a conflict.",
       "<p>A room message would be a new wire type and new room state for something that is not an op, and lesson 2's room has exactly one kind of thing in its log. A column on <code>git_events</code> fails on cardinality: one event can touch several documents, and the canvas asks per document. So a table keyed by document, and a plain HTTP <code>GET</code> polled like the preview. Ponytails named: only the newest conflict is kept (upgrade: a row per event); polling (upgrade: SSE).</p>"),
  note("<strong>Accessibility is not optional here:</strong> <code>role=\"alert\"</code> makes a screen reader announce the banner when it appears, and the ship panel below uses <code>aria-live=\"polite\"</code> for progress because the page already has one <code>role=\"status\"</code> (the connection). The security review's list of things never to simplify away ends with accessibility for a reason."))

section("ship", "8 · Ship: idempotent by index, safe by a push that is never forced",
  "<p>Ship is F17: press it, and the document's page is a commit on its branch in Gitea with an open pull request into <code>main</code>; press it again, and the same pull request shows the new page. It is a job on a queue of its own, drained by its own process, because it holds the one credential that may <em>push</em>: no model and no Docker socket beside it.</p>",
  cut("apps/worker/src/main.ts", "// E5.5 (F17): Ship. Its own process", "// A worker has no port to probe"),
  cut("packages/db/migrations/0011_ship_jobs.sql", "-- E5.5 (F17)"),
  "<p><strong>Idempotence lives in Postgres.</strong> The <em>queued</em> ship is unique per document, so twenty presses at once make one job. Read why it is not \"one unfinished ship\": a press while one <em>runs</em> must queue the next, because the running one has already read the document and a press after an edit must ship that edit. Two ships running for one document are safe (below), so only the waiting one needs to be unique.</p>",
  cut("packages/db/src/index.ts", "        startShip: async ({ documentId, createdBy, idempotencyKey }) => {", "        async getShip(documentId)"),
  "<p>Lesson 3's lesson, applied again: the insert with <code>on conflict do nothing</code>, then a <em>second statement</em> to read the newest ship, because a CTE would share the write's snapshot and not see the winner's row. The api answers 201 when this press made the job and 200 when it joined one, and the canvas's panel polls while it runs and links the pull request (http(s) only, parsed with the contract before it goes near an <code>href</code>).</p>",
  cut("apps/worker/src/ship.ts", "/**\n * The `ship` queue's handler (F17", "/** A push refused because the branch moved"),
  cut("apps/worker/src/ship.ts", '  try {\n    await git(["init", "--quiet", "--bare"]);', "  } finally {\n    await rm(repo"),
  "<p>This is git <em>plumbing</em>: a commit built from objects, with no working tree and nothing of the customer's repository ever run. <code>init --bare</code>, a temporary index (<code>GIT_INDEX_FILE</code>), <code>read-tree</code> the parent's tree into it, <code>hash-object -w --stdin</code> to store the page as a blob, <code>update-index --cacheinfo</code> to put that blob at the page's path, <code>write-tree</code>, and <code>commit-tree</code> with the parent. If the new tree equals the parent's tree, the branch already holds the page: no commit, and <code>null</code> is the answer. The parent is the branch itself, or <code>main</code> for a first ship, so an engineer's commits and an out-of-shape page stay <em>under</em> the new commit, never overwritten.</p>",
  "<p><strong>The push is never forced.</strong> A branch that moved since the fetch refuses a push that is not on top of it (git's own fast-forward rule), and the loser builds again on the winner: three attempts, then <code>branch_busy</code> as a named failure. And <code>recordCommit</code> is called <em>before</em> the push (section 6's case study): by the time the webhook sees Ship's push, the row already says the commit is Ship's.</p>",
  cut("apps/worker/src/ship.ts", "/**\n * Per document, the pull request call in flight", "/** The branch's open pull request into main"),
  cut("apps/worker/src/ship.ts", '  const opened = await call("POST", "/pulls"', "export function createShipHandler"),
  "<p>Gitea's \"one open pull request per branch\" is a look-then-insert on <em>its</em> side, so two creates in the same instant could both pass it; the ships of one document ask one at a time in this process (the same promise-chain mutex as section 1's mirrors), with the ceiling named (a second ship worker) and the upgrade (an advisory lock). A 409 means the branch has its pull request, which is found by <code>head.ref</code> across pages of the listing. And the fetch that carries the token has <code>redirect: \"error\"</code>: a token for Gitea never follows a redirect to anywhere else.</p>",
  cut("apps/worker/src/ship.ts", "    try {\n      return await fetchImpl(", "  const opened = await call"),
  cut("apps/worker/src/ship.ts", "  return async (job, cancelled) => {"),
  cut("apps/web/src/ShipPanel.tsx", "const sentence = (ship: Ship)", "/**\n * F17: Ship turns the document"),
  cut("apps/worker/src/ship.int.test.ts", 'test("Ship once, Ship again: ONE open pull request', 'test("two ships at once'),
  cut("apps/api/src/ship.int.test.ts", 'test("twenty presses at once', 'test("a ship\'s output is checked'),
  vs([("<code>git hash-object</code>, <code>update-index --cacheinfo</code>, <code>write-tree</code>, <code>commit-tree</code>", "JGit: <code>ObjectInserter</code>, <code>DirCache</code>, <code>CommitBuilder</code>", "dulwich: <code>Blob</code>, <code>Tree</code>, <code>Commit</code> objects"),
      ("<code>AbortSignal.any([cancelled, stopping, AbortSignal.timeout(ms)])</code>", "a <code>CompletableFuture</code> composed with <code>orTimeout</code> and a cancel flag", "<code>asyncio.wait_for</code> plus a cancellation scope"),
      ("<code>fetch(url, { redirect: \"error\" })</code>", "<code>HttpClient.Redirect.NEVER</code>", "<code>requests.get(allow_redirects=False)</code> and check"),
      ("<code>z.url({ protocol: /^https?$/u })</code> before an <code>href</code>", "<code>URI.create</code> then a scheme check", "<code>urllib.parse</code> then a scheme check"),
      ("a partial unique index on <code>status = 'queued'</code>", "the same SQL; JPA cannot express it", "the same; Django <code>UniqueConstraint(condition=...)</code>")]),
  case("\"One unfinished ship per document\" would have folded a press during a run into a ship that had already read the older document.",
       "<p>The obvious index, mirroring the sandbox job's, is wrong here because of <em>when the document is read</em>. A sandbox job follows the document for as long as it runs; a ship reads it once, at the start. So the second press during a run must become a second job, and only the waiting one is unique. The test presses twenty times at once (one job), then presses while one runs (a second job), and the canvas reads the newest.</p>"),
  case("Two ships at once: neither loses, and there is still one pull request.",
       "<p>Both build a commit on the branch as they fetched it. One push wins; the other is refused as not a fast-forward and builds again on top, and the branch ends holding the page. Both then ask for a pull request; the second gets a 409 and finds the first's by <code>head.ref</code>. Note what makes this safe without a lock: git's own refusal rule and Gitea's own uniqueness, both on <em>their</em> side, and code that treats each refusal as a normal answer with a name.</p>"),
  case("Ship ships <em>on top of</em> an engineer's out-of-shape page, never over it.",
       "<p>The conflict banner is up: an engineer pushed a page with a hook in it. Ship's commit has that commit as its parent, and its tree is the parent's tree with the one file replaced; the branch is back in shape and the engineer's history is intact. The e2e (<code>e2e/ship.spec.ts</code>) does exactly this with the banner up, twice, and checks the page in Gitea against a fresh generation of the final document, byte for byte. Byte equality is right here because the file is <em>ours</em>: that is the other half of section 3's argument.</p>"),
  note("<strong>Principal-level point:</strong> idempotence is a property of a <em>key</em>, and the key must be chosen from what the operation reads and when. Ship reads at start, so the key is \"a ship that has not started yet\". A preview reads continuously, so its key is \"a preview that has not ended\". Same table, same <code>on conflict do nothing</code>, different predicate, for a reason you can state."))

section("testing", "9 · Testing a loop that spans four processes and a git server",
  "<p>The loop crosses the canvas, the api, Postgres, the sync server, two worker processes, Docker and Gitea. The tests get three things right that no unit could.</p>"
  "<p><strong>Git fetches a path as it fetches a URL, so a local bare repository stands in for Gitea.</strong> The git peer's and Ship's integration tests run against <code>localOrigin()</code>: a bare repo and a clone in a temp directory, where \"an engineer\" commits and pushes. No Gitea, no network, and the code under test is the real <code>createGitPeer</code>, the real <code>pushOps</code>, the real <code>shipPage</code>. Two suites do need the dev stack's Gitea (<code>gitea.int.test.ts</code> for the bootstrap, <code>ship.int.test.ts</code> for pull requests) and say so in their names.</p>",
  cut("apps/worker/src/git-testing.ts", "// Shared by the integration tests of the git peer and Ship", "export type LocalOrigin"),
  "<p><strong>The e2e layer runs the real workers from source and stops the compose ones.</strong> Playwright starts a sandbox worker, a git peer and a ship worker as its own servers, each printing a line when ready; and because they share Postgres and Redis with the dev stack, the compose workers would take e2e's jobs, so <code>setup.ts</code> stops all four for the duration and <code>teardown.ts</code> starts them again.</p>",
  cut("e2e/setup.ts", "// The e2e layer shares Postgres and Redis with the dev stack", "/** @public Playwright loads"),
  cut("playwright.config.ts", "    // The REAL git peer (E5.3b)", "    { command: `PUBLIC_HOST=localhost"),
  "<p><strong>Prove \"nothing changed\" with a hash, and \"as git\" with the frames.</strong> The conflict e2e asks the room for its document as a fresh joiner is welcomed with it, hashes it as canonical JSON (keys sorted: key order is not part of a page), and compares before and after the push, <code>seq</code> included. The push e2e records every WebSocket frame the canvas receives and asserts the op arrived stamped <code>actor.kind = \"git\"</code> with the commit as <code>runId</code>; and it plants a value on <code>window</code> before the push and reads it after, because a reload would lose it.</p>",
  cut("e2e/gitea.ts", "// Both sides of an F16 test", "const git = async"),
  cut("e2e/push.spec.ts", 'test("a push that edits the page\'s generated file'),
  cut("e2e/ship.spec.ts", "    // An edit, and Ship again", "  } finally {"),
  vs([("a bare repo in <code>tmpdir()</code> as the remote", "JGit's in-memory repository; or the same bare repo", "the same"),
      ("Playwright <code>webServer</code> entries with a <code>wait: { stdout }</code>", "Testcontainers' <code>LogMessageWaitStrategy</code>", "<code>wait_for_logs</code>"),
      ("<code>page.on(\"websocket\", ...)</code> to read the frames the canvas received", "no equivalent in Selenium; a proxy", "Playwright for Python: the same API"),
      ("a value planted on <code>window</code> to prove there was no reload", "the same trick in any browser driver", "the same"),
      ("canonical JSON (sorted keys) hashed with sha256", "Jackson's <code>ORDER_MAP_ENTRIES_BY_KEYS</code>, then a digest", "<code>json.dumps(sort_keys=True)</code>, then <code>hashlib</code>")]),
  case("Two integration files held the same forty lines, and the duplicate detector said so.",
       "<p><code>make check</code> runs <code>jscpd</code>. E5.3b's push tests and E5.3a's git peer tests each grew a local-origin helper, and the gate refused the copy. The helper moved to <code>git-testing.ts</code>, and in the same pass the room-joining and wait-for-live code shared by the preview, the push applier and Ship moved to <code>live.ts</code>. A duplicate detector in the gate is how a codebase written bead by bead, by different sessions, stays one codebase.</p>"),
  note("<strong>Honest status, repeated here because it matters:</strong> every integration and e2e test named in this chapter is written, reviewed and committed, and none has been run yet. The unit tests (parse, webhook, push-ops, ship's pure helpers, the git peer's parsers, the conflict sentences) run green in the gate on every commit. The section below is what running the rest looks like."))

section("demo", "10 · The full loop, by hand: what to run once the stack is verified",
  "<p>The loop has not been demonstrated end to end yet: the dev stack on the machine that built this chapter predates E5.1 (no Gitea, no <code>worker-git</code>, no <code>worker-ship</code> in <code>docker compose ps</code>), and the host was too loaded to run Docker suites alongside other work. These are the exact commands, in order, and what each one should show. Where a command needs the token, it is read from <code>.env</code> into the shell and never printed.</p>",
  shell("0 · Bring the stack up and watch the two new workers",
        "./init.sh                                    # Postgres, Redis, Gitea (127.0.0.1:3002), api, sync, worker, worker-sandbox, worker-git, worker-ship\n"
        "                                             # the seed pushed as ONE commit; the push webhook registered; PASS: ... seed in Gitea, hook installed\n"
        "docker compose ps                            # gitea, worker-git and worker-ship are listed and healthy\n"
        "docker compose logs -f worker-git worker-ship\n"
        "                                             # git peer watching http://gitea:3000/noon/sample-app.git (token present)\n"
        "                                             # worker draining queues: ship (to http://gitea:3000/noon/sample-app.git, token present)"),
  shell("1 · Ship → pull request",
        "open http://localhost:5173/?user=you@example.com     # New document, Add Button; note ?doc=&lt;id&gt; in the address bar\n"
        "# Press Ship. Within seconds the panel says \"Shipped. The pull request has the page as it is now.\" and links \"Pull request #1\".\n"
        "GITEA_TOKEN=$(grep '^GITEA_TOKEN=' .env | cut -d= -f2-)  # into this shell only; never echo it\n"
        "curl -s -H \"Authorization: token $GITEA_TOKEN\" 'http://localhost:3002/api/v1/repos/noon/sample-app/pulls?state=open' \\\n"
        "  | jq '.[] | {number, branch: .head.ref}'          # exactly one, whose branch is noon/&lt;id&gt;\n"
        "curl -s -H \"Authorization: token $GITEA_TOKEN\" \"http://localhost:3002/api/v1/repos/noon/sample-app/raw/src/pages/noon-&lt;id&gt;.tsx?ref=noon%2F&lt;id&gt;\"\n"
        "                                                   # the page: one import, export function Page, label={\"Button\"}"),
  shell("2 · Push → canvas, as an engineer",
        "AUTH=\"http.extraHeader=Authorization: Basic $(printf 'noon:%s' \"$GITEA_TOKEN\" | base64)\"   # the token as a header, never in the URL\n"
        "git -c \"$AUTH\" clone http://localhost:3002/noon/sample-app.git /tmp/sample-app && cd /tmp/sample-app\n"
        "git checkout noon/&lt;id&gt;\n"
        "sed -i '' 's/label={\"Button\"}/label={\"From git\"}/' src/pages/noon-&lt;id&gt;.tsx\n"
        "git commit -am 'relabel the button' && git -c \"$AUTH\" push origin HEAD\n"
        "# Back in the canvas, within about two seconds and without a reload: the button reads \"From git\".\n"
        "# Both doors, in Postgres: the webhook's row has a delivery id; a row the reconcile found does not.\n"
        "docker compose exec -T postgres psql -U noon -d noon -c \\\n"
        "  \"select ref, left(after_sha, 8) as commit, status, delivery_id is not null as via_webhook from git_events order by created_at\""),
  shell("3 · Break the shape → banner, nothing else",
        "# In the same clone: add a hook as the first line of Page(), then push.\n"
        "sed -i '' 's/^export function Page() {$/export function Page() {\\\n  const [count] = useState(0);/' src/pages/noon-&lt;id&gt;.tsx\n"
        "git commit -am 'count clicks' && git -c \"$AUTH\" push origin HEAD\n"
        "# The canvas shows the banner: \"A push to this page was not applied.\" with the commit, the file and \"It uses a React hook.\"\n"
        "# The button still reads \"From git\"; adding a Button still works, with the banner up.\n"
        "curl -s -H 'x-dev-user: you@example.com' http://localhost:3000/documents/&lt;id&gt;/conflict | jq   # commit, file, reason: hook"),
  shell("4 · Ship again → the same pull request, back in shape",
        "# Press Ship. The same \"Pull request #1\" gains a commit whose parent is the engineer's; the page is in shape again.\n"
        "curl -s -H \"Authorization: token $GITEA_TOKEN\" 'http://localhost:3002/api/v1/repos/noon/sample-app/pulls?state=open' | jq 'length'   # 1\n"
        "docker compose logs worker-git | grep skipped     # Ship's own push: {\"kind\":\"skipped\",\"why\":\"shipped\"}; the canvas is untouched by it"),
  shell("5 · Then the suites that prove it without hands",
        "pnpm exec vitest run --config vitest.integration.config.ts apps/api/src/webhook.int.test.ts apps/worker/src/git.int.test.ts apps/worker/src/push.int.test.ts\n"
        "                                             # local bare repos stand in for Gitea; Postgres and the sync server are real\n"
        "pnpm exec vitest run --config vitest.integration.config.ts apps/worker/src/gitea.int.test.ts apps/worker/src/ship.int.test.ts\n"
        "                                             # the dev stack's Gitea: the bootstrap, and ship-once-twice-same-pr-byte-identical\n"
        "pnpm exec playwright test e2e/push.spec.ts e2e/conflict.spec.ts e2e/ship.spec.ts\n"
        "                                             # the real canvas; stops the compose workers for the duration (see e2e/setup.ts)\n"
        "make check                                   # the whole gate, as the pre-commit hook runs it"),
  note("<strong>What to do when a step does not match this page:</strong> the page was cut from the code at commit <code>" + commit + "</code>, and the code is right until a test says otherwise. Read the log line, find the section above that owns that line, and file the difference against the bead that owns the code. A chapter that disagrees with a running system is a bug report, whichever of them is wrong."))

section("limits", "11 · What the type system could not see, epic 5 edition",
  "<p>Everything below compiled under <code>strict</code>, passed the linter and the first tests, or was rejected at design time by asking what the types could not ask.</p>",
  vs([("a sandbox on an internal network could not clone", "Docker publishes no port for an internal-only container (measured)", "the worker fetches; a bundle by <code>docker exec</code>"),
      ("ICC-off on one shared network cut the proxy off too", "measured, not read", "one network per document, the proxy joined to each"),
      ("a document id alone opened any preview through the public URL", "the URL was the only lock", "a per-container token: nonce + HMAC, checked twice"),
      ("Vite's 404 named the base", "read in Vite's source, measured on a local run", "a <code>pre</code> plugin answers a bare 404 first"),
      ("a blank frame through the tunnel", "Vite answers preflights before its proxy; origin \"null\" refused", "<code>preflightContinue</code> for <code>/preview/</code> only"),
      ("401s on the preview's modules", "the tunnel's basic auth; the frame carries no credentials", "fixed in the tunnel; know which hop answered"),
      ("a quoted attribute with <code>&amp;</code> would round-trip to another value", "JSX decodes entities; the parser does not", "refuse, and say how to write it"),
      ("deep nesting overflowed TypeScript's parser", "its walk recurses; ours does not", "<code>RangeError</code> is <code>too_deep</code>"),
      ("<code>parseDiagnostics</code> is internal to TypeScript", "the public route is a whole Program", "cast through <code>unknown</code>; fail closed if it is gone"),
      ("a replayed body under a fresh delivery id was a new event", "the header is not signed", "a second unique key on (branch, commit)"),
      ("a push during a reconcile fetch could be lost", "the flag was taken after the fetch", "take the flag first"),
      ("an event failed when Gitea was away", "\"failed\" is terminal and the reconcile never re-records", "back to <code>pending</code>"),
      ("a symlink named like a page read the worker's environment", "<code>readFile</code> follows links", "<code>O_NOFOLLOW</code>, <code>isFile()</code>, size first"),
      ("a two-way diff reverted every canvas edit since the file was generated", "the wrong base", "three-way: base, target, current"),
      ("a removed id came back as a new node", "an id is a name, not a value", "<code>earlierIds</code> from <code>git log -p</code>; refuse whole"),
      ("Ship's push came back as an engineer's edit and undid a racing canvas edit", "the webhook cannot tell who pushed", "record the commit BEFORE the push; skip it"),
      ("a force-push A → B → A reads as known", "keyed on (branch, commit)", "named ponytail; key on before as well"),
      ("two ships in one instant could both create a pull request", "Gitea's uniqueness is a look-then-insert", "one at a time per document; 409 → find by <code>head.ref</code>"),
      ("a press during a run folded into a ship that read the older document", "\"unfinished\" was the wrong predicate", "unique on <code>status = 'queued'</code>"),
      ("a CTE would not see the winner's row", "one snapshot per statement", "a second statement, again"),
      ("a token could follow a redirect off Gitea", "fetch follows redirects by default", "<code>redirect: \"error\"</code>"),
      ("forty duplicated lines across two suites", "written bead by bead", "<code>jscpd</code> in the gate; <code>git-testing.ts</code>, <code>live.ts</code>"),
      ("the per-org cap could overshoot", "a count is not an index (lesson 4)", "an advisory lock per org: the named upgrade, taken")], head=("What went wrong, or would have", "Why", "Fix")),
  note("<strong>The pattern, extended once more:</strong> lessons 2 to 4 said types prove shapes and say nothing about order, time, repetition, memory, who is speaking, what a subprocess does, or a browser boundary. Epic 5 adds: types cannot see <em>which delivery is the same event</em>, <em>which starting point a diff should use</em>, or <em>which side of a network a container is on</em>. Every one was answered the same way as before: a key chosen from what the operation reads, a measurement of the real thing, and a name for the failure."))

toc = "".join(f'<li><a href="#{sid}">{title}</a></li>' for sid, title, _ in S)
sections = "".join(f'<section id="{sid}"><h2>{title}</h2>{body}</section>' for sid, title, body in S)
style = re.search(r"<style>.*?</style>", (root / "docs/handbook/lesson-0.template.html").read_text(), re.S).group(0)
page = (pathlib.Path(__file__).parent / "lesson-5.template.html").read_text()
page = page.replace("{{STYLE}}", style).replace("{{TOC}}", toc).replace("{{SECTIONS}}", sections).replace("{{COMMIT}}", commit)
(out / "lesson-5.html").write_text(page)
print("built", len(page), "bytes at", commit, "with", page.count('<p class="label">From'), "code blocks")
