"""Builds docs/handbook/lesson-8.html. Every code block is cut from the real repo by anchor text,
so the page cannot show code that does not exist; a missing anchor fails the build."""
import html, os, pathlib, re, subprocess
here = pathlib.Path(__file__).resolve()
root = pathlib.Path(os.environ.get("NOON_ROOT") or (here.parents[2] if (here.parents[2] / "SPEC.md").exists() else pathlib.Path.cwd()))
out = pathlib.Path(os.environ.get("NOON_OUT") or root / "docs/handbook")
commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True).stdout.strip()

def cut(path, start, end=None, include_end=False):
    src = (root / path).read_text()
    i = src.index(start)
    j = len(src) if end is None else src.index(end, i + len(start)) + (len(end) if include_end else 0)
    body = src[i:j].rstrip()
    return (f'<p class="label">From <span class="mono">{path}</span></p>'
            f'<div class="scroll"><pre><code>{html.escape(body)}</code></pre></div>')

def shell(title, body):
    return f'<p class="label">{title}</p><div class="scroll"><pre class="out"><code>{body}</code></pre></div>'

def vs(rows, head=("TypeScript (this repo)", "Java", "Python")):
    body = "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows)
    return f'<div class="scroll"><table><tr>{"".join(f"<th>{h}</th>" for h in head)}</tr>{body}</table></div>'

def case(title, body): return f'<div class="break"><p class="label">Case study · found by review, by a learning test, or by a test that was written to refute a claim</p><p><strong>{title}</strong></p>{body}</div>'
def note(body): return f'<p class="note">{body}</p>'
m = lambda s: f"<span class='mono'>{s}</span>"

S = []
def section(sid, title, *parts): S.append((sid, title, "".join(parts)))

section("map", "The map: what identity, roles and a trail mean here",
  "<p>Epic 1 built the tenancy: every org route sits behind one membership query, a stranger and a missing org are the same 404 (F2), and the caller was whoever an <code>x-dev-user</code> header said. Epic 8 makes the caller real and asks the three questions that follow from it. <strong>Who are you</strong> (F23): a password that is hashed slowly and compared in constant time, a session that is a row in Postgres and a cookie the page's script cannot read, and a dev header that outside development opens nothing. <strong>What may you do</strong> (F24, F25): a role read from the very row that proved membership, checked by every route and by the room for every op, and a share that opens one document to someone outside the org, with a revocation that closes their socket within ten seconds and refuses every way back, including a token signed before the revoke. <strong>Who did what</strong> (F26): an audit row written inside the action's own statement, in a table the app's database role cannot update or delete and a trigger refuses to everyone else.</p>",
  vs([("1", m("apps/api/src/password.ts"), m("packages/db/migrations/0015_sign_in.sql"), "scrypt with its parameters in the stored string; a dummy hash so an unknown email costs a hash too; an opaque 32-byte token kept only as its SHA-256"),
      ("2", m("apps/api/src/identity.ts"), m("apps/api/src/app.ts"), "the session cookie (HttpOnly, Secure, SameSite=Strict); <code>chooseIdentity</code>: only the literal <code>development</code> keeps the header, behind a session; the worker's peers mint their own tokens with the service credential"),
      ("3", m("apps/api/src/app.ts"), m("packages/db/src/index.ts"), "<code>need(role)</code> on every org and document route, and a test that reads the router and fails for a route without one; the role from the membership row; <code>setMember</code> under an advisory lock; shares as a table of their own and the higher of the two roles"),
      ("4", m("apps/sync/src/server.ts"), m("packages/lease/src/access.ts"), "the role read before the upgrade, at the join, and again on every announcement and every 30 s; <code>mayEdit</code> checked when an op's turn comes; Redis pub/sub as a hint that says who changed, never what to"),
      ("5", m("packages/db/migrations/0017_audit_log.sql"), m("packages/db/src/index.ts"), "<code>audit_log</code> with no foreign keys; every audited action writes its row in a CTE of the same statement or in the same transaction; <code>provisionAppRole</code> revokes UPDATE, DELETE and TRUNCATE on every deploy; a trigger refuses the owner too"),
      ("6", m("apps/web/src/audit.ts"), m("apps/web/src/AuditView.tsx"), "a <code>Record</code> over the whole action enum, so a new action does not compile without its sentence; everything an entry says rendered as text")], head=("Step", "Where", "And", "What happens")),
  "<p>Four ideas carry the epic, and they are what an interviewer will press on. <strong>Authentication is a fixed-cost function of its input</strong> (section 1): whoever you claim to be, sign-in does one slow hash and answers the same bytes, because anything that varies with whether the account exists (time, status, body) is a list of accounts for whoever asks. <strong>A session is a row, not a claim</strong> (section 2): a credential you can revoke is a row you can delete; a signed stateless token cannot be revoked without a deny list, which is a table anyway, so the browser gets a row and only the 60-second sync token stays a JWT. <strong>Authorization lives where the data is fetched</strong> (sections 3 and 4): the query that proves membership returns the role, the route declares what it needs, and the room re-reads the role where the socket lives, because a socket outlives every token. <strong>An audit trail is evidence only if its writer cannot rewrite it</strong> (section 5): the row is written by the action's own statement, and the database, not the application's manners, refuses every change.</p>",
  vs([("scrypt from <code>node:crypto</code>, the parameters in the stored string", "Spring Security's <code>DelegatingPasswordEncoder</code> (<code>{bcrypt}</code>, <code>{argon2}</code>, <code>{scrypt}</code> prefixes: the same self-describing idea)", "Django's <code>algorithm$iterations$salt$hash</code> (PBKDF2 by default, argon2 optional): the same idea again"),
      ("a session row and an HttpOnly cookie; sign-out is a <code>DELETE</code>", "<code>HttpSession</code> with Spring Session JDBC; <code>SessionRegistry.expireNow()</code>", "<code>django_session</code>: an opaque key, a row, an HttpOnly cookie; <code>Session.objects.filter(...).delete()</code>"),
      ("<code>need(role)</code> per route plus a test over the router", "<code>@PreAuthorize(\"hasRole('OWNER')\")</code> and a <code>RoleHierarchy</code>; <code>authorizeHttpRequests(...anyRequest().denyAll())</code>", "<code>@permission_required</code>, <code>PermissionRequiredMixin</code>; django-guardian for per-object roles"),
      ("the role re-read in the room on a Redis hint", "Spring's WebSocket security checks the handshake only; a role change reaches an open socket by hand", "Channels' <code>AuthMiddlewareStack</code> checks at connect; the same gap"),
      ("audit rows in the action's statement, grants revoked, a trigger", "Hibernate Envers writes <code>_AUD</code> tables in the same transaction, but the app role may still <code>UPDATE</code> them", "django-simple-history, django-auditlog: histories, not fenced trails, unless the role is")], head=("This repo", "Java world", "Python world")))

section("passwords", "1 · Passwords: a slow hash that describes itself, and a sign-in that costs the same for everyone",
  "<p>A password is a low-entropy secret: people choose them, and an attacker who steals the table will guess them offline at whatever speed the hash allows. So the hash must be <em>slow</em>, and, since a GPU has thousands of cores that are each slow, it must also be <em>memory-hard</em>, so that every parallel guess pays in RAM as well as time. SHA-256 is neither: it is designed to be fast. bcrypt is slow but uses 4 KiB; scrypt and argon2 are both. scrypt was chosen because it ships with Node (<code>node:crypto</code>), and argon2id, OWASP's first choice, would be the pick when a native dependency is acceptable.</p>",
  cut("apps/api/src/password.ts", "/**\n * E8.1 (F23): passwords and sign-in tokens", "export async function hashPassword"),
  "<p>Read the numbers. scrypt's memory is <code>128 · N · r</code> bytes: with <code>N = 2^15</code> and <code>r = 8</code> that is 32 MiB per guess, and some tens of milliseconds on a laptop core. Node's default <code>maxmem</code> is exactly 32 MiB and the derivation would throw at the boundary, so the options pass <code>256 · N · r</code>: room for the parameters to rise. The stored string names <code>N</code>, <code>r</code> and <code>p</code>, which is what lets the cost go up next year without a migration: an old hash still verifies with the parameters it names, and the row is rewritten at the person's next sign-in if anyone wants that. Django and Spring's <code>DelegatingPasswordEncoder</code> store their hashes the same way, for the same reason. <code>NFKC</code> is NIST 800-63B's advice: the same password typed on two keyboards can arrive as two byte sequences (<code>é</code> as one code point or as <code>e</code> plus a combining accent), and without normalising, one of them would be refused.</p>",
  cut("apps/api/src/password.ts", "export async function hashPassword", "let dummy"),
  "<p>Three decisions in <code>verifyPassword</code>, each a small test. <strong>Constant time over the key.</strong> <code>timingSafeEqual</code> compares every byte whatever the first mismatch; a plain <code>===</code> on Buffers returns at the first difference, and a network attacker with enough samples can read the position of the mismatch out of the response time. Java's <code>MessageDigest.isEqual</code> and Python's <code>hmac.compare_digest</code> exist for the same reason. <strong>A ceiling on the parameters.</strong> The stored string is data from a database row, and a row that someone edited to ask for <code>N = 2^40</code> would turn every sign-in of that account into a denial of service on the api; the ceiling refuses it as a plain <code>false</code>. <strong>A refusal by scrypt is a no, not a crash.</strong> <code>N</code> that is not a power of two makes Node throw; the <code>.catch(() =&gt; undefined)</code> turns that into \"does not match\", so a tampered row cannot 500 the route either.</p>",
  cut("apps/api/src/password.ts", "let dummy"),
  "<p>Now the sign-in route itself, and the decision the whole section turns on: <em>no user enumeration</em>. Two branches look alike to a compiler, \"no such email\" and \"wrong password\", and the naive code answers the first one at once, without hashing anything. That answer arrives tens of milliseconds sooner, and a caller who times it learns which emails have accounts: the list a credential-stuffing run starts from. So an unknown email is verified against a real scrypt hash of a password nobody knows, both branches cost exactly one hash, and both answer the same bytes. The dummy is computed once and <em>warmed at startup</em>, in <code>buildApp</code>: were it lazy, the first unknown email would pay for two hashes, which is a tell of its own. Drill 2 plants the naive version.</p>",
  cut("apps/api/src/app.ts", "  // Paid for now, not by the first sign-in", "  app.use(async (c, next) => {"),
  cut("apps/api/src/app.ts", "  // Sign-up must say when an email is taken", "  // Public, and always 204"),
  "<p>Read <code>found?.passwordHash ?? (await dummyHash())</code> and then <code>found &amp;&amp; matches</code>: the hash is always computed, and the answer still needs both facts, so the dummy can never sign anyone in even if a password happened to match it (it cannot: it is a hash of 32 random bytes). The one place an account's existence <em>does</em> show is sign-up: without an email flow, which SPEC calls a non-goal, there is no way to answer \"maybe, check your inbox\" and still create the account, so a taken email is a 409, and that route goes through the same <code>allowAttempt</code> seam as sign-in, where E9.6's rate limiter plugs in. <code>SignInBody</code> is also deliberately looser than <code>SignUpBody</code>: a sign-in whose password is shorter than the sign-up rule allows is still just a wrong password, not a 400 that says \"that is not even a valid password\".</p>",
  cut("packages/contracts/src/index.ts", "/**\n * What a person calls themselves", "/** GET /auth/me"),
  cut("apps/api/src/auth.test.ts", 'test("an unknown email and a wrong password get the same answer', 'test("signing in starts a NEW session'),
  cut("packages/db/src/index.ts", "    signUp: async", "    credentialsFor: async"),
  cut("packages/db/migrations/0015_sign_in.sql", "-- E8.1 (F23): sign up, sign in, sign out."),
  "<p>The migration keeps credentials in a table of their own rather than as columns on <code>users</code>: a user created before sign-in existed, by the development header, simply has no row here, and sign-in for them verifies against the dummy like everyone else's miss. The <code>CHECK</code> on <code>password_hash</code> is the stored format written a second time, in SQL: a row that is not a scrypt string of ours cannot be inserted, whatever the application did.</p>",
  vs([("<code>scrypt(password, salt, 32, options, callback)</code> wrapped in <code>new Promise</code>", "<code>SCryptPasswordEncoder</code>; or BouncyCastle's <code>SCrypt.generate</code>", "<code>hashlib.scrypt(password, salt=..., n=..., r=..., p=..., maxmem=...)</code>"),
      ("<code>timingSafeEqual(key, expected)</code> on two Buffers of equal length", "<code>MessageDigest.isEqual(a, b)</code>", "<code>hmac.compare_digest(a, b)</code>"),
      ("<code>password.normalize(\"NFKC\")</code>", "<code>Normalizer.normalize(s, Normalizer.Form.NFKC)</code>", "<code>unicodedata.normalize(\"NFKC\", s)</code>"),
      ("<code>dummy ??= hashPassword(...)</code>: a memoised promise (the assignment runs once, everyone awaits the same one)", "a <code>Supplier</code> behind an <code>AtomicReference</code>, or a static holder", "<code>functools.cache</code> on a coroutine factory; or a module-level future"),
      ("<code>(value): value is string =&gt;</code>: a type predicate, so <code>token</code> narrows after the check", "no equivalent; an <code>Optional</code> and a boolean", "<code>TypeGuard[str]</code> from <code>typing</code>"),
      ("<code>randomBytes(16)</code> for the salt, <code>base64url</code> without padding", "<code>SecureRandom.nextBytes</code>, <code>Base64.getUrlEncoder().withoutPadding()</code>", "<code>secrets.token_bytes(16)</code>, <code>base64.urlsafe_b64encode(...).rstrip(b\"=\")</code>")]),
  case("The dummy hash is warmed at startup, not on the first miss.",
       "<p>The obvious shape is a lazy <code>dummyHash()</code> that computes on first use. Then the first sign-in with an unknown email costs two scrypt derivations, the dummy's and the comparison's, and answers noticeably later than every later miss: one request that stands out is enough to say \"that email was the first unknown one\". <code>buildApp</code> starts the computation and drops the promise; <code>dummy ??=</code> makes every later caller await the same one.</p>"),
  case("The parameter ceiling exists because a stored hash is input, not truth.",
       "<p>Nothing in the type system distinguishes a hash the app wrote from one an operator pasted into a row. Without the ceiling, a row asking for <code>N = 2^40</code> would make every sign-in of that account allocate terabytes and time out, and a database write becomes a way to take the api down one account at a time. The test feeds <code>scrypt$1099511627776$...</code> and asks for a plain <code>false</code>, and the same test refuses <code>N = 3</code> (not a power of two) without a throw.</p>"),
  case("Sign-in that validated like sign-up was rejected.",
       "<p>Reusing <code>SignUpBody</code> for sign-in would answer 400 \"must be at least 8 characters\" to a short password, which tells the caller something about the account's rules before any hash is computed, and separates \"malformed\" from \"wrong\" in the status code. <code>SignInBody</code> keeps only the caps, so that everything that is not a match is one 401 with one body.</p>"),
  note("<strong>The principle:</strong> an authentication endpoint is a function whose cost and whose answer must not depend on the secret it is protecting. Slow hashing protects the table if it leaks; constant-time comparison protects the comparison; the dummy hash protects the <em>existence</em> of the account. Miss any one and an attacker learns something for free. The rate limiter that E9.6 plugs into <code>allowAttempt</code> is the fourth layer, against online guessing at scrypt's price per try."))

section("sessions", "2 · Sessions: a row, a cookie, and why not a JWT",
  "<p>Signing in produces a session, and the first design question is what a session <em>is</em>. This repo already had one signed stateless token (E1.5's HS256 JWT that opens a document's socket for 60 seconds), so the tempting answer was a second one for the browser. It was rejected for one reason that decides most session designs: <strong>revocation</strong>. A signed token is valid until it expires, wherever it is; to revoke one early you need a deny list the server consults on every request, and a deny list is a table. So the browser's session is a table row from the start, and the token is 32 random bytes that mean nothing except \"look me up\".</p>",
  cut("apps/api/src/identity.ts", "/** The cookie a signed-in browser carries"),
  "<p>Two hashes appear in this epic and they are chosen on opposite principles. The <em>password</em> gets scrypt, slow and memory-hard, because a password can be guessed. The <em>session token</em> gets one SHA-256, fast, because 256 random bits cannot be guessed at any speed: the hash is there so that a read of the table (a backup, a log line with a query in it) hands nobody a live session, not to slow an attacker down. Hashing a high-entropy token with a KDF would cost tens of milliseconds on <em>every request</em> for no security. <code>isSessionToken</code> refuses anything that is not exactly the 43 base64url characters <code>newSessionToken</code> makes, so a malformed cookie never reaches the database.</p>",
  cut("apps/api/src/app.ts", "  // E8.1 (F23): sign up, sign in, sign out. The session is a cookie", "  // Sign-up must say when an email is taken"),
  cut("apps/api/src/app.ts", "  // Public, and always 204", '  app.post("/orgs"'),
  "<p>Each cookie flag is one attack. <strong><code>HttpOnly</code></strong>: a script on the page cannot read it, so a cross-site-scripting bug cannot exfiltrate the session (it can still act as the user while the page is open, which is why the rest of the app renders every string from the wire as text). <strong><code>Secure</code></strong>: the browser never sends it over plain http, except in development, where the app is served on <code>localhost</code> over http and a Secure cookie would never come back; <code>config.ts</code> turns it off for the literal <code>development</code> and nothing else. <strong><code>SameSite=Strict</code></strong>: the browser does not attach it to any request that starts from another site, which is the whole CSRF defence here. Epic 1 already refused bodies that are not <code>application/json</code>, which stops the form-post variant of CSRF; but <code>POST /documents/:id/session</code> reads no body and so never passed through <code>body()</code>, and only the cookie attribute protects it. The price of Strict is that a person arriving from a link in an email is signed out for that first navigation; the design accepts it.</p>",
  "<p><code>signedIn</code> mints a <em>new</em> token on every sign-in rather than reusing one a browser might already hold: the session-fixation attack is to plant a known cookie in a victim's browser and wait for them to sign in with it. And the expiry is fixed at sign-in, never slid forward on use, for the reason E1.4 found about the dev header: a sliding expiry makes every request a write (an <code>UPDATE</code> of <code>expires_at</code>), which takes a row lock and rules out a read replica; a fixed one makes <code>userForSession</code> a pure indexed read. Seven days is the trade.</p>",
  cut("packages/db/src/index.ts", "    startSession: async ({ userId, tokenHash, ttlSeconds }) => {", "    // Inputs are parsed with the SAME contract"),
  "<p>One statement does three things: sweeps this user's expired rows (a ponytail: someone who never signs in again keeps dead rows, and a periodic delete is the upgrade), inserts the new session, and writes the sign-in into the audit trail of every org the user belongs to, which is section 5's rule applied here: the row cannot exist without the event, nor the event without the row. A writable CTE (<code>with gone as (delete ...), s as (insert ... returning ...) insert ...</code>) is Postgres's way to make several writes one statement, and therefore one atomic step, without an explicit transaction.</p>",
  vs([("What revocation costs", "one <code>DELETE</code>; the token is dead on its next request", "impossible before <code>exp</code> without a deny list, which is a table with the same shape as the session table", ""),
      ("What each request costs", "one indexed read of <code>auth_sessions</code> by <code>token_hash</code>", "a signature check, no I/O", "the JWT's real advantage; it buys nothing here, where every route reads Postgres anyway"),
      ("What a leaked database gives", "SHA-256 of tokens: nothing usable", "nothing, but a leaked <em>signing key</em> gives every session at once, and rotating it signs everyone out", ""),
      ("Where the truth lives", "Postgres, which every api process reads", "in the token; several processes agree without sharing anything", "the property that made E1.5 pick a JWT for the sync token: the api signs, the sync node verifies, and they never call each other"),
      ("Lifetime", "7 days, fixed at sign-in", "as short as the deny-list gap you accept; the sync token lives 60 s for exactly this reason", "section 4 is about the one place 60 s was still too long")], head=("Question", "A session row (the browser)", "A signed stateless token (a JWT)", "Notes")),
  "<p><strong>The dev header, kept in its place.</strong> Epic 1's <code>x-dev-user</code> header made tenancy real before any sign-in existed. E8.1 keeps it for scripts, the chaos runs, the tunnel demo and \"two browser windows as two people\", but only where <code>NODE_ENV</code> is the literal <code>development</code>, and only <em>behind</em> a session: a signed-in browser is who it signed in as whatever header it also sends. <code>test</code> does not count as development, on purpose: an image built in CI and promoted with <code>NODE_ENV=test</code> must not accept the header. Unset means production, the safe side.</p>",
  cut("apps/api/src/identity.ts", "/**\n * Development only (SPEC §2.16)", "/** The cookie a signed-in browser carries"),
  cut("apps/api/src/config.ts", "  // Unset means production: the safe side.", "  PORT: port(3000)"),
  cut("apps/api/src/config.ts", "// Long enough to open a socket", "/** F31: the default AI run limit"),
  cut("apps/api/src/main.ts", "const identify = chooseIdentity(config.nodeEnv);", "const server = await startServer"),
  "<p><strong>Programs are not people.</strong> The worker's AI and git peers never used the header: they hold <code>SESSION_TOKEN_SECRET</code>, the same secret the api signs sync tokens with, and mint their own 60-second token for the actor they are (<code>agent</code> plus the run's id; <code>git</code> plus the commit). That is a <em>service credential</em>: a process authenticates as itself, and the token's <code>knd</code> claim, which only a holder of the secret can set, is what lets the room stamp \"the AI did this\" on an op in a way no browser can forge. The alternative, routing the worker's peers through the api with a new kind of principal, was rejected as an api hop on the worker's hot path for no gain. The integration test <code>service-credential.int</code> proves both peers still reach the room behind a session-only api.</p>",
  cut("packages/session-token/src/index.ts", "// A session token lets a peer open ONE document's WebSocket", "const HEADER"),
  cut("apps/worker/src/ai.ts", "      session: async () => ({", "    });", include_end=True),
  cut("apps/api/src/auth.test.ts", 'test("without a session every route but the probes', 'test("a second sign-up with the same email'),
  cut("apps/api/src/auth.int.test.ts", "// The REAL entry point in a REAL process", '  test("with NODE_ENV=development the header still works'),
  vs([("<code>setCookie(c, name, value, { httpOnly, secure, sameSite: \"Strict\", path: \"/\" })</code>", "<code>ResponseCookie.from(name, value).httpOnly(true).secure(true).sameSite(\"Strict\")</code>", "<code>response.set_cookie(name, value, httponly=True, secure=True, samesite=\"Strict\")</code>"),
      ("<code>const cookieOptions = { ... } as const</code>: a literal type, so <code>sameSite</code> is <code>\"Strict\"</code>, not <code>string</code>", "a <code>record</code> with final fields", "a <code>Final</code> dict, or a frozen dataclass"),
      ("<code>randomBytes(32).toString(\"base64url\")</code>", "<code>SecureRandom</code> + <code>Base64.getUrlEncoder().withoutPadding()</code>", "<code>secrets.token_urlsafe(32)</code>"),
      ("<code>createHash(\"sha256\").update(token).digest()</code>: a <code>Buffer</code>, stored as <code>bytea</code>", "<code>MessageDigest.getInstance(\"SHA-256\")</code>", "<code>hashlib.sha256(token.encode()).digest()</code>"),
      ("<code>with gone as (delete ...), s as (insert ... returning) insert ...</code>: three writes, one statement", "the same SQL through JDBC; JPA cannot express a writable CTE", "the same SQL with psycopg; the ORM cannot"),
      ("<code>nodeEnv === \"development\" ? developmentIdentity : sessionIdentity</code>: the strategy chosen once, at boot", "a <code>@Profile(\"dev\")</code> bean", "<code>settings.DEBUG</code>-gated middleware; the same danger of <code>DEBUG=True</code> in production")]),
  case("A stateless signed token for the browser was rejected.",
       "<p>It would have reused E1.5's package and needed no table. But sign-out would then be a client-side deletion only: a copy of the token in another tab, or a stolen one, works until it expires, and the only fix is a server-side list of revoked tokens checked on every request, which is a session table with worse ergonomics. The row won; the JWT stays where its stateless property is the point, between the api and the sync node.</p>"),
  case("A sliding expiry was rejected: it would have made every request a write.",
       "<p>Extending the session on each use feels friendlier. It turns <code>userForSession</code> into an <code>UPDATE ... RETURNING</code>, which takes a row lock per request and cannot be served from a read replica, the exact cost E1.4 found in the dev header's upsert. Seven days fixed at sign-in keeps identity a pure read; the trade is that a person is signed out a week after signing in, whatever they did meanwhile.</p>"),
  case("The header behind a session in development, not switched off, and not on for test.",
       "<p>Two pressures pulled in opposite directions: scripts and chaos runs need to act as several people without a browser, and a promoted image must never accept a header that lets anyone be anyone. The answer is the literal <code>\"development\"</code> and nothing else, with the session checked first even there, and a loud line in the log when the header is on. The integration test spawns the real <code>main.ts</code> with <code>NODE_ENV</code> unset, <code>production</code> and <code>test</code>, and asks 401 of every route with the header.</p>"),
  note("<strong>Principal-level point:</strong> pick the hash by the entropy of what it protects, and pick the token by how you will revoke it. Low entropy (a password): a KDF, slow and memory-hard. High entropy (32 random bytes): one fast hash, for the table's sake. Must be revocable at once (a browser session): a row. Must work across processes that never talk, for seconds (the sync token): a signature, with a short life as the only revocation, and section 4 shows what to do when even that is too long."))

section("roles", "3 · Roles at the query: the row that proves membership carries the role",
  "<p>Epic 1's door is a join: <code>select o.*, m.role from orgs o join memberships m on m.org_id = o.id where o.id = $1 and m.user_id = $2</code>. A stranger and a missing org both get no row, and no row is a 404. E8.2 adds one column to what that query already returns, the role, and puts it on the request context next to the org. Nothing about the caller's authorisation is fetched separately: the same read that says \"you may see this org\" says \"as a viewer\". Then each route declares the least role it needs.</p>",
  cut("packages/contracts/src/index.ts", "// --- Roles (F24)", "// --- HTTP bodies"),
  cut("apps/api/src/app.ts", "/** Every guard `need` made", "/** Turns Zod issues"),
  "<p><code>need</code> is a middleware factory typed over the context variable <code>role</code>, so <code>c.var.role</code> is a <code>Role</code>, never <code>any</code>, and it records itself in a <code>WeakMap</code> keyed by the middleware function. That map is for one test, and the test is the important half of the design: <strong>default deny</strong>. A handler compiles perfectly well without a guard, and in Spring or Django a route that forgot its <code>@PreAuthorize</code> or its decorator is open until someone notices. Here <code>app.test.ts</code> walks <code>app.routes</code>, looks every org and document route up in the map, and compares the whole table to the one it expects. A new route without <code>need</code> shows up as <code>undefined</code> and the test is red until someone decides who may call it; a role changed without meaning to shows up too.</p>",
  cut("apps/api/src/app.test.ts", "// E8.2 (F24): default deny."),
  cut("apps/api/src/app.ts", "  // EVERYTHING about one org lives behind this middleware", "  // E10.8: who is in the org"),
  "<p>Two status codes, and the rule for choosing between them. A <em>member</em> without the role gets <strong>403</strong>: they can already see the thing exists (they are in the org), so \"not found\" would be a lie that helps nobody. A <em>stranger</em> still gets <strong>404</strong> from the middleware before any <code>need</code> runs, because the first rule of tenancy (F2) is that a response never confirms another tenant's data exists. The rbac matrix test drives every route as an owner, an editor, a viewer and a stranger, least privileged first so that a refused write cannot leave anything the next row would see.</p>",
  cut("apps/api/src/rbac.int.test.ts", 'test("every route, every role', 'test("no escalation'),
  cut("apps/api/src/app.ts", "  // F24: only an owner changes roles", '  org.post("/workspaces"'),
  cut("packages/db/src/index.ts", "        setMember: async ({ email, role, by }) => {", "        // Both lists page over a join"),
  cut("packages/db/src/index.ts", "  /** `work` in one transaction, committed only when", "  /**\n   * One hit on a rate limit"),
  "<p><code>setMember</code> is the one place in the epic that needs a transaction rather than a statement, and the reason is a race the types cannot see. Rule: the last owner cannot step down, or the org has nobody who can change roles. Check: count the owners, refuse if the caller is the last. Race: two owners demote <em>each other</em> at the same moment; under READ COMMITTED each statement sees the other still an owner, both checks pass, and the org ends with none. There is no single row to lock (the rule is about a <em>set</em> of rows), so the transaction takes a Postgres <em>advisory lock</em> named after the org: <code>pg_advisory_xact_lock(hashtext('noon:members:&lt;orgId&gt;'))</code>, held until commit, so the second change waits for the first and then sees its result. The integration test fires both demotions with <code>Promise.all</code> and asserts <code>[200, 403]</code>: the caller's own role is read again under the lock, so the second change finds its caller no longer an owner. The audit row is written in the same transaction, and only when the role really changed.</p>",
  cut("apps/api/src/rbac.int.test.ts", 'test("two owners demoting each other', 'test("a member of org A'),
  "<p><strong>Shares (F25).</strong> An owner shares one document with someone outside the org, at editor or viewer, never owner. The first design question was where the row lives, and the answer is <em>not in <code>memberships</code></em>: a share must not make anyone a member, and every org route, plus <code>GET /orgs</code>'s keyset paging over the orgs a user belongs to, joins <code>memberships</code> and would have shown the org to the outsider. So <code>document_shares</code> is a table of its own, keyed by document and user, tied to the document's org by a composite foreign key so that a share can never point at a document of another org.</p>",
  cut("packages/db/migrations/0016_document_shares.sql", "-- E8.3 (F25)"),
  cut("packages/db/src/index.ts", "type ShareRole", "const MemberRow"),
  cut("packages/db/src/index.ts", "    getDocumentForMember: async (documentId, userId) =>", "    forOrg(orgId) {"),
  "<p><code>accessOf</code> is a scalar subquery spliced into the document lookup, and it answers \"the higher of the caller's org role and their share\" in SQL: a <code>union all</code> of the two candidate roles, ordered by their position in the array <code>['viewer','editor','owner']</code> descending, <code>limit 1</code>. That is \"max by enum order\" without a numeric column, and it costs two primary-key probes inside the one round trip the document routes already made (the E1.4 rule: one lookup per request). A member who is also shared a document at a higher role gets the higher one; revoking the share leaves their org role; an outsider with no share gets <code>null</code>, which the outer <code>where role is not null</code> turns into no row, and no row is 404.</p>",
  cut("apps/api/src/app.ts", "  // Everything under /documents/:id: the path names no org", "  // The routing hook (SPEC §2.11)"),
  cut("apps/api/src/app.ts", "  // F25: an owner of the document's org shares it", "  // An AI run (F9) is a job"),
  cut("packages/db/src/index.ts", "        share: async ({ documentId, email, role, by }) => {", "        createWorkspace: async ({ name }) => {"),
  "<p>Both share statements are one <code>insert ... select</code> or <code>delete ... returning</code> with the audit row in a CTE of the same statement. <code>share</code> selects from <code>documents</code> and <code>users</code> together, so a row is written only when the document is this org's <em>and</em> the email exists; either missing is zero rows, which the route answers as 404. <code>unshare</code> inserts the audit row <em>from the deleted row</em>, so revoking a share that does not exist deletes nothing, records nothing, and the row count says which happened. Every write is committed before it is announced (section 4): a sync node that hears of a change and reads the row must see the new one.</p>",
  vs([("<code>createMiddleware&lt;{ Variables: { role: Role } }&gt;</code>: typed request context", "<code>SecurityContextHolder</code>, or request attributes (untyped)", "<code>request.user</code>, an attribute set by middleware"),
      ("<code>new WeakMap&lt;object, Role&gt;()</code>: metadata on a function without touching it", "annotations read by reflection", "function attributes, or a decorator registry"),
      ("<code>RANK: Record&lt;Role, number&gt;</code> and <code>includes(role, need)</code>", "<code>RoleHierarchyImpl</code>: <code>OWNER &gt; EDITOR &gt; VIEWER</code>", "no hierarchy in Django's permissions; groups, or an <code>IntEnum</code>"),
      ("<code>c.var.role</code>: typed by the middleware's generic", "<code>@AuthenticationPrincipal</code>", "<code>request.user.role</code>"),
      ("<code>pg_advisory_xact_lock(hashtext($1))</code> around a set-level rule", "the same SQL; or <code>@Lock(PESSIMISTIC_WRITE)</code> on a parent row when there is one", "the same SQL; <code>select_for_update</code> when a row exists to lock"),
      ("<code>array_position(array['viewer','editor','owner'], role)</code>: an enum's order, in SQL", "a <code>CASE</code> expression, or a rank column", "the same SQL"),
      ("<code>foreign key (document_id, org_id) references documents (id, org_id)</code>: a composite key that pins the tenant", "the same DDL; JPA needs an <code>@IdClass</code>", "the same DDL; Django cannot declare it, use a migration")]),
  case("The role in the sync token was rejected (the E1.5 decision, kept).",
       "<p>It would have saved the sync server a read. But a token is checked once, at connect, and a socket then lives for hours: a role in it is stale the moment an owner changes anything, and a demoted editor keeps editing until they reconnect. The token says <em>who</em>; Postgres says <em>what</em>, at the moment of asking. Section 4 is how the sync server asks.</p>"),
  case("Shares as rows in memberships were rejected.",
       "<p>A share with a flag on the membership row would have been one table and one join. It would also have made every org route see the outsider as a member, listed the org in their <code>GET /orgs</code>, and let <code>setMember</code> promote a share to owner by accident. A table with its own key and a role constraint that excludes <code>owner</code> makes the wrong things impossible to write.</p>"),
  case("A second query for the role was rejected.",
       "<p>Reading the membership for the 404 and the role for the 403 in two statements is the obvious layering, and it doubles the round trips of every request for nothing: the membership row <em>is</em> the role. E1.4 had already found that identity must be one read; E8.2 keeps authorisation inside the same one, and E8.3 keeps the share lookup inside it too, as a subquery.</p>"),
  note("<strong>The principle:</strong> authorise where you fetch. A check in the handler can be forgotten; a check in the query that returns the data cannot be bypassed by any route that uses the query, and a table of routes with their guards, compared by a test, catches the route that used neither. Postgres row-level security is the same idea one layer down, and the natural next step if the api ever grows a second way to read the tables."))

section("room", "4 · Roles in the room: read before the upgrade, re-read at the op's turn, and revocation that beats the token",
  "<p>REST is easy: every request reads the row. A WebSocket is the hard case, because it is authenticated once and then lives for hours, and F24 demands that a role change reach an <em>open</em> session within ten seconds. The sync server never trusts the token for what someone may do (section 3's case study), so it reads the role itself, from Postgres, at three moments: <strong>before the upgrade</strong>, when the token arrives; <strong>at the join</strong>, once the socket is registered; and <strong>on every announcement and every 30 seconds</strong>, for as long as the socket lives. The result of a read is one boolean on the peer, <code>mayEdit</code>, and the room checks it when an op's <em>turn</em> comes.</p>",
  cut("apps/sync/src/server.ts", "  /**\n   * E8.2 (F24): a user's role on the document", "export function startSyncServer"),
  cut("apps/sync/src/room.ts", "  /** E8.2 (F24): may this peer change the document?", "};", include_end=True),
  cut("apps/sync/src/room.ts", "    if (!peers.has(peer)) return; // dropped while this op waited in the queue", "    // Before the dedupe"),
  "<p>\"At its turn, not when it arrived\" is the sentence to remember. The room is a queue (lesson 2): an op can wait behind others, and a demotion can land while it waits. Checking <code>mayEdit</code> when the op is <em>received</em> would let every op already queued through; checking at the head of the queue, one line before the dedupe and the journal, refuses them all. The refusal is <code>forbidden</code>, a reason the client turns into \"You can view this document but not edit it.\" and undoes on its own canvas; the viewer stays connected and keeps seeing everyone else's ops and presence.</p>",
  cut("apps/sync/src/room.test.ts", "// E8.2 (F24): a viewer sees everything and changes nothing.", "\n});", include_end=True),
  "<p><strong>The first read, before the upgrade.</strong> E8.3 moved it there, and the reason is the whole of F25's hard clause: <em>a token minted before the revoke must not get them back in</em>. The sync token lives 60 seconds and its signature is valid for all of them. A revoked outsider who kept one (their client did, to reconnect) would present a perfectly signed token, and a server that admitted on the signature alone would open the socket and only then discover, at the join, that there is no access, and close it with 4404. That is a socket that should never have existed, and, for a client that reconnects, a way to keep reopening one for a minute. So <code>admits</code> reads the row while the request is still HTTP, and a revoked peer's reconnect is a plain 401, indistinguishable from any other bad token. Postgres not answering is not a no (the join asks again and says \"try again\", 4503).</p>",
  cut("apps/sync/src/server.ts", "  /**\n   * E8.3 (F25): may the token's holder still open the document?", "  /**\n   * Takes the document's lease"),
  cut("apps/sync/src/server.ts", "  // Every socket past the upgrade, from BEFORE its role is first read", "  // \"Alive\" into Redis every tenth of a ttl"),
  cut("apps/sync/src/server.ts", "    // E8.2 (F24): who may be here and edit is Postgres's answer", "    let pending = rooms.get(documentId);"),
  cut("apps/sync/src/server.ts", "  /**\n   * Reads what this peer may do, and applies it.", "  function log(documentId"),
  "<p>Read <code>applyRole</code> and <code>recheck</code> with lesson 7's eye for \"which answer is newer\". A socket is added to <code>connected</code> <em>before</em> its role is first read, so an announcement published while that read is in flight still finds it and reads again. Now two reads are in flight for one socket and can return in either order; <code>asked</code> and <code>applied</code> number them, and an older answer that arrives after a newer one is dropped (<code>asked &lt; entry.applied</code>). Without that, a revoke could be undone by a read that started before it: the race test in <code>role-change.int</code> holds the first read's answer, revokes, lets the announcement's read land, then releases the old one, and asserts the peer never joins. A read that fails is retried until Postgres answers or the socket goes: a demotion must not be lost to one dropped connection. And the git peer is never asked: it is the service itself, not a person.</p>",
  "<p><strong>The announcement is a hint.</strong> The api commits the change, then publishes <code>{ orgId, userId }</code> on one Redis channel; every sync node re-reads the role of the live sessions that pair concerns. The message carries no role, on purpose: a forged or stale message can only cause a re-read, never grant anything. Pub/sub keeps nothing for a subscriber that was away, so a node whose connection comes back is told <code>\"all\"</code> and re-reads every live session. And because the api announces once, best effort (a ponytail E8.2 named), E8.3 found that a revoke could stay open for good if Redis was away at the api when it happened; the fix is a <em>sweep</em>: every node re-reads all its live sessions every 30 seconds, never two sweeps at once. REST is never behind, because it reads the row per request; only the sockets need the push.</p>",
  cut("packages/lease/src/access.ts", "/**\n * E8.2 (F24): \"this user's access to this org changed\"", "const channelOf"),
  cut("packages/lease/src/access.ts", "/**\n * A sync node's half."),
  cut("apps/sync/src/main.ts", "// E8.2 (F24): the api announces role changes on Redis", "process.stdout.write"),
  cut("apps/api/src/app.ts", "  // ponytail: announced once, best effort;", "  // Paid for now"),
  cut("apps/sync/src/server.ts", "  // ponytail: one indexed read per live session per sweep", "  const http = createServer"),
  cut("apps/sync/src/role-change.int.test.ts", 'test("an owner demotes an editor with the document open', 'test("a node that missed the announcement'),
  "<p><strong>Every way back, shut.</strong> Revocation closes the live socket with 4404, which peer-client treats as <em>fatal</em>: no reconnect. It is the same code a stranger's token would get at the join, so a revoked person learns nothing they did not know. A peer that reconnects by itself asks <code>/session</code>, whose document middleware reads the row and answers 404; peer-client reads a <code>null</code> session as \"give up\" (<code>no_session</code>). And the token minted before the revoke meets <code>admits</code>, above. The e2e spec does all three from a real second browser, and asserts the guest's canvas is gone and its status line with it.</p>",
  cut("packages/peer-client/src/peer.ts", "// Close codes that reconnecting cannot cure", "const KNOWN_TYPES"),
  cut("apps/sync/src/role-change.int.test.ts", 'test("shared with an outside user, they edit live; revoked', "// The revoke lands while the peer is on its way in"),
  cut("apps/sync/src/role-change.int.test.ts", "// The revoke lands while the peer is on its way in", 'test("a revoke nobody announced'),
  vs([("<code>Promise.withResolvers()</code>: a promise and its <code>resolve</code>, to hold a read from a test", "<code>CompletableFuture</code>, completed by hand", "<code>asyncio.Future</code>, or an <code>asyncio.Event</code>"),
      ("<code>setInterval(...).unref()</code>: a timer that does not keep the process alive", "a daemon thread", "not needed: the loop ends when the main task does"),
      ("<code>Set&lt;Connected&gt;</code> plus <code>asked</code>/<code>applied</code> counters", "<code>ConcurrentHashMap</code> and an <code>AtomicLong</code> per entry", "a dict and ints, safe under the one event loop"),
      ("<code>redis.subscribe(channel)</code> and <code>redis.on(\"message\", ...)</code> on a client of its own", "Jedis <code>JedisPubSub</code> on a dedicated connection; Lettuce's <code>StatefulRedisPubSubConnection</code>", "<code>redis.pubsub()</code> with <code>listen()</code> or <code>run_in_thread</code>"),
      ("<code>void sync.recheck(change)</code>: fire and forget, on purpose, with the promise never rejecting", "<code>CompletableFuture.runAsync</code>", "<code>asyncio.create_task</code>"),
      ("<code>ws.close(4404, \"cannot_open_document\")</code>: an application close code", "<code>session.close(new CloseStatus(4404, ...))</code>", "<code>await websocket.close(code=4404)</code>")]),
  case("Polling the role from the room was rejected: the E1.5 review asked for push.",
       "<p>A read of the role every few seconds per live session would meet the ten-second budget and needs no Redis. It also scales with the number of sockets, not with the number of changes, which is the wrong axis: most sessions never see a role change. The push carries who changed; the node reads only those. The 30-second sweep then exists for the failure case only, and its cost is one primary-key probe per session per half minute.</p>"),
  case("Checking mayEdit when an op arrives was rejected: at its turn.",
       "<p>The first shape refused a viewer's op in <code>submit</code>, before it was queued. A demotion that landed while an editor had ops waiting let every one of them through, because they had already passed the check. Moving the check to the head of the queue, next to the other things the room asks of an op when it is finally its turn, made \"an op queued before a demotion is refused too\" true, and the unit test pins it.</p>"),
  case("The E8.2 ponytail was not acceptable for a revoke.",
       "<p>Announcing once, best effort, was fine for a demotion: the person keeps editing until they reconnect, and REST already refuses them. It was not fine for a revoked share: with Redis away at the api at that moment, an outsider would keep a live socket into a document they no longer have access to, for as long as they kept it open. The sweep closes that window at 30 seconds, and the test unshares behind the api's back and waits for the sweep to close the socket.</p>"),
  case("A revocation epoch in the token was rejected.",
       "<p>The textbook answer to \"a token outlives a revoke\" is a counter in the token that the server bumps on revoke, so an older token fails a comparison. It needs the server to store the counter per user, which is a deny list by another name, and it does nothing for the live socket, which outlives every token anyway. Reading the row before the upgrade and re-reading it on the socket answers both cases with one mechanism.</p>"),
  note("<strong>Revocation must beat every lifetime you hand out.</strong> There are three here. The sign-in cookie (7 days): a row, so revocation is a <code>DELETE</code> and the next request fails. The sync token (60 s): the row is read <em>before the upgrade</em>, so its lifetime never matters. The socket (hours): the role is re-read on every announcement and every 30 seconds, and the room checks the result at each op's turn. A design that leaves any one of the three to \"wait it out\" has a window exactly that long, and F25's test asks for all three to be shut at once."))

section("audit", "5 · The audit trail: written by the action, and the database refuses to change it",
  "<p>An audit trail has three properties or it is a log. It is <strong>complete</strong>: an action that happened has a row, and an action that did not happen has none. It is <strong>immutable</strong>: nobody who can write the trail can rewrite it, the application included. It is <strong>durable against deletion elsewhere</strong>: removing the org, the user or the document must not remove the record of what they did. Each property is enforced by the database rather than by the application, and the migration says how.</p>",
  cut("packages/db/migrations/0017_audit_log.sql", "-- E8.4 (F26): the org's audit trail."),
  "<p><strong>Complete: the row is written by the action's own statement.</strong> Every audited action in the db package inserts into <code>audit_log</code> either in a CTE of the statement that performs it or inside the same transaction, never after it returns. Then an action cannot commit without its row (a crash between the two would otherwise lose the record), and a row cannot outlive an action that rolled back (a refused <code>last_owner</code>, a run that hit <code>run_in_progress</code>, a wrong password, a share of nobody: nothing is written). <code>actorOf</code> copies the actor's email in as it is <em>now</em>, because the row must still read correctly when the user is gone.</p>",
  cut("packages/db/src/index.ts", "// E8.4 (F26): every audited action inserts into audit_log IN ITS OWN STATEMENT", "// seq is a bigint"),
  cut("packages/db/src/index.ts", "      /** One statement: the run, if the document is this org's", "      // An id that is not a UUID cannot name anything"),
  cut("packages/db/src/index.ts", "      async recordConflict(documentId, input) {", "      async clearConflict(documentId) {"),
  "<p>Section 2 showed <code>startSession</code> writing one sign-in row per org the user belongs to (an org sees its members' sign-ins and nobody else's), section 3 showed <code>setMember</code> writing only when the role really changed, inside its transaction, and <code>share</code> and <code>unshare</code> writing from the row they wrote or deleted. <code>createRun</code> keeps the instruction, exactly as typed, markup and all, because the trail must say what was asked; the reader's job is to render it as text. <code>recordConflict</code>, which the worker's git peer calls, writes the rejected push with the actor <code>git</code> (a ponytail: not the person who pushed; the webhook's pusher on <code>git_events</code> is the upgrade).</p>",
  "<p><strong>Immutable: the database says so, twice.</strong> The app connects as <code>noon_app</code>, a role that <code>provisionAppRole</code> creates with data access only. It gets a blanket <code>GRANT select, insert, update, delete on all tables</code>, and <code>alter default privileges</code> so that new tables get the same; then, <em>after</em> the grant and on every provisioning, <code>UPDATE</code>, <code>DELETE</code> and <code>TRUNCATE</code> on <code>audit_log</code> are revoked. \"On every provisioning\" is the part that matters: a grant someone made by hand is gone after the next deploy, and the test grants them and re-provisions to prove it. The trigger is the second layer, for everyone the grants do not reach: the table's owner (grants do not bind an owner), and any role that was widened between deploys. It raises on <code>UPDATE</code> and <code>DELETE</code> per row and on <code>TRUNCATE</code> per statement. The app role cannot disable it: it owns nothing, so <code>alter table</code> is refused too.</p>",
  cut("packages/db/src/index.ts", "/**\n * Creates (or resets) the login role", "    // Postgres gives everyone CONNECT and TEMP"),
  cut("packages/db/src/audit.int.test.ts", 'test("as the app role, every UPDATE, DELETE and TRUNCATE', 'test("re-provisioning takes'),
  "<p><strong>Durable: no foreign keys, on purpose.</strong> The E1.2 review's finding about cascades applies with full force here. <code>on delete cascade</code> from <code>orgs</code> would erase an org's whole trail together with the org, which is exactly when someone might want to read it. <code>on delete set null</code> from <code>users</code> is an <code>UPDATE</code> of the audit row, which the trigger refuses, so the user delete itself would fail. So the table has no foreign keys at all, the email is copied in, and a row may name a user, a document or an org that no longer exists. The test deletes the org and both users and asserts the trail is byte-for-byte what it was.</p>",
  cut("packages/db/src/audit.int.test.ts", 'test("deleting the org, or the user who acted, erases nothing'),
  "<p><strong>Reading it.</strong> <code>GET /orgs/:orgId/audit</code> is owners only, like usage: what happened in an org is the business of whoever runs it. It pages newest first over the same keyset cursor every list in the repo uses (<code>page()</code> gained a <code>newestFirst</code> flag), and there is no route that changes an entry: the api test tries <code>POST</code>, <code>PUT</code>, <code>PATCH</code> and <code>DELETE</code> on the collection and on an entry and asks 404 of all of them. The web view renders every string as a React text node, and its words come from a <code>Record</code> over the whole <code>AuditAction</code> enum: add an action to the contract and <code>audit.ts</code> stops compiling until someone has written its sentence. Drill 1 makes you do exactly that.</p>",
  cut("apps/api/src/app.ts", "  // F26: the org's audit trail (sign-ins", '  app.route("/orgs/:orgId", org);'),
  cut("packages/contracts/src/index.ts", "// --- Audit (F26)", "export type AuditPage"),
  cut("apps/web/src/audit.ts", "import { ConflictReason"),
  cut("apps/api/src/audit.int.test.ts", "    const entries = await readAll(org.id); // newest first", "    for (const entry of entries) {"),
  cut("e2e/audit-view.spec.ts", "  // The instruction's markup stayed text", "  // Owners only"),
  vs([("<code>with j as (insert ... returning *), a as (insert into audit_log ... from j) select * from j</code>", "Envers writes <code>_AUD</code> rows from entity listeners in the same transaction; the app role can still <code>UPDATE</code> them", "django-simple-history writes from signals in the same transaction; same caveat"),
      ("<code>revoke update, delete, truncate on audit_log from noon_app</code>, after the grant, every deploy", "the same SQL, in Flyway or by hand; rarely done", "the same SQL; Django's migrations can run it"),
      ("<code>create trigger ... before update or delete ... execute function</code> that raises", "the same DDL", "the same DDL"),
      ("<code>check ((actor_kind = 'user') = (actor_id is not null))</code>: a boolean equality as an invariant", "the same DDL; Bean Validation cannot express it", "the same DDL; a <code>CheckConstraint</code> in <code>Meta</code>"),
      ("<code>jsonb_build_object('email', u.email, 'role', s.role)</code> and <code>z.record(z.string().max(40), z.string().max(4000))</code>", "a <code>Map&lt;String, String&gt;</code> column with a JSON converter", "<code>JSONField</code>; pydantic <code>dict[str, str]</code>"),
      ("<code>Record&lt;AuditAction, (d) =&gt; string&gt;</code>: exhaustive by construction", "a <code>switch</code> over an enum with <code>-Werror</code> on a missing case; or <code>EnumMap</code> checked at startup", "a dict, checked by nothing unless mypy sees a <code>Literal</code>"),
      ("<code>rejects.toMatchObject({ code: \"42501\" })</code>: the SQLSTATE for insufficient privilege", "<code>SQLException.getSQLState()</code>", "<code>psycopg.errors.InsufficientPrivilege</code>")]),
  case("Writing the audit row after the action returned was rejected.",
       "<p>The layered shape, <code>await db.setMember(...); await audit.write(...)</code>, is what an <code>AuditService</code> looks like in most codebases. A crash, a timeout or a deploy between the two loses the row, and a rolled-back action can leave one, because the second write has no idea the first did not commit. The CTE and the shared transaction make both impossible, and the test for it (\"a failed action leaves no audit row\") refuses two actions and counts.</p>"),
  case("Foreign keys on audit_log were rejected: the E1.2 finding, again.",
       "<p>Referential integrity is the reflex, and it is wrong for a trail: a cascade erases history when the thing it is about is deleted, and <code>set null</code> is an <code>UPDATE</code> the table refuses. The test deletes an org and its users and asserts the rows are unchanged, including the actor's id and email as they were.</p>"),
  case("Per-row checks in the application were rejected: the app role could still UPDATE.",
       "<p>A repository method that only ever inserts is a promise the code makes about itself; the app role's privileges are a fact about what any code running as it <em>can</em> do, including a bug, a migration script or a stolen connection string. Revoking the privilege makes the promise checkable: <code>has_table_privilege</code> answers it, and the test asks.</p>"),
  case("One global sign-in row was rejected: one per org.",
       "<p>A sign-in belongs to a person, not to an org, so one row seemed natural. But the trail is read per org, by its owners, and an org must see its members' sign-ins without seeing that a member also belongs elsewhere. The statement joins <code>memberships</code> and writes one row per org; a user in no org signs in unrecorded, which the test spells out.</p>"),
  note("<strong>The principle:</strong> an audit trail is a claim about the past that the present must not be able to edit. Making it in the same statement as the action gives completeness; taking the privilege away from the writer gives immutability against the application; the trigger gives it against everyone else who connects; copying values in and refusing foreign keys gives durability. Envers and simple-history give you the first for free and none of the others unless you do the database's part yourself."))

section("tradeoffs", "6 · Trade-offs and comparisons: where this design sits",
  "<p>The questions an interviewer asks about an auth design, with the honest answers for this one.</p>",
  vs([("Password hashing", "scrypt, <code>N=2^15, r=8</code> (32 MiB), parameters in the string, from <code>node:crypto</code>", "Spring's <code>DelegatingPasswordEncoder</code>, bcrypt by default, argon2 available", "Django: PBKDF2-SHA256 by default (fast to verify, not memory-hard), argon2 with a dependency"),
      ("The browser's session", "a row, an opaque 32-byte token kept as SHA-256, a 7-day fixed expiry, HttpOnly + Secure + SameSite=Strict", "<code>HttpSession</code> in Spring Session JDBC: the same design; <code>JSESSIONID</code>", "<code>django_session</code>: the same design; the key is stored in clear"),
      ("CSRF", "SameSite=Strict, plus JSON-only bodies from epic 1; no token", "a synchroniser token (<code>CsrfFilter</code>) by default", "a <code>csrftoken</code> cookie echoed in a header"),
      ("Service-to-service", "the worker mints 60-second HS256 tokens with a shared secret and an actor kind", "a client-credentials grant, or a shared secret", "the same"),
      ("Roles", "three nested roles per org, from the membership row, <code>need(role)</code> per route, a test over the route table", "<code>@PreAuthorize</code> + <code>RoleHierarchy</code>; no table of routes unless you write one", "<code>permission_required</code>; django-guardian for objects"),
      ("Per-object access", "a shares table joined as a subquery: the higher of two roles", "Spring ACL (an ACL table per object)", "django-guardian"),
      ("Live revocation", "read before the upgrade; re-read on a pub/sub hint; a 30 s sweep; checked at the op's turn", "<code>SessionRegistry.expireNow()</code> for HTTP only; WebSockets by hand", "Channels groups by hand"),
      ("Audit", "same-statement CTE, revoked grants, a trigger, no foreign keys", "Envers: history, editable by the app role", "simple-history, auditlog: the same"),
      ("Tenancy", "the membership join in every query (epic 1), shares as a second door", "Hibernate filters or <code>@TenantId</code>; RLS", "django-tenants (schemas); RLS")], head=("Question", "This repo", "Java world", "Python world")),
  "<p><strong>What is deliberately simple.</strong> Sessions are checked with one indexed read and no cache: a cache would make revocation a two-place problem, and one read is cheap. Roles are three, nested, per org: a role hierarchy is a total order, which is why <code>includes</code> is one comparison; the moment two roles are incomparable (\"billing\" and \"editor\"), the design becomes permissions, not roles, and the route table becomes a matrix. Authentication is a password: no OAuth, no email, no second factor, because the spec calls them non-goals and each is a large surface of its own.</p>",
  "<p><strong>What is not solved.</strong> There is no email flow, so sign-up must say when an email is taken, there is no password reset, and a member is added by an email that must already have signed up. The rate limiter behind <code>allowAttempt</code> is E9.6's and allows everything today, so an online guesser pays only scrypt's price per try. The api announces a change once, best effort, and the sweep covers the gap at 30 seconds. The sync server reads the role twice per connect, at the upgrade and at the join. There is no member list, no removal from an org (a demotion to viewer is the nearest thing), and no sharing screen: shares are made through the api. A rejected push is attributed to <code>git</code> and its commit, not to the engineer who pushed. Expired sessions are swept at their owner's next sign-in only. Every one of these is named where it lives, with its ceiling and its upgrade.</p>",
  note("<strong>The interview answer in one breath:</strong> scrypt with self-describing parameters and a dummy hash so sign-in costs the same for everyone; an opaque session token kept as its SHA-256 in a row, in an HttpOnly, Secure, SameSite=Strict cookie, revoked by a DELETE; a 60-second HS256 token between the api and the sync node, with the role deliberately not in it; the role read from the row that proves membership, declared per route and checked by a test over the router; the room reading the role before the upgrade, at the join and on every announcement, and checking it at each op's turn; and an audit trail written by the action's own statement in a table the app role cannot change and a trigger defends against everyone else."))

section("testing", "7 · Testing identity without a browser, and the database's refusals",
  "<p>The split from the earlier lessons holds: every decision has a pure test that ran on every commit, every I/O rule has an integration or end-to-end test that runs against the real stack. Five shapes are new to this epic.</p>",
  "<p><strong>A structural fake of the database.</strong> The auth routes are tested against an object with five methods, cast <code>as unknown as Db</code>: TypeScript's structural typing means the fake needs only what the routes call, and the cast records that this is a fake, not a <code>Db</code>. It also records what it was asked (<code>calls</code>), so \"a 400 body is refused before anything is hashed or stored\" is an assertion on an empty array.</p>",
  cut("apps/api/src/auth.test.ts", "function memoryDb() {", "function app(deps"),
  "<p><strong>A timing test with real medians.</strong> The enumeration defence cannot be tested with a mock of <code>verifyPassword</code>: the claim is about wall-clock time, so the test signs up, times five unknown emails and five wrong passwords through the real scrypt, and compares medians (medians, because one garbage collection would ruin a mean). Without the dummy hash the unknown email answers in well under a millisecond; the assertion is loose (<code>0.3</code>) so a loaded host does not make it flaky, and tight enough that the bug fails it by an order of magnitude.</p>",
  "<p><strong>The router read as data.</strong> Hono exposes <code>app.routes</code>, a list of <code>{ method, path, handler }</code>; <code>need</code> registered each guard in a <code>WeakMap</code>; the test joins the two and compares the whole table. It is a test of the <em>configuration</em>, not of any request, and it is the only kind of test that catches a route nobody wrote a test for.</p>",
  "<p><strong>The real entry point in a real process.</strong> A test that hands <code>startServer</code> an identity strategy cannot prove that <code>main.ts</code> chooses the right one from <code>NODE_ENV</code>. <code>useApiProcess</code> spawns <code>main.ts</code> with a clean environment (nothing from the runner leaks in, in particular vitest's own <code>NODE_ENV=test</code>), waits for <code>/health</code>, and the test asks 401 of the header with <code>NODE_ENV</code> unset, <code>production</code> and <code>test</code>, and 200 with <code>development</code>.</p>",
  cut("apps/api/src/testing.ts", "/**\n * The REAL entry point (main.ts) in a REAL process"),
  "<p><strong>A hook inside the role read.</strong> The revoke race needs a role read that has its answer but has not yet reached the server, exactly as a slow Postgres would produce. The test's <code>roles</code> function wraps the real one and awaits an <code>afterRead</code> hook the test sets per case; the hook resolves a promise the test awaits (\"the read has answered\"), then waits on one the test resolves later (\"now deliver it\"). Two <code>Promise.withResolvers()</code> and no fake clock.</p>",
  cut("apps/sync/src/role-change.int.test.ts", "/** E8.3's race tests: runs after each role read", "let publisher"),
  cut("apps/sync/src/role-change.int.test.ts", "  sync = await startSyncServer({ port: 0, secrets: [TEST_SECRET], store: t.db.documentStore(), roles: async", "  subscriber = accessSubscriber"),
  "<p><strong>Asking Postgres what a role may do.</strong> <code>has_table_privilege(role, table, 'update')</code> is the database's own answer to \"can this role change the trail\", and the app-role tests ask it before and after re-provisioning, then try the statements and match on SQLSTATE <code>42501</code>. A throwaway app role is provisioned per test file with the same function the migrate container runs, over the test's own schema.</p>",
  cut("packages/db/src/audit.int.test.ts", 'test("the app role holds SELECT and INSERT', 'test("as the app role'),
  cut("packages/db/src/testing.ts", "/** Provisions a throwaway app login role", "    async drop() {"),
  cut("apps/api/src/identity.test.ts", 'test("a session lookup is a pure read', 'test("in development a session wins'),
  vs([("<code>{ ... } as unknown as Db</code>: a structural fake with only the methods used", "Mockito, or an interface with one implementation per test", "<code>MagicMock</code>, or a <code>Protocol</code> and a small class"),
      ("<code>performance.now()</code> around a request, medians over five runs", "<code>System.nanoTime()</code>; JMH for anything serious", "<code>time.perf_counter()</code>"),
      ("<code>spawn(process.execPath, [main], { env: { PATH, ... } })</code>: a child with a clean environment", "<code>ProcessBuilder</code> with <code>environment().clear()</code>", "<code>subprocess.Popen(..., env={...})</code>"),
      ("<code>test.each([[\"unset\", {}], ...])(\"with NODE_ENV %s ...\")</code>", "<code>@ParameterizedTest</code> with <code>@MethodSource</code>", "<code>@pytest.mark.parametrize</code>"),
      ("<code>await expect(promise).rejects.toMatchObject({ code: \"42501\" })</code>", "<code>assertThrows</code> and <code>getSQLState()</code>", "<code>pytest.raises(InsufficientPrivilege)</code>"),
      ("<code>Promise.withResolvers&lt;undefined&gt;()</code> twice: \"answered\" and \"deliver\"", "two <code>CountDownLatch</code>es", "two <code>asyncio.Event</code>s")]),
  case("The dev-header test had to spawn the real entry point.",
       "<p>The first version passed <code>chooseIdentity(\"production\")</code> to <code>startServer</code> and asserted 401. It proved the strategy, not the wiring: <code>main.ts</code> could have ignored <code>NODE_ENV</code> entirely and the test would stay green. Spawning <code>main.ts</code> with a clean environment is slower (a process per case) and is the only test that would go red if someone \"simplified\" the boot.</p>"),
  case("A mocked timing test would prove nothing.",
       "<p>Replacing scrypt with a stub that sleeps would test the stub. The unit test pays for ten real derivations (a second or so) because the claim is about the real hash's cost; the drill's version stubs it, because there the claim is about the <em>shape</em> of the code, and the comment says so.</p>"),
  note("<strong>Honest status, repeated here because it matters:</strong> the unit tests (<code>password.test</code>, <code>auth.test</code> against the in-memory db, <code>identity.test</code>, the route table in <code>app.test</code>, the viewer's refusal in <code>room.test</code>, the contracts, <code>audit.test</code> in the web app, <code>config.test</code>) ran green on every commit. The integration suites (<code>auth.int</code> including the spawned entry point, <code>service-credential.int</code>, <code>rbac.int</code>, <code>role-change.int</code> including the token race and the sweep, the api's <code>audit.int</code>, the db package's <code>audit.int</code> and <code>app-role.int</code>) and the four e2e specs (<code>sign-in</code>, <code>viewer-rejected</code>, <code>share-and-revoke</code>, <code>audit-view</code>) are written, reviewed and committed, and passed in the clean-clone gate at <code>6700e74</code> on 2026-10-02. Section 8 is the same by hand."))

section("demo", "8 · By hand: sign up, demote, revoke, and try to edit the trail",
  "<p>The exact commands and what each should show. The api is on host port 3000, the sync node on 3001, the web app on 5173; the Postgres owner role is <code>noon</code> and the app's role <code>noon_app</code>. Sign in and out from the web app happens on the home page, with no <code>?user=</code> in the address; the dev header still works in this development stack, which is what lets one terminal act as several people.</p>",
  shell("0 · Bring the stack up and sign up as yourself, with a cookie jar",
        "./init.sh                                    # migrate runs 0015 (credentials, auth_sessions), 0016 (document_shares), 0017 (audit_log)\n"
        "open http://localhost:5173/                  # the sign-in form; Sign up, then New document; note ?doc=&lt;id&gt;\n"
        "curl -si -c jar -H 'content-type: application/json' -d '{\"email\":\"cli@example.com\",\"name\":\"Cli\",\"password\":\"correct horse battery\"}' localhost:3000/auth/signup\n"
        "                                             # 201; Set-Cookie: noon_session=&lt;43 chars&gt;; Max-Age=604800; Path=/; HttpOnly; SameSite=Strict (no Secure: development)\n"
        "curl -s -b jar localhost:3000/auth/me        # {\"user\":{...\"email\":\"cli@example.com\"}}\n"
        "curl -s localhost:3000/auth/me               # {\"user\":null}, and 200: nobody is not an error\n"
        "curl -s -H 'x-dev-user: cli@example.com' localhost:3000/orgs   # in development the header still works; try NODE_ENV=production and it is 401"),
  shell("1 · What Postgres keeps, and what an unknown email costs (F23)",
        "docker compose exec -T postgres psql -U noon -d noon -c \"select password_hash from credentials\"          # scrypt$32768$8$1$&lt;salt&gt;$&lt;key&gt;\n"
        "docker compose exec -T postgres psql -U noon -d noon -c \"select encode(token_hash, 'hex'), expires_at from auth_sessions\"   # a SHA-256, not the cookie\n"
        "time curl -s -H 'content-type: application/json' -d '{\"email\":\"nobody@example.com\",\"password\":\"x\"}' localhost:3000/auth/signin\n"
        "time curl -s -H 'content-type: application/json' -d '{\"email\":\"cli@example.com\",\"password\":\"wrong\"}' localhost:3000/auth/signin\n"
        "                                             # both {\"error\":\"invalid_credentials\"}, both about the same time: one scrypt each\n"
        "curl -si -b jar -X POST localhost:3000/auth/signout    # 204; Set-Cookie: noon_session=; Max-Age=0\n"
        "curl -s -b jar localhost:3000/orgs           # {\"error\":\"unauthenticated\"}: the row is gone, the copy in the jar is dead"),
  shell("2 · Roles, live (F24)",
        "curl -s -c jar -H 'content-type: application/json' -d '{\"email\":\"cli@example.com\",\"password\":\"correct horse battery\"}' localhost:3000/auth/signin >/dev/null\n"
        "ORG=$(curl -s -b jar localhost:3000/orgs | jq -r '.items[0].id')      # the org New document made for you (or create one: POST /orgs)\n"
        "curl -s -H 'x-dev-user: viewer@example.com' localhost:3000/auth/me >/dev/null     # the header creates them (development only)\n"
        "curl -s -b jar -X PUT -H 'content-type: application/json' -d '{\"email\":\"viewer@example.com\",\"role\":\"viewer\"}' localhost:3000/orgs/$ORG/members\n"
        "open 'http://localhost:5173/?user=viewer@example.com&doc=&lt;id&gt;'     # live; your edits appear; Add Card there: \"You can view this document but not edit it.\"\n"
        "docker compose exec -T redis redis-cli --no-auth-warning SUBSCRIBE access          # in another terminal: the hint, {\"orgId\":...,\"userId\":...}, on each change\n"
        "curl -s -b jar -X PUT -H 'content-type: application/json' -d '{\"email\":\"viewer@example.com\",\"role\":\"editor\"}' localhost:3000/orgs/$ORG/members\n"
        "                                             # the SUBSCRIBE prints one message; within 10 s, without a reload, the viewer's Add Card lands\n"
        "curl -s -b jar -X PUT -H 'content-type: application/json' -d '{\"email\":\"cli@example.com\",\"role\":\"viewer\"}' localhost:3000/orgs/$ORG/members   # {\"error\":\"last_owner\"}, 409"),
  shell("3 · Share, mint a token, revoke, try every way back (F25)",
        "curl -s -H 'x-dev-user: guest@example.com' localhost:3000/auth/me >/dev/null\n"
        "curl -s -b jar -X PUT -H 'content-type: application/json' -d '{\"email\":\"guest@example.com\",\"role\":\"editor\"}' localhost:3000/documents/&lt;id&gt;/shares   # {\"userId\":\"&lt;guest&gt;\",...}\n"
        "open 'http://localhost:5173/?user=guest@example.com&doc=&lt;id&gt;'      # live, editing; GET /orgs/$ORG as the guest is still 404: a share is not membership\n"
        "TOKEN=$(curl -s -X POST -H 'x-dev-user: guest@example.com' localhost:3000/documents/&lt;id&gt;/session | jq -r .token)   # minted BEFORE the revoke; good for 60 s\n"
        "curl -si -b jar -X DELETE localhost:3000/documents/&lt;id&gt;/shares/&lt;guest&gt;   # 204; the SUBSCRIBE prints the hint\n"
        "                                             # within 10 s the guest's tab shows \"This document cannot be opened\" and its status line is gone: 4404, no reconnect\n"
        "curl -si -X POST -H 'x-dev-user: guest@example.com' localhost:3000/documents/&lt;id&gt;/session    # 404\n"
        "curl -si -H 'connection: upgrade' -H 'upgrade: websocket' -H 'sec-websocket-version: 13' -H 'sec-websocket-key: dGhlIHNhbXBsZSBub25jZQ==' \\\n"
        "  -H \"sec-websocket-protocol: noon.v1, $TOKEN\" localhost:3001/documents/&lt;id&gt;       # HTTP/1.1 401: read before the upgrade, whatever the signature says"),
  shell("4 · The trail, and trying to change it (F26)",
        "curl -s -b jar localhost:3000/orgs/$ORG/audit | jq '.items[] | [.at, .actor.email, .action, .detail]'   # newest first: share_revoked, share_granted, role_changed x2, signed_in...\n"
        "open 'http://localhost:5173/?audit='$ORG     # or Home, then \"Audit trail of ...\"; the instruction of a run shows as text, markup and all\n"
        "curl -si -b jar -X DELETE localhost:3000/orgs/$ORG/audit           # 404: no such route\n"
        "docker compose exec -T -e PGPASSWORD=\"$(grep '^APP_DB_PASSWORD=' .env | cut -d= -f2-)\" postgres psql -U noon_app -d noon -c \"update audit_log set action = 'signed_in'\"\n"
        "                                             # ERROR:  permission denied for table audit_log (42501)\n"
        "docker compose exec -T postgres psql -U noon -d noon -c \"delete from audit_log\"       # the OWNER: ERROR:  audit_log is append-only: DELETE refused\n"
        "docker compose exec -T postgres psql -U noon -d noon -c \"select has_table_privilege('noon_app', 'audit_log', 'update')\"   # f"),
  shell("5 · Then the checks that prove it without hands",
        "pnpm exec vitest run apps/api/src/password.test.ts apps/api/src/auth.test.ts apps/api/src/identity.test.ts apps/api/src/app.test.ts apps/web/src/audit.test.ts   # the pure halves\n"
        "pnpm exec vitest run --config vitest.integration.config.ts apps/api/src/auth.int.test.ts apps/worker/src/service-credential.int.test.ts apps/api/src/rbac.int.test.ts \\\n"
        "  apps/sync/src/role-change.int.test.ts apps/api/src/audit.int.test.ts packages/db/src/audit.int.test.ts packages/db/src/app-role.int.test.ts\n"
        "pnpm exec playwright test e2e/sign-in.spec.ts e2e/viewer-rejected.spec.ts e2e/share-and-revoke.spec.ts e2e/audit-view.spec.ts\n"
        "make check                                   # the whole gate, as the pre-commit hook runs it"),
  note("<strong>What to do when a step does not match this page:</strong> the page was cut from the code at commit <code>" + commit + "</code>, and the code is right until a test says otherwise. A step that fails is a finding: write it as <em>sequence → false belief → consequence → smallest fix</em> (SPEC §4a's form) and file it against the bead that owns the code."))

section("limits", "9 · What the type system could not see, epic 8 edition",
  "<p>Everything below compiled under <code>strict</code>, passed the linter and the first tests, or was rejected at design time by asking what the types could not ask.</p>",
  vs([("a fast hash for passwords", "a hash is a hash", "scrypt: slow and memory-hard, parameters in the string"),
      ("an unknown email answered without hashing", "two branches look alike", "verify against a dummy hash; <code>found &amp;&amp; matches</code>"),
      ("the first miss cost two hashes", "lazy initialisation looks free", "the dummy warmed in <code>buildApp</code>"),
      ("a row asking for <code>N = 2^40</code>", "a number is a number", "a ceiling on the parameters; scrypt's refusal is a no"),
      ("<code>é</code> as one code point and as two", "two equal-looking strings", "<code>NFKC</code> before hashing"),
      ("a sign-in validated like a sign-up", "one body schema is simpler", "<code>SignInBody</code> keeps only the caps"),
      ("the session token stored as itself", "a string is a string", "its SHA-256, as <code>bytea</code>"),
      ("a cookie a script could read", "a cookie is a cookie", "<code>HttpOnly</code>"),
      ("a planted cookie becoming a session", "same name, same shape", "a new token on every sign-in"),
      ("a sliding expiry writing on every read", "an <code>UPDATE</code> looked harmless", "fixed at sign-in; identity stays a pure read"),
      ("a stateless token for the browser", "no table looked simpler", "a row you can delete"),
      ("<code>POST /session</code> with no CSRF defence", "no body, so no JSON check", "<code>SameSite=Strict</code>"),
      ("an image promoted with <code>NODE_ENV=test</code> accepting the header", "\"not production\" reads as \"safe\"", "only the literal <code>development</code>"),
      ("a name with a right-to-left override", "a string", "<code>DisplayName</code> refuses <code>\\p{Cf}</code>"),
      ("a route without a guard", "a handler compiles without one", "the route table test over <code>app.routes</code>"),
      ("404 to a member", "\"not found\" felt safer", "403 for members, 404 for strangers"),
      ("two owners demoting each other", "READ COMMITTED shows each an owner", "an advisory lock per org"),
      ("an editor promoting themselves", "PUT members was an org route", "<code>need(\"owner\")</code>"),
      ("the role in the token", "a claim is a claim", "read from Postgres at every join"),
      ("<code>mayEdit</code> checked when an op arrives", "queued ops had passed", "checked at the op's turn"),
      ("a forged pub/sub message granting a role", "a message is data", "a hint only: the node re-reads"),
      ("a missed announcement", "pub/sub keeps nothing", "<code>\"all\"</code> on ready, and a 30 s sweep"),
      ("an older role read overwriting a newer", "two awaits, either order", "<code>asked</code>/<code>applied</code> numbering"),
      ("a token minted before the revoke opening a socket", "a valid signature", "the row read before the upgrade: 401"),
      ("a revoke between the read and the registration", "the registry did not have the socket yet", "read again after registering"),
      ("a share that made a member", "a flag on the membership row", "a table of its own, never owner"),
      ("the audit row after the action", "two awaits look sequential", "one statement (a CTE) or one transaction"),
      ("a trail cascading away with its org", "referential integrity", "no foreign keys; the email copied in"),
      ("<code>set null</code> on a user delete", "looked harmless", "it is an <code>UPDATE</code>; no foreign key"),
      ("the app role able to <code>UPDATE</code> the trail", "a blanket grant, default privileges", "revoked on every provisioning, plus a trigger"),
      ("a sign-in recorded once, globally", "it belongs to a person", "one row per org"),
      ("an instruction rendered as markup", "a string", "text nodes only; the e2e plants <code>onerror</code>"),
      ("a new <code>AuditAction</code> without a sentence", "a <code>switch</code> with a default", "a <code>Record</code> over the enum"),
      ("the same role set again recorded as a change", "an upsert is an upsert", "compare <code>found.role</code> first")], head=("What went wrong, or would have", "Why", "Fix")),
  note("<strong>The pattern, extended once more:</strong> lesson 7 said types cannot see time or which process is speaking. Epic 8 adds the two that identity turns on: types cannot see <em>who is asking</em> (a stranger's request and a member's are the same TypeScript) and cannot see <em>what a value costs to compute</em> (a fast hash and a slow one have the same signature; a branch that skips the hash returns the same type). Both were answered as before: put the truth in one place (the membership row, the session row, the audit table), read it at the moment of asking, make the cost the same on every path, and write a test that provokes the exact case: the timing, the race, the forgotten guard, the privilege."))

toc = "".join(f'<li><a href="#{sid}">{title}</a></li>' for sid, title, _ in S)
sections = "".join(f'<section id="{sid}"><h2>{title}</h2>{body}</section>' for sid, title, body in S)
style = re.search(r"<style>.*?</style>", (root / "docs/handbook/lesson-0.template.html").read_text(), re.S).group(0)
page = (pathlib.Path(__file__).parent / "lesson-8.template.html").read_text()
page = page.replace("{{STYLE}}", style).replace("{{TOC}}", toc).replace("{{SECTIONS}}", sections).replace("{{COMMIT}}", commit)
(out / "lesson-8.html").write_text(page)
print("built", len(page), "bytes at", commit, "with", page.count('<p class="label">From'), "code blocks")
