"""Builds docs/handbook/lesson-10.html. Every code block is cut from the real repo by anchor text,
so the page cannot show code that does not exist; a missing anchor fails the build."""
import html, os, pathlib, re, subprocess
here = pathlib.Path(__file__).resolve()
root = pathlib.Path(os.environ.get("NOON_ROOT") or (here.parents[2] if (here.parents[2] / "SPEC.md").exists() else pathlib.Path.cwd()))
out = pathlib.Path(os.environ.get("NOON_OUT") or root / "docs/handbook")
commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=root, capture_output=True, text=True).stdout.strip()

def cut(path, start, end=None, include_end=False):
    src = (root / path).read_text()
    i = src.index(start)
    j = len(src) if end is None else src.index(end, i + len(start)) + (len(end) if include_end else 0)
    body = src[i:j].rstrip()
    return (f'<p class="label">From <span class="mono">{path}</span></p>'
            f'<div class="scroll"><pre><code>{html.escape(body)}</code></pre></div>')

def shell(title, body):
    return f'<p class="label">{title}</p><div class="scroll"><pre class="out"><code>{body}</code></pre></div>'

def vs(rows, head=("TypeScript + React (this repo)", "Java (Swing, JavaFX)", "Python (Qt, Tk)")):
    body = "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows)
    return f'<div class="scroll"><table><tr>{"".join(f"<th>{h}</th>" for h in head)}</tr>{body}</table></div>'

def case(title, body): return f'<div class="break"><p class="label">Case study · found by review, by a learning test, or by a test that was written to refute a claim</p><p><strong>{title}</strong></p>{body}</div>'
def note(body): return f'<p class="note">{body}</p>'
m = lambda s: f"<span class='mono'>{s}</span>"

S = []
def section(sid, title, *parts): S.append((sid, title, "".join(parts)))

section("map", "The map: eight beads, one write path, and where each gesture becomes one op",
  "<p>Until this epic the frontend only drove the backend: a toolbar of \"Add X\" buttons, a list of \"Select X\" buttons, a form per node. Epic 10 makes it an editor that feels like Figma (owner decision, 2026-09-30) and the whole point of the chapter is what did <em>not</em> change while it did: the four ops (keystone 3), the one write path through <code>packages/peer-client</code> (keystone 2), the replica's two documents, the room's verdict. Every pane you will read about is a <em>view</em> over the replica, and every gesture, however much geometry it takes to read, ends as exactly one call to <code>peer.submit(op)</code>.</p>",
  vs([("1", m("apps/web/src/tokens.css"), m("apps/web/src/useTheme.ts"), "every colour, size and space as a custom property; the dark block keyed on <code>html[data-theme]</code>, set before the first paint; <code>theme.test</code> recomputes WCAG AA for every text/surface pair from the CSS itself; <code>Shell.tsx</code> owns only where things go"),
      ("2", m("apps/web/src/viewport.ts"), m("apps/web/src/Surface.tsx"), "the sample app's REAL components inside an <code>inert</code> frame on an infinite sheet; screen = world × zoom + offset as one <code>transform</code> on one layer; outlines measured after render into world coordinates; the deepest box wins the hit-test (<code>selection.ts</code>)"),
      ("3", m("apps/web/src/layer-moves.ts"), m("apps/web/src/LayersPanel.tsx"), "an ARIA tree whose selection is the canvas's, both ways; a drop or Alt+arrow becomes ONE <code>move_node</code> whose index is counted after the node is taken out; refuses only the structurally impossible, never predicts <code>validate()</code>"),
      ("4", m("apps/web/src/controls.ts"), m("apps/web/src/Inspector.tsx"), "the manifest rendered: one control per prop KIND, layout props by name and kind, defaults as placeholders, Reset as <code>set_prop null</code>; a typed value is one op on blur or Enter; a refusal repeated beside its control by <code>aria-describedby</code>; <code>spaces.ts</code> shades gap and padding on the canvas"),
      ("5", m("apps/web/src/library-adds.ts"), m("apps/web/src/LibraryPanel.tsx"), "a listbox of tiles, each a small real render; a drag onto a row or the canvas, Enter or a click all end in a Slot and one <code>add_node</code>; the id minted once in <code>Canvas.tsx</code>; a refused add sends the selection back to the page"),
      ("6", m("apps/web/src/cursors.ts"), m("packages/peer-client/src/peer.ts"), "cursors ride the wire as world points bounded at ±1e6 and are drawn inside <code>.world</code>; the AI has no pointer, so <code>onOp</code> (told after each ordered op is applied) anchors its mark to the node its last op touched; a still cursor fades by the clock"),
      ("7", m("apps/web/src/shortcuts.ts"), m("apps/web/src/Preview.tsx"), "ONE registry drives every keydown handler and the <code>?</code> sheet; a test refuses two rows one keydown could mean; the preview in a device frame of the device's real CSS width scaled by one transform; a native <code>&lt;dialog&gt;</code> for the sheet"),
      ("8", m("apps/web/src/OrgView.tsx"), m("apps/web/src/ShareDialog.tsx"), "two read routes in the E8.2 role table; the session carries a <code>role</code> beside the token (a hint for the screen, never authority); the members list and the shares are NOT optimistic: every row is the api's answer, and a 403 re-reads the world")], head=("Step", "Pure module", "Component", "What it does")),
  "<p>Four ideas carry the epic. <strong>The UI is a function of the replica</strong> (section 1): no pane holds a copy of the document; React re-renders every pane from <code>peer.doc</code> when the replica's <code>revision</code> moves, which is why another person's move appears in the tree, on the canvas and in the inspector at once, and why the selection is derived (a node someone removed is simply the page again). <strong>Geometry in, one op out</strong> (sections 3 to 6): a pointer's height on a row, a point on an infinite sheet, a blur on a number field are read by pure modules into a Drop, a Slot or a value, and each becomes one of the four ops through the one <code>submit</code>; nothing in the editor knows a second way to write. <strong>Refuse only the impossible</strong> (section 4): the tree, the library and the inspector build every op the document's shape allows and let the replica and the room say no, so <code>validate()</code> has one copy. <strong>The screen decides nothing</strong> (section 9): a role in the session shows or hides a button; the api and the room read the row for themselves on every request and every op.</p>",
  note("<strong>What this chapter assumes:</strong> lesson 2's peer-client (the replica's <code>confirmed</code> and <code>optimistic</code>, <code>submit</code>, the room's verdict as <code>onRejected</code>) and lesson 8's roles. What it teaches from zero: React itself, CSS custom properties, coordinate transforms, the WAI-ARIA tree, listbox and dialog patterns. If you have written a Swing, JavaFX or Qt application, section 1 and section 10 are where your instincts will be wrong in useful ways."))

section("react", "1 · React from zero: a component is a function of its inputs, and the editor is a function of the replica",
  "<p>You know the desktop model: a widget is an object with state, an event mutates the object (<code>label.setText(...)</code>, <code>tree.getModel().insertNodeInto(...)</code>), and the toolkit repaints what changed. React inverts it. A <em>component</em> is a function from props (its inputs) to a description of what should be on the screen (JSX, which compiles to calls that build a tree of plain objects); when an input changes, React calls the function again and <em>diffs</em> the new description against the last one, touching only the DOM nodes that differ. You never say \"update this label\"; you say \"given this document, here is the whole inspector\", and React works out that one <code>&lt;input value&gt;</code> changed. State that belongs to a component (a draft in a text field, whether a row is collapsed) lives in a <em>hook</em>, <code>useState</code>, whose setter schedules a re-render; state that lives <em>outside</em> React (a WebSocket, the OS theme, a clock) gets in through <code>useSyncExternalStore</code>, which is the whole trick of this app.</p>",
  cut("apps/web/src/usePeer.ts", "function openStore(", "const NOTHING"),
  "<p>Read <code>openStore</code> as an adapter. The peer changes on its own (a message arrives, a reconnect happens); React cannot see that. <code>useSyncExternalStore(subscribe, getSnapshot)</code> asks for two things: how to be told something changed (<code>subscribe</code> registers a listener; the peer's <code>onChange</code> and <code>onStatus</code> call every listener) and how to read a value that React compares with <code>Object.is</code> to decide whether to re-render (<code>snapshot</code>). The document is edited <em>in place</em> by the replica, so <code>peer.doc</code> is the same object before and after an op and would never look different; the snapshot is therefore a string of the numbers that do move: <code>revision</code>, <code>pendingCount</code>, <code>status</code>, <code>readOnly</code>, <code>presenceRevision</code>. A new string, a re-render of <code>Canvas</code>; the same string, nothing.</p>",
  cut("packages/peer-client/src/replica.ts", " * It holds TWO documents:", "export function createReplica"),
  "<p>That is why the editor can be a view: the replica already holds what the person should see (<code>optimistic</code>: what the server said plus every op of ours it has not answered yet, an invariant tested as a property in lesson 2), and <code>revision</code> is bumped whenever it changes. Every pane renders from <code>peer.doc</code>; none keeps a copy; so a move made in the tree is on the canvas in the same render, and a move made by someone else, arriving as a message, is in the tree, on the canvas and in the inspector in the render the message causes.</p>",
  cut("apps/web/src/usePeer.ts", "export function usePeer(", None),
  "<p>Two rules of the hook are load-bearing. <strong>Side effects go in <code>useEffect</code>, never in the render body.</strong> A render is a pure computation React may run and throw away (StrictMode does this on purpose in development, twice, to catch exactly this), so opening a WebSocket during render would open two; an effect runs after the commit, once per change of its dependencies (<code>[documentId]</code>), and returns a cleanup that closes the peer when the document changes or the component unmounts. <strong>A callback that may change every render is held in a <code>useRef</code></strong> (<code>latestOnOp</code>): a ref is a box React does not watch, so <code>Canvas</code> may pass a fresh arrow function each render without the effect re-running and the peer being reopened. The Java analogue is a listener registered once in <code>addNotify</code> and removed in <code>removeNotify</code>; the Python analogue is a signal connected in <code>__init__</code> and disconnected in <code>closeEvent</code>; the difference is that React will call your render function far more often than a toolkit calls <code>paint</code>, and it must be safe to.</p>",
  cut("apps/web/src/Canvas.tsx", "  // DERIVED, not stored", "  const layers = layersOf(doc);"),
  "<p><strong>Derive, do not store.</strong> The canvas keeps only <em>which id the person wanted</em> (<code>wanted</code>); the node shown is <code>doc.nodes[wanted] ?? root</code>, computed every render. When someone else removes the selected node, no event handler has to notice: the next render finds no such node and the selection is the page, and one live sentence says so. Every derived value in this file (the labels, which nodes are containers, who has what selected, the AI's anchor) is recomputed from the document on each render, which sounds wasteful to a Swing programmer and is the reason the panes can never disagree: there is no second copy to fall out of date. The <code>ponytail</code> in <code>Surface.tsx</code> says where this stops paying: every node re-rendered on every change is fine at 64 levels and small documents; <code>memo</code> per node keyed on the node object is the upgrade.</p>",
  cut("apps/web/src/Canvas.tsx", "  const submit = (op: Op): boolean => {", "  // The selected node's refused prop edits"),
  "<p>And here is the one write path as the editor sees it. Every pane receives this <code>submit</code> as a prop; the replica's verdict comes back synchronously (<code>result.ok</code> false: a notice at once, and for an add, the selection stays on the page); the room's verdict comes back later through <code>onRejected</code>, which <code>usePeer</code> turns into the same kind of notice. There is no other function in <code>apps/web</code> that can change the document.</p>",
  cut("apps/web/src/Surface.tsx", "  // A ref, not state: the drag's last point", "  const root = doc.nodes[doc.rootId];"),
  "<p>Last, <strong>state versus ref</strong>, the distinction a React beginner gets wrong most. <code>useState</code> is for values the screen renders from: change it and React re-renders. <code>useRef</code> is for values that change without anything on the screen depending on them: the last pointer position during a pan, a press that may or may not become a drag, \"focus the tab stop once it has rendered\". A drag's origin put in state would re-render the whole canvas sixty times a second for nothing; in a ref it costs a property write.</p>",
  vs([("<code>function Inspector(props) { return &lt;aside&gt;...&lt;/aside&gt;; }</code>: a function from inputs to a description", "<code>class Inspector extends JPanel</code> with fields and setters", "<code>class Inspector(QWidget)</code> with attributes and slots"),
      ("<code>useState</code>: change it and the function runs again", "<code>setText</code> then <code>repaint()</code>", "<code>setText</code>; Qt repaints"),
      ("<code>useSyncExternalStore(subscribe, snapshot)</code>", "a <code>PropertyChangeListener</code> that calls <code>SwingUtilities.invokeLater(repaint)</code>", "a signal connected to <code>update()</code>"),
      ("<code>useEffect(() =&gt; { open(); return close; }, [documentId])</code>", "<code>addNotify</code> / <code>removeNotify</code>", "<code>showEvent</code> / <code>closeEvent</code>"),
      ("<code>useRef</code>: a box React does not watch", "a plain field", "a plain attribute"),
      ("re-render everything, diff the DOM", "repaint the damaged region", "repaint the damaged region")]),
  case("StrictMode rendered twice and would have opened two peers.",
       "<p>An early version opened the peer in <code>useMemo</code> \"so it is created once\". In development React runs the render twice and keeps one result, so two WebSockets opened and one leaked. Opening in <code>useEffect</code> with a cleanup fixed it and is the rule now (lesson 2's <code>e2-5a</code> memory). The instinct from Java (\"construct it in the constructor\") is exactly wrong here: a render is not a constructor, it is a <code>paint</code>.</p>"))

section("tokens", "2 · Tokens, theming and contrast as a test",
  "<p>A CSS <em>custom property</em> (<code>--accent: #1d4ed8</code>) is a variable that lives in the cascade: it is set on an element, inherited by its descendants, and read anywhere below with <code>var(--accent)</code>. Unlike a Sass variable, which is substituted at build time, it is resolved at <em>style time</em>, per element, so changing it on <code>&lt;html&gt;</code> recolours the page without touching a rule, and setting it again on a subtree recolours only that subtree. <code>tokens.css</code> declares every colour, size, space and radius the app uses as a custom property and nothing else declares one; <code>app.css</code> only refers to them.</p>",
  cut("apps/web/src/tokens.css", "  /* the ONE accent */", "  /* notices */"),
  cut("apps/web/src/tokens.css", ':root[data-theme="dark"] {', "  --fg: #e6e9ee;"),
  "<p>Two decisions here. <strong>One accent.</strong> Selection, focus ring, links and the primary button share <code>--accent</code>; Figma's discipline, and it makes \"what is interactive\" one colour a person learns once. <strong>The dark block keys on an attribute, not a media query.</strong> <code>html[data-theme]</code> carries the <em>resolved</em> theme; a media query would need a second copy of every token for the \"OS dark but the person chose light\" case, and would flash the OS theme before script ran. <code>color-scheme</code> tells the browser which palette its own form controls and scrollbars should use, so a <code>&lt;select&gt;</code> in the dark theme is dark too.</p>",
  cut("apps/web/src/theme.ts", "export const resolveTheme", None),
  cut("apps/web/src/useTheme.ts", "export function useTheme()", None),
  "<p><code>theme.ts</code> is pure: a remembered preference and the OS's answer come in, a theme comes out, and <code>toggled</code> remembers the <em>opposite of what is shown</em> as an explicit choice, so a person who pressed the toggle on a dark OS gets light and keeps light when the OS flips. <code>useTheme</code> binds it: the OS preference is an external store (a <code>matchMedia</code> change is not a render), read through <code>useSyncExternalStore</code> exactly as the peer is; the choice is <code>useState</code> initialised from <code>localStorage</code>, read defensively (a private window may refuse it); and an effect writes the resolved theme onto <code>&lt;html&gt;</code>. <code>main.tsx</code> calls <code>applyStoredTheme()</code> before the first render, so the first paint is already right: no flash.</p>",
  cut("apps/web/src/theme.test.ts", "const light = tokensOf", 'test("the dark block redefines'),
  "<p>The contrast test is the part to remember for an interview: <em>accessibility as a unit test</em>. It parses <code>tokens.css</code> itself (not a copy of the values), builds the dark palette as the light one overridden by the dark block (what the cascade does), and recomputes WCAG 2.x relative luminance and contrast (<code>colour.ts</code>, the same function that checks the presence palette) for every text/surface pair the UI actually uses, at 4.5:1 for text and 3:1 for borders and rings. A token edit that breaks contrast is a red test, not a review comment. The last test in the file asks that the dark block redefine every colour the light block declares, because a colour left out would inherit its light value and show light on dark.</p>",
  cut("apps/web/src/app.css", "/* The editor's own control rules", ".node { display: contents; }"),
  "<p>And the cascade's second use: <em>the frame is the sample app's page, not the editor's</em>. The design system's own tokens (<code>--ds-*</code>) apply inside the frame and the library tiles; so that the editor's own <code>input</code> and <code>button</code> rules, which reach into the frame too, do not paint the sample app's field with the dark theme's surface, the editor's tokens are <em>redefined</em> on <code>.page-frame</code> to resolve to the design system's palette. One rule, and a field on the canvas is the sample app's field in both themes (E10.6's hand-off; the cursors spec asserts the Input is white in dark).</p>",
  vs([("<code>--accent</code> on <code>:root</code>, <code>var(--accent)</code> below, resolved per element at style time", "<code>UIManager.put(\"Panel.background\", ...)</code> and a Look-and-Feel", "a Qt stylesheet with <code>palette(...)</code>; Tk's <code>option_add</code>"),
      ("<code>:root[data-theme=\"dark\"] { --bg: ... }</code>: one attribute flips everything", "swap the LookAndFeel and <code>updateComponentTreeUI</code>", "<code>app.setPalette(dark)</code>"),
      ("<code>color-scheme: dark</code> for the browser's own controls", "n/a: the L&amp;F draws them", "the palette covers them"),
      ("contrast recomputed in a unit test from the CSS", "a manual audit", "a manual audit")]),
  case("The presence palette was checked on white, not on a dark surface.",
       "<p>E2.6 derived a colour per peer and checked it read as text on white. In the dark theme those names sat on a dark surface at about 3:1. The fix was not a second palette: the colour became an avatar's <em>fill</em> with white initials (the palette is checked to carry white text, <code>colour.test</code>), and the name beside it is plain <code>--fg</code>. A colour that has to work as text on two backgrounds is a colour that has to be tested twice; a colour that is only ever a background for white text is tested once.</p>"))

section("coords", "3 · Coordinate systems: one transform, outlines in world space, and the deepest box wins",
  "<p>An infinite canvas has two coordinate systems. <em>World</em>: the page frame's own pixels at 100 %, where the Button is at (240, 100) for ever. <em>Screen</em>: where a world point is drawn inside the canvas element right now, given the zoom and the pan. One convention everywhere, and the whole of <code>viewport.ts</code> follows from it:</p>",
  cut("apps/web/src/viewport.ts", "export const toWorld", "export const zoomStep"),
  "<p><code>zoomAt</code> is the function a beginner gets wrong: zooming about the pointer means the world point under the pointer must stay under it, so take that point (<code>toWorld</code> at the old zoom), then choose the new offset so <code>toScreen</code> of it at the new zoom is the anchor again. The test asserts exactly this for four zooms, and that a point elsewhere on the screen moves away from the anchor by the right factor. Everything is pure, clamped to 10–400 %, and tested as arithmetic; <code>Surface</code> only wires events to it.</p>",
  cut("apps/web/src/viewport.ts", "export function fit(", "export const percent"),
  cut("apps/web/src/Surface.tsx", '        <div className="world"', '          <div ref={frame}'),
  cut("apps/web/src/app.css", "/* ONE transform for everything", ".page-frame { box-sizing"),
  "<p>The frame and the editor layer (outlines, cursors, shades, drop lines) both live in <code>.world</code>, which carries the <em>one</em> <code>translate(x, y) scale(zoom)</code>. Zooming and panning therefore change one style attribute; nothing is re-laid out, nothing is re-measured, and the GPU composites the layer. The price is that strokes and labels would scale with the frame, so they divide by <code>--zoom</code> in CSS:</p>",
  cut("apps/web/src/app.css", "/* A box-shadow spread, not a border", ".outline-peer {"),
  "<p>A 2 px stroke at 300 % is <code>calc(2px / 3)</code> in world units, which is 2 px on the screen. The stroke is a <code>box-shadow</code> spread and not a <code>border</code> because Chrome snaps border widths to whole device pixels, so a border thickened in steps as the zoom rose; a shadow spread stays fractional. The labels do the same for their padding, radius and font size.</p>",
  cut("apps/web/src/Surface.tsx", "  // The outlines follow the components' real boxes", "    const wrapperOf = (id: string)"),
  "<p>The outlines are <em>measured</em>, not computed: the real components lay themselves out (a Stack's flex row decides where its Button is), so after each render a <code>useLayoutEffect</code> reads every selected, hovered and peer-selected node's <code>getBoundingClientRect()</code> and converts it to world coordinates by <code>toWorld</code> and a division by the zoom. <code>useLayoutEffect</code> rather than <code>useEffect</code> because it runs synchronously after the DOM is updated and before the browser paints, so the outline never lags the frame by a frame. Once in world coordinates the outline zooms and pans by CSS alone: the measuring pass runs after a <em>render</em>, never after a wheel event. The <code>setOutlines((current) =&gt; same ? current : next)</code> shape matters: an effect that sets state on every run would render again for ever; returning the same object when nothing moved ends the loop.</p>",
  cut("apps/web/src/Surface.tsx", "  // A native listener, not onWheel", "  // On the canvas `data-component` names a NODE"),
  "<p>One place React's abstraction is not enough: the wheel. Ctrl+wheel is the browser's own page zoom and a plain wheel scrolls the pane, so the handler must call <code>preventDefault()</code>, which is only allowed on a listener registered with <code>{ passive: false }</code>; React does not promise that for <code>onWheel</code>. So the listener is native, added in an effect, removed in its cleanup. Trackpad pinches arrive as many small <code>deltaY</code>s, a mouse notch as about 100; <code>wheelZoom</code> is exponential in the delta, so up-then-down lands where it started, and capped so one wild notch cannot jump the range.</p>",
  cut("apps/web/src/selection.ts", "export function hitTest", "export type Step"),
  "<p>Hit-testing does not ask the DOM which element is under the pointer (<code>elementFromPoint</code> would answer with a <code>&lt;span&gt;</code> inside the Button, or the frame), it asks the <em>document</em>: every node's box is measured, and the deepest box containing the point wins, because a child is drawn on top of its parent and is what the eye lands on; among equals the later in document order wins, which is the one painted last. Nothing under the point is the empty sheet, and the caller selects the page. Pure, so tested with plain boxes.</p>",
  cut("apps/web/src/Surface.tsx", "function NodeView(", "/** A wrapper's own element"),
  cut("apps/web/src/designSystem.ts", "export const scopeTo", "export const frameStylesheet"),
  "<p>The components are the sample app's real ones, imported straight from the seed (they are the repo's own static code, the same files the manifest was extracted from), with each node's children rendered <em>inside</em> its component, so a Stack lays out its children exactly as the running page would. The wrapper is <code>display: contents</code>: it names the node for the editor and takes no box of its own, so the flex items are the components themselves. The frame is <code>inert</code>, an HTML attribute that makes a subtree take no clicks, no focus and no screen-reader stop: the Button <em>is</em> the sample app's Button, but pressing it does nothing, and the canvas is the one focusable thing. The seed styles its page on <code>:root</code> and <code>body</code>; on the canvas the page is one frame among the editor's surfaces, so those two selectors are rewritten to the frame's class and everything else is left as written: one source of truth, the seed's own stylesheet, scoped on load. The <code>ponytail</code> is honest about the ceiling: a regex over CSS the repo owns; a customer's design system would render in a sandboxed iframe, never in the editor's origin.</p>",
  vs([("<code>transform: translate() scale()</code> on one layer; strokes divide by <code>--zoom</code>", "<code>Graphics2D.transform(AffineTransform)</code> in <code>paintComponent</code>; strokes divided by the scale by hand", "<code>QGraphicsView.setTransform</code>; <code>QPen.setCosmetic(True)</code> for a constant-width stroke"),
      ("<code>toWorld</code> / <code>toScreen</code> as two pure functions", "<code>AffineTransform.inverseTransform</code>", "<code>QGraphicsView.mapToScene</code> / <code>mapFromScene</code>"),
      ("the deepest measured box wins", "<code>Component.getComponentAt</code> (the shallowest)", "<code>QGraphicsScene.itemAt</code> (the topmost by z)"),
      ("<code>inert</code> on the frame", "a glass pane over the components", "<code>setAttribute(Qt.WA_TransparentForMouseEvents)</code>"),
      ("measure after render in <code>useLayoutEffect</code>", "<code>getBounds()</code> after <code>validate()</code>", "<code>sceneBoundingRect()</code> after layout")]),
  case("An outline drawn as a border thickened with the zoom.",
       "<p>The first outline was <code>border: 2px solid</code> divided by <code>--zoom</code>. At 250 % it was visibly thicker than at 100 %, and at 40 % it vanished: Chrome snaps border widths to whole device pixels before compositing. The e2e spec (<code>canvas-zoom-pan-select</code>) asserts a constant stroke width across zooms; the fix was a box-shadow spread, which stays fractional. A learning about the renderer, not about React, and the kind a screenshot baseline catches and a unit test cannot.</p>"))

section("layers", "4 · The layers tree: an ARIA tree whose selection is the canvas's, and a drop that is one move_node",
  "<p>The tree is the same document, rendered a second time, and the point of the section is what that costs: nothing. <code>LayersPanel</code> receives <code>doc</code>, the rows <code>Canvas.tsx</code> names (\"Stack 2\" is the second Stack in reading order), <code>selected</code> and <code>submit</code>; picking in the tree calls <code>onSelect</code>, which sets <code>wanted</code> in <code>Canvas</code>, which re-renders both the tree and the canvas with the new selection. There is no \"sync the tree to the canvas\" code because there are not two selections.</p>",
  cut("apps/web/src/LayersPanel.tsx", "            <li\n              key={row.id}", "              {/* The disclosure"),
  "<p>The WAI-ARIA Authoring Practices <em>tree</em> pattern, in its flat form: one <code>role=tree</code>, every row a <code>treeitem</code> with <code>aria-level</code>, <code>aria-setsize</code> and <code>aria-posinset</code> (so a screen reader says \"Button 1, level 3, 1 of 2\"), <code>aria-expanded</code> only on rows that have children, <code>aria-selected</code> on the one selected. The APG allows a flat list when nesting the DOM would only nest the problems, and here it makes the drop hit-test and the roving tabindex one <code>querySelector</code> each. <em>Roving tabindex</em>: exactly one row has <code>tabIndex=0</code> (the selected row, or its nearest shown ancestor when it is folded away), every other row <code>-1</code>, so Tab enters the tree once and arrows move inside it; that is the pattern for every composite widget in this epic (the tree, the library's listbox). The disclosure triangle is a <code>span</code>, not a <code>button</code>, because a control inside a <code>treeitem</code> is \"nested interactive\" and axe flags it; Left and Right are its keys.</p>",
  cut("apps/web/src/LayersPanel.tsx", "  // The tab stop: the selected row", "  const labelOf"),
  cut("apps/web/src/layer-moves.ts", "export function dropToMoveOp", "\n/**\n * What a pointer at"),
  "<p>This is the function the chapter is named for. A <code>Drop</code> (which node, over which row, before/after/into) becomes <em>one</em> <code>move_node</code>, or null when there is nowhere to go. Two details are load-bearing. <strong>The index is the node's FINAL position among its new siblings, counted after it was taken out</strong> (SPEC keystone 3): dropping <code>card</code> after <code>stack</code> in <code>[card, stack, text2]</code> means <code>[stack, card, text2]</code>, index 1, not 2, which is why the siblings are filtered before <code>indexOf</code>. Get this wrong and every downward move within a parent lands one too far; the drill in this lesson plants exactly that. <strong>It refuses only what is structurally impossible on the document it can see</strong>: the page itself, a node onto itself or into its own subtree (a cycle; <code>within</code> carries a <code>seen</code> set so a corrupt document with a cycle cannot hang the tab), a place beside the page. A container that takes no children, an index past the end, a node someone removed meanwhile: those are the replica's and the room's verdict, shown as their refusal like any other edit's, because a second copy of <code>validate()</code> here would drift.</p>",
  cut("apps/web/src/layer-moves.ts", "export function placementAt", "export type KeyMove"),
  cut("apps/web/src/LayersPanel.tsx", "  // --- the pointer: press selects", "  // --- the keyboard (WAI-ARIA APG tree"),
  "<p>The drag is <em>pointer events</em>, not HTML drag and drop. A press selects and remembers where; a press that travels 4 px becomes a drag and <em>captures</em> the pointer (<code>setPointerCapture</code>: every further event comes to the tree whatever is under the pointer, so letting go over the canvas still ends the drag cleanly); on each move the row under the pointer is found with <code>elementFromPoint</code> (here the DOM is right, because the rows are the DOM), the pointer's height on the row becomes a placement (<code>placementAt</code>: a container's middle half is \"into\"; a leaf has only a top and a bottom half, so the line always shows where the node <em>would</em> go and \"into\" is never offered), and the row wears a line or a box; <code>pointerup</code> sends the one op. HTML drag and drop was rejected because the canvas already speaks pointer events (one gesture vocabulary), it draws a ghost image to fight, and its <code>dragover</code> fires on its own clock. The <code>setDrag((was) =&gt; same ? was : next)</code> shape is the outline trick again: no render for a move that changed nothing.</p>",
  "<p>The keyboard's four moves are drops too: Alt+Up is \"before my previous sibling\", Alt+Down \"after my next\", Alt+Right \"into my previous sibling\" (the room says whether it takes children), Alt+Left \"after my parent\"; <code>keyMoveOp</code> builds the <code>Drop</code> and calls the same <code>dropToMoveOp</code>, so the pointer and the keys cannot disagree about the op. Delete sends <code>remove_node</code>, and the focus falls to the page with the selection. A live region says every move and removal in words, because a moved row is silent to a screen reader.</p>",
  vs([("<code>role=tree</code>, flat <code>treeitem</code>s with <code>aria-level</code>, roving tabindex", "<code>JTree</code> with a <code>TreeModel</code>; focus handled by the L&amp;F", "<code>QTreeView</code> over a <code>QAbstractItemModel</code>"),
      ("the tree renders <code>peer.doc</code>; no model of its own", "<code>DefaultTreeModel</code> mirrors your data and you keep them in step", "the model IS your data through <code>data()</code>/<code>index()</code>"),
      ("a drop is one <code>move_node</code> through <code>submit</code>", "<code>TransferHandler.importData</code> mutates the model", "<code>dropMimeData</code> mutates the model"),
      ("pointer events + <code>setPointerCapture</code>", "<code>DragSource</code>/<code>DropTarget</code> (AWT DnD)", "<code>QDrag.exec()</code>"),
      ("refuse only geometry; the replica and the room say the rest", "<code>canImport</code> predicts the rule", "<code>canDropMimeData</code> predicts the rule")]),
  case("A drop into a leaf was disabled in the tree, and the tree learnt a rule it did not own.",
       "<p>The first draft greyed out a Button row while a layer was dragged over it, \"so the person never sees a refusal\". Review asked where the tree learnt that a Button takes no children: from the manifest, a second reading of a rule <code>validate()</code> already applies. The bead's own text settled it: the tree refuses only what the document's shape makes impossible; everything else is built and refused by the replica in the same frame, with the same sentence a viewer, a slow room or the AI would get. The e2e spec asserts the sentence for Alt+Right into a Button rather than a colour on a row.</p>"),
  case("Selecting on focus would have moved the selection when Tab landed on the tree.",
       "<p>The APG's tree pattern lets focus and selection follow each other, and the first version selected whatever row received focus. But the tab stop is the selected row <em>or its nearest shown ancestor</em> when the selection is folded away; Tab landing on that ancestor would have changed the selection to it. Now arrows move focus and selection together (<code>select</code>), but a bare focus (Tab) changes nothing, and Space or Enter selects the focused row.</p>"))

section("inspector", "5 · The inspector is the manifest, rendered: one control per prop kind, one op per edit",
  "<p>The inspector knows no component by name. The manifest (lesson 2: extracted from the design system's source) says, for each component, which props it has, of what kind, whether required, with what default; the inspector renders <em>that</em>. So a regenerated manifest with a new prop gets its control with no code change, and <code>controls.test</code> walks the committed manifest to prove every prop has one.</p>",
  cut("apps/web/src/controls.ts", "export function controlFor", "\n/**\n * The auto-layout props"),
  "<p>Read the <code>default</code> branch twice. <code>const unknown: never = type</code> is the compiler's exhaustiveness check: <code>type</code> is a discriminated union of four kinds, and after four <code>case</code>s TypeScript narrows it to <code>never</code>; add a fifth kind to the contract and this line stops compiling until a control exists for it. The <code>throw</code> under it is the runtime's answer to a manifest from a newer extractor that this build has never heard of: a prop without a control must fail loudly, because a prop that renders as nothing is a prop nobody can edit and nobody notices. Java has this as a <code>switch</code> over a sealed interface with pattern matching (Java 21); Python has <code>assert_never</code> from <code>typing</code>.</p>",
  cut("apps/web/src/controls.ts", "const LAYOUT_PROPS", "/** A component's props in two sections"),
  "<p>The Layout section is the one thing keyed on a name, and deliberately on <em>name and kind</em>: <code>gap</code> as a number is a stepper that shades the space between children; <code>gap</code> as a string is just a string and lands in Props. A design system whose Stack calls it <code>spacing</code> gets a plain stepper and no shade, which is correct: the shade would have nothing true to show.</p>",
  cut("apps/web/src/Inspector.tsx", "function NumberField(", "/** A switch:"),
  "<p>The commit semantics are E2.5b's, kept on purpose. A <em>typed</em> value (text or number) is one <code>set_prop</code> when the person leaves the field or presses Enter, never one per keystroke: a flood of ops would meet the room's per-peer rate limit and fill the audit log with \"title = H\", \"title = He\", \"title = Hel\". The draft lives in <code>useState</code> only while the field is being edited; the document stays the source of truth, and <code>value={draft ?? prop}</code> means the field shows the document the moment the draft is committed or abandoned. A choice, a switch, an arrow step and a stepper button are each one deliberate edit, so they send at once. The <code>validity.badInput</code> line is a browser fact worth knowing: a number field reports <code>\"\"</code> both when it is empty and when it holds text it cannot read (\"12abc\"); taking the second for the first would silently delete the prop.</p>",
  cut("apps/web/src/Inspector.tsx", '    <div className="field" data-prop', "/** A titled part of the inspector"),
  "<p>One row per prop: the name as a <code>label</code> (or, for a radio group, a span the group is <code>aria-labelledby</code>, because a <code>fieldset</code> that has been given <code>role=radiogroup</code> is not reliably named by its <code>legend</code>), the control, Reset while the prop is set (sending <code>set_prop null</code>, which removes it; not offered for a required prop, which has no unset state), the default in words while it is not, and the refusal its last edit met. <code>aria-describedby</code> ties the refusal sentence to the control so a screen reader hears it when the field is focused; there is deliberately no second <code>role=alert</code> here, because the notice strip already announced it. <code>usePeer</code>'s <code>Refusal</code> remembers its <code>op</code> for exactly this: the inspector filters the refusals to the selected node's <code>set_prop</code>s, latest per key, and <code>submit</code> dismisses the old complaint about a prop before a new edit of it is sent, so a fixed value clears both.</p>",
  cut("apps/web/src/spaces.ts", "export function gapsBetween", None),
  cut("apps/web/src/Surface.tsx", "function paddingOf(", "/** Which way a container lays"),
  "<p>Shading is the inspector talking to the canvas through <code>Canvas</code>'s state: hovering <em>or focusing</em> a gap or padding control sets a <code>Hint</code>; <code>Surface</code> measures that node (the ring of computed padding inside its box, or the spaces between consecutive children's boxes; <code>spaces.ts</code> is pure geometry) in world coordinates and draws translucent outlines, so the shade zooms with the frame. Padding is read from the component's <em>computed</em> style, what the design system actually applied whether from the prop or its own default, and in the element's own px times the zoom, because <code>getBoundingClientRect</code> answers in screen px after the world's scale and <code>getComputedStyle</code> in CSS px before it.</p>",
  vs([("<code>controlFor(prop)</code>: a switch over the prop's kind, exhaustive by <code>never</code>", "a <code>PropertyEditor</code> per type, looked up by <code>PropertyEditorManager</code>", "<code>QItemDelegate.createEditor</code> by <code>QVariant</code> type"),
      ("commit on blur or Enter; one op", "<code>JFormattedTextField</code> commits on focus lost", "<code>QLineEdit.editingFinished</code>"),
      ("<code>value={draft ?? prop}</code>: the document is the source, the draft a moment", "the text field IS the state until you read it back", "the widget IS the state"),
      ("<code>set_prop null</code> removes a prop; a required one has no Reset", "a \"restore default\" per editor", "the same"),
      ("<code>aria-describedby</code> the refusal", "a tooltip on the field", "<code>setToolTip</code>")]),
  case("A radio group's legend did not name it once it had a role.",
       "<p>The segmented control is a <code>fieldset</code> with <code>role=radiogroup</code> and had a <code>legend</code> for its name. axe reported the group unnamed in one engine: a <code>fieldset</code> given an explicit role is no longer a fieldset to the accessibility tree, and its legend no longer counts. The name is now a visible span the group is <code>aria-labelledby</code>. The same file carries a second lesson about native controls: native <code>&lt;input type=number&gt;</code> spin arrows were rejected because they cannot do Shift ×10 and, worse, do not commit, so a spin would have changed the field and sent nothing.</p>"))

section("library", "6 · The library: three intents, one Slot, one add_node, an id minted once",
  "<p>The \"Add X\" toolbar becomes a listbox of tiles, each the real component rendered small under a second scoping of the seed's stylesheet, <code>inert</code> and <code>aria-hidden</code> (a tile's name is the component's, not its sample text). Three gestures add: Enter or Space on a tile, a click, and a drag onto a layer row or onto the canvas. All three end in a <code>Slot</code>, and a slot becomes the op.</p>",
  cut("apps/web/src/library-adds.ts", "export function addOpAt", "/** Beside `id`"),
  cut("apps/web/src/library-adds.ts", "export function slotOnCanvas", "/** A child's extent"),
  "<p><code>library-adds.ts</code> mirrors <code>layer-moves.ts</code> on purpose: a tree drop reuses the tree's own <code>placementAt</code> (a tile over a row reads exactly as a dragged layer does, and the row wears the same line or box, because <code>LayersPanel</code> takes an <code>insertion</code> from outside); a canvas drop takes the node under the pointer from the same <code>hitTest</code> the selection uses, and for a container the index the pointer has passed along its layout axis (<code>indexAlong</code>: how many children's middles it is past; flex row → x, else y); Enter or a click adds into a selected container at the end, <em>after</em> a selected leaf, onto the page otherwise. And, like the tree, it refuses only geometry: into a Button is a slot, and the replica refuses it.</p>",
  cut("apps/web/src/Canvas.tsx", "  // The library's one add (E10.5)", "  // The others on the sheet (E10.6)"),
  "<p>The id is minted <em>here</em>, in <code>Canvas</code>, with <code>crypto.randomUUID()</code>, random and never reused (SPEC §2.4: a reused id would let a late op for a removed node land on a new one), and the new node is selected only if the replica took the op. A refused add (a viewer, or the room later) would otherwise leave <code>wanted</code> pointing at a node that never existed, and the live region would say \"removed by someone else\"; the effect in <code>Canvas</code> that watches refusals for an <code>add_node</code> of the wanted id sends the selection back to the page instead.</p>",
  cut("apps/web/src/LibraryPanel.tsx", "  const onPointerUp = (): void => {", "  // --- the keyboard (WAI-ARIA APG listbox"),
  cut("apps/web/src/Surface.tsx", "export function slotUnder", "\n/**\n * The rectangles a hint shades"),
  "<p>The one exported function of <code>Surface</code> that is not a component: the library, holding a captured pointer, needs to know what slot the canvas would give a drop at a screen point, and <code>slotUnder</code> is the one place that reads the canvas's boxes for it, with the same measuring helpers the outlines use. The library then tells <code>Canvas</code> what it is carrying and over what (<code>onCarry</code>), and <code>Canvas</code> hands the tree an <code>insertion</code> or the canvas a <code>Slot</code> to draw, so the indicator is drawn by whichever pane owns the boxes.</p>",
  cut("apps/web/src/LibraryPanel.tsx", "            <li\n              key={component.name}", "              {/* Inert AND hidden"),
  "<p>The APG <em>listbox</em>: <code>role=listbox</code>, <code>role=option</code> with <code>aria-selected</code>, roving tabindex as in the tree, a search box above that narrows the list (ArrowDown in it moves to the tiles: a scope of its own in the registry). Empty containers get 24 px and a dashed edge on the canvas, or an empty Stack could never be dropped into. The <code>ponytail</code>s are the honest ceilings: a two-column grid whose arrows walk in reading order (six components); a <code>src</code> prop gets an inline SVG so no tile makes a request for a name that is not an address (a failed request is a console error, and the e2e fixture fails on any).</p>",
  vs([("three intents → one <code>Slot</code> → one <code>add_node</code>", "a palette's <code>ActionListener</code> and a drop handler each mutate the model", "the same, twice"),
      ("<code>crypto.randomUUID()</code> minted once in the caller", "<code>UUID.randomUUID()</code>", "<code>uuid.uuid4()</code>"),
      ("<code>role=listbox</code> / <code>option</code>, roving tabindex", "<code>JList</code>", "<code>QListWidget</code>"),
      ("the tile is the real component, <code>inert</code> and <code>aria-hidden</code>", "a <code>ListCellRenderer</code> painting a stamp", "an item delegate")]),
  case("A tab beside Layers would have made the drop onto a row impossible.",
       "<p>The obvious pane layout was Layers and Library as two tabs of the left pane. A drag from a tile onto a <em>row</em> needs both on the screen at once, so the library sits under the layers. A layout decision forced by a gesture; worth naming because it is the kind of thing a mock-up hides.</p>"))

section("cursors", "7 · Presence in world coordinates, and a cursor for a peer that has no pointer",
  "<p>Epic 2 sent a cursor as a fraction of the canvas element, the right answer when every window drew the whole page in the same box. With zoom and pan per window a fraction of one canvas is a different spot on the sheet from a fraction of another; only a <em>world point</em> names the same component in both.</p>",
  cut("packages/contracts/src/index.ts", "const WORLD_LIMIT", "\n/**\n * One CONNECTION's presence"),
  cut("apps/web/src/Surface.tsx", "    const box = event.currentTarget.getBoundingClientRect();\n    // In WORLD coordinates", "  const onPointerUp"),
  "<p>Out: <code>toWorld</code> of the pointer's position inside the canvas, rounded to hundredths (a sub-pixel is noise on the wire). The contract bounds the value at ±1e6 so a wild number never rides the wire, and takes any point of the infinite sheet: left of or above the frame is a place too. In: the mark is drawn <em>inside</em> <code>.world</code> at its world point, so this window's own transform places it on the same component, and it divides by <code>--zoom</code> so the arrow and the tag keep their screen size. Nothing is converted on the receiving side; the cursors unit test says it in arithmetic (two viewports, one world point, the same button), and the e2e spec says it with two browsers at different zooms and a tip within 4 px of the other's Button centre.</p>",
  cut("apps/web/src/app.css", "/* A cursor sits in .world at its world point", ".cursor-glyph {"),
  cut("apps/web/src/cursors.ts", "export function trackCursors", "\n/**\n * The AI has no pointer"),
  cut("apps/web/src/Canvas.tsx", "  // The others' cursors with the time each last moved", "  // The AI panel is open until"),
  "<p>Idle is <em>by the clock, not by an event</em>. A presence refresh repeats the same spot every 2 s, and that is not a move; <code>trackCursors</code> keeps the old <code>movedAt</code> when the point is unchanged. Nothing arrives when a pointer rests, so no event could fade it; while any cursor is shown a one-second tick re-reads <code>Date.now()</code> and the mark's <code>data-idle</code> attribute drives a CSS opacity transition. Note the shape in <code>Canvas</code>: the tracked map is a <code>useRef</code> renewed on every render from what the peer says now, the moved-at times being the only thing remembered between renders, and the tick is a <code>useState</code> whose value nobody reads: its only job is to cause a render.</p>",
  cut("packages/peer-client/src/peer.ts", "  /**\n   * Every op the room has ORDERED", "  onStatus?:"),
  cut("packages/peer-client/src/peer.ts", "    const effects = replica.receive(message);", '    if (message.type === "welcome") {'),
  cut("apps/web/src/cursors.ts", "export function aiAnchors", "/** The cursor's tag"),
  "<p>The AI has no pointer, so presence cannot say where it is. But the room stamps every ordered op with its actor (keystone 3: stamped by the room from the verified session, never sent by the peer), and the peer already applies those ops; <code>onOp</code> tells a listener after each apply. It is a <em>window onto who did what, not a write path</em>: the listener is told after the fact, returns <code>void</code>, and nothing in the peer depends on anyone listening. <code>aiAnchors</code> keeps one anchor per agent actor id from its add, move and set_prop ops (two runs are two anchors) and hands back the <em>same</em> map for anyone else's op, so React sees no change and renders nothing for a person's edits. <code>Surface</code>'s measuring pass, the one that finds the outlines' boxes, also finds where the anchored node is; the mark is a spark set inside the node's corner, where a pointer would not be; before the first op, or when the node is gone, it sits on the page. The <code>ponytail</code>: a removal leaves the anchor where it was, because the op does not carry the parent and the listener hears it after apply; a <code>parentId</code> on the broadcast is the upgrade.</p>",
  cut("apps/web/src/Canvas.tsx", "  // The others on the sheet (E10.6)", "  // An avatar in the bar jumps"),
  "<p>The bar is the <em>record</em> of who is here; the cursors are decoration. An avatar per connection (initials on the person's colour, white text: the palette is checked for that) is a button that makes their selection ours and pans the canvas to centre it (<code>centreOn</code>, one more pure function of the viewport), disabled while they have none; one polite sentence says the list when it changes. The marks live in the editor layer, which is <code>aria-hidden</code>: decoration must not talk, and the e2e spec asserts the cursor has an <code>aria-hidden</code> ancestor.</p>",
  vs([("a cursor is a world point, bounded, to the hundredth", "your own protocol; the same lesson applies", "the same"),
      ("<code>onOp</code>: told after apply, returns void", "a read-only <code>ModelListener</code>", "a signal with no slot that writes"),
      ("idle by a 1 s tick reading <code>Date.now()</code>", "a <code>javax.swing.Timer</code>", "a <code>QTimer</code>"),
      ("the same <code>Map</code> back = no render", "<code>equals</code> before <code>firePropertyChange</code>", "compare before <code>emit</code>")]),
  case("Mapping the fractional cursor through the frame's box broke the moment either side panned.",
       "<p>The cheap fix for E10.2's zoom was to keep the fraction and divide by the frame's box on each side. It held while both windows showed the whole frame and broke as soon as one panned: a fraction of a <em>viewport</em> is not a fraction of the <em>frame</em>. The wire changed instead, to the one coordinate system that is the same everywhere, and the e2e spec zooms and pans both sides before it measures.</p>"))

section("shortcuts", "8 · One shortcut registry, a native dialog, and a preview that is the device's real width",
  cut("apps/web/src/shortcuts.ts", "export const SHORTCUTS = [", '  { scope: "layers", action: "down"'),
  cut("apps/web/src/shortcuts.ts", "type Entry = (typeof SHORTCUTS)[number];", "/** The shortcuts of one scope, for the sheet. */"),
  "<p>Every key the editor answers is a row: a scope (where it works: the focused widget, or <code>global</code> for everywhere the person is not typing), an action, the <code>KeyboardEvent.key</code> values, Alt and Shift, and a sentence. The table drives two things. The <em>handlers</em>: Surface, LayersPanel, LibraryPanel, Inspector, the splitter and Canvas's global listener call <code>actionFor(scope, event)</code> and switch on the action, never on <code>event.key</code>. The <em>sheet</em>: <code>ShortcutSheet</code> lists the same rows by scope. So a key the sheet promises is a key that works. The TypeScript is worth reading slowly: <code>as const satisfies readonly Shortcut[]</code> keeps the literal types (each <code>action</code> is a string literal, not <code>string</code>) while checking the shape; <code>ActionOf&lt;S&gt;</code> is then <em>derived from the table</em>, so a handler's <code>switch</code> is checked against the rows of its scope, and adding a row is the whole of adding a key (drill 1). Ctrl and Cmd are never bound: those chords are the browser's, and <code>actionFor</code> answers null for them. <code>shortcuts.test</code> fails on two rows one keydown could mean, in one scope or global against any.</p>",
  cut("apps/web/src/shortcuts.ts", "export const typingIn", "const GLYPHS"),
  cut("apps/web/src/Canvas.tsx", '  // The global shortcuts (shortcuts.ts, scope "global")', "  // A gap or padding control is hovered"),
  "<p>The global keys (<code>?</code>, <code>P</code>) are a <code>window</code> listener added in an effect, and they are ignored while the person is typing (<code>typingIn</code>: a <code>?</code> typed into the library's search box is a <code>?</code>) or while a modal is up. Order matters: a widget's own handler runs first and, finding no action of its own, lets the key bubble to the window; that is why <code>Surface</code>'s handler returns early on <code>null</code> instead of calling <code>preventDefault</code> for everything.</p>",
  cut("apps/web/src/ShortcutSheet.tsx", "export function ShortcutSheet", "  return ("),
  "<p>The sheet is a native <code>&lt;dialog&gt;</code> shown with <code>showModal()</code>: the browser traps focus inside it, makes the rest of the page <code>inert</code>, closes it on Escape and gives focus back to where it was, all without a line of trap code, and axe likes it. The React shape is the one to copy: <code>open</code> is the caller's state; an effect tells the element to match it; the element's own <code>close</code> event (Escape, the button) tells the caller. A click on the dialog element itself is a click on the backdrop, because the body fills the dialog. The Share dialog (section 9) is the same shape with a form in it.</p>",
  cut("apps/web/src/preview-split.ts", "export function frameScale", "/** The preview never narrower"),
  cut("apps/web/src/Preview.tsx", "        {/* The fit box takes the SCALED size", "      </div>\n      <p aria-live"),
  "<p>The preview was a strip under the canvas at one width. Now it is a resizable split beside the canvas, and the page runs in a <em>device frame</em> that is the device's <em>real</em> CSS size (390, 768 or 1280 wide), scaled down by one <code>transform</code> to fit the pane and never above life size. So the page inside measures itself at 390 px and its own media queries answer; scaling the iframe by a <code>width</code> attribute was rejected because the page would then see the scaled width. The bezel is a box-shadow, never a border, so it takes nothing from the width (a bordered 390 would leave the page 374). <code>useMeasured</code> is a <code>ResizeObserver</code> in a <code>useLayoutEffect</code> that sets state only when the size changed, the same no-render-for-no-change shape as the outlines. Every isolation rule from E4.3 is unchanged and <code>preview.spec</code> still asserts them: <code>sandbox=\"allow-scripts\"</code> without <code>allow-same-origin</code>, the URL asked for each second and never kept, loopback or own origin only, the container's token in the path; and the preview mounts only while open, because an open preview holds a container.</p>",
  cut("apps/web/src/Preview.tsx", '          <div\n            role="separator"', "          <Preview documentId"),
  "<p>The divider is the APG <em>window splitter</em>: <code>role=separator</code> with <code>aria-orientation</code>, <code>aria-valuenow/min/max</code> and a <code>valuetext</code>, focusable, dragged by pointer with capture or moved 24 px at a time with Left and Right through the registry's <code>splitter</code> scope. Its <code>ponytail</code>s: the width and the device are a session's choice, not remembered; the narrow layout stacks the two with no divider.</p>",
  vs([("one table; <code>actionFor(scope, event)</code>; <code>ActionOf&lt;S&gt;</code> derived from it", "<code>InputMap</code>/<code>ActionMap</code> per component; <code>KeyStroke.getKeyStroke(\"alt UP\")</code>", "<code>QAction.setShortcut</code>; <code>QShortcut</code> with a context"),
      ("a test that no two rows collide", "none; the last <code>put</code> wins silently", "Qt warns of an ambiguous shortcut at runtime"),
      ("<code>&lt;dialog&gt;.showModal()</code>: focus trap, inert page, Escape, focus return, free", "<code>JDialog</code> with <code>setModal(true)</code>", "<code>QDialog.exec()</code>"),
      ("a device frame of real CSS width, scaled by one transform", "n/a", "n/a")]),
  case("P as Shift+P, and a hand-rolled focus trap, both rejected.",
       "<p>Two habits from other toolkits were proposed and refused. Binding the preview to Shift+P \"so it cannot fire while typing\": a bare letter outside fields is what Figma does, and <code>typingIn</code> already keeps it out of the search box; the chord would have been a second answer to a solved problem. And a focus trap of our own for the sheet: forty lines that a native modal dialog does better, with the page made <code>inert</code> for free, which no hand-rolled trap can do.</p>"))

section("screens", "9 · Screens for what the api already does: a role as a hint, and a list that is never guessed",
  "<p>E10.8 adds no ability. The api could already list members and change roles (E8.2), share and revoke (E8.3); it lacked two <em>read</em> routes and every screen. The section is about what a screen may decide, which is nothing, and about when <em>not</em> to be optimistic.</p>",
  cut("apps/api/src/app.ts", "  // E10.8: who is in the org, with their roles.", "  // F24: only an owner changes roles"),
  cut("apps/api/src/app.ts", '  document.get("/shares", need("owner")', "  // F25: an owner of the document's org shares it"),
  "<p>Both routes are rows in the E8.2 route-role table, which <code>app.test</code> checks: a route without a <code>need</code> fails the test. Members are readable by a viewer (every member meets these people in every document already, and the screen an owner changes roles on is the one a viewer reads); shares are owners-only, as sharing itself is (the list names people outside the org, and an editor has no business with it). Both page like every other list, over a join handed to <code>page()</code> as the table, with the org and the document in the WHERE: a list never reaches past the tenant the middleware already proved.</p>",
  cut("packages/contracts/src/index.ts", "export const SessionResponse", "export type SessionResponse"),
  cut("apps/web/src/Canvas.tsx", '            {role === "owner" && <button', '            <button type="button" aria-label="Keyboard shortcuts'),
  "<p>The editor shows Share to an owner only, and it must know that without asking a route that would answer 403 (the e2e fixture fails on any console error, and a viewer's page must stay clean). So the session response gains an optional <code>role</code>: what the document middleware read from the same row that proved access, <em>beside</em> the token and never in it. E1.5 stands: the token says who; the routes and the room read the row for themselves on every request and every op. <code>usePeer</code> keeps the latest session's role (a reconnect mints a new session and passes here too, so the hint follows the api's latest word), and <code>Canvas</code> shows Share and mounts the dialog only for <code>\"owner\"</code>. A hint for the screen, never authority: a role that changes under an open page is met as a sentence from the api at the next action, and by the room sooner, on its next Redis hint or 30 s sweep (E8.3). Rejected: probing <code>GET /shares</code> on open (a 403 in the console for every non-owner) and putting the role in the token (a token is minted once and read many times; a role changes).</p>",
  cut("apps/web/src/members.ts", "const MEMBER_REFUSALS", "export const memberRefusalWords"),
  cut("apps/web/src/members.ts", "export function withMember", None),
  cut("apps/web/src/OrgView.tsx", "  const apply = async (at: string, email: string, role: Role)", "  const add = async"),
  "<p>Here is the contrast with the document. The replica is <em>optimistic</em>: an edit is shown before the room answers, because the ops were designed for it (small, validated locally by the same rules, rebuilt from a journal on refusal). A membership change is <em>not</em>: <code>withMember</code> applies the api's own answer, never the request; the 409 <code>last_owner</code>, the 404 <code>no_user</code> and a 403 are sentences from a <code>Record</code> over the api's whole vocabulary (a name added to the api's answers stops this file compiling until it has words); and a 403 or 404 makes the page drop its local changes and read the list again, because the world moved under it. The caller's own role is read from the list they were given (<code>roleOf</code>): the member list already carries it, so no route need say it twice. Every name and email is a React text node: React escapes text children, so a name of <code>&lt;img onerror=...&gt;</code> is letters on the screen.</p>",
  cut("apps/web/src/ShareDialog.tsx", "  const revoke = async (member: Member)", "  return ("),
  "<p>The Share dialog is the sheet's shape with a form: a native <code>&lt;dialog&gt;</code>, the list read afresh every time it opens, add at viewer or editor, change a role, and Revoke that asks <em>in place</em>. Focus management is the craft here: the confirmation appears where the person was and <code>autoFocus</code> lands on the answer they came for; Keep gives focus back to the button that asked, once it is drawn again (a <code>setTimeout(0)</code>, because the button does not exist until the next render); a revoke removes the row, so focus goes to the email field rather than falling out of the dialog. The global shortcuts stay quiet while it is up. The <code>ponytail</code>: the first page of shares (50); a 51st is not listed; a \"show more\" as the org pages have is the upgrade.</p>",
  cut("apps/web/src/links.ts", "export function hrefTo", None),
  "<p>Home lists your organisations, and an org's pages (members, audit trail, AI usage) share one nav with <code>aria-current</code>. <code>hrefTo</code> is the address bar as the router (<code>?doc=</code>, <code>?org=</code>...) and carries the development <code>?user=</code> along, so two windows stay two people from one page to the next; with a real sign-in there is none and the link is just the page.</p>",
  vs([("the members list applies the api's answer; a 403 re-reads", "a <code>TableModel</code> updated from the response", "the same"),
      ("<code>role</code> beside the token in the session, read from the row", "a <code>Principal</code>'s roles in the session; re-checked per request by Spring Security", "Django's <code>request.user</code>, re-checked per view"),
      ("<code>Record&lt;Refusal, string&gt;</code>: a new refusal name is a compile error", "an <code>EnumMap</code> with a <code>switch</code> that is not exhaustive", "a <code>dict</code> and a KeyError in production"),
      ("React text nodes: escaped by construction", "Swing's <code>JLabel</code> renders <code>&lt;html&gt;</code> if the text starts with it", "Qt rich text if the string looks like HTML")]),
  case("Probing GET /shares on open would have put a 403 in every viewer's console.",
       "<p>The first idea for \"is this person an owner\" was to ask <code>/shares</code> when the editor opens and show Share if it answers. Every viewer and editor would have opened the document to a 403 in the console, which the e2e fixture treats as a failure, and which a support engineer would read as a bug. The session already knew the role from the row it proved access by; saying it beside the token cost one optional field and no authority.</p>"))

section("tradeoffs", "10 · Trade-offs and comparisons: where this editor sits",
  "<p><strong>Retained widgets versus a view of the state.</strong> Swing, JavaFX, Qt and Tk are <em>retained-mode</em>: a widget tree is built once and mutated by events, and the toolkit repaints the damage. React is <em>declarative over a retained DOM</em>: your code describes the whole screen from state on every change and React mutates the DOM to match. The desktop model is faster per event and puts the truth in the widgets, where it drifts (the classic Swing bug is a <code>TreeModel</code> that no longer matches the data). The React model puts the truth in one place (here the replica) and makes every pane a projection; the cost is that render must be cheap and pure, which is why the pure modules of this epic are small and the components thin. JavaFX's property bindings and Qt's model/view are each half-way to this: the view updates from a model, but the model is yours to keep in step.</p>",
  "<p><strong>Optimistic versus confirmed.</strong> The document is optimistic because the replica can afford it: the same <code>validate()</code> runs locally, a refusal is a rebuild from <code>confirmed</code> plus the remaining pending ops, and the invariant is tested as a property. The members list is confirmed-only because its truth is rows behind locks and side effects, and a guessed row would lie. The rule of thumb: be optimistic where you can run the server's rule locally and recover from a refusal by recomputation; otherwise show the answer.</p>",
  "<p><strong>One transform versus re-layout.</strong> A canvas that re-lays its content out at every zoom (setting widths and font sizes) is how a browser's own page zoom works and is right for text. A design canvas wants the frame to be a picture that scales: one <code>transform</code> on one layer, composited, with the editor's own strokes divided back to screen size. Figma does the same on a WebGL canvas; here the \"picture\" is live DOM, so the components stay real and inspectable, and the price is that measuring must happen after render.</p>",
  "<p><strong>HTML drag and drop versus pointer events.</strong> HTML DnD gives you cross-window drags, a ghost image and the OS's drop semantics, at the cost of a second event vocabulary, a ghost to fight, and <code>dragover</code> on its own clock. Pointer events with capture give one vocabulary for the canvas, the tree and the library, an indicator that follows the exact pointer, and Escape to cancel; they cannot drag out of the window, which nothing here needs.</p>",
  "<p><strong>Where Figma differs.</strong> Figma's canvas is freeform vectors on a WebGL surface with its own layout engine, and multiplayer is a CRDT-like property map with last-writer-wins per property. Noon's canvas is a <em>tree of real components</em> laid out by the design system itself (SPEC §5: no freeform drawing, no absolute positioning, so the design can become code), and multiplayer is a server-ordered op log (the note on multiplayer approaches has the comparison). The Figma <em>feel</em> (a dotted infinite sheet, zoom at the pointer, layers left and inspector right, one accent, a <code>?</code> sheet, cursors with name tags) is borrowed; the model is not.</p>",
  vs([("React: describe the screen from state; diff the DOM", "Swing/JavaFX: mutate widgets; repaint damage", "Qt/Tk: mutate widgets; repaint damage"),
      ("one replica, every pane a projection", "a model per widget you keep in step", "model/view with the model yours to keep"),
      ("optimistic where the rule runs locally, confirmed otherwise", "usually confirmed (a blocking call on the EDT is the anti-pattern)", "usually confirmed"),
      ("a11y by ARIA roles, checked by axe in a test", "the L&amp;F's accessibility bridge", "Qt's accessibility plugin"),
      ("theming by custom properties in the cascade", "Look-and-Feel objects", "palettes and stylesheets")], head=("This repo", "Java desktop", "Python desktop")))

section("testing", "11 · Testing a screen: pure halves as arithmetic, a WebSocket that counts frames, axe in both themes",
  "<p>The split from every earlier lesson holds, and the frontend makes it sharper: everything that can be a pure function is (viewport maths, hit-testing, drop-to-op, prop-to-control, slot-to-op, cursor tracking, the registry), tested as arithmetic in milliseconds; everything that needs a browser is an end-to-end spec against the real stack, run in the gate. Five shapes are new.</p>",
  cut("apps/web/src/theme.test.ts", "// [text, on surface, minimum]", "for (const [name, tokens] of"),
  "<p><strong>Accessibility as arithmetic.</strong> The contrast of every text/surface pair the UI uses, recomputed from <code>tokens.css</code> itself in both themes. A colour token is data, and data can be tested; the same idea checked the presence palette in E2.6.</p>",
  cut("apps/web/src/controls.test.ts", 'test("every prop of every component in the committed manifest', 'test("an unknown prop kind'),
  "<p><strong>The committed manifest as a fixture.</strong> The inspector's promise is \"every prop has a control\"; the test walks the real manifest rather than a hand-made one, so a regenerated manifest that breaks the promise breaks the test.</p>",
  cut("apps/web/src/cursors.test.ts", "// unit:cursor-world-coords (E10.6)", 'test("a cursor is tracked with'),
  "<p><strong>Two viewports, one point.</strong> The claim \"cursors agree across zoom\" is a statement about <code>toWorld</code> and <code>toScreen</code>, and the unit test says it with two viewports and the contract's parser; the e2e spec says it again with two browsers and a tip within 4 px, which is the wiring.</p>",
  cut("e2e/layers-drag-and-keyboard-reorder.spec.ts", "/** Counts the move_node ops THIS browser sends", 'test("the tree mirrors'),
  "<p><strong>A routed WebSocket that counts frames.</strong> \"One op per move\" is the chapter's thesis, and a spec that only looked at the resulting tree could not tell one <code>move_node</code> from a remove and an add, nor from one op per pixel. Playwright's <code>routeWebSocket</code> sits between the browser and the server, forwards every frame, and counts the ones whose op is a <code>move_node</code>; the spec asserts the count after each drag. <code>inspector-edits-propagate</code> does the same for <code>set_prop</code>: one per edit, none per keystroke.</p>",
  cut("e2e/fixtures.ts", "  cleanPage: [", "    { auto: true },"),
  cut("e2e/editor.ts", "export const axeClean = async", "/** Signs `user` in"),
  "<p><strong>Axe and a clean console, for free, in both themes.</strong> Every e2e test ends with two checks it did not write: the browser console stayed clean (a failed image request, a React warning, an unhandled rejection all fail the test) and the page has no axe violations. Because the fixture runs axe once in whatever theme the test left, the E10 specs also call <code>axeCleanLightAndDark</code>, and <code>shell-light-dark</code> takes screenshot baselines in both. After E10.6 those helpers and the editor's locators were copied from spec to spec; <code>noon-92o</code> moved them into <code>e2e/editor.ts</code> because <code>jscpd</code> found six clones, and made <code>Preview</code> a plain function because <code>knip</code> found it exported and unused, rejecting an ignore entry that would have hidden the next one.</p>",
  cut("e2e/shell-light-dark.spec.ts", "  // Light, as the OS says; screenshot and axe.", "  // The AI panel closes"),
  vs([("<code>expect(toWorld(v, toScreen(v, p))).toBeCloseTo(p)</code>", "<code>assertEquals(p, t.inverseTransform(t.transform(p)), 1e-9)</code>", "<code>pytest.approx</code>"),
      ("<code>page.routeWebSocket(...)</code> counting frames", "a proxy in the test; rare", "the same"),
      ("<code>new AxeBuilder({ page }).analyze()</code>", "no equivalent in the JDK; manual audits", "none"),
      ("<code>toHaveScreenshot(\"shell-dark.png\")</code>", "manual", "manual"),
      ("<code>readFileSync(\"tokens.css\")</code> as a fixture", "a resource file read in the test", "the same")]),
  case("A spec that pressed \"Select X\" buttons broke when the role moved, and the names did not.",
       "<p>Five earlier specs reached the layers as buttons; E10.3 made them treeitems. The specs changed one locator each (<code>getByRole(\"treeitem\", { name })</code>) and nothing else, because the accessible <em>names</em> were unchanged. Locating by role and name, the way a screen reader does, is what let the UI change shape under the tests without the tests changing meaning; and it is also why every E10 spec asserts a sentence (\"Button does not take children\") rather than a class.</p>"),
  note("<strong>Honest status, repeated here because it matters:</strong> the unit tests named in the status block ran green on every commit. The eleven end-to-end specs of this epic and <code>members-shares.int</code> are written, reviewed and committed, and passed in the clean-clone gate at <code>6700e74</code> on 2026-10-02, the screenshot baselines included. Section 12 is what running them looks like."))

section("demo", "12 · By hand: the theme, the zoom, a drag with the network tab open, two cursors, the sheet, Share",
  "<p>The exact commands and what each should show. The api is on host port 3000, the demo's web app on 5173; run a Vite of your own on 5199 so the demo is left alone. Two browser windows signed in as two people (<code>?user=</code> in development) are the whole harness for the collaboration steps.</p>",
  shell("0 · Bring the stack up, and an editor of your own",
        "./init.sh                                    # the stack; no new migrations in this epic\n"
        "pnpm exec vite --config apps/web/vite.config.ts --port 5199\n"
        "open 'http://localhost:5199/?user=ada@example.com'   # sign in, New document; note ?doc=&lt;id&gt;"),
  shell("1 · Tokens and the theme (E10.1)",
        "# press Dark theme in the bar: every surface flips; the page frame stays a white sheet on a dark desk\n"
        "# reload: still dark (localStorage noon.theme); in DevTools > Rendering, emulate prefers-color-scheme: light: still dark (the choice outranks the OS)\n"
        "# a fresh private window follows the OS live\n"
        "pnpm exec vitest run apps/web/src/theme.test.ts   # every text/surface pair AA in both themes, recomputed from tokens.css"),
  shell("2 · The canvas (E10.2)",
        "# ctrl/cmd+wheel over the Button: the point under the pointer stays put; the readout bottom-right changes; the outline's stroke does not thicken\n"
        "# + and - zoom about the centre; 0 and Fit refit; Space+drag and middle-drag pan; the clamp is 10 %..400 %\n"
        "# click a Button inside a Card: the deepest box wins; arrows walk siblings, Enter goes in, Shift+Enter out, Escape to the page\n"
        "# try to click the Button as a button: nothing happens (inert); Tab from the canvas leaves it in one stop"),
  shell("3 · One move_node per drag (E10.3)",
        "# DevTools > Network > WS > the /documents/ socket > Messages. Drag Text 1 onto the middle of Card 1 (a box), let go:\n"
        "#   exactly ONE frame {\"type\":\"op\",...\"op\":{\"type\":\"move_node\",\"nodeId\":...,\"newParentId\":...,\"index\":N}} goes up\n"
        "# drag it to the top quarter of Button 1 (a 2 px line): one frame, index 0. Alt+Down, Alt+Up, Alt+Left: one frame each\n"
        "# Alt+Right onto a Button: the line, then \"Button does not take children\" in the notice strip; no frame was refused by the tree, one was by the replica\n"
        "# in the other window: every move appears live in its tree and on its canvas"),
  shell("4 · The inspector (E10.4)",
        "# select a Stack: Layout shows direction and align as arrow segments, gap as a stepper; hover gap: the spaces between the children shade on the canvas\n"
        "# type 24 into gap and press Tab: ONE set_prop frame (watch the socket); type 1,2,3,4 slowly: still one frame, on blur\n"
        "# Up/Down step by 1 and send at once; Shift+Up by 10; Reset appears once set and sends set_prop null\n"
        "# in the other window as a viewer (?user=viewer@example.com, made a viewer on the org page): edit a prop: the refusal repeats under the control"),
  shell("5 · The library (E10.5)",
        "# drag the Card tile over the layers: a box round a container, a line beside a leaf, exactly as a dragged layer shows\n"
        "# drag the Button tile onto the canvas over the Card: a box round the Card and a line among its children; let go: ONE add_node frame; the new node is selected\n"
        "# select a Text, press Enter on a tile: added AFTER the text (a leaf), and selected"),
  shell("6 · Cursors in world coordinates, and the AI's (E10.6)",
        "open 'http://localhost:5199/?doc=$DOC&user=bob@example.com'   # a second window; zoom it to 32 % with -, and the first to 160 % with +\n"
        "# rest Bob's pointer on the Button: in Ada's window the arrow's tip is on HER Button, at her zoom; zoom Ada's window: it stays on the Button\n"
        "# hold still 5 s: it fades; move: it is back. Bob selects the Card: Ada presses Bob's avatar in the bar: her selection is the Card, centred\n"
        "# Ask the AI for 'a card with two buttons': a spark tagged AI sits on the node its last accepted op touched, moving as the run goes"),
  shell("7 · The preview split and the sheet (E10.7)",
        "# press P (or Preview in the bar): the running page opens beside the canvas in a phone frame at 390 CSS px, scaled to fit; Tablet and Desktop resize the frame, not the page's idea of its width\n"
        "# drag the divider, or focus it and press Left/Right; press P again: the preview unmounts (the container is released after a minute)\n"
        "# press ?: the sheet lists every key by scope; Tab cycles inside it (focus is trapped); Escape closes it and focus returns to where it was\n"
        "# type ? into the library's search box: it is a ? (typingIn)"),
  shell("8 · Members and Share (E10.8)",
        "open 'http://localhost:5199/?org=$ORG&user=ada@example.com'     # the members with roles; as an owner, selects and an Add form\n"
        "# add bob@example.com as viewer; change him to editor; try to make yourself, the only owner, an editor: \"An organisation must keep at least one owner...\"\n"
        "open 'http://localhost:5199/?org=$ORG&user=bob@example.com'     # the same list, no controls: the api decides, the screen only hides\n"
        "# in the document as Ada: Share in the bar (Bob's bar has none); share with carol@example.com (signed up) as viewer; Carol's window opens it live\n"
        "# Revoke: the confirmation appears in place with focus on Revoke; Keep returns focus to the button; Revoke closes Carol's session (her status says closed)"),
  shell("9 · Then the checks that prove it without hands",
        "pnpm exec vitest run apps/web/src   # every pure half of the editor\n"
        "pnpm exec vitest run --config vitest.integration.config.ts apps/api/src/members-shares.int.test.ts\n"
        "pnpm exec playwright test e2e/shell-light-dark.spec.ts e2e/canvas-zoom-pan-select.spec.ts e2e/layers-drag-and-keyboard-reorder.spec.ts e2e/inspector-edits-propagate.spec.ts \\\n"
        "  e2e/library-drag-to-canvas.spec.ts e2e/cursors-agree-across-zoom.spec.ts e2e/ai-cursor-on-touched-node.spec.ts e2e/preview-split-device-frames.spec.ts \\\n"
        "  e2e/shortcut-sheet.spec.ts e2e/members-role-change.spec.ts e2e/share-dialog.spec.ts\n"
        "pnpm exec playwright test --update-snapshots e2e/shell-light-dark.spec.ts e2e/home.spec.ts   # the baselines changed with the tokens; look at the diff before accepting\n"
        "make check                                   # the whole gate, as the pre-commit hook runs it"),
  note("<strong>What to do when a step does not match this page:</strong> the page was cut from the code at commit <code>" + commit + "</code>, and the code is right until a test says otherwise. A step that fails is a finding: write it as <em>sequence → false belief → consequence → smallest fix</em> (SPEC §4a's form) and file it against the bead that owns the code."))

section("limits-of-types", "13 · What the type system could not see, epic 10 edition",
  "<p>Everything below compiled under <code>strict</code>, passed the linter and the first tests, or was rejected at design time by asking what the types could not ask.</p>",
  vs([("a peer opened twice under StrictMode", "\"create it once\" in <code>useMemo</code>", "open in <code>useEffect</code> with a cleanup"),
      ("a snapshot that never changed", "<code>peer.doc</code> is the same object", "a string of the numbers that move"),
      ("a stale selection after someone else's remove", "state is state", "derive the node from <code>wanted</code> each render"),
      ("the canvas re-rendering sixty times a second while panning", "a drag point in state", "a ref"),
      ("an effect that set state on every run", "measuring is measuring", "return the same object when nothing moved"),
      ("a flash of the wrong theme", "the effect applies it", "<code>applyStoredTheme()</code> before the first render"),
      ("a dark token left out showing light on dark", "the cascade inherits", "a test that the dark block names every colour"),
      ("a colour at 3:1 on a dark surface", "\"it looked fine on white\"", "contrast recomputed for every pair, both themes"),
      ("the editor's <code>input</code> rule painting the sample app's field dark", "one stylesheet", "the tokens redefined on the frame to <code>--ds-*</code>"),
      ("the seed's <code>:root</code> restyling the editor", "a stylesheet is a stylesheet", "scoped to the frame's class on load"),
      ("a border stroke thickening with the zoom", "2px / zoom is 2px", "a box-shadow spread; Chrome snaps borders"),
      ("ctrl+wheel zooming the browser", "<code>onWheel</code> with <code>preventDefault</code>", "a native non-passive listener"),
      ("the shallowest element winning the click", "<code>elementFromPoint</code>", "the deepest measured box"),
      ("the Button on the canvas taking the click", "it is a real Button", "<code>inert</code>"),
      ("a corrupt document with a cycle hanging the tab", "a parent walk ends", "a <code>seen</code> set"),
      ("a move landing one too far", "index = position of the target", "counted after the node is taken out"),
      ("a remove and an add for a move", "\"take it out, put it in\"", "one <code>move_node</code> (drill 2)"),
      ("the tree predicting <code>validate()</code>", "grey out the leaf", "build the op; the replica refuses"),
      ("a control inside a treeitem", "a disclosure button", "a span; Left/Right are its keys"),
      ("Tab changing the selection", "select on focus", "arrows select; a bare focus does not"),
      ("a prop rendering as nothing", "an unknown kind falls through", "<code>never</code> and a throw"),
      ("<code>gap: string</code> shaded as a space", "keyed on the name", "name AND kind"),
      ("one <code>set_prop</code> per keystroke", "<code>onChange</code> sends", "commit on blur or Enter"),
      ("\"12abc\" deleting a prop", "<code>value === \"\"</code>", "<code>validity.badInput</code>"),
      ("a radio group unnamed", "a fieldset has a legend", "<code>aria-labelledby</code> a span"),
      ("a spin that changed the field and sent nothing", "native spin arrows", "buttons that commit"),
      ("a refused add leaving a selection on a ghost", "select the new id", "select only if the replica took it; back to the page on refusal"),
      ("a tile fetching an image called \"Image\"", "<code>src</code> is a string", "an inline SVG"),
      ("a cursor as a fraction of the canvas", "the E2.6 answer", "a world point, bounded, to the hundredth"),
      ("a cursor never fading", "no event when a pointer rests", "a 1 s tick reading the clock"),
      ("a presence refresh counted as a move", "the same spot arrived again", "keep <code>movedAt</code> when unchanged"),
      ("a render for every person's op in the AI's anchors", "a new Map each time", "the same Map back"),
      ("a cursor that talks", "<code>aria-live</code> on the mark", "an <code>aria-hidden</code> layer; the bar is the record"),
      ("a key the sheet promised that did nothing", "two lists", "one registry drives both"),
      ("two rows on one key", "the last one wins", "a test that no two collide"),
      ("<code>?</code> in the search box opening the sheet", "global is global", "<code>typingIn</code>"),
      ("a hand-rolled focus trap", "modals need one", "<code>&lt;dialog&gt;.showModal()</code>"),
      ("the page seeing the scaled width", "scale the iframe", "a frame of the real width, scaled by transform"),
      ("a bordered 390 leaving the page 374", "a border is a bezel", "a box-shadow"),
      ("a 403 in every viewer's console", "probe <code>/shares</code>", "<code>role</code> beside the token"),
      ("a role in the token", "\"the token knows\"", "the row, read per request and per op"),
      ("a guessed member row", "optimistic everywhere", "the api's answer only; a 403 re-reads"),
      ("focus falling out of the dialog on revoke", "the row is gone", "focus to the email field"),
      ("a name rendered as markup", "a string is a string", "React text nodes"),
      ("six copies of the e2e scaffolding", "each spec stands alone", "<code>e2e/editor.ts</code>; jscpd said so"),
      ("an unused export hidden by a knip ignore", "\"it is fine\"", "make it a plain function")], head=("What went wrong, or would have", "Why", "Fix")),
  note("<strong>The pattern, extended once more:</strong> lesson 9 said types cannot see how many times a call happens or which clock a number came from. Epic 10 adds the two that make a UI hard: types cannot see <em>which coordinate system</em> a number is in (a screen px, a world px and a fraction are all <code>number</code>), and cannot see <em>which copy is the truth</em> (a widget's field and the replica's node have the same type). Both were answered as before: put the truth in one place (the replica, the registry, the manifest, <code>tokens.css</code>) and derive everything else from it on every render; name the coordinate system in the function's name (<code>toWorld</code>, <code>toScreen</code>) and convert at the edge, once; and write the test that provokes the exact case: two viewports and one point, a routed socket counting frames, the contrast of every pair, a manifest walked prop by prop."))

toc = "".join(f'<li><a href="#{sid}">{title}</a></li>' for sid, title, _ in S)
sections = "".join(f'<section id="{sid}"><h2>{title}</h2>{body}</section>' for sid, title, body in S)
style = re.search(r"<style>.*?</style>", (root / "docs/handbook/lesson-0.template.html").read_text(), re.S).group(0)
page = (pathlib.Path(__file__).parent / "lesson-10.template.html").read_text()
page = page.replace("{{STYLE}}", style).replace("{{TOC}}", toc).replace("{{SECTIONS}}", sections).replace("{{COMMIT}}", commit)
(out / "lesson-10.html").write_text(page)
