// DRILL 1 · extend a type, end to end.  Starts RED. Do not edit this file.
//
// With two sync nodes, a person's canvas lands on whichever node owns the room, and nothing on the screen says
// which. An operator lining up two tabs during a failover wants to see them move; a person filing a bug wants to
// name the node. Carry the node id from the lease to the screen. You will touch, in this order:
//   1. packages/contracts/src/index.ts     `SessionResponse` gains `nodeId`, OPTIONAL (an api with one sync node has no
//                                          table and no id to give), validated as a node id is (1-32 of a-z, 0-9 and -,
//                                          starting with a letter or digit): a value the wire cannot be trusted to shape.
//   2. packages/lease/src/lease.ts         `syncRouter` answers `{ wsUrl, nodeId }` instead of a bare string; a single node
//                                          answers `{ wsUrl }` with no nodeId at all (exactOptionalPropertyTypes: spread it
//                                          in). The type checker now names every caller: apps/api/src/app.ts (/session puts
//                                          it in the response), apps/worker/src/live.ts (roomUrl wants the address only),
//                                          apps/sync/src/testing.ts, the two one-room integration tests, failover.int.
//                                          That list IS the drill: every one is a place the contract changed.
//   3. packages/peer-client/src/peer.ts    a `nodeId: string | undefined` getter: whatever the LAST session() answer named,
//                                          set before the socket is dialled, so a peer sent elsewhere by a 4409 shows the
//                                          node it lands on next. session()'s type accepts the field.
//   4. apps/web/src/reasons.ts             `onNode(nodeId: string | undefined): string`: "on sync-2", or "" for none.
//   5. apps/web/src/Canvas.tsx             the status line gains " · on sync-2" after "saved", only when there is a node id.
//                                          As TEXT, in {}, like every string that came over the wire.
// Then run:  make check   and   sh drills/lesson-7/check.sh
import { expect, test } from "vitest";
import { SessionResponse } from "@noon/contracts";
import { manifest as designSystem } from "@noon/design-system";
import { emptyDoc } from "../../packages/doc-model/src/index.ts";
import { parseSyncNodes, syncRouter } from "../../packages/lease/src/lease.ts";
import { connectPeer } from "../../packages/peer-client/src/index.ts";
import * as reasons from "../../apps/web/src/reasons.ts";

const DOC = "11111111-1111-4111-8111-111111111111";
const session = { wsUrl: `wss://noon.example.com/sync-2/documents/${DOC}`, token: "t", expiresAt: "2026-09-30T00:00:00.000Z" };
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
async function until(condition: () => boolean, what: string): Promise<void> {
  for (const deadline = Date.now() + 2000; !condition(); await sleep(5)) if (Date.now() > deadline) throw new Error(`timed out waiting for: ${what}`);
}

test("the contract: a session may name the sync node it points at, and only a node id is accepted", () => {
  expect(SessionResponse.parse({ ...session, nodeId: "sync-2" })).toHaveProperty("nodeId", "sync-2");
  expect(SessionResponse.parse(session)).not.toHaveProperty("nodeId"); // one node: no table, no id
  expect(SessionResponse.safeParse({ ...session, nodeId: "Sync" }).success).toBe(false);
  expect(SessionResponse.safeParse({ ...session, nodeId: "" }).success).toBe(false);
  expect(SessionResponse.safeParse({ ...session, nodeId: "a b" }).success).toBe(false);
});

test("the router says which node it chose; a single node has no id to give", async () => {
  const nodes = parseSyncNodes("sync=ws://one:3001,sync-2=ws://two:3001");
  if (!nodes) throw new Error("fixture");
  const all = () => Promise.resolve<ReadonlySet<string>>(new Set(["sync", "sync-2"]));
  const owned = syncRouter({ nodes, owner: () => Promise.resolve({ token: 3, nodeId: "sync-2" }), alive: all, pick: () => "sync" });
  expect(await owned(DOC)).toEqual({ wsUrl: `ws://two:3001/documents/${DOC}`, nodeId: "sync-2" });
  const free = syncRouter({ nodes, owner: () => Promise.resolve(undefined), alive: all, pick: () => "sync" });
  expect(await free(DOC)).toEqual({ wsUrl: `ws://one:3001/documents/${DOC}`, nodeId: "sync" });
  const one = syncRouter({ nodes: { kind: "one", url: "ws://sync.test:3001" }, owner: () => Promise.reject(new Error("must not be asked")), alive: () => Promise.reject(new Error("must not be asked")) });
  expect(await one(DOC)).toEqual({ wsUrl: `ws://sync.test:3001/documents/${DOC}` });
});

/** A scripted server, one socket at a time: `script(socket, nth)` says what the nth connection does. */
function fakeNet(script: (socket: FakeSocket, nth: number) => void) {
  const sockets: FakeSocket[] = [];
  class FakeSocket extends EventTarget {
    readonly url: string;
    constructor(url: string) {
      super();
      this.url = url;
      sockets.push(this);
      queueMicrotask(() => { script(this, sockets.length); });
    }
    send(): void { /* nothing is asserted on what the peer sends */ }
    close(code = 1000): void { this.dispatchEvent(Object.assign(new Event("close"), { code })); }
    say(message: unknown): void { this.dispatchEvent(Object.assign(new Event("message"), { data: JSON.stringify(message) })); }
  }
  return { sockets, WebSocketImpl: FakeSocket as unknown as typeof WebSocket };
}
type FakeSocket = EventTarget & { url: string; say(message: unknown): void; close(code?: number): void };

test("peer-client remembers the node its LAST session named, so a peer sent elsewhere by a 4409 shows where it landed", async () => {
  const welcome = { type: "welcome", doc: emptyDoc(), seq: 0 };
  const net = fakeNet((socket, nth) => {
    socket.say(welcome);
    if (nth === 1) socket.close(4409); // not the owner: ask /session again
  });
  const answers = [{ wsUrl: "ws://one/documents/d", token: "t", nodeId: "sync" }, { wsUrl: "ws://two/documents/d", token: "t", nodeId: "sync-2" }];
  let asked = 0;
  const peer = connectPeer({ manifest: designSystem, retryMs: { min: 10, max: 20 }, session: () => Promise.resolve(answers[Math.min(asked++, 1)] ?? null), WebSocketImpl: net.WebSocketImpl });
  const nodeId = () => (peer as unknown as { nodeId?: string }).nodeId;
  await until(() => net.sockets.length === 2 && peer.status === "live", "live on the second node");
  expect(net.sockets.map((socket) => socket.url)).toEqual(["ws://one/documents/d", "ws://two/documents/d"]);
  expect(nodeId()).toBe("sync-2");
  peer.close();
});

test("the canvas's words: 'on sync-2', and nothing when the session named no node", () => {
  const onNode = (reasons as Record<string, unknown>)["onNode"] as ((nodeId: string | undefined) => string) | undefined;
  expect(typeof onNode).toBe("function");
  expect(onNode?.("sync-2")).toBe("on sync-2");
  expect(onNode?.(undefined)).toBe("");
});
