// The Redis password is a local secret generated by ./init.sh into .env; nothing is hard-coded here.
function redisUrl(): string {
  if (process.env["TEST_REDIS_URL"]) return process.env["TEST_REDIS_URL"];
  const password = process.env["REDIS_PASSWORD"];
  if (!password) throw new Error("REDIS_PASSWORD is not set: run ./init.sh (it writes .env and starts Redis)");
  return `redis://:${password}@localhost:${process.env["REDIS_PORT"] ?? "6380"}`;
}
export const TEST_REDIS_URL = redisUrl();
