import { connect, createServer, type Socket } from "node:net";

// The Redis password is a local secret generated by ./init.sh into .env; nothing is hard-coded here.
function redisUrl(): string {
  if (process.env["TEST_REDIS_URL"]) return process.env["TEST_REDIS_URL"];
  const password = process.env["REDIS_PASSWORD"];
  if (!password) throw new Error("REDIS_PASSWORD is not set: run ./init.sh (it writes .env and starts Redis)");
  return `redis://:${password}@localhost:${process.env["REDIS_PORT"] ?? "6380"}`;
}
export const TEST_REDIS_URL = redisUrl();

/**
 * A Redis stand-in whose first `connections` connections answer their FIRST INFO (ioredis's ready check) properly and
 * every later one (BullMQ's version check) with an integer: what gate 11 met, "doc.split is not a function" out of
 * BullMQ's connection start. Every connection after those is a plain pipe to the test Redis.
 */
export async function poisonableRedis(connections: number): Promise<{ url: string; close(): Promise<void> }> {
  const real = new URL(TEST_REDIS_URL);
  let poisoned = 0;
  const sockets = new Set<Socket>();
  const server = createServer((client) => {
    sockets.add(client);
    if (poisoned++ >= connections) {
      const upstream = connect(Number(real.port || 6379), real.hostname);
      sockets.add(upstream);
      client.pipe(upstream).pipe(client);
      upstream.on("error", () => client.destroy());
      client.on("error", () => upstream.destroy());
      return;
    }
    let pending = Buffer.alloc(0);
    let infos = 0;
    client.on("error", () => undefined);
    client.on("data", (chunk: Buffer) => {
      pending = Buffer.concat([pending, chunk]);
      // Each command is an array of bulk strings: *N CRLF ($len CRLF bytes CRLF){N}.
      for (;;) {
        const text = pending.toString("latin1");
        const head = /^\*(\d+)\r\n/u.exec(text);
        if (!head) return;
        let at = head[0].length;
        const words: string[] = [];
        for (let i = 0; i < Number(head[1]); i++) {
          const bulk = /^\$(\d+)\r\n/u.exec(text.slice(at));
          if (!bulk || text.length < at + bulk[0].length + Number(bulk[1]) + 2) return;
          words.push(text.slice(at + bulk[0].length, at + bulk[0].length + Number(bulk[1])));
          at += bulk[0].length + Number(bulk[1]) + 2;
        }
        pending = pending.subarray(at);
        const info = "# Server\r\nredis_version:7.2.0\r\nloading:0\r\n";
        if (words[0]?.toLowerCase() !== "info") client.write("+OK\r\n");
        else client.write(infos++ === 0 ? `$${String(info.length)}\r\n${info}\r\n` : ":1\r\n");
      }
    });
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const { port } = server.address() as { port: number };
  const url = new URL(TEST_REDIS_URL);
  url.hostname = "127.0.0.1";
  url.port = String(port);
  return { url: url.href, close: () => { for (const socket of sockets) socket.destroy(); return new Promise((resolve) => server.close(() => { resolve(); })); } };
}
