// DRILL 3.  Starts RED. Do not edit this file; fix cursor.ts.
import { expect, test } from "vitest";
import { ClientMessage } from "@noon/contracts";
import { cursorToDraw, cursorToSend } from "./cursor.ts";
import { toScreen, type Point, type Viewport } from "./viewport.ts";

// Two windows on one document. Ada's canvas element sits at (300, 100) on her screen and shows the frame at 50 %;
// Bob's sits at (0, 56) and shows it at 240 %, panned. The Button's top-left corner is the frame's (240, 100).
const ada: Viewport = { x: 200, y: 80, zoom: 0.5 };
const adaCanvas: Point = { x: 300, y: 100 };
const bob: Viewport = { x: -300, y: 10, zoom: 2.4 };
const BUTTON: Point = { x: 240, y: 100 };
/** Where a world point is on Ada's SCREEN: the canvas's corner plus the viewport's transform. */
const onAdaScreen = (world: Point): Point => { const at = toScreen(ada, world); return { x: at.x + adaCanvas.x, y: at.y + adaCanvas.y }; };

// The whole bug in one sentence: the arrow lands on the Button in Ada's window and somewhere else in Bob's. Read the
// failing assertion before you open cursor.ts: in which coordinate system was the cursor sent, and which one does
// `cursorToDraw` (and the real `.world` transform) expect?
test("a pointer resting on the Button in Ada's window is drawn on the Button in Bob's, at his zoom and pan", () => {
  const sent = cursorToSend(ada, adaCanvas, onAdaScreen(BUTTON));
  const drawn = cursorToDraw(bob, sent);
  const bobsButton = toScreen(bob, BUTTON);
  expect(drawn.x).toBeCloseTo(bobsButton.x, 1);
  expect(drawn.y).toBeCloseTo(bobsButton.y, 1);
});

test("what is sent names the spot on the sheet, whatever Ada's zoom: zoomed out or in, the same pointer on the Button sends the same cursor", () => {
  const zoomedIn: Viewport = { x: -100, y: -40, zoom: 3 };
  const a = cursorToSend(ada, adaCanvas, onAdaScreen(BUTTON));
  const b = cursorToSend(zoomedIn, adaCanvas, { x: toScreen(zoomedIn, BUTTON).x + adaCanvas.x, y: toScreen(zoomedIn, BUTTON).y + adaCanvas.y });
  expect(a).toEqual({ x: 240, y: 100 });
  expect(b).toEqual({ x: 240, y: 100 });
});

test("left of or above the frame is a place too, sent to the hundredth, and the wire takes it", () => {
  const sent = cursorToSend(ada, adaCanvas, onAdaScreen({ x: -40.507, y: 1200.004 }));
  expect(sent).toEqual({ x: -40.51, y: 1200 });
  expect(ClientMessage.safeParse({ type: "presence", cursor: sent, selection: null }).success).toBe(true);
});
