// DRILL 2.  Starts RED. Do not edit this file; fix room.ts.
import { expect, test } from "vitest";
import type { Op, SequencedOp, ServerMessage } from "@noon/contracts";
import { emptyDoc, ROOT_ID } from "../../../packages/doc-model/src/index.ts";
import { createFencedRoom, Fenced, ROOM_ELSEWHERE, type Peer, type Store } from "./room.ts";

let nextId = 0;
const uuid = (): string => `00000000-0000-4000-8000-${String(++nextId).padStart(12, "0")}`;
const add = (nodeId: string): Op => ({ type: "add_node", nodeId, parentId: ROOT_ID, index: 99, component: "Stack", props: {} });
const row = (seq: number, actorId: string, nodeId: string): SequencedOp => ({ seq, opId: uuid(), actor: { kind: "user", id: actorId }, op: add(nodeId) });
/** Lets everything queued behind a submit reach the store: a macrotask, after every microtask of the room's chain. */
const tick = (): Promise<void> => new Promise((resolve) => setTimeout(resolve, 0));

function peer(id: string): Peer & { inbox: ServerMessage[]; closes: number[] } {
  const inbox: ServerMessage[] = [];
  const closes: number[] = [];
  return { id, inbox, closes, send: (m) => void inbox.push(m), close: (code) => void closes.push(code) };
}
const added = (rows: SequencedOp[]): string[] => rows.map((r) => (r.op.type === "add_node" ? r.op.nodeId : r.op.type));

/**
 * The documents row and op_journal in memory. `claim` is what the documents row names (a takeover sets it, as
 * store.claim() does after a larger lease token). `down`: every round trip is refused. `freeze()` holds the NEXT
 * round trip until the returned function is called: what a process paused past its lease looks like to the store.
 * insertIf checks and writes in one synchronous step, as one SQL statement does; the real table's unique key on seq
 * is left out so that the journal can SHOW a zombie row rather than hide it behind a second failure.
 */
function memoryStore() {
  const rows: SequencedOp[] = [];
  const state: { claim: string | undefined; down: boolean; hold: Promise<void> | undefined } = { claim: undefined, down: false, hold: undefined };
  const trip = async (): Promise<void> => {
    if (state.down) throw new Error("connection refused");
    const held = state.hold;
    state.hold = undefined;
    await held;
  };
  const store: Store = {
    async claimOf() {
      const answer = state.claim; // the row is read by Postgres now...
      await trip(); // ...and the answer reaches a process that may be frozen meanwhile
      return answer;
    },
    async insert(op) {
      await trip();
      rows.push(op);
    },
    async insertIf(op, claim) {
      await trip();
      if (state.claim !== claim) throw new Fenced("fenced");
      rows.push(op);
    },
  };
  const freeze = (): (() => void) => {
    let thaw = (): void => undefined;
    state.hold = new Promise<void>((resolve) => { thaw = resolve; });
    return () => { thaw(); };
  };
  return { store, rows, state, freeze };
}

// The whole feature in one sentence: an owner paused past its lease cannot append once another node took the room.
// Read the failing assertion: which row is in the journal, whose room has never seen it, and what does the new
// owner's next append do to a journal that holds it?
test("an owner frozen between its fence check and its write cannot add a row after the new owner claimed and read the journal: the check and the write are ONE step", async () => {
  const { store, rows, state, freeze } = memoryStore();
  state.claim = "a";
  const room = createFencedRoom({ doc: emptyDoc(), store, claim: "a" });
  const [x, y] = [peer("x"), peer("y")];
  room.join(x); room.join(y);
  for (const nodeId of ["n1", "n2", "n3"]) await room.submit(x, { opId: uuid(), op: add(nodeId) });
  expect(rows.map((r) => r.seq)).toEqual([1, 2, 3]);

  // The zombie: x's next edit is on its way through the room when the process freezes (docker pause) past its lease.
  const thaw = freeze();
  const late = room.submit(x, { opId: uuid(), op: add("zombie") });
  await tick();
  // Meanwhile node B took the lease with a larger token, CLAIMED the document, and read the journal: three rows.
  state.claim = "b";
  const read = rows.length;
  thaw(); // the old owner runs again, believing nothing happened
  await late;

  // Nothing by the old owner may follow what B read: B's room has never seen it and never will.
  expect(added(rows)).toEqual(["n1", "n2", "n3"]);
  expect(room.lost).toBe(true);
  expect(room.doc.nodes["zombie"]).toBeUndefined();
  expect([x.closes, y.closes]).toEqual([[ROOM_ELSEWHERE], [ROOM_ELSEWHERE]]);
  // B numbers on from what it read; the journal is 1..4 with no gap and no duplicate.
  await store.insertIf(row(read + 1, "b-peer", "b1"), "b");
  expect(rows.map((r) => r.seq)).toEqual([1, 2, 3, 4]);
});

test("an outage is not a fence: the write is refused as unavailable, the room keeps its peers and stays", async () => {
  const { store, rows, state } = memoryStore();
  state.claim = "a";
  const room = createFencedRoom({ doc: emptyDoc(), store, claim: "a" });
  const x = peer("x");
  room.join(x);
  await room.submit(x, { opId: uuid(), op: add("n1") });
  state.down = true;
  const refused = { opId: uuid(), op: add("n2") };
  await room.submit(x, refused);
  expect(x.inbox.at(-1)).toEqual({ type: "rejected", opId: refused.opId, reason: "unavailable" });
  expect(x.closes).toEqual([]);
  expect(room.lost).toBe(false);
  state.down = false;
  await room.submit(x, { opId: uuid(), op: add("n3") });
  expect(added(rows)).toEqual(["n1", "n3"]);
  expect(room.seq).toBe(2);
});

test("once fenced, the room applies nothing, sends every peer to the new owner exactly once, and swallows what was queued behind", async () => {
  const { store, rows, state } = memoryStore();
  state.claim = "a";
  const room = createFencedRoom({ doc: emptyDoc(), seq: 0, store, claim: "a" });
  const [x, y] = [peer("x"), peer("y")];
  room.join(x); room.join(y);
  await room.submit(x, { opId: uuid(), op: add("n1") });
  state.claim = "b"; // a newer owner claimed the document while this room was idle
  await Promise.all(["n2", "n3", "n4"].map((nodeId) => room.submit(y, { opId: uuid(), op: add(nodeId) })));
  expect(added(rows)).toEqual(["n1"]);
  expect(Object.keys(room.doc.nodes).sort()).toEqual(["n1", ROOT_ID].sort());
  expect([x.closes, y.closes]).toEqual([[ROOM_ELSEWHERE], [ROOM_ELSEWHERE]]);
  expect(y.inbox.filter((m) => m.type === "rejected")).toEqual([]); // the peers are gone: nobody is told "unavailable"
  const late = peer("late");
  room.join(late);
  expect(late.closes).toEqual([ROOM_ELSEWHERE]);
  expect(late.inbox).toEqual([]);
});
