// DRILL 2.  Starts RED. Do not edit this file; fix room.ts.
import { expect, test } from "vitest";
import type { Op, SequencedOp, ServerMessage } from "@noon/contracts";
import { emptyDoc, ROOT_ID } from "../../../packages/doc-model/src/index.ts";
import { createDurableRoom, type Journal, type Peer } from "./room.ts";

let nextId = 0;
const uuid = (): string => `00000000-0000-4000-8000-${String(++nextId).padStart(12, "0")}`;
const add = (nodeId: string): Op => ({ type: "add_node", nodeId, parentId: ROOT_ID, index: 99, component: "Stack", props: {} });
const setGap = (nodeId: string, value: number): Op => ({ type: "set_prop", nodeId, key: "gap", value });

function peer(id: string): Peer & { inbox: ServerMessage[] } {
  const inbox: ServerMessage[] = [];
  return { id, inbox, send: (m) => void inbox.push(m) };
}
const ops = (p: { inbox: ServerMessage[] }) => p.inbox.filter((m): m is Extract<ServerMessage, { type: "op" }> => m.type === "op");
const rejects = (p: { inbox: ServerMessage[] }) => p.inbox.filter((m): m is Extract<ServerMessage, { type: "rejected" }> => m.type === "rejected");

/** op_journal in memory, with its two unique keys, outliving any room built on it. `down`: every call rejects. */
function memoryJournal() {
  const rows: SequencedOp[] = [];
  const state = { down: false };
  const find = (actorId: string, opId: string) => rows.find((r) => r.actor.id === actorId && r.opId === opId);
  const journal: Journal = {
    append(op) {
      if (state.down) return Promise.reject(new Error("connection refused"));
      const original = find(op.actor.id, op.opId);
      if (original) return Promise.resolve(original); // op_journal_op: a resend, answered with the original row
      if (rows.some((r) => r.seq === op.seq)) return Promise.reject(new Error("op_journal_seq")); // a rival writer
      rows.push(op);
      return Promise.resolve(undefined);
    },
    since: (seq) => (state.down ? Promise.reject(new Error("connection refused")) : Promise.resolve(rows.filter((r) => r.seq > seq).sort((x, y) => x.seq - y.seq))),
  };
  return { journal, rows, state };
}

// The whole epic in one sentence: an op is durable BEFORE anyone hears of it. Read the failing assertion:
// who heard of an op that the database refused, and what does the room believe its own seq is now?
test("if the journal refuses the op, nobody receives it, the document is untouched, and its number is not used up", async () => {
  const { journal, rows, state } = memoryJournal();
  const room = createDurableRoom({ doc: emptyDoc(), journal });
  const [a, b] = [peer("a"), peer("b")];
  room.join(a); room.join(b);
  await room.submit(a, { opId: uuid(), op: add("n1") }); // seq 1, saved
  state.down = true;
  const refused = { opId: uuid(), op: add("n2") };
  await room.submit(a, refused);
  expect(rejects(a)).toEqual([{ type: "rejected", opId: refused.opId, reason: "unavailable" }]);
  expect(ops(b).map((m) => m.seq)).toEqual([1]); // b never heard of n2: it was never made durable
  expect(room.doc.nodes["n2"]).toBeUndefined();
  expect(room.seq).toBe(1); // the number was not taken: a failed write leaves no gap
  expect(rows.map((r) => r.seq)).toEqual([1]);
});

test("every accepted op is journaled BEFORE it is broadcast, in the order it is broadcast, under concurrent submits", async () => {
  const { journal } = memoryJournal();
  const order: string[] = [];
  const room = createDurableRoom({ doc: emptyDoc(), journal: { ...journal, append: async (op) => { await Promise.resolve(); order.push(`journal ${String(op.seq)}`); return journal.append(op); } } });
  const watcher: Peer = { id: "w", send: (m) => { if (m.type === "op") order.push(`broadcast ${String(m.seq)}`); } };
  const [a, b] = [peer("a"), peer("b")];
  room.join(a); room.join(b); room.join(watcher);
  await Promise.all(Array.from({ length: 10 }, (_, i) => room.submit(i % 2 ? a : b, { opId: uuid(), op: add(`n${String(i)}`) })));
  expect(order).toEqual(Array.from({ length: 10 }, (_, i) => [`journal ${String(i + 1)}`, `broadcast ${String(i + 1)}`]).flat());
});

test("a resend after the room restarted gets its ORIGINAL seq, and nothing is applied twice", async () => {
  const { journal, rows } = memoryJournal();
  const first = createDurableRoom({ doc: emptyDoc(), journal });
  const a = peer("a");
  first.join(a);
  const gap = { opId: uuid(), op: setGap("n1", 8) };
  for (const op of [{ opId: uuid(), op: add("n1") }, gap, { opId: uuid(), op: setGap("n1", 12) }]) await first.submit(a, op);
  // The ack of `gap` was lost. The room is rebuilt from what was saved (here: its final state), and remembers nothing.
  const again = createDurableRoom({ doc: structuredClone(first.doc), seq: first.seq, journal });
  const back = peer("a");
  again.join(back);
  await again.submit(back, gap);
  expect(ops(back)).toEqual([{ type: "op", seq: 2, opId: gap.opId, actor: { kind: "user", id: "a" }, op: gap.op }]);
  expect(again.doc.nodes["n1"]?.props["gap"]).toBe(12); // the old value was NOT written again
  expect(again.seq).toBe(3);
  expect(rows).toHaveLength(3);
});

test("storage down: every peer hears read-only before the sender hears its refusal, nothing is acknowledged; recover replays what landed, then says writable", async () => {
  const { journal, rows, state } = memoryJournal();
  const room = createDurableRoom({ doc: emptyDoc(), journal });
  const [a, b] = [peer("a"), peer("b")];
  room.join(a); room.join(b);
  await room.submit(a, { opId: uuid(), op: add("n1") }); // seq 1
  state.down = true;
  const held = { opId: uuid(), op: add("n2") };
  await room.submit(a, held);
  expect(a.inbox.slice(2)).toEqual([{ type: "status", readOnly: true }, { type: "rejected", opId: held.opId, reason: "unavailable" }]);
  expect(b.inbox.slice(2)).toEqual([{ type: "status", readOnly: true }]);
  expect(await room.recover()).toBe(false);
  // Behind the room's back, the held op LANDED in the journal after all (a reply lost on the way back).
  rows.push({ seq: 2, opId: held.opId, actor: { kind: "user", id: "a" }, op: held.op });
  state.down = false;
  expect(await room.recover()).toBe(true);
  expect(b.inbox.slice(3)).toMatchObject([{ type: "op", seq: 2, opId: held.opId }, { type: "status", readOnly: false }]);
  await room.submit(a, held); // the sender's held copy comes back, as peer-client does on "writable"
  expect(ops(a).filter((m) => m.opId === held.opId).map((m) => m.seq)).toEqual([2, 2]);
  expect(rows.map((r) => r.seq)).toEqual([1, 2]);
  expect(Object.keys(room.doc.nodes).sort()).toEqual(["n1", "n2", ROOT_ID].sort());
});
