// DRILL 1 · extend a type, end to end.  Starts RED. Do not edit this file.
//
// Give a workspace an optional `description`. You will touch four places, in this order:
//   1. packages/contracts/src/index.ts   the Workspace contract and CreateWorkspaceBody
//   2. packages/db/migrations/           a NEW file, 0003_...sql (never edit an applied migration)
//   3. packages/db/src/index.ts          WorkspaceRow, createWorkspace, and the OrgScope type
//   4. apps/api/src/app.ts               probably nothing: why? (that is the lesson)
// Then run:  make check   and   sh drills/lesson-1/check.sh
import { expect, test } from "vitest";
import { useTestServer } from "../../apps/api/src/testing.ts";

const ctx = useTestServer();
const json = (body: unknown): RequestInit => ({ method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });

async function anOrg(): Promise<string> {
  return ((await (await ctx.fetch("/orgs", json({ name: "Drill 1" }))).json()) as { id: string }).id;
}

test("a workspace can be created with a description, and reads back with it", async () => {
  const org = await anOrg();
  const created = await ctx.fetch(`/orgs/${org}/workspaces`, json({ name: "Design", description: "  Everything checkout  " }));
  expect(created.status).toBe(201);
  const ws = (await created.json()) as { id: string; description?: string };
  expect(ws.description).toBe("Everything checkout"); // trimmed, like a name

  const read = (await (await ctx.fetch(`/orgs/${org}/workspaces/${ws.id}`)).json()) as { description?: string };
  expect(read.description).toBe("Everything checkout");
});

test("the description is optional: an old client that never sends it keeps working", async () => {
  const org = await anOrg();
  const created = await ctx.fetch(`/orgs/${org}/workspaces`, json({ name: "No description" }));
  expect(created.status).toBe(201);
  // Absent, not null and not "": exactOptionalPropertyTypes in action (Lesson 0, section 6).
  expect(Object.hasOwn((await created.json()) as object, "description")).toBe(false);
});

test("a bad description is a 400 that names the field, and nothing is stored", async () => {
  const org = await anOrg();
  for (const description of ["x".repeat(501), `a${String.fromCharCode(0)}b`, 42]) {
    const res = await ctx.fetch(`/orgs/${org}/workspaces`, json({ name: "Bad", description }));
    expect(res.status).toBe(400);
    expect(((await res.json()) as { issues: { field: string }[] }).issues[0]?.field).toBe("description");
  }
  expect(((await (await ctx.fetch(`/orgs/${org}/workspaces`)).json()) as { items: unknown[] }).items).toEqual([]);
});
