// DRILL 1 · extend a type, end to end.  Starts RED. Do not edit this file.
//
// A worker dies mid-run (kill -9, OOM, a lost host); fifteen seconds later the sweep hands the run to another worker
// as attempt 2, which replays the dead attempt's steps and carries on (chapter, sections 2 and 3). The person watching
// the panel sees "The AI is working" the whole time and never learns that anything happened, and an operator reading
// a bug report cannot tell a first attempt from a third. Carry the claim count from the row to the screen. You will
// touch, in this order:
//   1. packages/contracts/src/index.ts     `Run` gains `attempt`, a whole number that is at least 0 (0: never claimed,
//                                          1: its first worker, 2: a worker took it over once...). REQUIRED, not optional:
//                                          every run has been claimed some number of times, and an optional field is a
//                                          field every reader has to guess about.
//   2. packages/db/src/index.ts            `RunRow` reads the `attempts` column (0019 added it; `select *` already returns
//                                          it) and maps it: `attempt: r.attempts`. Nothing else in the db package changes:
//                                          every route that answers a Run (create, read, cancel, newest) goes through RunRow.
//   3. the type checker names the rest:    every place that builds a `Run` by hand (apps/worker/src/run.int.test.ts's
//                                          claim expectation, any test fixture) now lacks a field. That list is the drill.
//   4. apps/web/src/progress.ts            `attemptWords(run: Run): string`: "" for a run on its first attempt (or none
//                                          yet), and for attempt n >= 2 a sentence that STARTS with "Attempt n" and says
//                                          that a worker died and another picked the run up. AiPanel.tsx shows it under
//                                          the status sentence, as text in {}, only when it is not "".
// Then run:  make check   and   sh drills/lesson-9/check.sh
//
// Predict first: the sweep gives the run back to the queue and a worker claims it as attempt 2, and a slow first worker
// may still be alive at that moment. Whose steps does the panel show while both exist, and which line of the db
// package makes that true? (Section 5 of the chapter has the answer.)
import { readFileSync } from "node:fs";
import { expect, test } from "vitest";
import { Run } from "@noon/contracts";

const root = new URL("../../", import.meta.url);
const read = (path: string): string => readFileSync(new URL(path, root), "utf8");
const base = {
  id: "0f9c7a0e-1b2c-4d3e-8f00-000000000001",
  orgId: "0f9c7a0e-1b2c-4d3e-8f00-000000000002",
  documentId: "0f9c7a0e-1b2c-4d3e-8f00-000000000003",
  status: "running",
  instruction: "add a hero",
  error: null,
  createdAt: "2026-09-30T00:00:00.000Z",
  startedAt: "2026-09-30T00:00:01.000Z",
  finishedAt: null,
  steps: [],
};
/** A run as the api will answer it once step 1 is done; typed loosely so this file runs while the drill is red. */
const run = (attempt: number): Run => Run.parse({ ...base, attempt }) as Run;

test("the contract: a run says how many times it was claimed, and the count is required, whole and never negative", () => {
  expect(Run.parse({ ...base, attempt: 2 })).toHaveProperty("attempt", 2);
  expect(Run.parse({ ...base, attempt: 0 })).toHaveProperty("attempt", 0);
  expect(Run.safeParse(base).success, "attempt is required").toBe(false);
  expect(Run.safeParse({ ...base, attempt: -1 }).success).toBe(false);
  expect(Run.safeParse({ ...base, attempt: 1.5 }).success).toBe(false);
});

// The drills run without Postgres, so the cheapest honest check is the row parser's text: `select *` already returns
// the column, and RunRow is the ONE place a jobs row becomes a Run.
test("the db package: RunRow reads the attempts column and maps it onto the run", () => {
  const source = read("packages/db/src/index.ts");
  const start = source.indexOf("const RunRow = z");
  expect(start, "RunRow in the db package").toBeGreaterThan(0);
  const body = source.slice(start, source.indexOf("\n// bigint and numeric arrive as STRINGS", start));
  expect(body).toMatch(/attempts:\s*z\.number\(\)\.int\(\)/);
  expect(body).toContain("attempt: r.attempts");
});

test("the view has words for a retry, and none for a first attempt", async () => {
  // A namespace lookup rather than a named import: while the drill is red the export does not exist, and the test
  // must fail on THIS assertion, not on loading the file.
  const progress: Record<string, unknown> = await import("../../apps/web/src/progress.ts");
  expect(typeof progress["attemptWords"], "attemptWords exported from apps/web/src/progress.ts").toBe("function");
  const attemptWords = progress["attemptWords"] as (run: Run) => string;
  expect(attemptWords(run(0))).toBe("");
  expect(attemptWords(run(1))).toBe("");
  expect(attemptWords(run(2))).toMatch(/^Attempt 2\b/);
  expect(attemptWords(run(3))).toMatch(/^Attempt 3\b/);
  expect(attemptWords(run(2))).not.toBe(attemptWords(run(3)));
});
