// DRILL 1 · extend a type, end to end.  Starts RED. Do not edit this file.
//
// The canvas says "read-only" and holds the person's edits, but not SINCE WHEN. A person deciding whether to
// wait or to go home wants the moment; an operator lining up three peers' screens wants the same moment on
// each. Carry the room's clock from the fall to the screen. You will touch, in this order:
//   1. packages/contracts/src/index.ts     `status` gains `at: z.number().int().min(0)` (the room's clock, epoch ms,
//                                          at the moment it changed), REQUIRED: the type checker will name every
//                                          place a status is built without it, and `make check` every test that
//                                          expects one. The welcome gains `readOnlySince`, optional, and present
//                                          exactly when `readOnly` is (exactOptionalPropertyTypes: spread it in).
//   2. apps/sync/src/room.ts               storageFailed() takes the moment from `now()` (the clock the room is LENT,
//                                          never Date.now: a test winds it by hand), keeps it, puts it in the status
//                                          and in the welcome of a peer joining meanwhile; recover() stamps its
//                                          "writable" the same way and forgets the moment.
//   3. packages/peer-client/src/peer.ts    a `readOnlySince: number | undefined` getter: set by a status or a welcome
//                                          that says read-only, cleared by "writable" and with the connection
//                                          (retryLater: it belonged to that room), like `readOnly` itself.
//   4. apps/web/src/reasons.ts             `readOnlyFor(sinceMs, nowMs): string`: "5 s" under a minute, "2 min" from
//                                          there, whole numbers rounded down, never negative (a browser clock behind
//                                          the server's says "0 s").
//   5. apps/web/src/Canvas.tsx             the alert reads "Read-only for 2 min: the server cannot save..." from
//                                          readOnlyFor and Date.now() read in render (a re-render every few seconds
//                                          is fine: the ConflictBanner's poll already causes them). As TEXT, in {},
//                                          like every string that came over the wire.
// Then run:  make check   and   sh drills/lesson-6/check.sh
// (`make check` will have opinions: room.test.ts and peer.test.ts build and expect statuses without `at`, and
// wire.test.ts says a bare status parses. That list IS the drill: every one of them is a place the contract changed.)
import { expect, test } from "vitest";
import type { Manifest, Op, SequencedOp, ServerMessage } from "@noon/contracts";
import { ServerMessage as ServerMessageSchema } from "@noon/contracts";
import { manifest as designSystem } from "@noon/design-system";
import { emptyDoc, ROOT_ID } from "../../packages/doc-model/src/index.ts";
import { connectPeer } from "../../packages/peer-client/src/index.ts";
import { createRoom, type Journal, type Peer } from "../../apps/sync/src/room.ts";
import * as reasons from "../../apps/web/src/reasons.ts";

const FELL = 1_700_000_000_000; // the room's clock when its storage failed
const BACK = FELL + 125_000; // ...and when it answered again
const add = (nodeId: string): Op => ({ type: "add_node", nodeId, parentId: ROOT_ID, index: 0, component: "Stack", props: {} });
const manifest: Manifest = { version: 1, components: [{ name: "Stack", acceptsChildren: true, props: [{ name: "gap", type: { kind: "number" }, required: false }] }] };
const uuid = (): string => crypto.randomUUID();
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
async function until(condition: () => boolean, what: string): Promise<void> {
  for (const deadline = Date.now() + 2000; !condition(); await sleep(5)) if (Date.now() > deadline) throw new Error(`timed out waiting for: ${what}`);
}

test("the contract: a status carries the room's clock, and a read-only welcome says since when", () => {
  expect(ServerMessageSchema.parse({ type: "status", readOnly: true, at: FELL })).toEqual({ type: "status", readOnly: true, at: FELL });
  expect(ServerMessageSchema.safeParse({ type: "status", readOnly: true }).success).toBe(false); // required: an older server is not this server
  expect(ServerMessageSchema.safeParse({ type: "status", readOnly: false, at: -1 }).success).toBe(false);
  const welcome = { type: "welcome", seq: 0, doc: emptyDoc(), readOnly: true, readOnlySince: FELL };
  expect(ServerMessageSchema.parse(welcome)).toMatchObject({ readOnly: true, readOnlySince: FELL });
  expect(ServerMessageSchema.parse({ type: "welcome", seq: 0, doc: emptyDoc() })).not.toHaveProperty("readOnlySince");
});

/** A journal behind a switch: while `down`, every call rejects. */
function switchable(): Journal & { state: { down: boolean } } {
  const rows: SequencedOp[] = [];
  const state = { down: false };
  const gate = <T>(work: () => T): Promise<T> => (state.down ? Promise.reject(new Error("connection refused")) : Promise.resolve(work()));
  return {
    state,
    append: (op) => gate(() => { rows.push(op); return undefined; }),
    find: () => gate(() => undefined),
    everAdded: (nodeId) => gate(() => rows.some((r) => r.op.type === "add_node" && r.op.nodeId === nodeId)),
    since: (seq) => gate(() => rows.filter((r) => r.seq > seq)),
  };
}
function roomPeer(id: string): Peer & { inbox: ServerMessage[] } {
  const inbox: ServerMessage[] = [];
  return { actor: { kind: "user", id }, session: { userId: id, orgId: "org", expiresAt: 0 }, mayEdit: true, inbox, send: (m) => void inbox.push(m) };
}

test("the room stamps the fall and the recovery with the clock it was LENT, and tells a late joiner since when", async () => {
  const journal = switchable();
  let clock = FELL;
  const room = createRoom({ doc: emptyDoc(), manifest, journal, now: () => clock });
  const [a, b] = [roomPeer("a"), roomPeer("b")];
  room.join(a); room.join(b);
  journal.state.down = true;
  await room.submit(a, { opId: uuid(), baseSeq: 0, op: add("n1") });
  expect(b.inbox.filter((m) => m.type === "status")).toEqual([{ type: "status", readOnly: true, at: FELL }]);
  const late = roomPeer("late");
  room.join(late);
  expect(late.inbox[0]).toMatchObject({ type: "welcome", readOnly: true, readOnlySince: FELL });
  journal.state.down = false;
  clock = BACK;
  expect(await room.recover()).toBe(true);
  expect(b.inbox.filter((m) => m.type === "status")).toEqual([{ type: "status", readOnly: true, at: FELL }, { type: "status", readOnly: false, at: BACK }]);
  const after = roomPeer("after");
  room.join(after);
  expect(after.inbox[0]).not.toHaveProperty("readOnlySince"); // a writable room's welcome is unchanged
});

/** A scripted server for one connection: says welcome at once, then whatever the test says. */
function fakeNet() {
  const sockets: FakeSocket[] = [];
  class FakeSocket extends EventTarget {
    constructor() {
      super();
      sockets.push(this);
      queueMicrotask(() => { this.say({ type: "welcome", doc: emptyDoc(), seq: 0 }); });
    }
    send(): void { /* nothing is asserted on what the peer sends */ }
    close(): void { /* the peer closes it when done */ }
    say(message: unknown): void { this.dispatchEvent(Object.assign(new Event("message"), { data: JSON.stringify(message) })); }
  }
  return { sockets, WebSocketImpl: FakeSocket as unknown as typeof WebSocket };
}
type FakeSocket = EventTarget & { say(message: unknown): void };

test("peer-client remembers since when, from a status or a welcome, and forgets it on 'writable'", async () => {
  const net = fakeNet();
  const peer = connectPeer({ manifest: designSystem, session: () => Promise.resolve({ wsUrl: "ws://test/documents/d", token: "t" }), WebSocketImpl: net.WebSocketImpl });
  await until(() => peer.status === "live", "live");
  const since = () => (peer as unknown as { readOnlySince?: number }).readOnlySince;
  expect(since()).toBeUndefined();
  net.sockets[0]?.say({ type: "status", readOnly: true, at: FELL });
  expect(peer.readOnly).toBe(true);
  expect(since()).toBe(FELL);
  net.sockets[0]?.say({ type: "status", readOnly: false, at: BACK });
  expect(since()).toBeUndefined();
  net.sockets[0]?.say({ type: "welcome", doc: emptyDoc(), seq: 0, readOnly: true, readOnlySince: FELL });
  expect(since()).toBe(FELL);
  peer.close();
});

test("the canvas's words: whole seconds under a minute, whole minutes from there, never negative", () => {
  const readOnlyFor = (reasons as Record<string, unknown>)["readOnlyFor"] as ((sinceMs: number, nowMs: number) => string) | undefined;
  expect(typeof readOnlyFor).toBe("function");
  expect(readOnlyFor?.(FELL, FELL + 5_400)).toBe("5 s");
  expect(readOnlyFor?.(FELL, FELL + 59_999)).toBe("59 s");
  expect(readOnlyFor?.(FELL, FELL + 60_000)).toBe("1 min");
  expect(readOnlyFor?.(FELL, BACK)).toBe("2 min");
  expect(readOnlyFor?.(FELL, FELL - 3_000)).toBe("0 s"); // a browser clock behind the server's
});
