// DRILL 2.  Starts RED. Do not edit this file; fix sign-in.ts.
import { expect, test } from "vitest";
import type { User } from "@noon/contracts";
import { createSignIn, type Hashing, type Store } from "./sign-in.ts";

const ann: User = { id: "11111111-1111-4111-8111-111111111111", email: "ann@example.com", name: "Ann" };
const ANN_HASH = "scrypt$32768$8$1$annsalt$annkey";
const DUMMY = "scrypt$32768$8$1$nobodysalt$nobodykey";
/** What scrypt costs, stood in for by a timer: the same for a right guess, a wrong one, and a hash that is nobody's. */
const SCRYPT_MS = 15;

/**
 * One account, and hashing that records every `stored` value it was asked to verify. A password "matches" a hash
 * when it is the hash's own (`ann` + ANN_HASH); the dummy matches nothing, as a hash of 32 random bytes would not.
 */
function world() {
  const verified: string[] = [];
  const store: Store = { credentialsFor: (email) => Promise.resolve(email.toLowerCase() === ann.email ? { user: ann, passwordHash: ANN_HASH } : undefined) };
  const hashing: Hashing = {
    async verify(password, stored) {
      verified.push(stored);
      await new Promise((resolve) => setTimeout(resolve, SCRYPT_MS));
      return stored === ANN_HASH && password === "correct horse battery";
    },
    dummy: () => Promise.resolve(DUMMY),
  };
  return { signIn: createSignIn({ store, hashing }), verified };
}
const median = (xs: number[]): number => [...xs].sort((x, y) => x - y)[Math.floor(xs.length / 2)] ?? 0;

test("the right password signs Ann in; the wrong one is refused; an unknown email is refused with the very same answer", async () => {
  const { signIn } = world();
  expect(await signIn("ann@example.com", "correct horse battery")).toEqual({ ok: true, user: ann });
  const wrong = await signIn("ann@example.com", "wrong horse battery");
  const unknown = await signIn("nobody@example.com", "correct horse battery");
  expect(wrong).toEqual({ ok: false, error: "invalid_credentials" });
  expect(JSON.stringify(unknown)).toBe(JSON.stringify(wrong));
});

// The whole bug in one sentence: an answer that arrives faster for an email nobody has tells the caller which emails
// have accounts, and a list of emails is what a credential-stuffing run starts from. Read the failing assertion:
// how many hashes did the unknown email cost, and against what should it have been verified?
test("an unknown email costs exactly one hash, of the dummy: sign-in does the same work whoever you claim to be", async () => {
  const { signIn, verified } = world();
  await signIn("ann@example.com", "wrong horse battery");
  await signIn("nobody@example.com", "wrong horse battery");
  expect(verified).toEqual([ANN_HASH, DUMMY]);
  // The dummy matches nothing: it must never sign anyone in, whatever they typed.
  expect(await signIn("nobody@example.com", "")).toEqual({ ok: false, error: "invalid_credentials" });
});

test("and so the timing says nothing: an unknown email is not measurably faster than a wrong password", async () => {
  const { signIn } = world();
  const time = async (email: string): Promise<number> => {
    const started = performance.now();
    await signIn(email, "wrong horse battery");
    return performance.now() - started;
  };
  const unknown: number[] = [];
  const wrong: number[] = [];
  for (let i = 0; i < 5; i++) {
    unknown.push(await time(`nobody-${String(i)}@example.com`));
    wrong.push(await time("ann@example.com"));
  }
  // With the bug the unknown email answers in well under a millisecond; the wrong password takes SCRYPT_MS.
  expect(median(unknown)).toBeGreaterThan(median(wrong) * 0.5);
});
